### ISSUE TITLE
UX: Unsure if things are delivered

### ISSUE THREAD

**Issue by roberthaverly** [WhisperSystems/Signal-iOS#1000]
I'll often hit send, then lock my phone and go about my day. I'll later open Signal, and then my thread will update and suddenly switch the "Delivered." I'm not sure if that means it wasn't delivered until I re-opened it, potentially an hour or more later, or if it was delivered when I first sent it.

**Comment by riyapenn** [comment]
It will only say delivered if your contact's device was connected to the internet to receive it.  See support page: http://support.whispersystems.org/hc/en-us/articles/212742268-How-do-I-know-my-message-was-delivered-

**Comment by FredericJacobs** [comment]
A message is sent as soon as it turns blue (light blue is used when being sent).

When a message is sent it will be delivered as soon as the other device has connectivity.

**Comment by roberthaverly** [comment]
Yeah, but it's unclear to the user what's happening. 

It shouldn't refresh and suddenly show "delivered" after I've opened the app back up and gone into the conversation. It makes it seem like it wasn't delivered until then. That's why I labelled it as a UX issue, because I don't think it's a functionality problem. I'm sure everything's being delivered just fine, but it doesn't feel like it.
