### ISSUE TITLE
App crashes when posting on a group 

### ISSUE THREAD

**Issue by hask** [WhisperSystems/Signal-iOS#1002]
App crashes when posting text on a group.

**Comment by FredericJacobs** [comment]
Can you email me a crash log to fred@whispersystems.org?

You can get them by following the following steps: https://bjango.com/help/crashlog/

**Comment by michaelkirk** [comment]
@hask can you confirm - did this happen while *creating* a new group, or while messaging an existing group?


I just had this crash while creating a new group, and wondering if I should create a new issue.

```
2016-03-11 15:30:15.577 Signal Dev[876:201861] *** Assertion failure in -[UIApplication _cachedSystemAnimationFenceCreatingIfNecessary:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UIApplication.m:1712
2016-03-11 15:30:15.581 Signal Dev[876:201861] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'
```

Which appears to be crashing at https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/view%20controllers/NewGroupViewController.m#L149
 because `presentViewController` is being called outside of the main thread.

**Comment by hask** [comment]
Hi Michael,

This did happen while messaging an existing group. After that, I created a
new group with the same participants and I had no problem messaging into
the new group.

Regards,

2016-03-11 17:38 GMT-06:00 Michael Kirk <notifications@github.com>:

> @hask <https://github.com/hask> can you confirm - did this happen while
> *creating* a new group, or while messaging an existing group?
>
> I just had this crash while creating a new group, and wondering if I
> should create a new issue.
>
> 2016-03-11 15:30:15.577 Signal Dev[876:201861] *** Assertion failure in -[UIApplication _cachedSystemAnimationFenceCreatingIfNecessary:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UIApplication.m:1712
> 2016-03-11 15:30:15.581 Signal Dev[876:201861] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'
>
> Which appears to be crashing at
> https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/view%20controllers/NewGroupViewController.m#L149
> because presentViewController is being called outside of the main thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/1002#issuecomment-195604024>
> .
>



-- 
Gema Jiménez Cantarero.

**Comment by michaelkirk** [comment]
OK thanks @hask, I've opened up https://github.com/WhisperSystems/Signal-iOS/issues/1108 as a separate issue.

**Comment by riyapenn** [comment]
From a user: https://gist.github.com/cd8bb3f5547a40068230 
iPhone 6s 
Send message, message is sent to the group, Signal crashes

**Comment by michaelkirk** [comment]
@hask is this still reproducible with this group? If so, could you provide a debug and a crash log?
https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-reports

**Comment by michaelkirk** [comment]
Feel free to re-open if you can reproduce.
