### ISSUE TITLE
Pod OpenSSL  issue, missing  openssl-1.0.2d.tar.gz Not Found

### ISSUE THREAD

**Issue by voipuser1** [WhisperSystems/Signal-iOS#1004]
Having trouble when doing 
$ pod install

Failed when trying to fetch: 
https://openssl.org/source/openssl-1.0.2d.tar.gz
Podfile:
pod 'OpenSSL',                    '~> 1.0.204.1'

Right now openssl is at openssl-1.0.2e
https://openssl.org/source/openssl-1.0.2e.tar.gz

How can we fix this??

Thanks

**Comment by FredericJacobs** [comment]
A fix is going to be pushed with the next commit.

**Comment by voipuser1** [comment]
Thanks Fredric.  Any idea when the next commit will be? 

Is there a temporary thing I can just change myself for right now to make it compile?  

Thanks

**Comment by swedakonsult** [comment]
Try checking out pull request #995.

**Comment by voipuser1** [comment]
Thanks @swedakonsult 

I actually already tried changing Podfiles to OpenSSL to 1.0.205. 

It just return a bunch of red text:


[!] /bin/bash -c 
set -e
VERSION="1.0.2e"
SDKVERSION=`xcrun --sdk iphoneos --show-sdk-version 2> /dev/null`
MIN_SDK_VERSION_FLAG="-miphoneos-version-min=7.0"

BASEPATH="${PWD}"
CURRENTPATH="/tmp/openssl"
ARCHS="i386 x86_64 armv7 armv7s arm64"
DEVELOPER=`xcode-select -print-path`

mkdir -p "${CURRENTPATH}"
mkdir -p "${CURRENTPATH}/bin"

cp "file.tgz" "${CURRENTPATH}/file.tgz"
cd "${CURRENTPATH}"
tar -xzf file.tgz
cd "openssl-${VERSION}"

for ARCH in ${ARCHS}
do
  CONFIGURE_FOR="iphoneos-cross"

  if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ] ;
  then
    PLATFORM="iPhoneSimulator"
    if [ "${ARCH}" == "x86_64" ] ;
    then
      CONFIGURE_FOR="darwin64-x86_64-cc"
    fi
  else
    sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c"
    PLATFORM="iPhoneOS"
  fi

  export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
  export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"

  echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
  echo "Please stand by..."

  export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} ${MIN_SDK_VERSION_FLAG}"
  mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
  LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"

  LIPO_LIBSSL="${LIPO_LIBSSL} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libssl.a"
  LIPO_LIBCRYPTO="${LIPO_LIBCRYPTO} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libcrypto.a"

  ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
  sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"

  make >> "${LOG}" 2>&1
  make all install_sw >> "${LOG}" 2>&1
  make clean >> "${LOG}" 2>&1
done


echo "Build library..."
rm -rf "${BASEPATH}/lib/"
mkdir -p "${BASEPATH}/lib/"
lipo -create ${LIPO_LIBSSL}    -output "${BASEPATH}/lib/libssl.a"
lipo -create ${LIPO_LIBCRYPTO} -output "${BASEPATH}/lib/libcrypto.a"

echo "Copying headers..."
rm -rf "${BASEPATH}/opensslIncludes/"
mkdir -p "${BASEPATH}/opensslIncludes/"
cp -RL "${CURRENTPATH}/openssl-${VERSION}/include/openssl" "${BASEPATH}/opensslIncludes/"

cd "${BASEPATH}"
echo "Building done."

echo "Cleaning up..."
rm -rf "${CURRENTPATH}"
echo "Done."

Building openssl-1.0.2e for iPhoneSimulator 9.1 i386
Please stand by...

**Comment by swedakonsult** [comment]
@voipuser1 you got this message when running ```pod install```?

**Comment by voipuser1** [comment]
Yes!

**Comment by felipesabino** [comment]
@voipuser1 Did you manage to find out why OpenSSL outputs the red text when executing `pod install`? I am having the same issue here...

**Comment by awkaw** [comment]
Problem - cp "file.tgz" "${CURRENTPATH}/file.tgz" OpenSSL 1.0.210
Which folder should file.tgz be copied from? Apparently it is not created there.
