### ISSUE TITLE
Hide Metadata

### ISSUE THREAD

**Issue by JimLoose** [WhisperSystems/Signal-iOS#1005]
Please move this topic to another Repo if wished

There is a messenger approach to hide metadata, which Signal doesn't
- https://news.ycombinator.com/item?id=10668494
- https://github.com/davidlazar/vuvuzela

Are there any plans for Signal?
Are there any plans that one can register a Signal account without Phonenumber or Gmail?

**Comment by FredericJacobs** [comment]
This is not the right place to discuss this.

This kind of discussion will take place on the mailing list.
