### ISSUE TITLE
Signal-iOS + TextSecureServer

### ISSUE THREAD

**Issue by testower** [WhisperSystems/Signal-iOS#1007]
Is there an application layer to support SignaliOS in addition to TextSecureServer?

I've set up the TextSecureServer, connected it to redis and postgresql, and verified that I can call its rest end-points. However, the calls that the app makes to what used to be "master.whispersystems.org" etc, don't seem to correspond to these end-points. 

What is the RedPhone API as opposed to TextSecureServer? Is it another layer of API that you have not published?

**Comment by 2-4601** [comment]
Hi,
I think this might be the wrong place to ask this. TextSecure Server is not supported by OWS but there are some folks at the [mailing list](https://lists.riseup.net/www/info/whispersystems) who have set up their own servers. Try there.

**Comment by testower** [comment]
My question isn't really about textsecureserver but about what the backend requirements for running Signal iOS are. It seems it depends on more than just textsecureserver, something that may be called red phone API? Seems like an appropriate question.

**Comment by 2-4601** [comment]
Do you have an issue with the iOS client connecting to the OWS production servers?
Or do you have an issue with the iOS client and your own server instance and how to configure it appropriately?
If latter this is not the right place to ask this. I'm basing this on similar questions previously asked at these trackers.

**Comment by FredericJacobs** [comment]
The TextSecure protocol is only a texting protocol.

RedPhone is the protocol that does phone calls.
