### ISSUE TITLE
Corrupted messages from only one contact

### ISSUE THREAD

**Issue by alisonLFP** [WhisperSystems/Signal-iOS#1008]
One of my contacts and I can't send or receive messages properly since yesterday. All messages display as corrupted. Both of us are on Signal for iOS version 2.2. Messages with all of our other contacts are working fine.

**Comment by 2-4601** [comment]
Could you submit a debug log after getting those corrupted messages? Logs from both devices might be helpful.
http://support.whispersystems.org/hc/en-us/articles/212476178-I-ve-found-issues-or-bugs-with-Signal-What-do-I-do-now- (that article needs a bit polishing :)

**Comment by alisonLFP** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

2-4601:
> Could you submit a debug log after getting those corrupted
> messages? Logs from both devices might be helpful. 
> http://support.whispersystems.org/hc/en-us/articles/212476178-I-ve-fou
nd-issues-or-bugs-with-Signal-What-do-I-do-now-
> (that article needs a bit polishing :)
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/WhisperSystems/Signal-iOS/issues/1008#issuecomment-
165583637
>
> 
Sure: https://gist.github.com/anonymous/c08db5f22ab0680a43a1
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJWcydaAAoJEJ/DQInL6DyjfbAP/1rs3vSMhpaMmoGLo/B6iZbI
Nt8G6x2Jk0v3/wOsND8Us6lj1Dm7Ijxm8z/QV37xD5Vja3ePacU0QQR2qTiUa2Dv
OvA2qvvsjLuxcpYB95N71I2OYxZAwd+N1+3aclgOsHrbSK4yXyN2BIWpUgeeAnLj
9UIykHcobyXZgQ/epQ7f9O3ndDuJVfJAai3BGOS5epgCzWK0Hqh54I+4gr9KWQrY
XVk6rabgzyr4j4TIjZdjJ7iKZm2FoDg/WJOwwv6g4mGydvZmb5eXEPUQ/L0Sm9zX
Doe/gJHyCIEOhkJTnyBfjVM7xTDA8QWlg3zkctLN6TpMoDSaktd4vHgxUwv/w2i+
aDn1a7M1OoPO0H9SMJep42Nr3mtWtpuqtygh4r8ImhEDpspV/Qqy9kJAymNE2Exd
dx521vfTpQfjZ255mSHoUdGZUbaPTCdRiG+89o1IIHF0n3/wYoJBhRmzm34Z3lcK
os9a+cetIZ+zROPMnAEUl3CJ7yFniIp3yjmGeIzxRWHtfWDkW5c9ClGZ26aIjvcx
sqORMBWYwRXe7FA4WmhkR1av99RXGz+JzHG7BOK0RU7jXg9RtZfdXMrQ0X8Z3CQX
oj6sMO7YvJCORnXNQRozUcBx2jBnnq6LqBb5g+CUuj+jOZXlhfKCTwpeHBCu9oQ2
cAvl9uUlWwaA5DUmx2LF
=WHlU
-----END PGP SIGNATURE-----

**Comment by 2-4601** [comment]
It seems the session with this one contact might have gone awry. If you are anxious to get it fixed there is an advanced setting to reset the session. I don't have an iOS device at hand so I can't say exactly where it is. But if you want to try it it would probably be best to contact support@whispersystems.org and they can tell you how to do it (or if you should do it at all).

On the other hand this might be some rare bug that shouldn't be happening and @FredericJacobs might like to fix it in which case you should wait when he finds the time to look into this.

**Comment by FredericJacobs** [comment]
I talked with @alisonLFP and got her to reset the session and that worked. But looking for a long time solution.

**Comment by alisonLFP** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

2-4601:
> It seems the session with this one contact might have gone awry. If
> you are anxious to get it fixed there is an advanced setting to
> reset the session. I don't have an iOS device at hand so I can't
> say exactly where it is. But if you want to try it it would
> probably be best to contact support@whispersystems.org and they can
> tell you how to do it (or if you should do it at all).
> 
> On the other hand this might be some rare bug that shouldn't be
> happening and @FredericJacobs might like to fix it in which case
> you should wait when he finds the time to look into this.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/WhisperSystems/Signal-iOS/issues/1008#issuecomment-
165828022
>
> 
Thanks for the reply! Frederic helped me with the quick fix and said
he was working on debugging.

Alison
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJWdFKWAAoJEJ/DQInL6Dyjo6gP/iBeB0t1uUbkXKb+EVEYzj/V
URvtBmImZq4JOSDT6UZRrnSkjVZ1LkAbP95mn2wFILZcxJeJFeUNpbYGbv3uzzIy
nrryc87x41s3kFWgAhw2b4BOwyBvBYBBjiZzbqx5vU6J7Fn/0AROsq0RKxVbkxGS
mXNf6Bc3q2hUQKIpwTRMdb5c1Zro/6mXsf5OmJPmA5/jckVkiMo0W3aHb7SjQYfu
FIEmsHU6+73m5APkUfX44PrDy3WK/v6jKd6xHq7BRmOgIQ8PmtZP1bwJygdZZR7X
wYUXlRNwMkjErKNFBHwhpD1rDIwO3Ysv45WtxXxuAwLGbA9nyVFe86QfebOzjRMN
KQU/Cz5zvUNFtVgpPgBGMIig/snW6ML04cAmxQZB/vlQM7QQfJtnaN9GhgUXMTHU
+uOFkw++j45Rn1BcAEnrc0vHfRJPQ33/qwSq3j54fElM+WjfWZ3IN8TpFq8Zx/qx
EHtbIRw5hmZHoOSGZhHM9WlEPCNgkDx3mfDZCnqQ1p5aXSyUKqmcJIfpizfA+KHA
pbPrEbkvl4kXTeIXnsIilRlkSRIyqoux2/iK7GINjx8kEzy6Op7Nq/VVlnOngM6t
MzzMuOivrIL0S+DSAnOygmecb0fNo6RFtpV0BwO2m15yWEV8qWW4T+HhoF735EBy
2OIL3qDTCyZsppZdCm/q
=/diB
-----END PGP SIGNATURE-----

**Comment by rocknjohn** [comment]
Please post the temporary solution of how to reset the session too. It would help others who encounter this issue and are searching for how to fix it. I'm also experiencing corrupted messages with one contact. Thanks.

**Comment by FredericJacobs** [comment]
1) Go to the conversation view of the contact you experience this issue with.
2) Long-press the name of the contact to get to the fingerprint view.
3) Long-press at the bottom of the screen.
4) A dialog should come up asking if you want to reset the session, click on "Reset the session" to continue.

**Comment by burningion** [comment]
Had this same issue. Fix from above worked for me. Latest version of iOS, seemed to have been caused by an emoji.

**Comment by jorgheymans** [comment]
fwiw just had the same issue after changing phones, with one particular contact only. Not sure if the phone change had anything to do with it.

**Comment by phrag** [comment]
Please add an explicit button "Reset Session" (instead of blank area under key compare screen).

I'm a long time Signal / Text secure user and this was very confusing for me on iOS.

**Comment by michaelkirk** [comment]
Recovering from corrupted session is now easier with https://github.com/WhisperSystems/Signal-iOS/commit/c6a2fbff23994bfa7ac55afc228d711a6608ccd8

And hopefully we can avoid some of these corrupted sessions all together with: https://github.com/WhisperSystems/SignalServiceKit/commit/03f05f217cd8f058f4371831ca89a4a32f93d511

Both of which are in the latest appstore release (2.6.4).
