### ISSUE TITLE
Problems playing videos sent from Signal-Android

### ISSUE THREAD

**Issue by justin-** [WhisperSystems/Signal-iOS#1010]
When I send a video recorded with the Android system camera app from a Nexus 5X to friends with Signal-iOS:

iPhone 6, iOS 8.4, Signal 2.2
"Unsupported attachment type"

iPhone 6+, iOS 9.1, Signal 2.2
Video plays but no sound
#902 may be related

**Comment by fxer** [comment]
No issues for me, received video recorded on and from a Nexus 5X w/ latest Android & Signal to my iPhone 6+ w/ latest iOS and Signal. Both video and audio work as expected

**Comment by FredericJacobs** [comment]
@moxie0 : Can you confirm what mime-types should be supported?

**Comment by riyapenn** [comment]
@justin- Can you toggle the vibrate/mute button on the side of your phone so sound is enabled? Then play video, you should hear sound.

**Comment by peterpanondrugs** [comment]
Sent from Signal Android -> iOS (iPhone 6s, version 2.2 & 2.3beta)
Happens quite often: https://gist.github.com/c6b8c43f5ae61edf535c4f17c77a83d1

fyi: Video was sent while the recipient was definitly not online! then logged into 3G and then Wifi.

Maybe it has smth to do with the Android bug:
https://github.com/WhisperSystems/Signal-Android/issues/5463

![2a9701cd-e08a-4730-8fc7-e0a97842bf86](https://cloud.githubusercontent.com/assets/8776733/15656791/ee0fe608-26aa-11e6-8226-02f2385c1e2c.png)

**Comment by peterpanondrugs** [comment]
Update: After deinstall and fresh installation. all works fine.

**Comment by t3io** [comment]
I see this too with Signal-Android 3.25.3 sending to Signal-iOS 2.6.9

Debug logs from the iOS device (iPad 2):
https://gist.github.com/f1b99ce5367a664a7d80a34378d48c94 After one attachment.
https://gist.github.com/64f4511d5ec2ba7d6491a8237e691a9c After second attachment.

This is what the iPad displays:
![image](https://cloud.githubusercontent.com/assets/24854137/21577928/94dc09b2-cf75-11e6-8554-fdc1b0e95787.png)

This is not 100% reproducible, but the majority of video clips sent between these two signal end points - all captured on the Android phone, hence of same source format, are declared "unsupported file type" by Signal-iOS.

Let me know for any further info that will help troubleshoot this.

**Comment by michaelkirk** [comment]
Thanks for the logs @t3io! What version of Android are you running?

Your logs show that the file was uploaded by Signal-Android with mime-type `video/*`, but my understanding, based on what Signal-iOS currently supports, is that it should be one of the following:

* `video/3gpp`
* `video/3gpp2` 
* `video/mp4`
* `video/quicktime`
* `video/x-m4v`

@moxie, is this a Signal-Android bug?

**Comment by t3io** [comment]
@michaelkirk The sender is on Android 6.0.1.

I probably need to test this further, but I believe I found the condition that triggers this bug:

- If I **forward** a videoclip that has already been sent via Signal earlier (say, a month ago, very likely with different Signal versions on both endpoints) to the iOS device, I get this bug.
- If I re-send the original video from my phone's "Gallery" as a new message, it is displayed properly on the iOS device.

So the bug seems to be triggered when forwarding an old videoclip message. Would be nice if other people could test/confirm. Let me know what logs would be helpful to troubleshoot this - I have access to both devices for the next 3-4 days.

**Comment by michaelkirk** [comment]
We've made some major changes to attachment handling lately, so I'm going to close. 

Please reopen if this is still reproducible.

**Comment by oskarandersen** [comment]
Still an issue when sending video,
From Android Pixel - Android 9 5th december update, from gallery  (17mb)
To iPhone 10 / iPhone 8 and 7s tested.
Tested as a group or individual.
Works if the sent video is forwarded to the same conversation.
Have not tested iOS to Android.

**Comment by taw6** [comment]
Sent from Samsung S8 (Android) to a group including iPhone 5s and 6s and another Samsung S8 the video is received but it appears to be empty on the ios device. When I send directly from the Samsung S8 to iPhone 5s I can also reproduce the issue 100% of the time. from the IOS device to the Samsung S8 it works seems to be a problem only from android to ios when you send an attached video.

I have 24x7 access to both these devices as they are both mine, let me know if you need further information.
