### ISSUE TITLE
Ability to delete conversation thread.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#1012]
There is currently no way to delete a contact conversation from the inbox UI.

**Comment by 2-4601** [comment]
For questions on how to use the app see the support site: http://support.whispersystems.org/hc/en-us/articles/212476218-What-are-these-options-Screen-Security-Archive-Group-chat-

**Comment by FredericJacobs** [comment]
You can swipe left from the Inbox UI to delete a conversation.
