### ISSUE TITLE
Unable to move conversation to archive.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#1013]
There is method to move a conversation to the archive.

**Comment by 2-4601** [comment]
For questions on how to use the app see the support site: http://support.whispersystems.org/hc/en-us/articles/212476218-What-are-these-options-Screen-Security-Archive-Group-chat-

**Comment by FredericJacobs** [comment]
Swipe right from inbox

**Comment by nanotechz9l** [comment]
Cool thx
