### ISSUE TITLE
Feature request: add passcode

### ISSUE THREAD

**Issue by altramarine** [WhisperSystems/Signal-iOS#1024]
Hi there,

This may come across a bit tinfoily but in my mind, its does not make sense not to have this feature. 
To add another layer of security, it would be beneficial to have an OPTIONAL passcode to enter Signal app.
Note, I am not suggesting fingerprint because one can be forced to unlock device using a fingerprint without court order.

**Comment by FredericJacobs** [comment]
Duplicate #738
