### ISSUE TITLE
Contacts w/o Signal apearing as (former) RedPhone users

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#1028]
Some of my contacts (with Android or iOS phones) are listed under Signal with their name in grey and a blue telephone handset on the right. I would think that they have RedPhone in Android or Signal 1.0 in iOS.

When I start a secure call with them, Signal tries to connects and after one second the call aborts with the message "Telephone number is not registered in Signal".

Is the contact intersection working properly?

**Comment by FredericJacobs** [comment]
We're migrating contact intersection and that should clear up some issues.

One possible edge case where this can happen and we can't do anything about it is when a user installed Signal, registered. Then later deleted the app or changed phone without unregistring.

In that case, we think the user still has the app. And it's only when we try to send him a push notification that we're told that the Apple Push notification token is no more valid. At that point, we do remove him from the contact intersection queries. But that can take some time with the bloom filter approach.
