### ISSUE TITLE
"Load Earlier Messages" not translatable

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#1033]
![earlier messages](https://cloud.githubusercontent.com/assets/174176/12051283/f88daaf2-af09-11e5-814a-43cefffd5391.jpg)
Signal 2.2

**Comment by aayushranaut** [comment]
It is, maybe not in your language. Which language are you using?

**Comment by 2-4601** [comment]
@aayushranaut That string is neither in current [master](https://github.com/WhisperSystems/Signal-iOS/blob/2c83046ff667d28944038d4d459efbbecb86a81e/Signal/translations/en.lproj/Localizable.strings) nor available at [Transifex](https://www.transifex.com/open-whisper-systems/signal-ios/language/en/).

**Comment by aayushranaut** [comment]
It is a part of JSQMessage(A dependency of the project) which can be found on https://github.com/jessesquires/JSQMessagesViewController
And the string is "load_earlier_messages"

**Comment by 2-4601** [comment]
Thanks @aayushranaut 
I guess this also explains #784.
So is the correct way to solve this by sending PRs to upstream (see https://github.com/jessesquires/JSQMessagesViewController/issues/237) or can Signal take care of this by itself?

**Comment by aayushranaut** [comment]
I think it will be better if you submit PR to JSQMessagesViewController repo.

**Comment by 2-4601** [comment]
That is a quick fix but it's very inconvenient for translators.

**Comment by aayushranaut** [comment]
I do not understand that language, otherwise I would've submitted a PR.

**Comment by aayushranaut** [comment]
@2-4601 if you can send me the translated text details, I would be glad to open a PR.
