### ISSUE TITLE
Very few contacts showing up

### ISSUE THREAD

**Issue by buzrocks** [WhisperSystems/Signal-iOS#1036]
Just installed Signal on a iPhone 6s plus ios 9.2, I have 78 contacts but only 8 are being shown in the signal app. There are also 3 contact names which are bold and the rest are faded or grayed out. no numbers are showing for contacts either. Not sure what to do?

**Comment by JohanDoe** [comment]
Not all your 78 contacts have signal/redphone/textsecure. See:

http://support.whispersystems.org/hc/en-us/articles/212743488-Why-are-my-contacts-different-colors-in-my-contact-list-

**Comment by FredericJacobs** [comment]
@buzrocks : Get more friends to use the app!
