### ISSUE TITLE
Fingerprint verification camera doesn't show close button

### ISSUE THREAD

**Issue by mikeokner** [WhisperSystems/Signal-iOS#1040]
Steps to reproduce:

1. Press and hold on contact's name when viewing conversation
2. Tap the top section of the screen where it says "Tap to scan another user's fingerprint"
3. A full screen camera view appears, with no obvious way to exit
4. Tap the very lower-left corner of the screen where the "X" is on the previous screen or where the "X" is when viewing the QR code for "Your Fingerprint" to close the camera view

The camera view should display an "X" button so users know where to tap to close the camera view.

**Comment by 2-4601** [comment]
Looks like a dupe of #957.

**Comment by mikeokner** [comment]
Aha indeed. Looks like it's been fixed in the next release.
