### ISSUE TITLE
Registering SMS capable SIP number fails

### ISSUE THREAD

**Issue by pusateri** [WhisperSystems/Signal-iOS#1042]
When creating a new account, I never received the SMS verification code for my SIP number. I was able to verify by voice call ok. But when signing up for Telegram secure chat, verification for the same phone number was received as an SMS correctly for my number and I have tested SMS so I know it works for others. I'm in the USA.

**Comment by FredericJacobs** [comment]
Not a Signal-iOS issue. This is for support, support@whispersystems.org
