### ISSUE TITLE
Screenshot of the conversation was possible 

### ISSUE THREAD

**Issue by itopal** [WhisperSystems/Signal-iOS#1051]
I thought ss of a conversation was not permitted on signal but I was able to get one on my first trial. iPhone 4s iOS 8.4.1

**Comment by big-r81** [comment]
Hi,

see [this](https://github.com/WhisperSystems/Signal-iOS/issues/819#issuecomment-112909599) post from Frederic. Afaik, there is no way to prevent this under iOS...

**Comment by FredericJacobs** [comment]
What @big-r81 said.
