### ISSUE TITLE
When building No known class method for selector 'edgeWithName:destinationFilePath:nodeDeleteRules:'

### ISSUE THREAD

**Issue by itree** [WhisperSystems/Signal-iOS#1052]
When building in xcode:

Got: 

Signal-iOS/Pods/TextSecureKit/src/Messages/Attachements/TSAttachmentStream.m:31:38: No known class method for selector 'edgeWithName:destinationFilePath:nodeDeleteRules:'

**Comment by bradbitler** [comment]
Me too. I still haven't figured out a solution...

**Comment by bradbitler** [comment]
It looks like TextSecureKit was recently updated if you run 'sudo gem update' it should update the dependancies. If not, try repulling and running to see if it fixes the issue.

**Comment by FredericJacobs** [comment]
Fixed in https://github.com/WhisperSystems/TextSecureKit/commit/b5a8cf0f0d4e7bde175ae72b4e813bd284538fd1
