### ISSUE TITLE
Notification sounds still active even if they are turned off

### ISSUE THREAD

**Issue by saadusman17** [WhisperSystems/Signal-iOS#1053]
On my iPhone 5, the notification sounds of signal app are on even though I turned them off in the app settings. To turn off, I went to settings (gear icon) inside the app, and turned off the Notification Sounds option. After turning them off, when I am away from Signal app, I still get notification sounds. If I turn off all sounds of iPhone by  hardware switch on the side of iPhone, I start getting vibration sounds. No way to permanently turn off notifications sounds.

Thanks,
Saad

**Comment by saadusman17** [comment]
Hi, 

I found a way to turn off the notification sound, it is possible by going to settings of iphone and find the signal app and then turn off notifications from there. That solves my problem, though I am wondering what "Notification Sounds" option is inside the app.

Thanks,
Saad

**Comment by 2-4601** [comment]
Same as #824? (#983)

**Comment by saadusman17** [comment]
HI, it is similar to other tickets you mentioned. 

1 more thing to add, I changed notification sound of signal to "off" from the iPhone settings (not app settings). That turns off sounds on each text i receive, but it also mutes the calls. So, no more bell rings when a call comes.

What I would like would be controls similar to the facebook messenger app. There you can turn off sounds for text messages so you don't hear constant beeps, and people around you don't get disturbed but when the call comes, you still hear the bell.

Thanks,
Saad

**Comment by FredericJacobs** [comment]
Duplicate #824
