### ISSUE TITLE
Signal freezes when conversation is archived, then pulled out of archive again

### ISSUE THREAD

**Issue by Ginari** [WhisperSystems/Signal-iOS#1056]
Bug reproduction:
1. Swipe right on a conversation to archive
2. Go into archived messages on top
3. Swipe right on the archived message to put it back into the normal inbox
4. Go back into the inbox and fail trying to tab something

Phone: iPhone 6s (MKQN2ZD/2)
Firmware: iOS 9.2.1
App Version: 2.2

**Comment by michaelkirk** [comment]
This sounds suspiciously like #1224 which has been fixed in master. Care to sign up for the next beta @Ginari and we can have it available to try next week in 2.3.3?

**Comment by michaelkirk** [comment]
Assuming this was fixed with #1224. Feel free to re-open if it's still an issue.
