### ISSUE TITLE
Some strings are not syncing to Transifex

### ISSUE THREAD

**Issue by allangarcia** [WhisperSystems/Signal-iOS#1061]
I'm trying to help the translation to pt-BR but some string are only available on English (Signal/translations/en.lproj/Localizable.strings) and are not appearing on pt-BR translation (Signal/translations/pt_BR.lproj/Localizable.strings) neither on Transifex. I posted a synced file thought the MR (https://github.com/WhisperSystems/Signal-iOS/pull/1060) but it was closed due the fact that translation is done on Transifex.

I think that this issue have to be handled by some core developer.

**Comment by 2-4601** [comment]
It would help the person who is going to fix this if you'd list the strings that have issues.

**Comment by allangarcia** [comment]
It's not a missing issue, it's a syncing problem. Some legacy strings appears on pt-BR localization file that aren't used and some new strings that are used on the app aren't on the pt-BR file. I actually did the manual sync and proposed a PR with the corrected file, but was rejected due the translation is actually done on trasifex, but on transifex the strings aren't synced. That's why I opened this issue.

**Comment by michaelkirk** [comment]
From @allangarcia PR #1060

> Some strings are not available on Transifex... like REGISTRATION_NON_VALID_NUMBER or RELAY_REGISTERED_ERROR_RECOVERY... and several others.

**Comment by michaelkirk** [comment]
FYI this script https://github.com/WhisperSystems/Signal-iOS/pull/1081 can be used to find unused entries in the strings file. 

They might just get overwritten again the next time there is a Transifex dump though.

**Comment by michaelkirk** [comment]
@allangarcia translations have been uploaded and we await your contributions. Thank you!
