### ISSUE TITLE
Make JSQMessagesViewController strings translatable

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#1062]
(I'm fusing #784 and #1033 into one issue.)

Three strings are not available for translation at Transifex because they rely on the strings of [JSQMessagesViewController](https://github.com/jessesquires/JSQMessagesViewController).

The strings are:
- _"Load Earlier Messages"_
- _"Send"_
- _"New Message"_

![re-animate f88daaf2-af09-11e5-814a-43cefffd5391](https://cloud.githubusercontent.com/assets/174176/12590739/18ea219a-c46d-11e5-8487-85aeb3474414.jpg)

Currently affected languages (based on what's available at the upstream project):
- az_AZ
- bg_BG
- bs
- ca
- cs
- da
- el_GR
- es
- fil
- fi
- hr
- hu
- lv
- nb_NO
- sl
- sv_SE

Work around:
Submit a translation as a pull request to JSQMessagesViewController (see https://github.com/jessesquires/JSQMessagesViewController/issues/237) and wait for it to get included in Signal iOS.

**Comment by michaelkirk** [comment]
This will be solved with #1255.

![image](https://cloud.githubusercontent.com/assets/217057/16853401/0bded5c0-49c1-11e6-8b40-67679570e144.png)
(It took me at least 2 minutes to remember how to switch back to english.)

Thanks for the upstream update @2-4601  👍
