### ISSUE TITLE
Code signing issues: Failed to code sign "Signal"

### ISSUE THREAD

**Issue by arielelkin** [WhisperSystems/Signal-iOS#1063]
I've followed [the build instructions](https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md) to build the app on Xcode 7.2, and the build fails because:

![image](https://cloud.githubusercontent.com/assets/1756909/12622627/8993c504-c526-11e5-9700-517bcddac9bc.png)

The magical "Fix issue" fails because "An App ID with Identifier **'org.whispersystems.signal'** is not available. Please enter a different string."

![image](https://cloud.githubusercontent.com/assets/1756909/12622576/50a4cb08-c526-11e5-8c1d-af05c8b5d989.png)

Is this the expected behaviour? Should I create a new App ID (something like `com.myname.signal`)  in my Apple Developer Portal?

**Comment by big-r81** [comment]
> Is this the expected behaviour? Should I create a new App ID (something like com.myname.signal) in my Apple Developer Portal? 

Yes, it should work if you create a new bundle identifier....

**Comment by arielelkin** [comment]
Then [BUILDING.md](/WhisperSystems/Signal-iOS/blob/master/BUILDING.md) needs to be updated, as it currently says that a `git clone` and `pod install` are sufficient to build and run, and that's not the case.

**Comment by big-r81** [comment]
Great, you found a problem and maybe you have a solution.

Then you can help and contribute to the project!
Update the [BUILDING.md](https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md) by yourself and send a pull request to the developers!

**Comment by FredericJacobs** [comment]
Codesigning instructions change with every Xcode build.
Every developer who would make valuable contributions likely knows how it works.

**Comment by arielelkin** [comment]
@FredericJacobs Developers who would make valuable contributions are also put off when a project's build instructions doesn't keep [its promises](https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md):

> Build and Run and you are ready to go!

The build instructions should at the very least not include that promise. 

Be that as it may, I'd be happy to make a pull request that would add the necessary steps to add the new App ID to your developer portal, give it the required permissions, generate the relevant certificates, and add them to Xcode. 

If the codesigning instructions change in the forthcoming Xcode builds, I'd be happy to update BUILDING.MD accordingly via pull requests. 

Trust me, many people, me included, are put off from contributing to many worthwhile projects because their build instructions are inadequate. 

I'd be happy to help out with Signal's build instructions. 

Would you consider reopening this issue so that I can submit the corresponding pull request?

**Comment by big-r81** [comment]
@arielelkin 
You can send a PR whether this issue is open or closed. If you make a reference to the issue number, than it is automatically referenced here. ;-)

**Comment by arielelkin** [comment]
@big-r81 @FredericJacobs I know I can send a PR whether the issue is opened or closed, but you closed the issue so it seems like you don't deem a PR necessary. 

If I send a PR that adds the aforementioned build instructions to BUILDING.MD, does it have a chance of being merged?

**Comment by allangarcia** [comment]
@arielelkin on a open source project like signal the core developer doesn't have any obligations to merge all contributions he receives. That why is a fork / pull request model. In my code base I'm doing a complete UX redesign, using size classes, etc, but I'm not doing this because will being merged, if the team like my work they will merge, if not I can use signal app on my phone with my changes! That the beauty of it, you do what you need for yourself, than share with others!

**Comment by arielelkin** [comment]
@allangarcia I think you're missing the point. I just want to improve _this_ project's build instructions to make it easier for other developers to build _this_ project.

Writing these build instructions takes time. I'd be happy to do it but it would be of no use if they stay in my fork. So before I write them I want the maintainers to tell me whether or not it would be a pull request they'd be interested in.
