### ISSUE TITLE
Not able to view contact's fingerprint

### ISSUE THREAD

**Issue by rianhunter** [WhisperSystems/Signal-iOS#1066]
Hello,

On an iPhone 5 running iOS 9.2.1 running signal 2.2, there is no way to obtain the fingerprint of the person I'm texting with.

If I enter the conversation screen, holding their name doesn't work, tapping their name doesn't show their number either.

I looked through all previous issues and no one has reported this.

Thank you

**Comment by rianhunter** [comment]
I've been trying this for days and it hasn't worked, I just re-entered the app and it worked...

I'm not crazy. I think some previous UI action had disabled some tap handler. For instance, opening the image dialog (but not necessarily that). I'll repost if I'm able to reproduce reliably.

**Comment by 2-4601** [comment]
> I looked through all previous issues and no one has reported this.

#788, #1057 :)

**Comment by rianhunter** [comment]
I fail
