### ISSUE TITLE
No audio when iphones ringer hardware switch is set to mute and playing audio/video/voice note

### ISSUE THREAD

**Issue by horsebatterystaple** [WhisperSystems/Signal-iOS#1072]
iPhone 5, iOS 9.2.1, signal 2.2

Reproduceable

**Comment by big-r81** [comment]
This is the expected behavior. I don't expect any sound if i switched to silent mode!

**Comment by riyapenn** [comment]
This is consistently a situation where a user expects it to work as they manually are pressing the play button to hear the audio/video/voice note.  Sounds like these users expect the Silent/vibrate switch to still control notifications or sounds they do not have control of i.e. an incoming message or call vs manually pressing play.  Re-opening for design/UIUX consideration.

**Comment by TreatyOfRome** [comment]
This has been fixed with merged PR #1980 Signal v2.11.0. Only for video playback though.

**Comment by charlesmchen** [comment]
@TreatyOfRome This should be fixed for audio attachments as well in the latest beta.

**Comment by charlesmchen** [comment]
See https://github.com/WhisperSystems/Signal-iOS/pull/2007 and https://github.com/WhisperSystems/Signal-iOS/pull/2008
