### ISSUE TITLE
Unable to send a message to self.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#1073]
I am unable to send myself a message.

**Comment by 2-4601** [comment]
What happens when you send a message to yourself?
See #573.

**Comment by nanotechz9l** [comment]
For some reason on my phone 6s I am unable to send myself a message. Signal fails to find my contact name or phone number to even begin the message phase.

**Comment by riyapenn** [comment]
Not a bug.
Save yourself as a contact. That is put your number as a contact in your phone.

**Comment by nanotechz9l** [comment]
Hi riyapenn, thats def the first thing I checked and issue still persists. This one is a weird one. Not too important tho.

**Comment by michaelkirk** [comment]
@nanotechz9l can you clarify:

1. You have yourself as a contact, composed and sent a message to yourself, but never received it
2. You cannot add yourself as a contact, thus you cannot compose/send a message to yourself.

**Comment by michaelkirk** [comment]
> You have added yourself as a contact, composed and sent a message to yourself, but never received it.
> 
> **OR**
> 
> You cannot add yourself as a contact, thus you cannot compose/send a message to yourself.

@nanotechz9l I'm closing this for now as I can't reproduce it. Please reopen if you have details.

**Comment by MavrikD** [comment]
Is there a feature to allow the echoed messages to show up on Desktop (encrypted)?
