### ISSUE TITLE
Feature request: Delete conversation on all devices

### ISSUE THREAD

**Issue by forthrin** [WhisperSystems/Signal-iOS#1075]
Consider the following:

When starting a new conversation with a person or a group, you can enable a setting, so that when one of the participants at any time decides to delete conversation,

1. The conversation is instantly deleted on all devices who have taken part in the conversation.
2. All participants are informed that "The conversation has been deleted with all participants".

Conversely, if some users have gone offline so the delete request cannot be completed, the remaining participants are informed that, "Still waiting to delete conversation for John Doe and Mary Lamb."

There would thus be a "pact" among the participants, that the conversation is destroyed once finished, in cases where one wants to ensure no-one has local copies of a conversation for whatever reason.

A weakness is obviously that people can still from taking screenshots of the entire conversation as to keep for future evidence. But I'd still like the development team to consider this feature, or possibly discuss it into something even better, before considering a possible implementation.

**Comment by mawed** [comment]
This is close to self-destructing messages, so I don't think this will happen. Look here:

http://support.whispersystems.org/hc/en-us/articles/213134237-Why-doesn-t-Signal-have-self-destructing-messages-or-remote-deletion-functionality-

**Comment by forthrin** [comment]
Fair enough. You have considered it and have a good rationale for not doing so. I will close this issue.
