### ISSUE TITLE
Problem with installing openssl from pod

### ISSUE THREAD

**Issue by ArkadiuszBanas** [WhisperSystems/Signal-iOS#1076]
During pod installing I've received: 
`Installing OpenSSL (1.0.205)

[!] Error installing OpenSSL
[!] /usr/bin/curl -f -L -o /var/folders/_k/3smslx552gq2w0l43sx_zs0r0000gn/T/d20160212-81963-1u45fd5/file.tgz https://openssl.org/source/openssl-1.0.2e.tar.gz --create-dirs`

The problem is 'openssl-1.0.2e.tar.gz' not existing anymore. Podfile needs to be updated.

**Comment by ArkadiuszBanas** [comment]
Comment to commit: 
There's no sens to specify pod version as X.X.XXX with ~> mark. 
There was two ways to fix that:
1. '~> 1.0' 
2. '1.0.216'. 

I've choosed first option to be consistent with rest of podfile.
Of course it's FREEBIE :)

**Comment by ArkadiuszBanas** [comment]
Previous pull request was abandoned.

**Comment by michaelkirk** [comment]
This has been fixed in master.
