### ISSUE TITLE
Donation box for an independent crypto code audit?

### ISSUE THREAD

**Issue by deucalion** [WhisperSystems/Signal-iOS#108]
First of all: thank you for porting this great software to iOS, I greatly appreciate it!

Would it be possible for you to set up a site / service, where users can donate for a third party code audit regarding the safety and security [of the cryptography involved] of Signal-iOS?

Thanks!

PS: Great work on BitHub!

**Comment by Baigle** [comment]
I wouldn't mind a donate option in general, its a justifiable cause and really the easiest and best option for mobile use.

**Comment by FredericJacobs** [comment]
@Baigle : http://bithub.whispersystems.org/

**Comment by Calefornia** [comment]
Recent audit:
https://www.onthewire.io/audit-of-signal-protocol-finds-it-secure-and-trustworthy/

**Comment by michaelkirk** [comment]
I'm going to close this as we use github for tracking specific product bugs/feature requests.

If you'd like to talk more about this, try the forum: https://whispersystems.discoursehosting.net/
