### ISSUE TITLE
Reference to non-existent "+" button on empty inbox

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1080]
<img width="175" alt="screen shot 2016-02-14 at 12 50 02 am" src="https://cloud.githubusercontent.com/assets/217057/13032376/b3990336-d2b5-11e5-8f98-f125e96fed6c.png">

Text says "Tap on the + button" but the app has an edit button instead of a "+" button. In the app store version I'm seeing the "+" button. 

<img width="34" alt="screen shot 2016-02-14 at 12 56 20 am" src="https://cloud.githubusercontent.com/assets/217057/13032378/ca2f4bb4-d2b5-11e5-9850-159dd7fc901a.png">

**Comment by michaelkirk** [comment]
Ah, this was caused by #950.

**Comment by big-r81** [comment]
Okay, only for my understanding:
The change of the english localization will trigger a change on transifix to retranslate the key "EMPTY_ARCHIVE_FIRST_TEXT"?
