### ISSUE TITLE
Translation for Tamil

### ISSUE THREAD

**Issue by kracekumar** [WhisperSystems/Signal-iOS#1082]
[Transifex IOS](https://www.transifex.com/open-whisper-systems/signal-ios/) doesn't have an option for Tamil. I am currently translating for [Android](https://www.transifex.com/moxie/signal-android/translate/#ta/) and like to do it for IOS as well.

**Comment by 2-4601** [comment]
I think new languages should be requested through Transifex. (Unfortunately Transifex has no URI for the request page so can't give a direct link.)

**Comment by kracekumar** [comment]
@2-4601 Thanks. Found the option and sent a request.

**Comment by kracekumar** [comment]
@2-4601 Will any one accept the invite or how is it ? I am unable to join the team.

**Comment by 2-4601** [comment]
I think the request needs to be manually accepted by the project maintainer. You'll just have to wait for that, sorry.
Btw, you can close this issue here.

**Comment by kracekumar** [comment]
Thanks. Waiting for someone to approve it.
