### ISSUE TITLE
Please provide tactical procedures for verifying contacts (messages and phone)

### ISSUE THREAD

**Issue by gatewaydrug** [WhisperSystems/Signal-iOS#1085]
There are clear FAQs on how to see your own and contacts keys (as well as phone security code for calls), but what are the step by step procedures we should use to ensure we are talking to who we think we are talking to?  

For example, for messages, should we verify by adding them first and looking at their device in person second to compare keys?  For phone, how does the two word code help ensure we are talking to the correct person?

These may be basic question and not related to code, but any help would be appreciated.  Also if this should move to a different forum, happy to do so. thanks

**Comment by riyapenn** [comment]
Sounds like you saw the support page: http://support.whispersystems.org/hc/en-us/articles/212476208-How-do-I-verify-a-contact-Is-my-call-private-

Check archives of the mailing list and continue discussions there.  Sign up here: https://lists.riseup.net/www/subscribe/whispersystems. 

Please close issue as GH is not for discussions, but tracking bugs.
