### ISSUE TITLE
Error connecting to socket

### ISSUE THREAD

**Issue by almas123** [WhisperSystems/Signal-iOS#1089]
Hello,I get an error-Error connecting to socket Error Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 404" UserInfo=0x17446fd40 {NSLocalizedDescription=received bad response code from server 404, HTTPResponseStatusCode=404
Because of what I'm getting the same mistake?

**Comment by michaelkirk** [comment]
@almas123 when do you get this message? When you first launch the app? Is this an app crash or a alert? If it's an app crash could you post the stack trace?

**Comment by almas123** [comment]
Thank you for choosing the solution to my problem, fortunately, I was able to solve this problem.

**Comment by NishithaJain** [comment]
@almas123 
hi can you please lemme know how you solved this error. I am stuck with same thing.
Thank you

**Comment by almas123** [comment]
hello,I solved this problem, remove, several rows in class AFNetworking.

**Comment by NishithaJain** [comment]
But am not using any AFNetworking framework

**Comment by NishithaJain** [comment]
@almas123 
Is there any other way to get rid off this error.
Thankz in advance:)

**Comment by NishithaJain** [comment]
Strange!
The error just disappeared leaving behind new error .Below is the error 
error:Error Domain=SRWebSocketErrorDomain Code=2133 "Invalid Sec-WebSocket-Accept response" UserInfo={NSLocalizedDescription=Invalid Sec-WebSocket-Accept response}
Can you please help me with this?
@almas123
