### ISSUE TITLE
Feature request: Message trimming per chat

### ISSUE THREAD

**Issue by francwalter** [WhisperSystems/Signal-iOS#1090]
Hallo
I think, a very important feature for security enhancement is the "Message trimming" > "Delete old messages" (in Settings > Chats and media) . Delete old messages when the "Conversation length limit" is reached.
I set it to 5. If I have a private conversation and don't want anybody else to read this, the conversation must be deleted after reading it, because my phone could be lost or stolen and then the messages could be read if I forgot to delete them manually.
I could use the encrypting feature, but this is too unhandy, especially if I use a secure password, which is neccessary for security.
But the message trimming is only for all chats. I have chats which are less important, where I even would like to keep the chat history more than the last 5 messages. 
So the feature request is to do message trimming per individual chat, also for groups. In addition to the global setting.
The new setting could be set in the conversation setting, where I can "Mute conversation" or set the "Notification sound" etc.

Thanks

frank

**Comment by 2-4601** [comment]
Looks like you opened this at the wrong repository :)
In any case there's already an issue for this at the Android repo https://github.com/WhisperSystems/Signal-Android/issues/5176

**Comment by francwalter** [comment]
Oh! Yes, sorry :)
I mixed it up. Can be closed or deleted then. Thank!
