### ISSUE TITLE
High Traffic to master.whispersystems.org when not using app

### ISSUE THREAD

**Issue by Ewarren7** [WhisperSystems/Signal-iOS#1091]
I was doing some traffic analysis for an unrelated issue and happen to catch that in the last 2 hours 
![image](https://cloud.githubusercontent.com/assets/7004081/13367399/5efe1b0e-dcb0-11e5-9658-d5ec27f012b1.png)

I had not opened signal in days, and this seemed quite excessive for a 2 hour time frame.

Using signal 2.2 on iOS 9.2.1 on iPhone 6

**Comment by 2-4601** [comment]
Sounds like #866.

**Comment by Ewarren7** [comment]
@2-4601 thanks missed that. Ill post there
