### ISSUE TITLE
linker error

### ISSUE THREAD

**Issue by darrenw** [WhisperSystems/Signal-iOS#1093]
Clean build, just checked out the code on a brand new mac, following instructions from BUILDING.md
Fresh install of cocoapods, xcode 7.2.1.
Build fails with a linker error regarding '-l22519'.

exact text follows: 
Ld /Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Products/Debug-iphonesimulator/Signal.app/Signal normal x86_64
    cd /Users/darren/Documents/Code/Signal/Signal-iOS
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -L/Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Products/Debug-iphonesimulator -L/Users/darren/Documents/Code/Signal/Signal-iOS/Pods/OpenSSL/lib -L/Users/darren/Documents/Code/Signal/Signal-iOS -F/Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Products/Debug-iphonesimulator -F/Users/darren/Documents/Code/Signal/Signal-iOS -filelist /Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Intermediates/Signal.build/Debug-iphonesimulator/Signal.build/Objects-normal/x86_64/Signal.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -l25519 -lAFNetworking -lAxolotlKit -lCocoaLumberjack -lDJWActionSheet -lFFCircularProgressView -lHKDFKit -lJSQMessagesViewController -lJSQSystemSoundPlayer -lMantle -lPastelogKit -lProtocolBuffers -lSCWaveformView -lSQLCipher -lSSKeychain -lSocketRocket-PinningPolicy -lTextSecureKit -lTwistedOakCollapsingFutures -lUnionFind -lYapDatabase -lc++ -lcrypto -licucore -llibPhoneNumber-iOS -lssl -framework AudioToolbox -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreTelephony -framework Foundation -framework MapKit -framework MobileCoreServices -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -fobjc-arc -fobjc-link-runtime -framework ContactsUI -framework PushKit -framework Social -framework CoreMedia -framework MobileCoreServices /Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Products/Debug-iphonesimulator/libspeex.a /Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Products/Debug-iphonesimulator/libspandsp.a -framework MessageUI -framework MediaPlayer -lz -framework QuartzCore -framework Security -framework AddressBook -framework AddressBookUI -framework CFNetwork -framework SystemConfiguration -framework CoreTelephony -framework UIKit -framework Foundation -framework AVFoundation -framework AudioToolbox -lPods -Xlinker -dependency_info -Xlinker /Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Intermediates/Signal.build/Debug-iphonesimulator/Signal.build/Objects-normal/x86_64/Signal_dependency_info.dat -o /Users/darren/Library/Developer/Xcode/DerivedData/Signal-bxjbofcidicpemepkqsusecfhvbj/Build/Products/Debug-iphonesimulator/Signal.app/Signal

ld: library not found for -l25519
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by michaelkirk** [comment]
Just double checking - you did open the "Signal.xcworkspace" not the "Signal.xcodeproj", right?

**Comment by darrenw** [comment]
oof, yeah, that's it. sorry! there's some other error right now but it's unrelated.
