### ISSUE TITLE
Allow URLSchemes support

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#11]
Examples:
- sgnl://call:+111111111
- sgnl://text:+111111111
- sgnal://vcode:3322256 (for signup verification link in SMS)

**Comment by corbett** [comment]
hey, what's our decision here? was something like this merged?

**Comment by FredericJacobs** [comment]
No, still open. Not high priority, will add this with 2.1 or something.

**Comment by corbett** [comment]
ok.. this makes sense.

On Wed, Jan 7, 2015 at 10:08 AM, Frederic Jacobs <notifications@github.com>
wrote:

> No, still open. Not high priority, will add this with 2.1 or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/11#issuecomment-69001720>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by MattDelmarter** [comment]
Please allow the URL to include the actual text to send to the specified number.

Example: 
signal://msg?text=Hi&to=+1555999

**Comment by mbootsman** [comment]
What is the status of this?
