### ISSUE TITLE
Accepting new key should update all unreadable messages.

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1107]
When your friend changes their key and sends you multiple messages, you should only have to accept the new signature once to validate *all* new messages.

### To reproduce

- Hippo started a conversation with Squirrel
- Then Later Hippo re-installs Signal, generating a new set of credentials
- And Hippo sends the first message "Hey bud!"
- And Hippo sends the second message "I just reinstalled Signal!"
- Squirrel doesn't see the text, but sees two "key warning messages" in their place
- When Squirrel taps the first "key warning message"
- And Squirrel chooses to accept Hippo's new key (after very carefully verifying them out of band of -course!)
- Squirrel sees "Hey bud!"
- But Squirrel does not see "I just reinstalled Signal!"
- Instead Squirrel still sees the key warning message for the second message.
  - Squirrel can see the second message by tapping on it and accepting the signature for that message too, but that's not ideal.

What *should* happen is that Squirrel sees **all** new messages after accepting the signature once.

**Comment by 2-4601** [comment]
Same as #531?

**Comment by michaelkirk** [comment]
It absolutely is. Didn't realize it first time I read that issue. :) thanks @2-4601!

**Comment by michaelkirk** [comment]
This actually is different from #531. #531 is about only showing one warning per missed message, which I actually think would be a step backwards from a UX standpoint. As is, the warning shows a placeholder for which messages you should review if you accept the key - this is especially useful in a  group conversation that's received a lot of messages since you last left.

E.g. Imagine you're in a group conversation with Squirrel and Raccoon.

Raccoon: First one to claim my leftovers can have them.
Squirrel: [ Accept new key ]
Raccoon: Sure is nice out today.
...lots of other messages..
Squirrel: [ Accept new key ]
...lots of other messages..

In this case it's nice to know at each point that Squirrel has sent a message. So you know all the places to review after accepting the key.

I think the primary UX issue with multiple keychange messages is *this* issue wherein you should only have to accept an identity key once, and am in favor of leaving a warning for each of the received messages.

**Comment by michaelkirk** [comment]
This is working for incoming messages. And we don't want it for outgoing messages. Rather, we want the sender to explicitly opt in to resending each of their failed messages.
