### ISSUE TITLE
Installing on Grandstream - GXV3240

### ISSUE THREAD

**Issue by theochino** [WhisperSystems/Signal-iOS#1109]
Hello, 

I am trying to install the software on the Grandstream - GXV3240 android type desktop phone.
Any luck in making the installer available to every device ?

Regards,
Theo Chino
![img_0069](https://cloud.githubusercontent.com/assets/5959961/13724487/5cda08e6-e855-11e5-82d4-bc92d34d52b7.JPG)

**Comment by michaelkirk** [comment]
Hi Theo - this is the tracker for the iOS device only.

Android: https://github.com/WhisperSystems/Signal-Android
Desktop: https://github.com/WhisperSystems/Signal-Desktop

**Comment by theochino** [comment]
Oups; I'll post on the Android Side. Sorry.
