### ISSUE TITLE
should be easier to recover from "Received a corrupted message"

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1110]
I somehow got into a state where each time Alice sent Bob a message (or vice-versa) the receiving party would only see: "Received a corrupted Message"

![image](https://cloud.githubusercontent.com/assets/217057/13730794/405a6478-e917-11e5-899a-c4f6e1f89853.png)

I was able to remedy this on both sides by resetting the session on one side.

![image](https://cloud.githubusercontent.com/assets/217057/13730792/292daf76-e917-11e5-9e97-9a171d89c618.png)

Maybe we should fire up the "reset session" modal when user taps on the "received a corrupted message" message, with an appropriate admonition. However, at this point we're opening the "user has to know the risks of resetting their keys" can of worms.

Of course, better yet messages should never be corrupted, but if we do get into this state, it should be straight forward to recover, else the two party members cannot speak again without reinstalling the app.

**Comment by 2-4601** [comment]
AFAIK, the long term goal is to get rid of the manual reset session altogether. In the mean time it's a workaround for the hopefully rare cases when sessions get out of tune. But an even better workaround would be what you suggested (i.e. tapping the error should bring up the option to reset the session).

If you can reproduce a case that causes a corrupted message, that would be great.

Related #1008.

**Comment by petergault** [comment]
Yes, it'd be great if it could bring that view open. If there isn't the time available for that, it could even link to the support site: http://support.whispersystems.org/hc/en-us/articles/215238158-What-do-I-do-if-I-received-a-corrupted-message-

A simple help link next to the text should do the trick.

**Comment by riyapenn** [comment]
Some logs for reference, if needed:
1. https://gist.github.com/8f77cad9e7f9258f37d67f250b18a8dc
2. https://gist.github.com/5b997fd9ea28a3ef6cf93abe2fc9c8de 
3. https://gist.github.com/192e69bcf62b75402491c217d1460928 
4. https://gist.github.com/f39b628887fdd9e2ce6f0835f7e725b8 
5. https://gist.github.com/065737dc716dd0510fe397822e3907dd 
6. https://gist.github.com/d1ca6d59294739635619ca79d9de0535

**Comment by michaelkirk** [comment]
fixed in https://github.com/WhisperSystems/Signal-iOS/commit/c6a2fbff23994bfa7ac55afc228d711a6608ccd8
