### ISSUE TITLE
Sometimes image messages don't expand message bubble to fit contents

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1111]
Haven't been able to reliably reproduce this but seen it several times.

After taking the images using camera (first one is fine, review the last two):

![img_0351](https://cloud.githubusercontent.com/assets/217057/13730896/c6725de8-e919-11e5-9954-c310eb3f8666.PNG)

After closing and restarting signal, I can see all image-containing bubbles correctly expanded to fit their image size.

![img_0352](https://cloud.githubusercontent.com/assets/217057/13730899/d20226ca-e919-11e5-8233-082478be759b.PNG)

**Comment by 2-4601** [comment]
Related #421?

**Comment by michaelkirk** [comment]
This was *not* fixed by #1237. (But fix is forthcoming in #1255)
