### ISSUE TITLE
Client failed 

### ISSUE THREAD

**Issue by tomeklew** [WhisperSystems/Signal-iOS#1118]
Anyone knows how to fix it?

**Comment by tomeklew** [comment]
https://gist.github.com/5cc6ade952470f4dc54a

**Comment by michaelkirk** [comment]
dupe of #1115 

This is also affecting android, seems like a server side error and not specific to the iOS client.

**Comment by FredericJacobs** [comment]
This was an infrastructure issue affecting Europe. Should be fixed now.

**Comment by tomeklew** [comment]
Thanks
