### ISSUE TITLE
dual registrations both notifiable but cannot be answered

### ISSUE THREAD

**Issue by temp140801** [WhisperSystems/Signal-iOS#112]
iOS 7.1.2, Signal 1.0.3.
1) register number of SIM in handset with Signal installed, SMS confirmed.
2) register on same handset for another number in another phone with no Signal installed, SMS confirmed.
3) re-register number of SIM in handset with Signal installed, SMS confirmed.
Calls to either number would trigger notification. Calls to number of SIM in handset with Signal installed can be answered normally. Viewing notification of calls to the other registered number would launch Signal app, but no call answering UI, while ringing continues.
Would prefer to be able to answer multiple registered numbers on same handset, but also to fully unregister a number or transfer registration of any number to another handset if required. Same for future messaging.

**Comment by FredericJacobs** [comment]
Signal 2.0 has support for RedPhone unregistering when deleting account.
