### ISSUE TITLE
Switching numbers

### ISSUE THREAD

**Issue by madduck** [WhisperSystems/Signal-iOS#1120]
We regularly move between countries and use two SIM cards. Devices like the Fairphone even allow you to do this without shutting down the device. Unfortunately, Signal seems to be locked in to one number, and switching to another number would mean deregistering (losing all messages), and re-registering, which is rather tedious if you have to do it every few weeks.

Couldn't there be a way to maintain multiple accounts and switch between them, or have the account even be selected automatically based on the active SIM, while the message store is shared between the accounts?

cc. @mjollnir

**Comment by haffenloher** [comment]
What exactly is the problem you want to solve? You can just continue using your existing Signal registration with as many different SIMs as you want.

**Comment by michaelkirk** [comment]
Although I believe you could continue to receive messages with Signal registered to your old number, I think contact discovery would get weird. I'm not 100% sure how contact discovery works, but I believe a workaround is that new people would have to add your old number to their address book in order to find you.

**Comment by haffenloher** [comment]
@madduck's scenario is just switching back-and-forth between two SIMs. Instead of re-registering with the other number every time (and having to inform all contacts they now need to Signal-message him using his other number), he and his Signal contacts could simply do nothing and continue messaging as usual

**Comment by greycubesgav** [comment]
I've not personally tried this (I will in about 2 weeks time when I head to another country for a few months), this is certainly how Whatsapp works. 
E.g my Whatsapp account works as before with a sim from a different country, people just need to use my original phone number to add me as a contact.
I'm hoping Signal works the same.

**Comment by michaelkirk** [comment]
@madduck - can you clarify, have you actually tried switching sim cards and had issues using Signal?

If so, what happened, and what were you expecting to happen?

**Comment by madduck** [comment]
Thanks for following up.

After switching SIMs, I can still use Signal, but my messages appear as if sent by the old number. Even if both sides have Signal installed, peers can't send Signal messages unless they know and use the old number. The new number will result in SMSs being sent instead.

But the folks in country A don't really know my number in country B, nor vice versa, and so I end up sending SMSs accidentally, and given #5078, the text messages often end up going to invalid numbers even.

Wouldn't it be possible for me to just have multiple identities, i.e. one number in A and one number in B, and I could choose which one to default to, and otherwise A's number would be used if I corresponded with others who have the same country prefix, and similarly for country B?

**Comment by michaelkirk** [comment]
Thanks for the clarifying details @madduck. What you are asking totally makes sense, but it's currently not possible.

**Comment by madduck** [comment]
Yeah, was afraid you'd say that. This in combination with the inability to import/export on iOS really screws things up for us, as well as any Signal users relocating or switching devices/providers…

**Comment by sylvaticus** [comment]
My 2 cents.. would have been nice I had it.

After years I am in France, I am gonna now close my Italian number (where signal is registered to) for my French number.. I need to manually re-register with a new account and let all my Italian Friends know of the new number.
In WhatsApp instead there is a nice "Change number" feature that allows you to specify which friends should be notified of your new number (those you chatted with/everyone/custom).
In this way who added me using the old number doesn't need to add me again using the new number. And I don't loose any message history.

**Comment by SchulteMarkus** [comment]
What @sylvaticus said...
