### ISSUE TITLE
Crash at sending (iOS 9.2/latest signal)

### ISSUE THREAD

**Issue by Rafiot** [WhisperSystems/Signal-iOS#1122]
Environment: 

* Sender: iOS 9.2, latest version of Signal 
* Receiver: Android 6 (Cyanogenmod, latest), latest version of Signal 

Context:

The key on the android (receiver) has been changed (it was working before). And since then, Signal crash when sending a message to this particular contact (it works with all the other contacts).

Has been tested:

* Refreshing the key on the receiver device -> no difference
* Refreshing the key on the sender device -> the app crash when renewing the key

Please let me know if I can give more details that would help solving the issue.

**Comment by Rafiot** [comment]
Seems to have fixed itself... You may want to look at it still, it is weird.

**Comment by michaelkirk** [comment]
This is the Signal-iOS tracker. Would you post your crash report on https://github.com/WhisperSystems/Signal-Android?

**Comment by liliakai** [comment]
@michaelkirk Sounds like it was the iOS side that was crashing though.

@rafiot If it happens again it'd be good to get a debug log.

**Comment by Rafiot** [comment]
Yes, the issue was happening on the iOS client, communicating with the android one (was working the other way around).

@liliakai Noted, I will do that next time.

**Comment by Rafiot** [comment]
Oh, same bug again. I have the logs, but it contains at least my pone number. Where can I send it that isn't publicly available to everyone?

**Comment by FredericJacobs** [comment]
@Rafiot : A debug log is useless. support@whispersystems.org needs crash logs.
https://bjango.com/help/crashlog/

**Comment by Rafiot** [comment]
oh, ok. Well, this is gonna take more time then, I'll reopen if possible later.

Also, might be good to remove the debug log thing then if it is useless as it makes the users upload private information on github for no reason...
