### ISSUE TITLE
What is the detail of the encrytion?

### ISSUE THREAD

**Issue by richmonkey** [WhisperSystems/Signal-iOS#1123]
I understand the DH. but i can't know the detail how to got the aes's secret.
IdentityKey, signedprekey, ratchetKey, onetimeprekey, basekey..., it's complicated.

**Comment by 2-4601** [comment]
This tracker is used for bugs and feature requests. If you would like to get some help with Axolotl try stackoverflow.com or similar places. You can also try at https://whispersystems.discoursehosting.net/
