### ISSUE TITLE
Commit access for contributor(s)

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#1128]
I know Whisper Systems is looking for a full time iOS dev and it has been a difficult role to fill. @FredericJacobs did/does great work, but isn't listed on the Whisper Systems website anymore. Is he gone now?

@moxie0 Would you consider granting commit access to @michaelkirk? If Michael would be game. His pull requests have been on point and high quality. See the PR queue. Example: https://github.com/WhisperSystems/Signal-iOS/pull/1105

Granting commit access, even temporarily, to a high quality contributor seems like a way for Signal to keep momentum while the search for a full time developer continues. I'm concerned that if there isn't an active maintainer currently that contributor PR's will sit without getting merged and contributors may stop contributing.

**Comment by aayushranaut** [comment]
I second that commit access should be given to a high quality contributor otherwise the other contributors would lose momentum.

**Comment by moxie0** [comment]
Thanks but this isn't a discussion forum, we only use GH issues for tracking bugs.
