### ISSUE TITLE
Missing contacts

### ISSUE THREAD

**Issue by SASDOE** [WhisperSystems/Signal-iOS#1131]
I only seem to be able to see a dozen of my contacts versus the roughly 200 I actually have. I've tried refreshing the list but to no avail. The result is I cannot invite any of my friends to use the app.

**Comment by 2-4601** [comment]
Have you checked?
- http://support.whispersystems.org/hc/en-us/articles/212476148-Who-can-I-talk-to-with-Signal-Where-are-my-contacts-
- http://support.whispersystems.org/hc/en-us/articles/213133077-What-settings-or-permissions-do-I-need-to-enable-on-my-iPhone-
