### ISSUE TITLE
Preview attached media in message composition box before sending

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1132]
Signal-iOS does not allows users to preview media attachments before sending them.

This is a "nice-to-have" with the current app, but a "need-to-have" if we are going to implement "media paste" functionality.

To clarify, compare the behavior of adding a photo from your photo library in iOS Messenger vs. Signal. 

**In iOS Messages** the "compose" text area is populated so you can see what you're about to send and add an annotating caption:

![image](https://cloud.githubusercontent.com/assets/217057/14295735/d8cf9824-fb44-11e5-8deb-8cb79a6dec35.png)

 **In Signal**, after picking an image from your library, it is immediately sent. A caption must be authored in a subsequent text message:

![image](https://cloud.githubusercontent.com/assets/217057/14295772/fd443b74-fb44-11e5-8af8-9f9a0ed5fe34.png)

The iOS Messages approach is slightly preferred in the existing use case, because you can annotate your picture with a caption, or combine multiple images in a single message. Whatever, not a big deal either way, but a little nicer than what Signal-iOS does. 

However, when you consider this composition interface in terms of how a "paste" feature would work in future Signal, it would be disastrous to just fire off a message with whatever the user has pasted unless the user has a chance to confirm it's content - e.g. what if you got distracted and forgot what was in your paste buffer, inadvertently sending the wrong thing.

So, apart from a little nicer composition interface, the real purpose of this feature is to pave the way for media pasting. #793 

In line with what Signal-Desktop and Signal-Android expect to display, attachments need to be limited to _1_ single attachment per message.

**Comment by michaelkirk** [comment]
Ah, this is a dupe of #858

**Comment by michaelkirk** [comment]
Actually - reopening. #858 is overloaded to mean two usefully decomposable things:

1. The first roughly corresponds to what I've covered here.
2. The second is about extra tools for the media picker, and sounds similar to how iOS Messages does media attachments:

![image](https://cloud.githubusercontent.com/assets/217057/14296760/a26c1438-fb49-11e5-972a-85b8c2b280a6.png)

**Comment by bakagirl** [comment]
Average user here: its totally, totally frustrating to accidentally send a picture you didn't mean to just because your finger glanced the wrong picture and no confirmation comes up to verify. Definitely my #1 frustration with Signal as is. Would love to see either the iMessage confirmation window or something akin to that for a fix.

**Comment by Robbbb** [comment]
Similar to @bakagirl , sending the wrong image can have devastating social consequences. 
My intuition, based on every other app that sends from library, is that a single tap will make the image full screen and prompt for [send] or [done]. The thumbnail is too small to evaluate, especially for sight-impaired users and users with smaller handsets.

**Comment by gwerbin** [comment]
+1. As for the "needs design" label, I think it would make the most sense to just copy whatever iMessage does for this (and probably any other) UX/UI decision.

**Comment by michaelkirk** [comment]
Solved by paste functionality.

**Comment by Robbbb** [comment]
I don't see this as solved at all.

My understanding is that even with paste functionality, which is great, a single tap on an image in your library will immediately send it.

This is counter-intuitive, frustrating, potentially embarrassing,  and different from every other messaging app on my phone. The thumbnails are too small to make a "is this the correct photo" decision, and a single tap to "preview" results in an often mistaken sending action.

Messenger, iMessage, What'sApp, Telegram, Google Hangouts, Slack, GroupMe, Line, WeChat, Gmail, Mail all behave intuitively.

**Comment by Hnasar** [comment]
Indeed this bug impacted an acquaintance of mine, and she's both furious at the app and quite embarrassed.
 
I was very surprised to see the difference in functionality compared to the android version, but at least there are plans to address the issue.

I think the "Needs design" label needs to be dropped. Like, @gwerbin says, it's probably best to match what android signal, and what iMessage do, which is to show the image above a text entry, and only send both the image and text when the send button is clicked. So essentially, it'd be great to implement what the first image in this thread shows.

**Comment by charlesmchen** [comment]
This has been addressed in the forthcoming release v2.11

**Comment by Hnasar** [comment]
Yay thanks for your work @charlesmchen !
For others curious, it this functionality seems to be implemented mostly commit:9882eeea9 but it's spread out a little.
