### ISSUE TITLE
refreshing contacts freezes UI

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1135]
When I go to "Compose new message"
And I pull-down to refresh
Then I see a contact indicator for a second, but then it disappears
And the UI becomes unresponsive to taps and scrolling
And finally (~15 seconds later) I see a "Bummer! We couldn't fetch an updated contact list from the server. Please try again later."

So in this case the error message is expected, because I'm behind a captive wi-fi portal, but the UI should not be blocking in.

The UI also blocks when the update is successful, but it's not quite as noticeable.

**Comment by FredericJacobs** [comment]
When you say UI block, do you mean freeze because main thread is blocked?

**Comment by michaelkirk** [comment]
The app becomes unresponsive to any gestures (scrolling/tapping), assuming that the main thread is blocked.

**Comment by ThuggishNuggets** [comment]
This sounds like the data fetch is happening on the main thread (hence the freezing), or UI work is being dispatched onto a background thread (hence the ~15 second delay), or both.

**Comment by telip007** [comment]
I'm new and would like to solve it, where is the file which handles the display ?

**Comment by nixnuex** [comment]
I cannot reproduce this bug. Seems to be solved in HEAD. Please close.

**Comment by michaelkirk** [comment]
Verified - thanks for noticing @nixnuex.
