### ISSUE TITLE
Launch Image looks like a Lemon

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1136]
I see this on my device (iphone 6) when launching, but not in the iphone6 simulator appstore version and master.

![image](https://cloud.githubusercontent.com/assets/217057/14368550/76166bb4-fcec-11e5-9de2-4eaf2d1c23f3.png)

**Comment by FredericJacobs** [comment]
I don't think there's anything that can be done with this. It's a static that is provided for launch time.

Gonna close this. Feel free to reopen if I'm missing a magic way that we can fix this. But seems like an OS thing.

**Comment by michaelkirk** [comment]
I'm not seeing this behavior when using a .xib for the Launch screen. I'll open a PR with that momentarily.

**Comment by michaelkirk** [comment]
> Note this only appears when status banner from tethering for instance is present during launch

Funny that I didn't realize this was the cause, but makes sense. All kinds of apps are broken this way. =)

Interesting choice that apple chose to crop images from the middle outward.

Anyway, #1137 adapts appropriately.
