### ISSUE TITLE
Add support for linking to Signal Desktop

### ISSUE THREAD

**Issue by aaronraimist** [WhisperSystems/Signal-iOS#1142]
- [x] I have searched open and closed issues for duplicates
As far as I can tell this bug was never opened: https://github.com/WhisperSystems/Signal-Desktop/issues/226#issuecomment-109793305 and still hasn't been fixed: https://twitter.com/whispersystems/status/718157985504100352

----------------------------------------

### Bug description
Signal for iOS should be able to link to [Signal Desktop](https://github.com/WhisperSystems/Signal-Desktop)

### Steps to reproduce
- open Signal Desktop

**Actual result:** Unable to link to Signal Desktop
**Expected result:**
- Signal Desktop should present instructions on linking the iOS app with the Desktop app
- the iOS app should be able to scan the QR code and link with the Desktop app
- the iOS app should sync with the Desktop app

**Comment by danielschonfeld** [comment]
@FredericJacobs if you want, I'm willing to take a stab at it.

**Comment by bowlofstew** [comment]
This would be pretty awesome to have.  I'm up for helping out as well.

**Comment by ThuggishNuggets** [comment]
I'll also contribute to this in any way that I can. I'm looking for any documentation on what communication is happening between Signal Desktop and Android if anyone knows of any.

**Comment by urbaniak** [comment]
I'm also happy to contribute if there were any kind of docs what needs to be done in iOS version to get multi device working.

**Comment by kylecook80** [comment]
I am willing to help as well if someone knows what needs to be done.

**Comment by paul4335** [comment]
What's the status of the Signal-Ios support for Signal-Desktop? Do you think it's likely that this feature might be introduced this year?

**Comment by d0t1q** [comment]
Any update? This thread has been dead since June.

**Comment by michaelkirk** [comment]
Currently in beta. If you're interested in trying it out, email "support@whispersystems.org" with the subject "I'd like to join the Signal iOS Beta"

**Comment by CodeMichael** [comment]
I'll be pairing with at least 3 machines total.  Are there specific test cases you're looking to be executed?

**Comment by michaelkirk** [comment]
see #1320, #1330
