### ISSUE TITLE
SignalServiceKit refactor rendering glitches

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1146]
This issue is mostly a placeholder for rendering glitches blocking release as reported by @FredericJacobs 

> Eg. Messages from previous thread that you were viewing, appearing in the one you are currently viewing.

Some maybe relevant commits:
- large [SignalServiceKit](https://github.com/WhisperSystems/SignalServiceKit/) refactor: https://github.com/WhisperSystems/Signal-iOS/commit/c6d44e59e235cd8fb4b037a690a0a1c3d261f717
- Big changeset to the MessageViewController: https://github.com/WhisperSystems/Signal-iOS/commit/2c83046ff667d28944038d4d459efbbecb86a81e

**Comment by michaelkirk** [comment]
I don't really notice any glitches when viewing short or plain text threads, however as threads get longer and include more media, things get really slow, and frames start to drop.

Doing some analysis in instruments showed we're spending a lot of time building our TSInteractions. As a quick first step, I've cached them here: 

@FredericJacobs can you see if this improves the situation that you were experiencing?

https://github.com/WhisperSystems/Signal-iOS/compare/master...michaelkirk:fix-glitchy-ui?expand=1

There seems to be some more low hanging optimization fruit that I will continue to attack.

**Comment by FredericJacobs** [comment]
No, I'm not talking about dropped frames.

When you have a few threads and switch back and forth between them, some messages from other threads might be rendered in the wrong thread.

**Comment by michaelkirk** [comment]
I haven't been able to reproduce this, so I am going to let it float until the beta. Hopefully getting more users involved will get us more reproduction data.

**Comment by michaelkirk** [comment]
AFAIK this was not reproduced. Closing.
