### ISSUE TITLE
Quadriplegic text input question

### ISSUE THREAD

**Issue by escapologyBB** [WhisperSystems/Signal-iOS#1149]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

###  Does using Apple's voice recognition feature negate the encryption Signal provides

Please excuse me if this is the wrong place to ask this, but I wasn't sure if it was a bug, issue or question so just let me know and I can shift it to the right place ASAP if I've made a mistake.

I'm quadriplegic and so to input text into any app on iOS, Signal included, I need to use Apple's voice recognition system. I do this by clicking on the microphone icon on the iOS keyboard and then speaking my message. When I've finished speaking there is a gap of a couple of seconds until the text appears in the Signal text field and I can press send. The alternative to using their voice recognition is to peck out every single message one character at a time using Apple's Switch Control accessibility feature, which is incredibly time-consuming and does not make for easily flowing conversation. It's a total pain in the bottom.

My concern is that Apple's voice recognition service works (AFAIK) by processing your voice on their servers: the voice to text conversion is not done on the device. I think this means I'm sending Apple my side of every conversation I have on Signal because I'm sending them my words to be converted from voice to text. Obviously when the text is returned and inputted into Signal's text field and I press send everything becomes encrypted; but am I circumventing my encrypted conversation by using Apple's voice recognition service?

I would like to have encrypted text conversations with my friends and Signal is obviously the gold standard here. I have to use IOS for Switch Control, with which I can use my chin to fully control the phone. Nothing suitable exists on android.

I was so excited when I saw that the desktop version came out but that needs an android device to work unfortunately.

Thanks in advance!

### Steps to reproduce
- Click the microphone icon on the iOS keyboard
- Dictate the text of your message
- Press send when the text is returned from processing by Apple.

### Device info
**Device**: iPhone 6s
**iOS version**:  9.3.1
**Signal version: All versions's

**Comment by michaelkirk** [comment]
We aren't doing any special handling of speech-to-text. As I understand, Apples service works as you described. 

Closing as I think this discussion is better suited for the forum - you might get a better answer / ideas there: https://whispersystems.discoursehosting.net.

**Comment by escapologyBB** [comment]
Thanks for the info.
