### ISSUE TITLE
intermittent: "Load Earlier Messages" shows for empty thread. Crashes when tapped

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1150]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

Sometimes when I open an empty message thread I see the "Load Earlier Messages" button.

### Steps to reproduce
- tap compose, select recipient you have no message history with
- leave thread empty, return to inbox
- relaunch app and go to thread

**Actual result:** Sometimes, I see an empty thread with the "Load Earlier Messages" button displayed.
**Expected result:** An empty thread without the "Load Earlier Messages" button displayed.

### Screenshots

![image](https://cloud.githubusercontent.com/assets/217057/14464575/486b006c-009d-11e6-8dec-db3abf69299b.png)

### Device info
**Device**: iphone6
**iOS version**: 9.3.1
**Signal version:** HEAD (9d4befd)

**Comment by big-r81** [comment]
I can't reproduce this yet...

The only occurence of this message is in JSQMessagesLoadEarlierHeaderView...

**Comment by FredericJacobs** [comment]
I noticed that. It has to do with switching threads. Probably, need to reset those when reloading data after changing `threadId` in conversation view or something.
