### ISSUE TITLE
Gifs do not display correctly

### ISSUE THREAD

**Issue by kooki3monst4r** [WhisperSystems/Signal-iOS#1157]
- [ x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
gifs display as static images

### Steps to reproduce
It always happens. A gif is received and just appear to be an image. 

**exprcted result**
Gifs are animated and move

### Screenshots
n/a

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.1
**Signal version:** 2.2

### Link to debug log
https://gist.github.com/174f84ec85e26a055528f3c35c591489

**Comment by 2-4601** [comment]
> I have searched open and closed issues for duplicates

GitHub's search is quite bad but it's not that bad https://github.com/WhisperSystems/Signal-iOS/issues?q=is%3Aissue+gif :smile:

**Comment by michaelkirk** [comment]
Fixed in https://github.com/WhisperSystems/Signal-iOS/pull/886, pending app store release.
