### ISSUE TITLE
Inconsistency between the user interface and the displayed text in different languages

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#1160]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
There is an Inconsistency between the user interface and the displayed text in different languages.

On devices with english language all is fine! The translation key is:
"EMPTY_ARCHIVE_FIRST_TEXT" = "Tap on the compose button.";

I checked some tranlslations (German, French, Danish, Croatian).
There the keys are:
"EMPTY_ARCHIVE_FIRST_TEXT" = "„+“-Schaltfläche antippen.";
"EMPTY_ARCHIVE_FIRST_TEXT" = "Appuyez sur le bouton +";
"EMPTY_ARCHIVE_FIRST_TEXT" = "Tap på + knappen";
They mention all the "+" button.

So i looked for a "+" button in the project and found it in Image.xcassets labeled "add-conversation"...

### Steps to reproduce
- fresh installed app or delete alle conversations

**Actual result:** In the top right corner the compose button image is shown
**Expected result:** 
Multiple options:

1. Change all other translations
2. Change the english translation and the button image

### Screenshots
English version (description + button image correct):
<img src="https://cloud.githubusercontent.com/assets/9985963/14761710/fb384e6e-0969-11e6-9a91-c0575f8ef002.png" width="200">

German version with changed "+" button image:
<img src="https://cloud.githubusercontent.com/assets/9985963/14761798/5a79cfa6-096a-11e6-8a66-05ccb0fb70f3.PNG" width="200">

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.1
**Signal version:** latest master branch [](https://github.com/WhisperSystems/Signal-iOS/commit/f05429b5945a0d6062a9f14a682a672f1603803e)

###Possible solution
I think the easiest solution is to change the button image and the english description!

**Comment by FredericJacobs** [comment]
I doubt it's related to the language. The version that you see in the simulator is master, where it was changed. The version you have on your phone is the old '+' version, that we moved away from. When string changes will be pushed to Transifex, the wording will be adapted.

**Comment by big-r81** [comment]
I changed the button image to  "+" in the german version... it is not the default. the default is the composer image, but than the translations are wrong!

**Comment by michaelkirk** [comment]
> but than the translations are wrong!

Yup.

@big-r81 see https://github.com/WhisperSystems/Signal-iOS/issues/1080 for the english version of this issue.

**Comment by big-r81** [comment]
Okay, only for my understanding:
The change of the english localization will trigger a change on transifix to retranslate the key "EMPTY_ARCHIVE_FIRST_TEXT"?

**Comment by michaelkirk** [comment]
@big-r81 that's correct. We've just uploaded the latest translations, so our translators will see that this string needs to be retranslated.
