### ISSUE TITLE
Feature request: contacts listed randomly instead of alphabetically or logically

### ISSUE THREAD

**Issue by Anatoly-IVANOV** [WhisperSystems/Signal-iOS#1170]
When adding someone new to a chat / call, the contact list appears in a random order (or so it seems to me). I have approx 3 000 contacts on my iOS, and the first ones on the top are NOT the ones I use often.

Ideally, the behavior would be:

1) best -- some fuzzy logic of "contacts used most" (have no idea whether Apple allows for that data to be pulled from somewhere)

2) OK -- alphabetical

Sorry if it's a duplicate -- did search before submitting, did not find anything relevant.

==ADD==

In my case, I have quite a few contacts in cyrillic. The list shows up a random (each time a new random list), going something like:
- cyrillic contact 95
- latin contact 78
- latin contact 52
- cyrillic contact 675
- latin contact 341

==Context==
- iPhone 5S
- iOS 9.3.1 (13E238)
- Signal version: latest curent

**Comment by 2-4601** [comment]
Related #754, #1158.

**Comment by michaelkirk** [comment]
@Anatoly-IVANOV - contacts are sorted by surname, but:
1. we're not smart about localizing it (#1158)
2. if multiple have the same surname (including if they don't have a surname) they aren't sorted correctly.

The good news is with Signal >=2.3, you should see way less contacts, since we're no longer including non-signal contacts.

I'll leave this open until point 2. is addressed.

**Comment by michaelkirk** [comment]
A maybe related problem, at least with english localizations, is that if a contact was missing the sorting name (e.g. in my case, if someone was missing their last name), they would not be sorted correctly or consistently. 

This much, at least, is addressed in https://github.com/WhisperSystems/Signal-iOS/pull/1482

Were the mis-sorted contacts missing part of their name?

**Comment by Anatoly-IVANOV** [comment]
@michaelkirk — No, in my case most of the 3 000 contacts have both their first and family names (and are easy to tell apart, as the family names as all caps).

**Comment by michaelkirk** [comment]
@Anatoly-IVANOV this should be fixed in the latest app store release. 

If it's not, can you provide a couple of names which would exhibit this mis-sorting?
