### ISSUE TITLE
UX: Create "New message" for greyed non-Signal contacts shows "Blue phone headset" symbol instead of "Invite to Signal" symbol, bold Signal contacts lack a "Chat" symbol

### ISSUE THREAD

**Issue by Anatoly-IVANOV** [WhisperSystems/Signal-iOS#1171]
Purely a UX issue.

If I want a new message, I don't want to call that contact. Show a "dialogue" icon, ie as Skype does it (they have 2 icons, 1 for chat, 1 for call).

I can send you a vector file of a vanilla chat icon, if it helps.

Have searched for something similar at GitHub, read through the FAQ... no explanation anywhere. Sorry if it's a dupe.

==Context==

* iPhone 5S
* iOS 9.3.1 (13E238)
* Signal version: latest curent

**Comment by big-r81** [comment]
Hi,

if you press on the name of the contacts you will get into "chat mode".

**Comment by Anatoly-IVANOV** [comment]
@big-r81 — Thanks! But when in the "New message" list of contacts, pressing on the name does nothing  for me. At least in iOS.

We're talking about a new contact, not the "historically talked / phoned with via Signal" contact, right?

**Comment by big-r81** [comment]
Are the names grayed out or do they have a bold prename and a normal black name? Can you make a picture?

**Comment by Anatoly-IVANOV** [comment]
@big-r81 — Greyed-out.

OK, I scrolled through all 3 000 of my contacts and indeed, some of them are bold and with those, the "press to chat" does work.

So, I suggest the following algo:

1) title = "Your contacts already on Signal"

2) list everyone already on Signal, in alphabetical order (or recent first), add a "chat" icon (pressing the name without knowing what it will do  is really not that intuitive, especially as I use a similar gesture to scroll)

3) title = "Your contacts not on Signal - invite them"

4) list everyone NOT on Signal, in alphabetical order (or recent first), add a "plus" icon, instead of the "call" button

**Comment by tge-linee** [comment]
Related: https://github.com/WhisperSystems/Signal-iOS/issues/950 (actually the same issue)

And the fix: https://github.com/WhisperSystems/Signal-iOS/commit/53793e3c0fbdb4d2f9211e23bdebd1809aebdc86

**Comment by michaelkirk** [comment]
It sounds like this is the result of confusion around Signal not correctly distinguishing between registered/unregistered users. This should have been addressed with 2.3 release, starting a couple weeks back. Feel free to re-open with clarification is this is still an issue.
