### ISSUE TITLE
App stops sending notifications for messages

### ISSUE THREAD

**Issue by snakecharmer1024** [WhisperSystems/Signal-iOS#1174]
I have an iPhone 5, using iOS 9.3.1 and even tho in Settings I have Signal set to send Notifications, it will not and I have to open Signal in order to see if I have messages. This problem has persisted for a few OS updates and I have a friend with an earlier iPhone 3 that has the same problem. It affects the usability considerably.

I can look into this problem this weekend if no one else has time. Maybe if someone has a guess where the issue lies they could point me to the right neighborhood.

**Comment by michaelkirk** [comment]
@snakecharmer1024 - are you able to receive calls?

Could you try going to "settings > advanced > "Re-register for push notifications".

Then see if you are getting notifications and if you can receive calls.

Please let me know if that fixes things for you, as we may be able to prevent this happening to other users in the future.

**Comment by snakecharmer1024** [comment]
@michaelkirk That fixed it! Thank you! I can get notifications and receive calls now. 

I'll go ahead and close this issue.

**Comment by michaelkirk** [comment]
This actually is a bug. You shouldn't have to push a "fix me" button. We ahouldnbe automatically re registering you when your token changes.

**Comment by plchan** [comment]
is this issue in the production version or the beta version of app?

**Comment by michaelkirk** [comment]
It's potentially an issue in the current app store version as well as the beta.

**Comment by plchan** [comment]
thanks. I have reported the same issue on the beta. the current app store version causes me some confusion about the contact an love how it is being handed in the beta.

**Comment by plchan** [comment]
tried the fix to re-register on the beta version and it does not fix the issue on beta :(

**Comment by michaelkirk** [comment]
>  I have reported the same issue on the beta.

If you're talking about #1182, it sounds to me like an unrelated issue. 

This issue is about devices not receiving push notifications, e.g. getting messages when the app isn't launched, seeing messages on your lock screen, and receiving calls. Not about inviting people over sms.

**Comment by plchan** [comment]
Yes. i reported the #1182 and if so, i guess it is a new issue, rather than related with #1174.

thanks for clarifying it.
