### ISSUE TITLE
Unknown progressbar after starting app

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#1176]
What is this light blue progress-bar (marked red) after starting the signal app?

It stops approximitly  at 80-90%...

![simulator screen shot 12 05 2016 12 46 44](https://cloud.githubusercontent.com/assets/9985963/15212454/00d629be-1841-11e6-8f05-7f7810b86fb6.png)

![simulator screen shot 12 05 2016 12 46 46](https://cloud.githubusercontent.com/assets/9985963/15212455/00db4b74-1841-11e6-8810-0be6cffe191c.png)

![simulator screen shot 12 05 2016 12 46 48](https://cloud.githubusercontent.com/assets/9985963/15212457/00e56fd2-1841-11e6-865e-aad0558bddc3.png)

![simulator screen shot 12 05 2016 12 47 11](https://cloud.githubusercontent.com/assets/9985963/15212456/00e3b5f2-1841-11e6-9adc-f8d78c5ce5ca.png)

**Comment by michaelkirk** [comment]
This is a refresh indicator for when the app polls the server for new messages, it would hang if your device is not able to communicate with the OWS server.

GH issues aren't for getting support. Try http://support.whispersystems.org/ or https://whispersystems.discoursehosting.net

**Comment by big-r81** [comment]
I did a issue, because the indicator stays at 80-90%.
But it should't stop every time at 80-90%. If the polling is done the indicator should be at 100%...

**Comment by michaelkirk** [comment]
If you can reproduce this on a device that is online, then this could be a bug. 

Can you verify the device is online (e.g. you can browse the internet) and provide steps to reproduce. For me the bar completes.

**Comment by big-r81** [comment]
I can reproduce this in the simulator and on my device...

The device is online!

Steps to reproduce:
Kill app and start it again, than the progressbar starts growing and stops at 80-90%.

Here is a video of the app starting on the device (iPhone 6):

![progressbar](https://cloud.githubusercontent.com/assets/9985963/15256185/8b836824-1940-11e6-9256-04b64f61c0da.gif)
