### ISSUE TITLE
Text input field expanded when multi-line draft in other conversation thread exists

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1179]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
"New Message" field is expanded when there is a multi-line draft in a different conversation thread. On message send the extra lines/spaces do not go through.

### Steps to reproduce
- Go to existing conversation or create new, referenced as Thread A below
- Write a multi-line message in the text input field
- Press the back arrow (top left corner)
- Go to a different conversation thread or create a new one, referenced as Thread B below

**Actual result:** 
Thread B text input field is expanded to same height of Thread A's draft. Height resumes to normal after sending Thread A's draft or it a 1 line draft.  Message sent in Thread B does not include extra spaces
**Expected result:** Thread B input field should not be expanded

### Screenshots
blob:chrome-extension%3A//bikioccmkafdpakkkcpdbppfkghcmihk/fae9740a-bde4-4a97-9116-ae7d1e375caf
blob:chrome-extension%3A//bikioccmkafdpakkkcpdbppfkghcmihk/62ecf658-43a1-4ab7-a949-fa8cce16fb85

### Device info

**Device**: iPhone 6s
**iOS version**: 9.3.1
**Signal version:** 2.3

### Link to debug log
https://gist.github.com/9701fd2dcc91094a82cf519434644fcf

**Comment by michaelkirk** [comment]
Seems like the screenshots failed to attach @riyapenn.

This might be related to: 2c83046ff667d28944038d4d459efbbecb86a81e
