### ISSUE TITLE
unable to send invite via sms on the latest beta version (2.3)

### ISSUE THREAD

**Issue by plchan** [WhisperSystems/Signal-iOS#1182]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
unable to send invite via sms on the latest beta version (2.3)

### Steps to reproduce
when i searched the phone number, it shows "send sms to xxxxx" in blue color. i touched the send sms message in blue area, and it returned back to "New Message" screen. it never redirected me to the SMS / iMessage screen to send the msg out.

**Actual result:** - it returns back to message screen without redirect to the SMS msg app to send the invitation
**Expected result:** - in the production version, it redirects it to SMS msg app in iOS and allow to customize the messages prior to be sent manually thru click the send button.

### Device info

**Device**: iPhone 5s
**iOS version**: 9.3.0
**Signal version:** 2.3

**Comment by michaelkirk** [comment]
Confirmed that this is working in the app store version but not the beta.

**Comment by plchan** [comment]
do you have a timeframe of fixing this bug?
