### ISSUE TITLE
Read Receipts

### ISSUE THREAD

**Issue by thomasrive** [WhisperSystems/Signal-iOS#1184]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Unable to see read receipts
### Steps to reproduce
 - Sending a message shows that it was delivered, but there is no option for to parties to voluntarily send read receipts. Participants therefore have to send another message stating their reading of the delivered message.

### Device info

**Device**: iphone4s
**iOS version**: 9.3.1
**Signal version:** 2.2

**Comment by 2-4601** [comment]
Duplicate https://github.com/WhisperSystems/Signal-iOS/issues?q=is%3Aissue+read+receipts
