### ISSUE TITLE
compose place holder text doesn't line up with draft text

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1194]
## Bug description

User-entered text is rendered a little higher than the placeholder text. I believe the placeholder text margins are better, and we should fix this by lowering the user entered text.

### Steps to reproduce
- Compose message
- Tap "New Message" (empty compose text placeholder)
- Type a message

### Screenshots

This is two overlayed screenshots. On the left is placeholder text, on the right is the same text ( "New Message"), as entered by the user.

![image](https://cloud.githubusercontent.com/assets/217057/15482477/c7a11396-20e4-11e6-978f-0d07f7f4de14.png)

### Device info
**Device**: iPhone 6
**iOS version**: 9.3
**Signal version:** HEAD(d7c4857)

**Comment by nixnuex** [comment]
I cannot reproduce this behavior. Seems to be solved in HEAD. Please close.

**Comment by michaelkirk** [comment]
Thanks for noticing @nixnuex!
