### ISSUE TITLE
Corrupt messages suddenly appearing after a few hours long chat

### ISSUE THREAD

**Issue by danielschonfeld** [WhisperSystems/Signal-iOS#1203]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
After a while, all messages started showing up corrupted error on both devices while previously working without a problem.

**Comment by michaelkirk** [comment]
@danielschonfeld  can you please follow the issue template and provide

- debug log
- device info (both devices)

What do you mean by corrupted? What are you seeing - What are you expecting to see?

As it is, there's not enough information to do anything with this issue report, but feel free to re-open with the details.
