### ISSUE TITLE
Can't use phone number verification (for 3rd party build)

### ISSUE THREAD

**Issue by abspoel** [WhisperSystems/Signal-iOS#1209]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When running the app on my phone from XCode, I need to verify my phone number. I receive an SMS with a verification code, but after inputting it the code and clicking "Submit Verification Code", I get an animated spinner and the app hangs.

### Steps to reproduce
- using tag: 2.3.1.0
- built using a custom provisioning profile

Does this have anything to do with push notifications not working for unofficial builds? Is there a workaround?

**Comment by michaelkirk** [comment]
It is likely due to your app not receiving the registration push notification. You won't be able to do this with a third party build.

**Comment by abspoel** [comment]
Is there a way to get around this so I can still use a custom build? How do other developers without access to the official build profile do this?
