### ISSUE TITLE
Feature Request: Implement VoIP API for lockscreen call notifications

### ISSUE THREAD

**Issue by aaronraimist** [WhisperSystems/Signal-iOS#1213]
- [X] I have searched open and closed issues for duplicates

---

Signal for iOS should implement the new VoIP API announced at WWDC to provide full screen native call notifications.

See this WWDC session: https://developer.apple.com/wwdc16/230
### Steps to reproduce
- Receive phone call on Signal

**Actual result:** Notification appears
**Expected result:** New VoIP full screen notification appears
### Screenshots

![](https://pbs.twimg.com/media/Ck2daxEWsAAu1I5.jpg)
https://twitter.com/stanfy/status/742422600891129856
https://twitter.com/FredericJacobs/status/742423636657737728

**Comment by FredericJacobs** [comment]
For the record, the relevant API docs: [CallKit](https://developer.apple.com/reference/callkit)

**Comment by big-r81** [comment]
and this [WWDC Video](https://developer.apple.com/videos/play/wwdc2016/230/) when available.

**Comment by kayovoldk** [comment]
got a question about this one. I was thinking about trying to get this working and i was wondering if the relevant code needs to be written in obj-c or if swift is an option?

**Comment by michaelkirk** [comment]
Just objective c at the moment.

**Comment by martimarkov** [comment]
+1

**Comment by greatislander** [comment]
According to a [recent report](https://theintercept.com/2016/11/17/iphones-secretly-send-call-history-to-apple-security-firm-says/):

> … incoming missed calls that are made through third-party VoIP applications like Skype, WhatsApp, and Viber, and that use Apple CallKit to make the calls, also get logged to [iCloud].

Just FYI.

**Comment by pwnsdx** [comment]
Thanks for working on it, this feature is super useful. Sad it log calls on iCloud if activated. Is there a way to prevent this behavior?

**Comment by michaelkirk** [comment]
Will be in 2.7.0
