### ISSUE TITLE
Crash after deleting message

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1218]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

App crashes after deleting a message and switching threads. 

Not *every* time, but most of the time.

### Steps to reproduce
- enter a thread
- long press on message to pop edit menu.
- choose "delete"
- return to inbox
- go to any thread

**Actual result:** App crashes (SEGFAULT)
**Expected result:** 🍨 

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.2
**Signal version:** HEAD (965261f4659372e47b9c7f1274c555b67207f72e)

### Link to debug log

With zombies enabled, I get this in my console:

```
2016-06-14 18:54:34.019 Signal[5077:2027278] *** -[JSQMessagesCollectionViewCellOutgoing release]: message sent to deallocated instance 0x157c67240
```

Maybe related to the async removal in YapDatabaseModified callback?

**Comment by big-r81** [comment]
I can confirm this in the beta (2.3.1)!

**Comment by michaelkirk** [comment]
Attack of the zombies. 👻 
```
[JSQMessagesCollectionViewCellIncoming release]: message sent to deallocated instance 0x12f2443e0
```

**Comment by michaelkirk** [comment]
This is a bug in JSQMessagesViewController that's been fixed upstream. https://github.com/jessesquires/JSQMessagesViewController/issues/1026

Pulling the fix into our branch.

Would be great to unfork and get back on upstream. =)

**Comment by big-r81** [comment]
> Would be great to unfork and get back on upstream. =)
Yes, @FredericJacobs knows best, what they have added to our fork of JSQMessagesViewController to extract those features and get back to upstream.
