### ISSUE TITLE
Signal hangs after swipe gesture in conversation view

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#1222]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal hangs if the following steps are performed

### Steps to reproduce
- go into a conversation thread
- swipe left (or use the back button) to go back to the the conversation overview
- swipe left again (nothing happens as expected)
- click on a conversation thread again to go into thread or for example on the settings button

**Actual result:** 
Signal hangs, a complete restart is necessary to work again!

**Expected result:** Signal should go into the thread.

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.2
**Signal version:** 2.3.2.1 (actual Testfligt beta)

**Comment by riyapenn** [comment]
I am unable to consistently reproduce this on 6S, but have once.  Please indicate your 3D touches and reactions (you should see a transparent image of your home screen) in the second swipe left.

**Comment by big-r81** [comment]
i can't test 3d touch, since i have an iPhone 6 only...

**Comment by riyapenn** [comment]
Overlooked that, 3D touch is on 6S and later. I can also consistently repro on iPhone 5S.

**Comment by dns13** [comment]
This bug seems to be back at least since I use Signal (end of march this year). I can constistently reproduce this on every released version since then.

When in the conversations overview swipe right from the left border to try to go back. Nothing happens but app freezes when trying to open any conversation. Close the app (force quitting is not required) and open again to fix this.

**Comment by michaelkirk-signal** [comment]
@dns13  - I can't immediately reproduce this. Does this happen to you *every* time? Or is there something more to the reproduction that could help us track down the issue?

**Comment by dns13** [comment]
@michaelkirk-signal yes, I can reproduce this every single time. Use iOS back gesture in main menu (conversation overview) which does nothing (as intended), then open any chat. App freezes in main menu until reopened.

**Comment by michaelkirk-signal** [comment]
Thanks for the report @dns13 - this is fixed in #3540

**Comment by dns13** [comment]
Great, thanks!
