### ISSUE TITLE
App crashes on open *most of the time*, timestamps are wrong

### ISSUE THREAD

**Issue by snakecharmer1024** [WhisperSystems/Signal-iOS#1234]
Upgraded my version of Signal, now I have to try to open it several times before it will actually open, the other times it crashes immediately after bringing up the screen. 

Also some of my messages have the wrong timestamp, off by months. 

iPhone 5
iOS 9.3.2

**Comment by michaelkirk** [comment]
Can you clarify which version of Signal you're on? There's been a few
releases recently.

**Comment by snakecharmer1024** [comment]
Yes 2.3.3

**Comment by snakecharmer1024** [comment]
Also people are telling me messages I send are corrupted on the other end

**Comment by michaelkirk** [comment]
Can you elaborate on "corrupted on the other end"? What are they seeing and
what client are they using?

**Comment by michaelkirk** [comment]
Also @snakecharmer1024 could you submit a crash log(s): https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-report#to-submit-your-crash-report

**Comment by snakecharmer1024** [comment]
I haven't been able to get corrupted data from the recipient. I'll submit a crash log soon, thank you

**Comment by snakecharmer1024** [comment]
https://gist.github.com/140a76a9452f65d099c980b8e65f58c5

**Comment by snakecharmer1024** [comment]
The other person was using Android when reporting corrupted messages from me. Another person on iOS received my messages just fine.

**Comment by michaelkirk** [comment]
Hey @snakecharmer1024, thanks for the debug log, but it's actually the crash log that I'm after:  https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-report#to-submit-your-crash-report

Can you send one in?

**Comment by snakecharmer1024** [comment]
Sent

**Comment by michaelkirk** [comment]
@snakecharmer1024
The crash you're experiencing is looks simlar to a DB corruption we're seeing overwhelmingly on  ios8.0/ios8.1 devices. Did you recently update to ios9.3, or have you been using Signal with ios9 previously? 

The trouble is, once the DB is corrupted on ios8/8.1, upgrading to ios9 won't help.

If you've been running ios9 for a while, then it's likely a different issue.

**Comment by michaelkirk** [comment]
Also, if you are desperate, it's likely that a de-install/re-install will allow the app to boot, but you'll lose all your message history and reset your authentication credentials/group memberships. Not ideal.

**Comment by snakecharmer1024** [comment]
I updated a while before this issue appeared. Since updating Signal to 2.3.4, the crashes are less frequent. It was and is usable, so no desperation.

**Comment by michaelkirk** [comment]
@snakecharmer1024 are you by chance on our beta team? There is a perhaps-related fix to this there.

**Comment by snakecharmer1024** [comment]
It has stopped happening, so closing. Thanks for the invite!

**Comment by michaelkirk** [comment]
@snakecharmer1024 was it fixed when you installed the beta in the last day or was it fixed well before that? Do you recall what version?

**Comment by snakecharmer1024** [comment]
Hmmm it was the last update I downloaded, 2.4.1. I haven't installed the beta. Must have been a few weeks ago.
