### ISSUE TITLE
Altered (Google) Contacts

### ISSUE THREAD

**Issue by j-seymour** [WhisperSystems/Signal-iOS#1240]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Using Signal Private Messenger appears to alter Google Contacts data.  This happened twice: Once each with each of two contacts.

### Steps to reproduce
- Install Signal Private Messenger
- Have somebody else that's in your Google contacts install Signal Private Messenger
- Exchange text messages

**Actual result:** Contact's entry in Google Contacts becomes altered in that their phone number listed under "Mobile" is arbitrarily (?) changed to "Home," "Other", etc.
**Expected result:** I don't expect my Contacts data to be altered at all

### Device info

**Device**: Motorola Moto G (2013) (1st Generation)
**OS version**: Android 5.1  (It's since had a security patch.  I don't recall the system version at the time)
**Signal version:** I do not recall.  This was a month or two ago.  (Sorry for the tardy bug report.)

**Comment by michaelkirk** [comment]
Looks like this is for Android. Can you take if over there: https://github.com/WhisperSystems/Signal-Android
