### ISSUE TITLE
Signal crash on iPhone

### ISSUE THREAD

**Issue by DiagonalArg** [WhisperSystems/Signal-iOS#1244]
I'm the only Signal contact of a friend who has an iPhone (version 4).  Recently he showed me that Signal was showing a black screen.  Prior to that, everything was working fine.  I removed Signal and reinstalled.  Now it won't verify, either by text or by phone call.  That is, no text or call is received.  I'd like to debug with him, but I only see him one day a week.  Given that I can't get into the app, could someone give me a pointer on where to start, in which case I will update this issue.

**Comment by michaelkirk** [comment]
@DiagonalArg What version of iOS is your friend using?

Could you supply any relevant Signal logs from the system logs? 

1. On your phone, open the Settings App
2. Go to Privacy, then Diagnostics & Usage
3. Select Diagnostics & Usage Data
4. Locate the log for the crashed app. Crash logs will be named in the format: Signal-(DateTime).ips
5. Select the desired log. Then, using the text selection UI select the entire text of the log. Once the text is selected, tap Copy
6. Paste the copied text into an email to support@whispersystems.org with the subject "iOS Crash Log: &lt;Github Issue Reference&gt;"
  * **Example subject:** iOS Crash Log: Crash on launch #111
  * **Example subject:** iOS Crash Log: Crash when sending video #222

**Comment by DiagonalArg** [comment]
iOS version 8.1.2 (12B440).  There was an iOS update waiting, so we decided that he will update first and then we'll try installing Signal again.  I'll add that without signal installed, #3. above (Diganostics & Usage) did not appear under Privacy.  Perhaps it only appears when Signal is installed.

I'm keeping this browser page open and will update.

**Comment by michaelkirk** [comment]
> Perhaps it only appears when Signal is installed.

It's a system tool - unrelated to Signal. So it should be there somewhere.

I think it was caled "General/Diagnostics" on iOS8. Other steps should be the same.

**Comment by michaelkirk** [comment]
Closing this as we haven't received any new information. Feel free to re-open with more details.

There was a crash fix in the most recent release that might be related.
