### ISSUE TITLE
Crash when attaching media on ios10 

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1245]
This only affects ios10 clients. You'll have to download the latest XCode beta to reproduce.

### Steps to reproduce
- Go to thread view 
- press Paperclip
- "Choose form Library..."

### Link to debug log

Haven't looked into it, but this may be because of new privacy requirements in ios10.

**Comment by sschritt** [comment]
Unable to reproduce in beta 2. Seems to be working fine (v.2.3.3, iPhone 6s).
