### ISSUE TITLE
Country name not showing next to country code during registration on iOS10

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1246]
### Steps to reproduce
- Install on a fresh iOS10 simulator
- App should launch on the registration screen.
- Tap on country code (+1) to choose your country code
- See table of country codes

**Actual result:** 
![image](https://cloud.githubusercontent.com/assets/217057/16635951/fc322d6c-4389-11e6-850a-97f31cb83f74.png)

**Expected result:**
![image](https://cloud.githubusercontent.com/assets/217057/16635985/2d03aa38-438a-11e6-8cbf-f30be2f71250.png)

**Comment by big-r81** [comment]
Hi Michael,

for me it's working with xcode-beta2...

iPhone 6 -Simulator:
<img src="https://cloud.githubusercontent.com/assets/9985963/16914201/867e6368-4cf0-11e6-88e4-aa1b199bd51b.png" width="300">

iPhone SE - Simulator:
<img src="https://cloud.githubusercontent.com/assets/9985963/16914105/db7e68d2-4cef-11e6-93d2-9bd54149da14.png" width="300">

**Comment by michaelkirk** [comment]
Strangely, I can't reproduce this now either. 👀

**Comment by big-r81** [comment]
FYI, works in beta3 (xcode & ios) too!

**Comment by michaelkirk** [comment]
Closing this as I haven't been able to reproduce it after the one time on the beta simulator.

👀 👀
