### ISSUE TITLE
Bubble for video attachment should render with same AR as video

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1270]
When I am sent a video with portrait aspect ratio, I see a landscape bubble, but I should see a bubble with portrait aspect ratio, as I do with image attachments.

Here's a screenshot of a video with landscape aspect ratio followed by a video with portrait aspect ratio:

![image](https://cloud.githubusercontent.com/assets/217057/17008078/0c1783ac-4ea3-11e6-9711-145bef2fadcc.png)

vs receiving images which produce bubbles properly shaped to the aspect ratio of their media content.
<img width="370" alt="screen shot 2016-07-20 at 5 57 25 pm" src="https://cloud.githubusercontent.com/assets/217057/17008146/8c0522e0-4ea3-11e6-8e6e-32aed90b8c82.png">

However, the photos look mis-aligned because of their different width.
- [ ] Width should be fixed, and uniform.
  - [ ] photo
  - [ ] GIF
  - [ ] Video
- [ ] Height should be determined by aspect ratio, cropping at some point if it's a really tall message.
  - [ ] photo
  - [ ] GIF
  - [ ] Video

**Comment by p4nci** [comment]
I think cropping it's intentional,
see also https://github.com/WhisperSystems/Signal-Android/issues/3579, https://github.com/WhisperSystems/Signal-Android/issues/4806

**Comment by mdouglass** [comment]
Starting on a fix for this, will be fixed width, height dictated by aspect ratio but with a clamped min/max so we don't get too tall or too short.
