### ISSUE TITLE
Ability to block numbers/contacts

### ISSUE THREAD

**Issue by rdela** [WhisperSystems/Signal-iOS#128]
As suggested by [@txtjs on twitter](http://twitter.com/txtjs/status/502795519580573696)

> possible to block numbers in future versions?

**Comment by huertanix** [comment]
Signal seems to be ignoring blocked iOS contacts/numbers. :<

**Comment by pjctech** [comment]
+1

**Comment by openfly** [comment]
+2

**Comment by ohemorange** [comment]
+4

**Comment by zmanian** [comment]
I did some research and there doesn't appear to be any api for accessing the system blocklist that Signal could use.

CallKit exposed an api for adding numbers to the blocklist in iOS 10 but nothing about checking numbers against the blocklist so the Signal blocklist probably needs to remain separate.

**Comment by Eeko** [comment]
This is kind of important as an attacker can effectively DoS the usage of the app for a user whose phone number they know. Just script a client to spam a number with garbage messages.

**Comment by bakagirl** [comment]
+5

**Comment by huertanix** [comment]
@zmanian Could you share links to some of the research you found on not being able to access to system blocklist?

**Comment by kofalt** [comment]
I was just contacted by an acquaintance who said they had to uninstall Signal due to a user harassing them. The Android app has a block feature (under conversation settings) but it sounds like the iOS app does not?

Would it be possible to get movement on this? If nothing else there's at least one user for whom this feature is required to use the app at all.

**Comment by michaelkirk** [comment]
Hi, this is an important issue, but the comments have not been productive, so I'm going to lock.

As a reminder, do not "+1" or "me too" issues unless you have new details to add. It spams every single subscriber to the list, increasing the noise to signal ratio. It's possible for you to upvote issues by using the GitHub reactions feature.

![screen shot 2017-02-06 at 11 12 41 am](https://cloud.githubusercontent.com/assets/217057/22655135/334656c6-ec5d-11e6-8284-6ed8b143d860.png)

**Comment by charlesmchen** [comment]
This is done and released.
