### ISSUE TITLE
Missing localized string (german) when saving media item

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#1280]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When long pressing on a media item to copy/delete/save the item, the localized
string for saving is missing

### Steps to reproduce
- long press on media item

**Actual result:**
Showing: "Kopieren | Löschen | Save"
**Expected result:**
Should show: "Kopieren | Löschen | Speichern"
### Screenshots
<img src="https://cloud.githubusercontent.com/assets/9985963/17028386/bb527524-4f67-11e6-891b-46d917c35eb5.PNG" width=300>

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.3
**Signal version:** 2.4.0.2 (Testflight)

P.S.
From Testflight:

Does anybody even read these notes?

Yes I do! ;-)

**Comment by michaelkirk** [comment]
Translations are done at https://www.transifex.com/. Looks like this has been since translated in German, so it'll go out in the next build.

**Comment by michaelkirk** [comment]
>> Does anybody even read these notes?

> Yes I do! ;-)

Good to know! ❤️
