### ISSUE TITLE
Crashes when connected to VPN/Tor

### ISSUE THREAD

**Issue by signal-101** [WhisperSystems/Signal-iOS#1310]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Describe here the issue that you are experiencing.

App crashes (actually backgrounds itself repeatedly) on boot while connected to VPN.
### Steps to reproduce
- turn on VPN
- open app
- app backgrounds
- rarely creates debug

**Actual result:**
- have to repeatedly close and attempt to reopen.
- works 85% of the time if I switch on then off airplane mode before attempting to open the app

**Expected result:**
- turn on VPN
- open app
### Screenshots

None
### Device info

**Device**: iDevice 5,3
**iOS version**: 9.3.2
**Signal version:** 2.4.0
### Link to debug log

https://github.com/WhisperSystems/Signal-iOS/issues/1309

**Comment by signal-101** [comment]
VPN setup:

Phone -> OpenVPN app -> Amazon web services VPN endpoint running OpenVPN -> squid proxy -> Tor SOCKS server -> Tor network -> Internet

Does not crash on direct connection to the Internet.

**Comment by michaelkirk** [comment]
Crash log over in: https://github.com/WhisperSystems/Signal-iOS/issues/1309

**Comment by michaelkirk** [comment]
Is this still an issue with the latest release? (2.6.1)

**Comment by mkb** [comment]
I'm using Signal  with a VPN and I'm not having this issue. If I can provide any additional info to help narrow this down, just give a shout.

* Signal 2.6.5
* iPhone 6
* iOS 10.1.1

**Comment by signal-101** [comment]
Works fine after upgrading to a newer version of hardware.

**Comment by michaelkirk** [comment]
Thanks for the update.
