### ISSUE TITLE
Debug log enabled by default in production build 

### ISSUE THREAD

**Issue by PeterTonoli** [WhisperSystems/Signal-iOS#1312]
- [X] I have searched open and closed issues for duplicates

I'm creating this duplicate issue to reopen #39 . 

As of iOS build 2.4.1.x, the debug log is on by default. @FredericJacobs wrote that the debug log would be disabled in version 1.0.5, and further a 'stable' release of version 2. 

While the debug log can be disabled, this relies on users being adequately informed that debugging is on by default, as well as how to disable it, which I don't believe so (as it's hidden under 'advanced settings', with no contextual help as to what the option does, nor the potential risks of having debug on).

**Comment by alist** [comment]
What's the status of this?

**Comment by nrizzio** [comment]
I think debug logs were intentionally kept on by default: https://github.com/WhisperSystems/Signal-iOS/pull/1313#issuecomment-263304437

**Comment by michaelkirk** [comment]
Debug logs are super useful to us, and disabling them by default just makes it that much less likely that we'll get useful bug reports from most users. The paranoid can disable it.
