### ISSUE TITLE
iOS accessibility 'Darken Colours' also darkens whites

### ISSUE THREAD

**Issue by NiklasBr** [WhisperSystems/Signal-iOS#1317]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When activating the accessibility to increase contrast the header in Signal become less contrasty.

### Steps to reproduce
 1. Enter *Settings: General: Accessibility: Increase Contrast*
 2. Enable *Darken Colours*
 3. Open *Signal*

**Actual result:** The icons and tabs in the header turns grey, decreasing contrast. The blue colour keeps its hue/lightness.
**Expected result:** I would expect the blue header to be somewhat darker while the white parts would remain white (just like signal strength, clock, and battery remain white in the header).

### Screenshots

![img_4646](https://cloud.githubusercontent.com/assets/279826/17889379/32ead52c-6930-11e6-9e7f-9dda2366e6e2.PNG)

### Device info

**Device**: iPhone SE
**iOS version**: 9.3.4
**Signal version:** 2.4.1

### Link to debug log
n/a

**Comment by Calefornia** [comment]
I can look at the colors in Xcode later, but I wanted to first show that its not unique to Signal. The Timer app also has the white circle become dark...
![fullsizerender-1](https://cloud.githubusercontent.com/assets/7418271/18413502/2fe665a4-7799-11e6-808e-e7e1e9fce100.jpg)

**Comment by michaelkirk** [comment]
This is a system wide heuristic which we can't control.

**Comment by NiklasBr** [comment]
Thanks for looking into this, @michaelkirk 

Are you sure this is a system wide heuristic? Some apps such as Google Authenticator can do full white on blue without turning grey when Darken Colours are activated. See with, and without the setting activated:

![fullsizerender 2](https://cloud.githubusercontent.com/assets/279826/18439597/5314bfbc-7906-11e6-9886-b3db2cf00699.jpg)
![fullsizerender](https://cloud.githubusercontent.com/assets/279826/18439598/533f9f2a-7906-11e6-927f-745198f80746.jpg)
