### ISSUE TITLE
Use the native keyboard for IOS conversations

### ISSUE THREAD

**Issue by wdormann** [WhisperSystems/Signal-iOS#1318]
- [ x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Some iOS keyboards use learning from what you've typed, such as SwiftKey.  Signal should use the native keyboard for text input when chatting, just like many web pages in Safari do when entering text into a password field.  (when selecting such a field, the custom keyboard is swapped back to the native iOS keyboard).

### Steps to reproduce
Install SwiftKey keyboard for iOS
Start typing a message to somebody in Signal

**Actual result:** 
Notice that SwiftKey is being used for the messages sent via Signal.

**Expected result:** 
Signal should switch to the native keyboard to avoid the possibility that anything you type is learned and/or used in other ways.

### Device info

**Device**: iPhone 6s
**iOS version**: 9.3.5
**Signal version:** 2.4.1

**Comment by hoechenberger** [comment]
I strongly disagree. It should be the users' choice which keyboard to use. I would stop using Signal if it forced me to use the native keyboard, which I don't like.

**Comment by michaelkirk** [comment]
We won't be doing this.
