### ISSUE TITLE
Localized text cropped in "accept new key" dialogue

### ISSUE THREAD

**Issue by nixnuex** [WhisperSystems/Signal-iOS#1324]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The dialog asking for the acceptance after a key change notification has too limited space for some localized strings (e.g. in German), leading to missing words.

### Steps to reproduce
- Change your language to German
- Provoke the receipt of a key change notification and tap on it

**Actual result:** The localized string "Neuen Identitätsschlüssel in Zwischenablage kopieren" ends up as "Neuen Identitätsschlüsse...Zwischenablage kopieren" due to space limitation. This might be unclear for the user.
**Expected result:** The dialogue text should be fully readable, maybe covering two lines in case it's needed.

### Screenshots
![signal](https://cloud.githubusercontent.com/assets/2345318/18487915/6d338300-79f7-11e6-9b37-fdfd3494f809.jpg)

### Device info

**Device**: iPhone 6
**iOS version**: 10.0
**Signal version:** 2.4.1

**Comment by RiseT** [comment]
As an alternative, one could cut down these strings to their essentials. Removing "new" for example.

The whole layout seems a bit off. E. g. the actual key should start with a new line.

**Comment by michaelkirk** [comment]
This is getting overhauled as part of the new fingerprint format.

**Comment by RiseT** [comment]
For the meantime, I've just shortened "Identitätsschlüssel" (identity key) to "Schlüssel" (key) in the German translation. Should suffice. In Signal Android, it has been translated the same way for a long time.

**Comment by nixnuex** [comment]
Fixed in 2.6.0
