### ISSUE TITLE
Generate localizable strings with `genstrings`

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1331]
Our current manual process for managing localizable strings is a pain.

1. time consuming
2. error prone
3. redundant
4. doesn't remove unused strings
5. makes it less likely that translation hints get updated

Our current source strings live in a single file, at https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/translations/en.lproj/Localizable.strings

When new strings are needed they are added manually to that file (mostly manually anyway, see `Signal/translations/bin/genstrings-for-file` for a small step in automation). Recently I've started also including translation context hints to NSLocalizedString, and also manually copying them into our strings file. What a waste! 

The proposed process should populate en.lproj with string file(s) containing all the strings used in Signal-iOS, SignalServiceKit, and JSQMessagsViewController.

Pull requests welcome!

**Comment by nixnuex** [comment]
I set up a little tool: pull #1333. Is this what you were thinking of?

**Comment by nixnuex** [comment]
Fixed in  #1411 and  #1333.
