### ISSUE TITLE
Cannot receive invites to group chat, get "Received unsupported attachment type." error

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [WhisperSystems/Signal-iOS#1341]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When my friend invites me to a group chat, I don't see the group chat anywhere in the UI for me to tap on and join, and in my chat with him I see an error message that says "Received unsupported attachment type."

### Steps to reproduce
- Friend invites me to group chat.

**Actual result:** In the chat between my friend and I, when he invites me, I just see an error message saying "Received unsupported attachment type."  And I don't see the group chat in the UI available anywhere for me to join.  He says that on his app, he's able to see me as a participant in the group.

**Expected result:** I'm new to the app, but I would imagine the group chat would appear in my Inbox, and that I wouldn't get any error messages in my chat with my friend.

### Screenshots
![inbox showing chat with friend, and test group I created (not group I was invited to)](https://cloud.githubusercontent.com/assets/3108318/18726788/d4ff53ca-7ffa-11e6-8e14-2a7f26c85393.PNG)
![chat with friend showing error messages when he invites me to group](https://cloud.githubusercontent.com/assets/3108318/18726789/d5067cae-7ffa-11e6-80c4-ef6a76cd9ec7.png)

### Device info
**Device**: iPhone SE
**iOS version**: 10.0.1
**Signal version:** 2.4.2

### Link to debug log
After tapping "Submit Debug Log" it gives me a dialog to choose GitHub issue or email.  When I choose GitHub issue, it just takes me to the issues section of this GitHub repo in my phone's browser.  There's no link as far as I can see for the debug log.

**Comment by michaelkirk** [comment]
This was a new bug introduced in 2.4.2. It only affects groups without avatars though. The work-around is to add a group avatar.

It'll be fixed properly in the forthcoming 2.5 release with https://github.com/WhisperSystems/SignalServiceKit/commit/1824af5335d8faa9f30eed40f0e1dc8198650ceb

**Comment by Amit-PivotalLabs** [comment]
Thanks, workaround worked.
