### ISSUE TITLE
Show alert when attempting to take photo after disabling camera permission.

### ISSUE THREAD

**Issue by speedygonzalez1103** [WhisperSystems/Signal-iOS#1346]
## Edited Bug Description (original follows)

When attempting to take a photo after disabling camera permissions there is no indication that Signal doesn't have the appropriate permissions.
### Steps to reproduce
- in settings.app go to Signal and disable camera permissions
- go to a chat in signal
- press clip symbol to attach 
- choose "take picture or video"

**Actual result:** Camera app opens, but shows black screen.

**Expected result:** An alert showing:

**Title:** Signal Doesn't Have Permission to Use Your Camera.
**Description:**
To take a photo, first open your systems Settings app, scroll down to Signal, and enable the camera permission.
### Bug description

Taking instant picture or video from within Signal chats shows photo and video app but black screen. You cannot take an instant picture or video from within Signal. White button to take picture or red button to record a video is not working. You can only press "cancel" to go back to Signal chat.
### Steps to reproduce
- go to a chat in signal
- press clip symbol to attach 
- choose "take picture or video"

**Actual result:** Camera app opens, but shows black screen. White button to take picture is not working. You can only click on "cancel" to go back to chat screen. You can swop to video but red record button is not working. Camera is generally working well. I can take a picture or video through the standard iOS camera app itself, and can attach it to a chat through "choose from photo gallery ..."
**Expected result:** I would expect to see camera picture to take an instant photoshot or videoshot to attach to your chat.
### Device info

**Device**: iPhone 5S
**iOS version**: 10.0.1
**Signal version:** 2.4.2

**Comment by michaelkirk** [comment]
Can you attach a screenshot of your privacy settings?

Go to Settings, then scroll all the way down to Signal. It should look like this:
![image](https://cloud.githubusercontent.com/assets/217057/18809064/0e761236-8241-11e6-8101-629586d30d87.png)

**Comment by speedygonzalez1103** [comment]
Thanks. My Settings were not correct. It is now working as expected.

**Comment by Trolldemorted** [comment]
Nevertheless, Signal maybe should display an error in this case.

**Comment by michaelkirk** [comment]
> Nevertheless, Signal maybe should display an error in this case.

Agreed.

**Comment by michaelkirk** [comment]
solved in 
https://github.com/jaropawlak/Signal-iOS/commit/4df1c45acba7354693e4f079624e4fd6676d4844
