### ISSUE TITLE
Scanning non-linking code should give a useful response

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1347]
### Bug description

When you're on the link desktop screen and you scan some random code, you don't get any good feedback that the code you scanned is invalid. 

### Steps to reproduce
- Running at least 2.5.0(currently in beta)
- Go to settings > linked devices > link new device
- Scan some random QR code, e.g. a fingerprint QR code.

**Actual result:**
- See "Link this Device?" alert.
- When you tap to confirm, the alert is dismissed and you're still looking at the QR Scanning screen.

**Expected result:** 

### Should see alert

- **Title:** Invalid Linking Code.
- **Description:** The code you scanned doesn't look like a valid linking code.
- **Actions** 
  - **Retry:** Dismisses the alert and restarts the capture session.
  - **Cancel:** Pops you back to the "Linked Devices" manager screen.

**Comment by mdouglass** [comment]
Just a note, I'm starting work on this issue.

**Comment by michaelkirk** [comment]
In https://github.com/WhisperSystems/Signal-iOS/commit/bbfffdf79f0ac374ee3c811006e224c49a55e850

**Comment by michaelkirk** [comment]
Thanks!
