### ISSUE TITLE
Signal 2.5.1 early crash on startup

### ISSUE THREAD

**Issue by nixnuex** [WhisperSystems/Signal-iOS#1350]
### Bug description
After upgrading to 2.5.1 Signal crashes on startup. Tested on iOS 10.0.1 & 10.0.2.

Log: https://gist.github.com/anonymous/eaf512f5417659c23cf36a2cc11e774b

### Device info

**Device**: iPhone 6
**iOS version**: 10.0.2
**Signal version:** 2.5.1

**Comment by echo743** [comment]
looks like a duplicate of #1348

**Comment by nixnuex** [comment]
Indeed, sorry for duplication... 😚
