### ISSUE TITLE
Crash at start (iOS App)

### ISSUE THREAD

**Issue by drombo** [WhisperSystems/Signal-iOS#1352]
### Bug description
iOS App 2.5.1 does not start. It crashs immediately on my iPhone6 with iOS 10.0.2

### Steps to reproduce
Try to start the app

**Actual result:** crash
**Expected result:** app starts

### Device info

**Device**: iPhoen 6
**iOS version**: 10.0.2
**Signal version:** 2.5.1

**Comment by echo743** [comment]
looks like a duplicate of #1348 

>Fix will go out in the next release, coming soon. Stay tuned.

**Comment by michaelkirk** [comment]
Should be fixed by 2.5.2 available in the app store now.
