### ISSUE TITLE
Request for contacts uses creepy wording

### ISSUE THREAD

**Issue by fulldecent** [WhisperSystems/Signal-iOS#1354]
On first app launch, Signal for iOS requests access to your contacts and refuses to operate unless you do. The explanation given is

 > Signal requires access to your contacts. We do not store your contacts on our servers.

This is an equivocation and it makes me not trust Signal. I immediately deleted the app. Negative reviews on the App Store show other people with similar feelings. There are several valid ways to interpret the given explanation. Please instead use more concrete wording that avoids ambiguity.

Possible replacements for first sentence:

> Signal requires complete access to all your contacts' details to make money.

> Signal only allow you to add friends if they are your contacts because ...

> Signal finds other users by phone number. Currently the only supported way to find contacts is to share just the phone numbers (and nothing else) from your contacts list.

Possible replacements for the second sentence:

> We do not store your contacts on our servers; instead, we store them on a shared host in Russia.

> We send this to Signal's servers to find friends. Signal then immediately deletes this information and does not keep "backups".

> Your information is not sent to / stored on our servers.

**Comment by michaelkirk** [comment]
I agree that the wording is lacking.

FYI - We hash the numbers on the device and upload the hashes to the server to compute an intersection without ever sending the plain text to the server. On the server we immediately compute the intersection and do not store your relations on the server.

**Comment by pavellishin** [comment]
> We hash the numbers on your device and upload the hashes to the server to compute an intersection without ever sending the plain text phone numbers to the server.

There are only 10,000,000,000 possible U.S. phone numbers. That seems like a trivial amount to hash into a lookup table.

**Comment by michaelkirk** [comment]
@pavellishin
See more: https://whispersystems.org/blog/contact-discovery/

**Comment by krishicks** [comment]
Why does Signal require continuous access to Contacts? I can see requesting it for the initial load of the app, but if I disable it later I get the above *"Signal requires access…"* message. I get the bootstrapping problem driving the initial need, but ongoing?

**Comment by michaelkirk** [comment]
Rather than having a "signal address book" and a "real people address book", we consider "signal users" to be "real people" on ios.

This allows us to continuously sync
- avatars
- names
- adding a contact
- removing a contact

There's definitely a world where this is optional. Contributions accepted.

**Comment by kwhitefoot** [comment]
Is there any reason why a forked version that does not request such privileges would not work?

**Comment by fulldecent** [comment]
Also, FYI hashing the phone number is the wrong way to do it.

Instead you hash both numbers together. For an undirected graph, you put them into numerical order:

 > sha('["+12125551212","+15105551212"]')

In a directed graph, you put them in follower-followed order:

 > sha('{"FOLLOWER":"+12125551212","FOLLOWED":"15105551212"}')

Now your brute force search space is squared. Also there's a way to salt this. Not perfect, but better.

**Comment by lorenzhs** [comment]
@kwhitefoot Open Whisper Systems does not appreciate forks using OWS's servers. You can run your own server, but Moxie explained why using theirs is not okay at https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165 -- see also https://lwn.net/Articles/687294/

**Comment by lorenzhs** [comment]
@fulldecent for your proposal to work, the servers would need to store everybody's address book. In my opinion, that would be much worse than the current state.

**Comment by michaelkirk** [comment]
OK folks. GH is for reporting bugs. Please take it to the forum or mailing list.

**Comment by michaelkirk** [comment]
replaced with more constructive #1356
