### ISSUE TITLE
iOS 10.0.2 / Signal 2.5.2: Turn off notifications of group chats, but not normal messages

### ISSUE THREAD

**Issue by ancelotto** [WhisperSystems/Signal-iOS#1367]
I cannot find any way to turn off the notifications of group chats only.

What I would like to have is a distinction in the iOS notifications between normal messages and group chats.

Background: A group chat with a lot of postings and turned on notifications can be really annoying. But still you want to get notifications from normal user messages.

Any ideas?

Thank you.

**Comment by michaelkirk** [comment]
I think this problem would be better solved by the feature request at https://github.com/WhisperSystems/Signal-iOS/issues/346

Closing as duplicate.
