### ISSUE TITLE
Terminating messages

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/Signal-iOS#1376]
I have been sending terminating messages to a friend using Android. 
The behaviour was quite strange; 
I created an ID for Android as well as for the desktop client which seems not to support this feature at all

[https://github.com/WhisperSystems/Signal-Android/issues/5766](url)
[https://github.com/WhisperSystems/Signal-Desktop/issues/941](url)

Iphone 6 - iOS 10.0.0.2 - Signal 2.6.0.13

**Comment by michaelkirk** [comment]
Based on the conversation in those other threads it seems like you've addressed your issue.
