### ISSUE TITLE
Music Stops on Opening Signal

### ISSUE THREAD

**Issue by StevenRoddis** [WhisperSystems/Signal-iOS#139]
It's not such an issue now, but when text messaging is added it'll have more of an impact.

**Steps to reproduce:**
1. Close Signal & Stop the app from running*
2. Play Music
3. Open Signal

**What Happens:**
Music stops

**What should happen:**
Music keeps playing unless a call is placed.

\*It always happens after stopping Signal but only sometimes if reopening the app.

**Comment by corbett** [comment]
@FredericJacobs this looks to be closed.
