### ISSUE TITLE
Settings menu should be more obvious for contacts

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1390]
Plenty of folks are having trouble finding our conversation settings menu.

Also related is that some folks literally *can't* get to the settings, e.g. tapping on the contact name doesn't do anything.

https://github.com/WhisperSystems/Signal-iOS/issues/1402
https://github.com/WhisperSystems/Signal-iOS/issues/788

Likely because we're detecting and strapping behavior to the native navbar title, which sometimes fails. We probably won't have this issue if we're defining our own title view.

**Comment by riyapenn** [comment]
Instructions below and [here](http://support.whispersystems.org/hc/en-us/articles/213134237-Does-Signal-have-disappearing-messages-) for those users who come across this issue and still want to discover disappearing messages (before this gets addressed):

iOS Users

To enable disappearing messages on iOS

Go to your conversation
Tap on your contact's name, number, or group name in the header
Tap on the Disappearing Messages button. When enabled the button slides to the right and display a blue background
Use the slider to set your message timer anywhere from 5 seconds to 1 week
Tap on the '<' back arrow in the top left 
See the clock icon in the conversation header
See the alert in your conversation thread with the disappearing message timer
Send or receive a Signal message
See the hour glass underneath the message bubble that has a timer

**Comment by jschneier** [comment]
Any idea how we want this to look? I know the 3 dots is what is used on Android but it doesn't really fit in with iOS (although Slack does it). Whatsapp does this scrolling text thing underneath the name (not a huge fan) and the builtin Messages app doesn't have the ability to call on it. None of these seem good but all seem better than what we have now. Thoughts @michaelkirk?

**Comment by jschneier** [comment]
I had some more thoughts about this this past weekend and submitted a PR that covers them, let me know what you guys think!

**Comment by charlesmchen** [comment]
Done, available in our next release.

**Comment by charlesmchen** [comment]
Hopefully this is fixed by #1773 which will be available in our next release.
