### ISSUE TITLE
Submit Verification Code not working

### ISSUE THREAD

**Issue by dbarros** [WhisperSystems/Signal-iOS#1391]
### Bug description

I just downloaded Signal from the iOS App Store. I enter my phone number and receive an SMS with a verification code and link. I tap the link and it opens Signal, but it never is able to verify the code. The app sits there with the progress spinner in the "Submit Verification Code" button, in a seemingly endless loop. I am on the latest version of iOS 10.

### Steps to reproduce
- Download Signal for iOS from the App Store
- Enter your mobile phone number
- In Messages, tap on the link with the verification code OR manually enter the received code.

**Actual result:** 

The code is never verified, the progress spinner endlessly spins in the "Submit Verification Code" button.

**Expected result:** 

I'd expect to continue and be able to use the app.

### Device info

**Device**: iPhone 6
**iOS version**: 10.0.1
**Signal version:** 2.5.3

**Comment by riyapenn** [comment]
A. Did you contact support@whispersystems.org or check the [support page here](http://support.whispersystems.org/hc/en-us/articles/213132457-Are-you-having-trouble-verifying-on-Signal-) to troubleshoot?  

1. Install (or Re-install) Signal
2. Go to iPhone Settings > Signal > **Enable Background app refresh**
3. Open Signal
4. Hit "OK" when you get the pop-up alerts asking "Signal" Would like to Send You Notifications, etc.
5. Enter your number to register with Signal
6. When you get the SMS, click on the verification link. Do NOT type in the numbers yourself.
7. If registration still has not completed, restart your phone and repeat steps 1-6 above.


B. The [current version of Signal is 2.6.0 ](https://itunes.apple.com/us/app/signal-private-messenger/id874139669?mt=8)so you may be interested in updating.

**Comment by dbarros** [comment]
Thank you @riyapenn. I did look in the discussion forums and the issues in the Github repo, but didn't go through the main site's Support section. 

The problem was the Background Refresh not being enabled for the app. Once I enabled it, it worked. 

Interesting though that it needs it. Is there a reason, since the app is the front-most app at the time while it's trying to verify the code?

**Comment by dbarros** [comment]
@riyapenn found more of an explanation here: https://github.com/WhisperSystems/Signal-iOS/issues/1329

Thank you for replying though.
