### ISSUE TITLE
It's no longer possible to get a public device fingerprint

### ISSUE THREAD

**Issue by Sidnicious** [WhisperSystems/Signal-iOS#1396]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
It no longer seems to be possible to get a publicly-shareable device fingerprint (e.g. [1](https://keybase.pub/chris/security_stuff/signal_fingerprint.txt), [2](https://yawnbox.com/index.php/2015/11/19/custom-stamp-for-my-signal-fingerprint/)).

Now that the fingerprints for a conversation have been combined into safety numbers (#1365), there isn't a single number that represents your Signal identity. This makes it impossible to verify that you're talking to the right person without meeting them in person or contacting them privately out of band.

### Device info
**Signal version:** 2.6.0

**Comment by michaelkirk** [comment]
This is as intended. The point of safety numbers is that we believe them to be a more useful way for most of our users to verify privacy than explicit verification of two identity keys.

And having *both* "Safety Number Verification" and "Identity Key Verification" UI's creates more options for our users, and would just muddy the waters for most folks.

That said, it is possible to extract your portion of the safety number if you'd like a stable ID to post publicly. 

- Split the numeric fingerprint in half and compare across two contacts. 
- Your half is the half that appears in both.

But this isn't the flow that we're optimizing for. If you'd like to discuss further, please take it to the mailing list or forum.
