### ISSUE TITLE
Messages are not always in order when using Signal Desktop

### ISSUE THREAD

**Issue by ejpcmac** [WhisperSystems/Signal-iOS#1398]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

When Signal iOS receive some messages exchanged via Signal Desktop while Signal iOS was offline, they are not in order.
### Steps to reproduce
- Get Signal iOS and Signal Desktop synchronised
- Disconnect the network on the iPhone
- Exchange some messages with another person via Signal Desktop
- Connect the network again on the iPhone to synchronise Signal iOS

**Actual result:** All your messages are printed first in the conversation, then the other part’s ones.

**Expected result:** Your message and other part’s ones follows like in Signa Desktop.
### Screenshots

On Signal Desktop:

![capture d ecran 2016-10-15 a 19 10 35](https://cloud.githubusercontent.com/assets/6207605/19411946/49cc44f6-930b-11e6-81ed-c344f1dfe95c.png)

On Signal iOS:
![signal](https://cloud.githubusercontent.com/assets/6207605/19411964/8ac5d080-930b-11e6-89b0-b67ebc3454b8.jpg)
### Device info

**Device**: iPhone 5C
**iOS version**: 9.3.5
**Signal version:** 2.6.0

**Comment by michaelkirk** [comment]
I believe the underlying error is that we're sorting by timestamp that the message was created on the users device. So, when the participants clocks aren't in sync we get this misordering. 

A better solution would be to order messages by when we received them.

**Comment by ejpcmac** [comment]
I’ve just checked, and the 3 devices used (my iPhone, my Mac and other part’s iPhone) have the same time with a maximum of 1 second in difference. I’ve done another test, waiting 30 seconds between each message and the problem remains the same.

**Comment by vlovich** [comment]
Able to reproduce 100%.  Messages sent from to myself from desktop appear at the top of all messages on iOS rather than interleaved in message order.

**Comment by joostrijneveld** [comment]
Interestingly, the iOS client still shows accurate timestamps for each of the messages. This causes a sequence of non-chronological timestamps in between the message bubbles (i.e. my messages would be sent at 21:00 and 22:15, and replies came in at 21:30 and 23:00, and would be timestamped as such, but still ordered [mine][mine][theirs][theirs]).

This can be observed by keeping the iOS device offline over the span of a low-throughput conversation that lasts over a longer period of time (although I'm uncertain what the threshold is before these timestamps are inserted).

**Comment by charlesmchen** [comment]
Done.
