### ISSUE TITLE
Can't get to conversation settings for some contacts

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1402]
- Enter conversation
- Tap on conversation title

_Expected behavior:_ push to conversation settings screen.

_Actual behavior:_ nothing happens.

This seems to only affect certain conversation threads.

**Comment by 2-4601** [comment]
Haven't seen/used Signal iOS for months but could this be related to #788?

**Comment by michaelkirk** [comment]
Thanks for your eternal vigilance. =)

I wouldn’t be surprised if it *is* related as I re-purposed the existing gesture recognition code.

**Comment by MarcoZehe** [comment]
Note that double-tapping on the conversation header with VoiceOver on, which simulates a normal tap gesture, never opens the conversation settings in any conversation for VoiceOver users. Might be related to this.

**Comment by riyapenn** [comment]
Current work around for users is to remove the last name of the contact.

1. Go to contact's entry in iPhone contact's list
2. Edit entry to remove the last name of this contact
3. Save the change
4. Open Signal
5. Select existing conversation thread or create new conversation thread with contact
6. Tap on contact name

**Comment by riyapenn** [comment]
Log for user where this was an issue and then resolved by editing (adding) the last name where only first name and company existed prior to resolving: https://gist.github.com/ddbcbaf15ba1578a6db3cd574a3c3df4

**Comment by charlesmchen** [comment]
Hopefully this is fixed by https://github.com/WhisperSystems/Signal-iOS/pull/1773 which will be available in our next release.
