### ISSUE TITLE
Translation to Simplifier Chinese

### ISSUE THREAD

**Issue by charleslcso** [WhisperSystems/Signal-iOS#1404]
I would like to see how difficult (both technical, politics & App Store wise) it is to add a translation so the Chinese can use Signal on iOS before actually doing it myself. 

As there's no easy way to side load an app, I guess I must go thru the App Store for a new Signal version. Or I should add to the main branch instead?

**Comment by 2-4601** [comment]
You can translate the simplified Chinese version of Signal at Transifex: https://www.transifex.com/open-whisper-systems/signal-ios/language/zh_CN/

**Comment by charleslcso** [comment]
I see.

But I got a 403…

**Comment by 2-4601** [comment]
You need to create an account first: https://www.transifex.com/signup/

**Comment by charleslcso** [comment]
Got in.

Let me see what I can do.

**Comment by michaelkirk** [comment]
Yes, please do! zh_CN has been a little quiet lately.

Closing this as translation work is done in transifex.
