### ISSUE TITLE
Showing Avatars in Chats

### ISSUE THREAD

**Issue by ishi121** [WhisperSystems/Signal-iOS#1405]
Hello,

I need some help regarding Avatars.
How i can enable avatars in chats?

The JSQMessangerViewController says you need to set the size of the avatar on `viewDidLoad `method, So i set the size of the avatar

`self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeMake(50.0f,50.0f);
self.collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeMake(50.0f,50.0f);
`

Then i have to return the avatar image in the following method

`- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath`

Right now it is returning nil

So how i can return avatar from here? I dont know how I can get avatar image date.
I Hope someone can help me here :)

**Comment by michaelkirk** [comment]
The original request for this feature is #321. I think it was inadvertently closed, so I reopened it and am closing this issue.

> So how i can return avatar from here? I dont know how I can get avatar image date.

Avatars are already rendered in the SignalsViewController. See if you can trace it back from there.
