### ISSUE TITLE
Update error-message/re-try send string for sending to unregistered number

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1417]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Replace string "Failed to send message." with  "Your contact is no longer a Signal user."

### Steps to reproduce
- Message Bob who has just unregistered
- See message did not send as it is gray and states "Sending failed. Tap to retry."
- Tap on message bubble to retry

**Actual result:** -  re-try message send alert says
"Failed to send message."
Action items: 
Send again
Delete
Cancel

**Expected result:** re-try message send alert says
"Your contact is no longer a Signal user."
Action items: 
Send again (Until invite option/flow is available)
Delete
Cancel

### Screenshots

![fullsizeoutput_20](https://cloud.githubusercontent.com/assets/4898366/19703554/0f4407fa-9ab9-11e6-8e2e-e49b9b834536.jpeg)

### Device info

**Device**: iPhone 5C
**iOS version**: 10.0.2 (14A456)
**Signal version:** 2.6.3.8

**Comment by michaelkirk** [comment]
in 2.6.3.10
