### ISSUE TITLE
Update error-message/re-try send string for sending FROM unregistered number

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1418]
- [X] I have searched open and closed issues for duplicates

---
### Bug description

Replace string "Request failed: unauthorized (401)" with "Your device is not registered. Re-register or re-install Signal."
### Steps to reproduce
- Device A has a registered, working Signal number on iOS
- Register Device B with same phone number as Device A
- Device A is no longer registered
- Send message from Device A to a Signal contact
- See message did not send as it is gray and states "Sending failed. Tap to retry."
- Tap on message bubble to retry

**Actual result:** re-try message send alert says
"Request failed: unauthorized (401)"
Action items: 
Send again
Delete
Cancel

**Expected result:** re-try message send alert says
"Your device is not registered. Re-register or re-install Signal."
Action items: 
Re-register Signal (when this flow is available)
Delete
Cancel
### Screenshots

![fullsizeoutput_19](https://cloud.githubusercontent.com/assets/4898366/19702642/55d79802-9ab5-11e6-99e4-8619528e89c3.jpeg)
### Device info

**Device**: iPhone 5C
**iOS version**: 10.0.2 (14A456)
**Signal version:** 2.6.3.8

**Comment by riyapenn** [comment]
Unfortunately this is fairly common with users installing Signal iOS on an iPad after having it set up on an iPhone (where they used the same phone number to register both devices).

Temporary solution is to remove Request failed: unauthorized (401) and replace it with more information: "This device is no longer registered for use with Signal. Re-install Signal to register this device." (Would be a nice touch to replace "device" with iPhone, iTouch, iPad) 

Real solution: to make it clear to users that Signal iOS can only be registered to one device per phone number https://github.com/WhisperSystems/Signal-iOS/issues/959

**Comment by michaelkirk** [comment]
in https://github.com/WhisperSystems/Signal-iOS/commit/94d37d9c558bae363503a9665ad3fb99903be4d7
