### ISSUE TITLE
Message displayed on iOS occasionally trimmed

### ISSUE THREAD

**Issue by neoatlantis** [WhisperSystems/Signal-iOS#1422]
I suspect this relates to iOS, to reproduce, I would suggest:
1. send encrypted message
   1.  from a registered Android 6 phone using latest Signal App as of 2016-10-28 from Google Play,
   2.  to a registered iOS phone with also latest App downloaded.
2. the message were in Chinese, ranging from 20-40 characters.
3. as illustrated in attached screenshot, the message sent from Android were received, decrypted okay, but **sometimes only the first line could be displayed**. This happens only **occasionally**, since the pixel'ed message received under that were okay though longer.
4. long-press on the trimmed message, select-all, copy, then paste it to the input box, will get the full length.

![mmexport1477610109958_marked](https://cloud.githubusercontent.com/assets/2693447/19789087/183ad1c2-9cad-11e6-8ebc-ee83a0153fe9.jpg)

**Comment by michaelkirk** [comment]
If you can share any non-redacted text which replicates this issue, that would be helpful.

**Comment by miyar520** [comment]
The same problem occurs in Japanese as well, when the message is longer than 16 characters in Japanese. For example, if the text is

１２３４５６７８９０１２３４５６７８９０

(which is 123...90123...90 in Japanese), then the Signal displays only

１２３４５６７８９０１２３４５６

(i.e., 123...9012...56). This is displayed as the first line in a bubble, while the second line is blank.

As neoatlantis writes, copying and pasting the displayed message recovers the entire message.

**Comment by michaelkirk** [comment]
@miyar520 / others - Can you please provide the exact text and format so I can copy and paste it? As of yet I'm not able to reproduce, which will make this much simpler to solve.

**Comment by neoatlantis** [comment]
@michaelkirk  I tried another sentence, easy to reproduce。 

![signal-2016-10-29-181042-edited](https://cloud.githubusercontent.com/assets/2693447/19831253/8179f34e-9e05-11e6-9b8a-46765cdd7f9f.jpg)

both sending and receiving can cause, use these text for test:

1. `你看看是不是什么特定长度的句子的锅`
2. `你看看是不是什么特定长度的句子的`
3. `你看看是不是什么特定长度的句子`
4. `你看看是不是什么特定长度的句子的锅呢？！`
5. `你看看是不是什么特定长度的句子的锅呢呢呢呢呢呢？`
6. `一只敏捷的棕色狐狸跳过了一只懒惰的狗`
7. `一只敏捷的棕色狐狸跳过了一只懒惰的`:dog: （with a dog emoji at last)
8. `一百只敏捷的棕色狐狸跳过了一只懒惰的狗`

----

It does **NOT** happen with latin characters, see:

![mmexport1477758772826](https://cloud.githubusercontent.com/assets/2693447/19831287/ab78f48c-9e06-11e6-9200-92b8b15af63a.jpg)

**Comment by neoatlantis** [comment]
All tests on iPhone 6s, iOS 10.1
Another test shows it seems trimming the last line, see:

1. `这是一条纯中文的消息苟利国家生死以岂因祸福避趋之图样图森破搞个大新闻`
2. `这是一条中文加标点的消息……苟利国家生死以……岂因祸福避趋之……图样图森破……搞个大新闻……`   **Notice this is displayed correctly**
3. `这是一条中文加标点的消息，苟利国家生死以?岂因祸福避趋之！图样图森破。搞个大新闻。`
4. `这是一条中文加English的消息苟利国家生死以岂因祸福避趋之too young too simple 搞个大新闻` **This is also correct**
5. `这是一条中文加表情符号的消息`:frog:`苟利国家生死以岂因祸福避趋之图样图森破搞个大新闻`:eyeglasses:
6. `这是一条字数较少的消息苟利国家生死以岂因祸福避趋之`

My friend points out that 1) message mixed with `.……` or English words made it displayed correctly, and 2)if you mix with emoji, the last line height will increase.

![mmexport1477759186696](https://cloud.githubusercontent.com/assets/2693447/19831364/4ef3b79a-9e08-11e6-910c-055802c99455.jpg)

**Comment by neoatlantis** [comment]
My friend points out that 1) message mixed with `……` or English words made it displayed correctly, and 2)if you mix with emoji, the last line height will increase.

Is it possible that you are calculating the bubble's height by some formula related to the message length? Each CJK character will be counted as 1 character but takes doubled space to display.

![demostrate](https://cloud.githubusercontent.com/assets/2693447/19831666/2e2a54f8-9e10-11e6-8236-afdf23e41e41.png)

The first long text:
`庆历四年春滕子京谪守巴陵郡越明年政通人和百废具兴乃重修岳阳楼增其旧制刻唐贤今人诗赋于其上属予作文以记之helloworld予观夫巴陵胜状在洞庭一湖衔远山吞长江浩浩汤汤横无际涯朝晖夕阴气象万千此则岳阳楼之大观也前人之述备矣然则北通巫峡南极潇湘迁客骚人多会于此览物之情得无异乎`

The second text:
`庆历四年春滕子京谪守巴陵郡越明年政通人和百废具兴乃重修岳阳楼增其旧制刻唐贤今人诗赋于其上属予作文以记之helloworld予观夫巴陵胜状在洞庭一湖衔远山吞长江浩浩汤汤横无际涯朝晖夕阴气象万千此则岳阳楼之大观也前人之述备矣然则北通巫峡南极潇湘迁客骚人多会于此览物之情得无异乎a lazy fox jumps over a quick brown dog`

Both displayed wrong, and now it bugs to display approx. 2 less lines, cause of larger calculation error?

**Comment by mdouglass** [comment]
With the text suggested by @miyar520 above (１２３４５６７８９０１２３４５６７８９０) I was able to repro this in the iOS 10 simulator for the iPhone 7.  It looks like it is caused by the fix for #1368. If I disable that code (by setting isIOS10OrGreater = NO at OWSMessagesBubbleSizeCalculator.m:59) then the bubble displays correctly. 

with 1368 fix:
![with 1368 fix](https://cloud.githubusercontent.com/assets/5410142/19832240/632b401e-9dd3-11e6-896f-dd6788e50d8d.png)

without 1368 fix:
![without 1368 fix](https://cloud.githubusercontent.com/assets/5410142/19832241/63478788-9dd3-11e6-86a5-016a391ff4e2.png)

I'm going to take a look at backing out the fix for #1368 and see if I can find something that doesn't cause an issue here.

**Comment by neoatlantis** [comment]
@mdouglass Seems you are testing the [full-width numeric characters](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)? Then it really has something to do with calculating bubble size.

**Comment by miyar520** [comment]
@michaelkirk If you haven't been able to reproduce the problem, please suggest how to "provide the exact text and format." Being not a programmer, I am not sure what you want me to do and how. As @neoatlantis wrote, the text that I wrote was "12345678901234567890" with full-width numeric characters (in UTF-8). The problem itself will occur for any characters in Chinese, Japanese, or Korean (CJK).

**Comment by i7u** [comment]
I can confirm this bug on latest app version on latest iOS. Debug log:
https://gist.github.com/24cb6f44cad4b46eea32441f36e66cde
Issue occurs rather reliably when using Chinese only characters, it's fine with ASCII.

The sender sees a trimmed message:
![sender](https://cloud.githubusercontent.com/assets/2001138/19883355/cbef1c44-a00b-11e6-8e8e-52b53607b9a4.jpeg)

The recipient sees the complete message:
![recipient](https://cloud.githubusercontent.com/assets/2001138/19883361/d3d41176-a00b-11e6-8ced-76afe3e8920a.jpeg)

**Comment by michaelkirk** [comment]
> I'm going to take a look at backing out the fix for #1368 and see if I can find something that doesn't cause an issue here.

@mdouglass - I want to pick this up today unless you had something imminent.

**Comment by mdouglass** [comment]
I haven't made progress yet.  Go ahead and take it.
