### ISSUE TITLE
Can't message re-registered user unless they are in your contacts

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1430]
### Bug description

It's impossible to message someone who unregistered and then re-registered without adding them to your contacts.

#### Given
- Possum and Squirrel register for Signal
- Possum has Squirrel in her contacts.
- Squirrel does not have Possum in her contacts.
- Possum successfully sends Squirrel a message.
- Squirrel sees a message from +15555555555
- Squirrel can respond to Possum in the "+15555555555" thread.

#### When
- Possum uninstalls Signal =(
- Squirrel messages Possum and sees "Unregistered Number"
- Possum re-install Signal =)
- Squirrel messages Possum in their existing thread

#### Expected result

- Squirrel **should** see "Safety Numbers for +15555555555 Changed."

#### Actual result

- Squirrel sees "Sending failed" <-- FIXME
- Squirrel adds Possum to her contacts
- Squirrel resends the message to Possum
- Squirrel sees "Safety Numbers for +15555555555 Changed."

**Comment by riyapenn** [comment]
Closing as not seeing this as an issue anymore.  Even the re-send alerts the user that a safety number changed and needs to be accepted to successfully send again. Will re-open if this still exists for users on Signal iOS 2.10+
