### ISSUE TITLE
Support Arbitrary Filetypes

### ISSUE THREAD

**Issue by xanderdunn** [WhisperSystems/Signal-iOS#1431]
Support sending arbitrary file types.  I tried to send a PDF and was told it wasn't a supported file type.  I think PDFs, as well as pretty much any filetype, should be supported.  Is there any reason not to?

**Comment by strugee** [comment]
See also WhisperSystems/Signal-Android#993

**Comment by TreatyOfRome** [comment]
Issue could be closed. This feature has just been released in v2.11.1. :tada:

**Comment by charlesmchen** [comment]
Thanks @TreatyOfRome
