### ISSUE TITLE
Make it easier (or possible?) to use Signal for iOS in conjuction with signal-cli

### ISSUE THREAD

**Issue by mrkiko** [WhisperSystems/Signal-iOS#1438]
Make it easier to use Signal Private Messenger App in conjuction with signal-cli:
https://github.com/AsamK/signal-cli

and in general, provide an alternative to QR code, if possible and makes sense.
Thanks.

**Comment by michaelkirk** [comment]
I don't use signal-cli, so I'm not even sure what you're actually requesting, but we aren't supporting linking clients outside of the official OWS Signal clients.

**Comment by Trolldemorted** [comment]
what do you want to do?

link a signal-cli slave device to your signal-iOS, or link signal-iOS as a slave to your signal-cli master?

**Comment by mrkiko** [comment]
Thank you for your answer. I apreciate it very much.

By the way, I would like to have signal-cli as a slave to my iOS device, but I may also go the other way around if it's deemed necessary.
Using signal-cli could be very confortable to me: I actually find very confortable using command-line apps with my brailledisplay and for other reasons.
Thank you very much

**Comment by mrkiko** [comment]
Thank you very much for your reply.
My opinion is that, wether you are going tosupport unofficial clients or not, providing an alternative to QR would be a good idea, for accessibility sake.
thank you for your reply again,

**Comment by Trolldemorted** [comment]
You maybe should propose that signal-cli creates qrcodes, if you want a quick solution.

**Comment by mrkiko** [comment]
And then scan the screen with the iPhone?
Or maybe print the result somewhere?
Thank you guys again,

**Comment by Trolldemorted** [comment]
scanning the screen should work, why shouldn't it?

**Comment by mrkiko** [comment]
Thank you.
