### ISSUE TITLE
Development test accounts / documentation?

### ISSUE THREAD

**Issue by lazerwalker** [WhisperSystems/Signal-iOS#1442]
I have a question regarding best practices surrounding working on this app.

The last time I submitted a patch to this repo, I verified my changes by logging in as my own phone number, and sending a message to a friend (which I did on-device, since the simulator didn't have access to my phone book). 

This was pretty sub-par as a development experience. It was easier for me to test on-device rather than in the simulator, which isn't great. Registering a second copy of the app with my phone number seems to have screwed up my production copy of the app (I'm talking with support). I had to find and bug a friend with test messages, which is annoying and doesn't really scale.

Is there a better standard way of sending and receiving test messages? Be it a whole separate development server, a test development account one can access, or even just a known bot account you can message willy-nilly. 

If this already exists: it would be great if this lived in the README or similar!

If it doesn't: I'd love to see something like this exist, or (if its omission is is a conscious choice) hear why such a thing doesn't exist. If it's just for lack of attention, I'm potentially happy to help contribute some code time, if it can help lower the barrier to entry for new contributors.

**Comment by Trolldemorted** [comment]
Signal-cli can send and receive messages, i am using it with an old mobile number and it works great.
If your landline phone is able to receive sms you may also use that number.

**Comment by lazerwalker** [comment]
@Trolldemorted If I'm understanding you correctly, you're suggesting using signal-cli as a second client to message back and forth with from the iOS client?

I only have a single mobile phone number, no landline nor an old mobile phone number just lying around. Do you know if Signal supports signing up with a free Google Voice number?

Even separate from these logistical questions, on an idealogical/philosophical level, requiring developers to have even one personal phone number hooked up to a production server in order to debug client features seems pretty silly.

**Comment by Trolldemorted** [comment]
Google voice numbers should work, and free-sms-receive-websites work (if you find one that actually works, took me several hours for my 3rd account).

If you don't have a landline number you might just want to ask someone who does - all they have to do is forward the activation code from the sms to you.


There is a seperate testing server, but i never bothered to set a client up. Note that google voice is only available in the USA if i remember it correctly. [Signal-Desktop](https://github.com/WhisperSystems/Signal-Desktop/blob/master/CONTRIBUTING.md) mentions using it as a standalone client, but the page is quite outdated and i never tested it.

**Comment by michaelkirk** [comment]
Here's a start anyway: https://github.com/WhisperSystems/Signal-iOS/wiki/Development-Guide

Feel free to contribute improvements.
