### ISSUE TITLE
Can't send message into group - Beta v2.6.4 (9)

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#1444]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
In the beta before, Signal was crashing on sending into the group.

In the latest beta v2.6.4 (9), sending of a message fail with following error message:

Der Vorgang konnte nicht abgeschlossen werden.
contactsmanager.notfound-Fehler 777404.

in english:

The operation could not be completed
contactsmanager.notfound-error 777404.

**Hint:**
We have a group member, which doesn't use Signal anymore. 

Since we can't delete a member from a group, it seems that
this is the source of the problem.

**Comment by michaelkirk** [comment]
Thanks for the report. Do you know if the other’s are receiving the message?

**Comment by big-r81** [comment]
No, they are not receiving the messages from me!

**Comment by big-r81** [comment]
Works like a charme again!
