### ISSUE TITLE
feature request: screenshot notices

### ISSUE THREAD

**Issue by ydrchan** [WhisperSystems/Signal-iOS#1454]
Could you add a feature that when user took screenshot, it will give you a message that the user has taken a screenshot of the conversation?
like this in Telegram
![screenshot](https://cloud.githubusercontent.com/assets/19244253/20239376/cd2c44f0-a8cc-11e6-830c-8f35261f4f94.png)

thanks!

**Comment by 2-4601** [comment]
dupe #846
