### ISSUE TITLE
Two QR scan code strings are not translatable or not used

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#1455]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

Tried the iOS Signal version after a long while. Looks pretty sweet :)

### Bug description
Looks like the string key `SCAN_CODE_ACTION` is not used (it is in Transifex though).
Also there's a string "Scan the QR Code on your contact's device." which is not translatable on Transifex.

### Steps to reproduce
1. Change language to something else than English
2. Go to Verify Safety Numbers screen
3. Note that the text below is in English "Scan Code"
4. Tap to scan code
5. Note that the text on the next screen is in English "Scan the QR Code on your contact's device."

**Expected result:** Step 3 and 5 should have translated strings.

### Screenshots
![signal](https://cloud.githubusercontent.com/assets/174176/20240459/417e9796-a921-11e6-844f-fa6c7e47ccb6.jpeg)

### Device info

**Device**: iPhone 4S
**iOS version**: 9.3.5
**Signal version:** 2.6.4

**Comment by michaelkirk** [comment]
In Transifex now, Kiitos!
