### ISSUE TITLE
Signal doesn't ring when not in foreground

### ISSUE THREAD

**Issue by strugee** [WhisperSystems/Signal-iOS#1467]
- [X] I have searched open and closed issues for duplicates

I've seen #94, but this appears to be regression in that implementation.

----------------------------------------

### Bug description

When the phone is locked and a Signal call comes through, the phone vibrates but does not ring.

### Steps to reproduce

1. Set up Signal
2. Lock the phone
3. Signal call the iOS phone from an Android device (not sure if this is necessary, but it's what I'm doing)
4. Notice how a notification pops up on the lock screen and the phone vibrates, but does not ring.

If Signal is already open in the foreground when the call comes through, this issue does not happen. This issue also happens if the phone is on the home screen or in a different app.

Notification sounds are on in Signal settings. Every slider in Settings > Notifications > Signal is on and "alert style when unlocked" is set to "banners". Settings > Sounds > Vibrate on Ring is on and the ringer volume is loud. All the "sounds and vibration patterns" entries have sounds set (i.e. aren't "none" or something).

### Device info

**Device**: iPhone 6
**iOS version**: 10.0.2
**Signal version:** 2.6.4

### Link to debug log

https://gist.github.com/anonymous/e320f1c3d6745747bac10f466f9aeae3

The above debug log is me opening the app, calling, rejecting the call, locking the phone, calling again, opening the notification that appeared on the lock screen, and rejecting the call again.

**Comment by merkste** [comment]
I am experiencing the same issue. It's there any progress or news on the issue? This problem essentially renders incoming voice calls useless. How could I help?

**Comment by riyapenn** [comment]
Duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/1628?

**Comment by michaelkirk** [comment]
@strugee have you disabled iOS call integration?

**Comment by michaelkirk** [comment]
Oh - just realized how old this issue is. @strugee is this still happening with the latest? We've made a lot of changes to our calling system since you posted this.

**Comment by strugee** [comment]
Seems to be gone.
