### ISSUE TITLE
Commented out tests in SessionDescriptorTest.m

### ISSUE THREAD

**Issue by Strilanc** [WhisperSystems/Signal-iOS#147]

**Comment by corbett** [comment]
@Strilanc can you elaborate on the meaning behind this issue?

**Comment by Strilanc** [comment]
It's a reminder that there's commented out code in the file with the name
in the title. It should be removed or supplanted.

**Comment by corbett** [comment]
yes, but I have no idea why it was there to begin with, or why you
commented it out. I will go back to the code. seems like this should be a
#warning and not a github issue

On Wed, Jan 7, 2015 at 12:40 AM, Craig Gidney <notifications@github.com>
wrote:

> It's a reminder that there's commented out code in the file with the name
> in the title. It should be removed or supplanted.
> On 06 Jan 2015 7:08 PM, "Christine Corbett Moran" <
> notifications@github.com>
> wrote:
>
> > @Strilanc <https://github.com/Strilanc> can you elaborate on the
> meaning
> > behind this issue?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WhisperSystems/Signal-iOS/issues/147#issuecomment-68958073>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/147#issuecomment-68961095>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by Strilanc** [comment]
It looks like a straightforward
does-the-expected-data-parse-as-the-expected-value test. Someone probably
made a small change to the data or how it was retried, and commented out
the test instead of updating it.

The ideal fix is to grab some actual data sent in prod with a known test
key and contents, and confirm that the right things come out.

**Comment by michaelkirk** [comment]
Looks like this should be closed, resolved with 
https://github.com/WhisperSystems/Signal-iOS/commit/1b02e186f83c02ced9e23dbe0717af844a0f9d85
