### ISSUE TITLE
Visually differentiate my 30 digit safety number fingerprint from remote user's

### ISSUE THREAD

**Issue by grempe** [WhisperSystems/Signal-iOS#1478]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Feature request

For those, possibly advanced users, who want to take advantage of the ability to publish their fingerprint currently have to go through a non-intuitive process of comparing the safety numbers from two different contacts to determine which of the fingerprint digits belong to them.

In the Open Whisper Systems blog you wrote:

> However, there are some more advanced use cases which per-conversation safety numbers might not provide for (such as Charlie verifying Alice's fingerprint by checking with Bob), so we designed the safety number format to be a sorted concatenation of two 30-digit individual numeric fingerprints. Advanced users that would like to use fingerprints for more complex use cases can separate the two fingerprints from the safety number if necessary.

https://whispersystems.org/blog/safety-number-updates/

I agree that this is a useful use case, but you could make it much simpler to do with a simple visual change. I would suggest that you could highlight MY portion of the safety number with a different color, underline, or even something as subtle as light gray text vs. dark gray text for the two halves.

With this in place advanced users would always know that e.g. the light gray text is my own portion of the safety number and the dark text is the other person. Less advanced users would likely not even notice this distinction.

This reduces what is now a multi-step process (assuming you even have more than one contact conversation open to use for comparison) to a simple visual differentiation.

### Related issue

https://github.com/WhisperSystems/Signal-iOS/issues/1396

**Comment by moxie0** [comment]
Thanks @grempe but we're more interested in making the common case simple, smooth, and intuitive. We want this to appear as a single value that both parties compare, making one half visually distinct would undermine that. Thanks for the feedback though!
