### ISSUE TITLE
a message sent from myself will appear twice

### ISSUE THREAD

**Issue by coeusite** [WhisperSystems/Signal-iOS#1480]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
a message sent from myself will appear twice. 
one as sent, one as received.
(not a bug actually)

### Steps to reproduce
- send myself a message from the Chrome App
- check it on the iOS app

**Actual result:** a message sent by myself will appear twice
**Expected result:** it is better to show the message only once.

### Screenshots
http://imgur.com/a/ckzIE

### Device info
**Device**: iPhone 6p
**iOS version**: 10.1.1
**Signal version:** 2.6.5

### Link to debug log
NaN

**Comment by michaelkirk** [comment]
I don't think we should change this, as the proposed solution isn't better in any obvious way.
