### ISSUE TITLE
Settings for disappearing messages unaccessible

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#1486]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Unable to switch on or off disappearing messages. Maybe related to #1366.

### Steps to reproduce
- open a existing conversation or create a new one
- go to the conversation settings

**Actual result:** The button to switch on/off disappearing messages is pushed off screen and is unresponsive.
**Expected result:** The button should be accessible.

### Screenshots

![img_4661](https://cloud.githubusercontent.com/assets/5073538/20571243/9518b1e0-b19e-11e6-9439-fdd35084a33a.png)

### Device info

**Device:** iPhone 5
**iOS version:** 10.1.1 
**Signal version:** 2.6.6.5 beta

### Link to debug log
https://gist.github.com/9329f08b5dbfbfd8f8f22a3f80eaf79f

**Comment by riyapenn** [comment]
Also on iPhone SE
debug log device 1: https://gist.github.com/905fa67a2d32f7745f21903151a33751 
debug log device 2: https://gist.github.com/9eb5e208251837216020924f18e9cfd0

**Comment by guillett** [comment]
@riyapenn Could you post screenshots? Are you testing an English version? I can't replicate the issue on my device. Does language settings should have any impact? (Mine is French)

**Comment by michaelkirk** [comment]
@guillett see the screenshot in the description. It seems to be affecting at least the German translation, but presumably any with a long enough label.

**Comment by michaelkirk** [comment]
Also, because it's related to length it's going to be more of an issue on narrow devices (like iphone5)

**Comment by guillett** [comment]
Thanks @michaelkirk, I saw the screenshot in the description but I was hoping to have another bogus scenario (different language for instance).

I have done a hacky test and could not replicate the problem on the Simulator nor on my device.
I am not testing on 10.1.1 but previous versions (9.3 on device and 10.0 on Simulator).
 
![capture d ecran 2016-12-02 a 22 27 00](https://cloud.githubusercontent.com/assets/1410356/20851237/7da3aaf4-b8df-11e6-96eb-b53e9f4365a6.png)

![from_device](https://cloud.githubusercontent.com/assets/1410356/20851220/6405d856-b8df-11e6-8fc3-8c1e50ea4ec7.png)

**Comment by jschneier** [comment]
@guillett German is notorious for having long and unbroken nouns. For me (on an SE) this is trivially reproducible if I set the phone's language to German.

**Comment by guillett** [comment]
I manage to get the bogus behavior on the released application (from the App Store) but not from the repository. I switched to German and I hard-coded the labels to have the German versions and in both cases the font is shrunk to fit.

![part](https://cloud.githubusercontent.com/assets/1410356/20866830/e82ae056-ba36-11e6-9589-290a33ac52cd.png)

**Comment by jschneier** [comment]
@guillett I just rebuilt the latest from HEAD on my SE and I have this issue. It actually is (barely) clickable but the hitbox is nearly impossible. I opened a PR with before and after screenshots.
