### ISSUE TITLE
Search in 'Invite Friends' doesn't work as expected

### ISSUE THREAD

**Issue by titanous** [WhisperSystems/Signal-iOS#1490]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

The search bar in 'Invite Friends to Signal' filters the contacts but does not allow selecting them to send an invite.

### Steps to reproduce

- Select the new message button and press 'Invite Friends to Signal'
- Select 'Message' or 'Mail'
- Select the search bar and filter the list.
- Note that there are no check boxes in the filtered view.
- Tap on a contact and note that it goes into a highlighted state.
- Press cancel and note that the selected contact has not been checked for sending an invite.

### Device info

**Device**: iPhone 6
**iOS version**: 10.1.1
**Signal version:** 2.6.6.5 beta

**Comment by michaelkirk** [comment]
Thanks for the report. On it.

**Comment by michaelkirk** [comment]
solved in 2.6.6.7 (in beta)
