### ISSUE TITLE
Missing localized strings (croatian)

### ISSUE THREAD

**Issue by iadmir** [WhisperSystems/Signal-iOS#1493]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Missing localized strings.
Keys: SEND_BUTTON_TITLE, MESSAGE_COMPOSEVIEW_TITLE

### Steps to reproduce
- open conversation
- look to input form and submit button

**Actual result:** New message, Send
**Expected result:** Nova poruka, Šalji

### Screenshots

![img_4240 copy](https://cloud.githubusercontent.com/assets/23726384/20639627/f29ede76-b3c8-11e6-8b12-326e0818ae75.png)

### Device info

**Device**: iPhone 5S
**iOS version**: 10.1.1
**Signal version:** 2.6.6 beta

**Comment by michaelkirk** [comment]
Thanks for reporting.

The actual missing strings from the messages screen are from the JSQMessagesViewController project, they just happen to have the same English translation as the keys you listed.

Any interested in opening a PR there? 

https://github.com/jessesquires/JSQMessagesViewController/tree/develop/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle

**Comment by iadmir** [comment]
> Any interested in opening a PR there?`
Done!

but what's with others, this strings missing in Transifex
https://cloud.githubusercontent.com/assets/23726384/20639626/f26fdd74-b3c8-11e6-84ee-cc83ba697fd3.png

**Comment by iadmir** [comment]
JSQMessagesViewController updated, but I don't see it in last beta 2.6.8, still English translation..

https://github.com/jessesquires/JSQMessagesViewController/pull/1928

**Comment by ThePowerOfDreams** [comment]
This is also the case for Catalan.

**Comment by TreatyOfRome** [comment]
Fixed in 878806a. Issue can be closed.

**Comment by michaelkirk** [comment]
Thanks @TreatyOfRome
