### ISSUE TITLE
Feature suggestion: Invite new users

### ISSUE THREAD

**Issue by lailauch** [WhisperSystems/Signal-iOS#1496]
It's great to be able to invite new users through referral text message without leaving Signal App. 

This referral text is implemented by ton of Apps already. This feature would allow a Signal user to send referral text along with app link to a contact who is listed as not using Signal.

Humorous and witty call to action referral texts will benefit society.

**Comment by michaelkirk** [comment]
Coming in the next release! 

Or if you'd like to try it now, you can sign up for the iOS beta by emailing support@whispersystems.org with a subject like "sign me up for the Signa iOS beta"

https://github.com/WhisperSystems/Signal-iOS/pull/1494
