### ISSUE TITLE
Bluetooth / Signal Issues

### ISSUE THREAD

**Issue by RogerMannett** [WhisperSystems/Signal-iOS#1499]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I am hard of hearing and use a hearing aid with Bluetooth all the time. iOS iPhone calls are fine as are messenger calls and video, FaceTime , etc. when I am using this with a signal call, I get multiple call disconnects. I have tried to google a solution, but have found nothing that will help.  It is only if there is an alert or a email or msg that comes in and there is a notification, then the bluetooth will disconnect the call, screen goes back to the contacts screen again.
Doesn't happen with wired headset, or speaker.

### Steps to reproduce
- Problem recreated by ringing from another iphone
- Sending text msg to 6s with bluetooth attached during call
- Call disconnected

**Actual result:** Call disconnected
**Expected result:** Call to continue with notification scrolling off, but not affecting the call

### Device info
**Device**: iPhone 6s
**iOS version**: 10.1.1
**Signal version:**2.6.5
** Headset** Phonak ComPilot Air II

### Link to debug log

Log URL: https://gist.github.com/f3bd910429b4f4061ce9fc79635053fb

**Comment by RogerMannett** [comment]
The call was after the log ends- 1754on 11/29.
At first i believed the call was failing, but i suspect the other party hangs up after i cant reconnect on Bluetooth.
All sound goes at this point- i can hear nothing via speaker or plugged headset, i tried both afyter the bluetooth dropped yesterday.

**Comment by TreatyOfRome** [comment]
A lot of bluetooth issues have been addressed in Signal 2.14.0. Issue could be closed?

**Comment by RogerMannett** [comment]
Close - I will see how 2.14.0 works and re-open if issue persisits. I had stopped using Signal due to the problems with the bluetooth. I will try with latest release.
Thanks
