### ISSUE TITLE
Invite Flow: sort contact entries of just email address by first letter of email

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1518]
### Bug description
Contact list entry sorted under unknown '#' versus sorting under the first letter of the email address as done by iPhone's system

### Steps to reproduce
- Have contact entry of solely an email address, no other information in iOS contact list
- View Invite Flow  > Mail 

**Actual result:** Sorted under '#'
**Expected result:** Sorted under first character of email

### Screenshots

![signalemailinviteflow](https://cloud.githubusercontent.com/assets/4898366/20819823/c9780d52-b7eb-11e6-8b6e-58e19b8aa5d4.png)

### Device info

**Device**: iPhone 5C
**iOS version**: 10.1.1
**Signal version:** 2.6.6

**Comment by DRosadoYew** [comment]
Created a PR for this (#1521). Contacts with email but no name will be under the section which matches the email. If no email or name, they will be placed under #. 
I believe this is what you're asking for @riyapenn.

**Comment by michaelkirk** [comment]
In 2.6.9.4
