### ISSUE TITLE
Avatar for contact with emoji needs design/change

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1519]
- [X ] I have searched open and closed issues for duplicates (but feel like I've overlooked something so this could also be mentioned in another issue) However, https://github.com/WhisperSystems/Signal-iOS/issues/1512  regarding unsaved contacts is related.

----------------------------------------

### Bug description
If a contact's name starts with an emoji character in the contact list entry, a character is displayed in the Avatar

### Steps to reproduce
- Have contact name in contact list with an avatar
- view message compose contact list, view invite contact list or open conversation thread and go to inbox view of contact list 

OR
- Have contact saved in contact list with JUST a phone number, NO NAME.
- view message compose contact list, view invite contact list or open conversation thread and go to inbox view of contact list 

**Actual result:** Character with an A is displayed
**Expected result:** Suggestion is a cleaner avatar or different character. For example, Signal Desktop displays diamond with a question mark (image below)

### Screenshots

iOS image of avatar for contact with name '[Emoji] Google Voice' 
![avatar emoji name](https://cloud.githubusercontent.com/assets/4898366/20820741/59c090ae-b7f2-11e6-9834-2d5d6e2af79d.png)

Signal Desktop handling of emoji as first character of contact name:
<img width="61" alt="desktopemojiavatar" src="https://cloud.githubusercontent.com/assets/4898366/20820795/a4fd62a4-b7f2-11e6-854d-6291de784302.png">

### Device info

**Device**: iPhone 5C
**iOS version**: 10.1.1
**Signal version:** 2.6.6

**Comment by michaelkirk** [comment]
One approach would be to restrict initials to alphanumeric characters only.

**Comment by Stanzi97** [comment]
To be honest, who (except 12-year old girls, who are not the target group of Signal) have contacts which start with a Smily/Emoji??

**Comment by michaelkirk** [comment]
@Stanzi97 your comment is rude, unhelpful, and based on incorrect assumptions. Use respect when communicating here.

The current behavior is clearly broken and we should fix it.
