### ISSUE TITLE
Change iOS icon to Android icon

### ISSUE THREAD

**Issue by Stanzi97** [WhisperSystems/Signal-iOS#1522]
I think the Android icon is much more beautiful than the iOS icon. Moreover, as far a I know, the iOS icon was only created to fit Apple's demand that every iOS-App-icon has to be the same shape (a square with round edges).
This is, in my opinion, not very good, to be on point. I have thought about an icon for iOS that looks like this:
![wpirgjrpig](https://cloud.githubusercontent.com/assets/24295586/20866082/908eab92-ba23-11e6-8aa3-b67c8aa6420e.png)

**Comment by rainerzufall** [comment]
They are working on unification: https://twitter.com/whispersystems/status/804367877977444352 But I guess it will be the other way round...

**Comment by Stanzi97** [comment]
https://youtu.be/Tim5nU3DwIE?t=18s
