### ISSUE TITLE
Remove status bar from camera layout

### ISSUE THREAD

**Issue by iadmir** [WhisperSystems/Signal-iOS#1539]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Flash icon is too close and passes over the status bar. Sometimes it is difficult to choose an option.

### Steps to reproduce
- Open conversation
- Tap on attachment icon
- Choose to take photo in-app

**Actual result:** Camera layout with status bar
**Expected result:** Camera layout without status bar

### Screenshots

![img_4405](https://cloud.githubusercontent.com/assets/23726384/21079540/2da91004-bf95-11e6-9c6e-d5710f8d7018.PNG)

### Device info

**Device**: iPhone 5S
**iOS version**: 10.1.1
**Signal version:** 2.6.7 beta

**Comment by kevinmbeaulieu** [comment]
Looks like this has been fixed. Tested on iPhone 5S, 10.2 (wouldn't expect there to be a difference from 10.1.1 for this), 2.6.9. Can you confirm?
