### ISSUE TITLE
Unable to send signal message to non-contact phone number

### ISSUE THREAD

**Issue by Robbbb** [WhisperSystems/Signal-iOS#1540]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I cannot seem to send a message to someone's number until I have added them as a contact using the iOS contacts app. 

IE, meet a new person at a party, I ask how they like to be contacted, they (being so cool) say 'signal' and I open signal. They say their number and I type it in the to:field of the new message dialog. when I finish typing, i am prompted not to message them on Signal, but to invite them to Signal via unencrypted SMS. This is silly, as they have the app already. This happened to me yesterday when I met @liliakai  and she told me to write a report here. 

### Steps to reproduce
- meet a new person
- type their number into the to:box of the new message dialog

**Actual result:** I am taken out of the signal app to an unencrypted SMS, pre-populated with mis-directed marketing, as the recipient is already a user.
**Expected result:** An empty thread opens with my new friend

### Device info

**Device**: iDevice iPhone 6+
**iOS version**: 10.0.1
**Signal version:** 2.6.2

**Comment by JuliaAngwin** [comment]
I'm a journalist and this is a big issue in my community. Many of my sources do not want to add me to their contact book and I don't want them in mine either. 

I and other journalists would like to be able to contact people just using their phone number.

**Comment by chartgerink** [comment]
This seems like an iOS specific issue, I have been able to send messages on my Android phone to people who are not in my contacts list (note: I have the Signal app as the SMS default as well).

**Comment by JuliaAngwin** [comment]
yep, that's why I posted it in the iOS thread.

**Comment by charlesmchen** [comment]
This has been completed and will ship in 2.7.0.x.
