### ISSUE TITLE
Text in message bubbles displayed as cropped although copy and paste reveals entire message

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1543]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Message bubble text displayed as cropped (This issue previously occurred on some devices when an emoji was included.)

### Steps to reproduce
- Phone language: Japanese
- Receive text from contact 
"あいうえお 
かきくけこ 
さしすせそ"

**Actual result:** 
<img width="351" alt="screen shot 2016-12-13 at 8 25 22 pm" src="https://cloud.githubusercontent.com/assets/4898366/21169581/5477d7cc-c172-11e6-9f29-0e247eebab76.png">
"あいうえお 
かきくけこ 
                   "

**Expected result:** See 
あいうえお 
かきくけこ 
さしすせそ

### Device info

**Device**: N/A
**iOS version**: N/A likely iOS 10
**Signal version:** 2.6.5, but still likely an issue 

### Temporary work around
1. Go to iPhone Settings > General > Accessibility > Larger Text > Move the slider all the way to the right to the largest A (or among the 3 largest settings). Then go to Signal, and continue through to a conversation, you will notice the font has increased. The font size increase is not displayed in the conversation thread.

2. Long-press on the message bubble to highlight > paste elsewhere (i.e. message input field) and see the entire text

**Comment by miyar520** [comment]
I think this was solved in #1436. Indeed, the problem is not reproduced in my iPhone with Signal 2.6.9.

Device: iPhone 6s
Language: Japanese
iOS: 10.1.1

**Comment by riyapenn** [comment]
- Phone language: Chinese
- Receive text from contact 
<img width="199" alt="screen shot 2016-12-22 at 8 03 14 pm" src="https://cloud.githubusercontent.com/assets/4898366/21446913/b43c4876-c881-11e6-9f83-b775d7c235a9.png">


**Actual result:** 
"Hello, I am hungry, but I think that 
                                                            "

**Expected result:** 
"Hello, I am hungry, but I think that 
food is not tasty"

**Comment by riyapenn** [comment]
iPhone SE 64G iOS 10.2 
Phone language: Korean
Send text to contact
<img width="203" alt="screen shot 2016-12-22 at 11 33 56 pm" src="https://cloud.githubusercontent.com/assets/4898366/21449176/430befb2-c89f-11e6-91d2-0ea037c36c06.png">

Actual result:
"test for the message itself" 

Expected result:
"test for the message itself cropped. not w/ emoji."

**Comment by riyapenn** [comment]
Perhaps related? Reverse issue of message bubbles not having the space to display the text : https://github.com/WhisperSystems/Signal-iOS/pull/1269#issuecomment-234139940

**Comment by Gijutsu** [comment]
My friend in Japan can reproduce this using the lastest version of iOS and Signal, as well as on previous versions she had before I told her to test and upgrade iOS, Signal and also reinstall Signal when that didn't work:
Device: iPhone6 64GB NG4F2J/A
Phone language: Japanese
iOS versions: 10.2 (14C92) - but the bug was also present in previous versions.
Signal versions: 2.7.1 - but the bug was also present in previous versions.
![screenshot1](https://cloud.githubusercontent.com/assets/489153/23833901/4090ac9a-074d-11e7-9999-138a937b2e27.png)

Expected result:
"Can you make screenshot of this message"
"あいうえお
かきくけこ
さしすせそ"

Actual result:
"Can you make screenshot of this"
"あいうえお
かきくけこ"

**Comment by riyapenn** [comment]
log from 2.11.4: https://gist.github.com/731d016ddd5cc5938807c0b4940ce377

**Comment by michaelkirk** [comment]
In 2.19
