### ISSUE TITLE
Layout Bug, Disappearing Messages can't turn ON (iOS,Language German) 

### ISSUE THREAD

**Issue by desmo90** [WhisperSystems/Signal-iOS#1545]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I have determine this Bug in iOS when the system language ist set to german.
I can't turn on the timer, because the button is outside of the screen.
When i change my system language to english, is this bug vanished.

### Steps to reproduce
- change system language to german!
- open Signal App and choose a Conversation
- tap on the name, to open the conversation settings
- you see the bug! 

### Screenshots

Language German
![bug-signal-german](https://cloud.githubusercontent.com/assets/16727278/21182889/a14ec072-c205-11e6-8bf0-6c5d13d2a6ed.jpg)
Language English, no Bug!
![signal-english](https://cloud.githubusercontent.com/assets/16727278/21182912/bb727a0c-c205-11e6-8903-59f0d369d230.jpg)

### Device info

**Device**: iPhone 5 SE
**iOS version**: 10.1.1
**Signal version:** 2.6.7

**Comment by big-r81** [comment]
Hi demo90,

thank you for your report. This is already fixed (#1536) in the beta version and should be in the next app store version!

**Comment by michaelkirk** [comment]
Yup, rolling out soon.
