### ISSUE TITLE
[Feature Suggestion] Usernames

### ISSUE THREAD

**Issue by caveman1973** [WhisperSystems/Signal-iOS#1550]
Telegram has an interesting implementation of usernames. [Optionally] In Settings you register one that is linked to your phone number. If you do, anyone will be able to find you by your username and contact you – without having to know your phone number.

-It maintains usability. Continues to work as usual but if you want certain anonymity, you can register an username and give it instead of your phone number.
-When people add you thru username, they can't see your phone number.
-You can keep the username when changing phone numbers.

Signal offers privacy, protecting the content of your chat. Adding usernames, it can offer anonymity; protecting your phone number which can be used to gather location and practically everything about you.

**Comment by 2-4601** [comment]
Dupe #101.
