### ISSUE TITLE
Omit names for unknown contacts when linking to desktop

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1559]
### Bug description

Avatar for unknown Contact in Signal-Desktop shows up as "("

I think this is because Signal-iOS isn't correctly syncing their contact details.

### Steps to reproduce
- receive message from someone not in your contacts on Signal-iOS
- link to desktop

**Actual result:** See contact show up in Signal-Desktop with a name like `(323) 555 5555` and a `(` avatar 
**Expected result:** See contact show up in Signal-Desktop with no name and a `#` avatar.

**Comment by purpleplatypus** [comment]
I can't reproduce this issue by following your steps, I'm getting the expected `#` avatar.
Debug log from Signal-Desktop is below.
https://gist.github.com/82b19f12c05c46d87958564c535884fc

**Comment by michaelkirk** [comment]
This is no longer an issue.
