### ISSUE TITLE
Crash during call in background

### ISSUE THREAD

**Issue by iadmir** [WhisperSystems/Signal-iOS#1569]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
During a call, the application crashes when it is in the background

### Steps to reproduce
- Make call
- Press home button during call

**Actual result:** Continue with call in background
**Expected result:** Not possible to continue with call in background
### Device info

**Device**: iPhone 5S
**iOS version**: 10.2
**Signal version:** 2.6.9

**Comment by riyapenn** [comment]
Have you enabled all permissions for Signal, specifically, background app refresh?

Enable background app refresh:
iOS device Settings -> Signal -> Allow Background App Refresh
OR
iOS device Settings > General > Background App Refresh > Enable Background App Refresh AND Enable Signal

**Comment by iadmir** [comment]
Yes it's already enabled 

Poslano s mojeg iPhonea

02.01.2017., u 23:19, riyapenn <notifications@github.com> napisao:
