### ISSUE TITLE
Able to message but unable to verify key from US to German phone number

### ISSUE THREAD

**Issue by shushugah** [WhisperSystems/Signal-iOS#1571]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
A friend installed Signal on their iPhone 6, US sim card. They added me in their contacts and my german number +49...(etc) using iphone 5. They were able to message me, and I was able to message them. Tapping on my name did nothing. When they removed my name from contact book, they were able to message me still AND then verify me. This was an issue for any of their US contacts.   

### Steps to reproduce
- Create german contact of format +49 123 45678901 with a name
- Attempt to tap verify
- remove name and see that it can now be verified

**Actual result:** Does nothing
**Expected result:** Should open key exchange to compare

### Device info

**Device**: iPhone 5 and 6
**iOS version**: 9 and 10 respectively
**Signal version:** latest on both

**Comment by 2-4601** [comment]
Sounds like #1402.
