### ISSUE TITLE
Can't send messages by number or add contacts manually if have no signal contacts

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1573]
- [x] I have searched open and closed issues for duplicates

#1540 appears to be a related but separate issue.

----------------------------------------

### Bug description

A new user installs signal. They have zero contacts with signal. Can't send messages by number or add contacts manually.

### Steps to reproduce

- Get a new device OR remove all (signal-having) contacts from existing device.
- Install Signal.
- Try to send a message by phone number (not to a contact).
- Try to add a contact manually.

Observed: 

* They can't send a message by phone number.
* They can't add contacts manually (they can invite).

Expected:

* They can send a message by phone number.
* They can add contacts manually.

### Screenshots

![screen shot 2017-01-03 at 12 57 19 pm](https://cloud.githubusercontent.com/assets/625803/21617447/2fc20e28-d1b4-11e6-985d-6afb74d1975f.png)

### Device info

**Device**: Any
**iOS version**: Any
**Signal version:** 2.6.9

**Comment by riyapenn** [comment]
Related https://github.com/WhisperSystems/Signal-iOS/issues/1540

**Comment by charlesmchen** [comment]
This has been completed and will ship in 2.7.0.x.
