### ISSUE TITLE
Failure to initialize YapDatabase

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1578]
### Bug description

Since https://github.com/WhisperSystems/SignalServiceKit/pull/77** we see a good (bad) number of crashes on launch due to not successfully setting up the database.

Specifically here: https://github.com/WhisperSystems/SignalServiceKit/pull/77/files#diff-8257af4ec3f2c8631ab10dcb963d2c58R106

**_To be clear_, The crashing introduced in https://github.com/WhisperSystems/SignalServiceKit/pull/77 is preferable to the previous behavior in which this failure (if due to keychain error) would silently make the database permanently inaccessible - rendering the user unable to ever see their messages, prompt them with the registration screen, and if the abused user tried to register at this point, the app would just crash upon completing registration, with no chance of recovery.

**Comment by charlesmchen** [comment]
I've merged changes that should: a) help clients that encounter this issue reset to a "fresh install" state on startup b) eventually shed light on the frequency/nature of this issue, once we have analytics.
