### ISSUE TITLE
receive push notifications in development

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1579]
* [x] It would appear that we only register to receive remote notifications on app launch if user is registered. 
   * If user registers, app does not appear to register for RNs at that time.
   * ___CORRECTION___ this is already being done.
* [ ] We don't appear to be set up receive PNs in development. We should fix that.
* [x] If domain fronting is active, I believe it will be necessary to fetch messages whenever the app becomes active.

**Comment by michaelkirk** [comment]
> It would appear that we only register to receive remote notifications on app launch if user is registered.

Not super clear, but it *is* happening:
https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/view%20controllers/SignalsViewController.m#L217

**Comment by michaelkirk** [comment]
>  If domain fronting is active, I believe it will be necessary to fetch messages whenever the app becomes active.

I broke this out into: #1601 

And renamed this issue to reflect the remaining work.
