### ISSUE TITLE
Adding merged contact with multiple signal id's to group adds both

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1586]
### Bug description

When choosing members of a new group, if you pick a contact who has multiple Signal ID's, they will be added to the group multiple times (once per Signal ID).

### Steps to reproduce
- Add a system contact who has two Signal registered phone numbers
- Create a new group, adding that contact

**Actual result:** The group is created with *both* of that Signal user's number added to the group.
**Expected result:** I'm not sure. I only expected one number to be added. In my case, the user has a primary and secondary number, but we can't generalize anything around that. 

Primarily it's an design problem, and a design should be agreed upon before moving forward with any implementation [needs design]. My first thought is to drill down as you do with a CNContactPicker view to pick which number you want to invite.

**Comment by riyapenn** [comment]
I'm assuming the underlying fix (displaying ALL Signal numbers as separate contact entries regardless of contact linking) will also address this https://github.com/WhisperSystems/Signal-iOS/issues/1491

**Comment by michaelkirk** [comment]
This was solved long ago by disambiguating names for users with multiple devices.

e.g.
- "Michael (iPhone 1)"
- "Michael (iPhone 2)"
- "Michael (Home)"
