### ISSUE TITLE
Crash after enabling first (camera) permission request after install

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1588]
- [X] I have searched open and closed issues for duplicates, related/probably same issue as https://github.com/WhisperSystems/Signal-iOS/issues/1560 but this issue title is for ALL permissions prompted through the app vs specifically the microphone permission. Feel free to close this if #1560 fix resolves this.

----------------------------------------

### Bug description
Signal crashes after enabling the permission for the first time after install

### Steps to reproduce
- Install Signal
- Go to linked devices and see the need to scan QR code
- Enable camera permission for the first time

**Actual result:** App freezes, need to close out and come back to have ability to scan QR code
**Expected result:** Enable camera permission, and see the camera working to scan the QR code

### Device info

**Device**: iPhone 5C
**iOS version**: 10.1.1
**Signal version:** 2.6.9

### Link to debug log

https://gist.github.com/anonymous/297476e6139f840a550b071a63d9b3ee

**Comment by yaneurabeya** [comment]
+1

I don't necessarily get a crash from my iPhone 6S/2.6.13, but it definitely does act weird for a bit, then starts behaving properly after I exit back to the home screen, then reopen the app.

**Comment by footiecrazie** [comment]
created pull request 1818 for this issue
