### ISSUE TITLE
In app camera focus issue

### ISSUE THREAD

**Issue by jhellen** [WhisperSystems/Signal-iOS#1596]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
On my Motorola MotoG 3rd gen I have always had an issue taking in app pictures because it just isn't able to focus. So most of the time when I need to send a sharp pic then I need to take a pic outside the app first and then send it. Tapping the screen doesn't help either.

### Steps to reproduce
- tap the camera icon in the app
- take a picture

**Actual result:** Result is a blurry picture. If you keep turning the phone and keep changing the distance then there's a small chance that the camera is able to focus)
**Expected result:** Expected a sharp picture like when using the system camera app)

### Device info

**Device**: Motorola MotoG 3rd gen
**Signal version:** 3.26.2

**Comment by big-r81** [comment]
@jhellen 
you should report this to https://github.com/WhisperSystems/Signal-Android/issues, because this is the iOS issue repository.

**Comment by jhellen** [comment]
Sorry guys, for some reason I didn't notice. I'll close this and you may delete it so it doesn't clutter this space. Thanks for the guidance!
