### ISSUE TITLE
Awkward space left after scanning safety number

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1602]
### Bug description

After scanning a safety number QR code, the camera disappears, leaving an awkward space in the layout.

### Steps to reproduce
- send a contact a message
- open conversation settings by tapping name, then "verify safety number"
- scan their QR code
- see alert of "success" or "failure"
- dismiss alert

**Actual result:** 

Safety number screen is still up, but where the camera capture view was, is now an empty space.

**Expected result:**

**needs design**: Propose a design before contributing a solution.

Options include:

- Display graphic indicating success/failure result of the scan (similar to what Signal-Android does)
- dismissing safety number VC altogether.

### Screenshots

![signal](https://cloud.githubusercontent.com/assets/217057/21937524/c5f8fc98-d985-11e6-9b24-5f5f80fc9be0.jpg)

### Device info
**Device**: iPhone5c
**iOS version**: 9.3
**Signal version:** 2.6.11.1

**Device**: iPhone7
**iOS version**: 10.2
**Signal version:** 2.6.11.1

**Comment by christophhagen** [comment]
I would propose:

- if the number was correctly verified, dismiss the FingerprintViewController.
- if the number couldn't be verified, move qrContainer and instructionsContainer back up to restore the original layout. This enables rescanning or copying the number.

This could be very easily implemented and should serve its purpose.

**Comment by michaelkirk** [comment]
Fixed in #1799
