### ISSUE TITLE
App should work without contact access

### ISSUE THREAD

**Issue by alper** [WhisperSystems/Signal-iOS#1610]
I'm trying to get non-technical actually privacy-conscious people to use Signal and it's a solid no-go because of the contact access requirement.

I've seen #1356 and the work there would be good but I don't think that will address the reasons why people do not want to share their contacts.

1. People can't/won't trust that the contacts won't be shared after the phone has given access to them.

2. Full contact sets are sensitive and mostly irrelevant (most of the contacts are either accrued junk, work or people you have no direct interest in messaging anyway). The necessary contacts for initial usage are at max a dozen and those can easily be entered by hand.

**Comment by mat1th** [comment]
I agree with this. I never share my full list of contacts. I always disable the calDAV sync on my phone and create local contacts (with only the info needed for the app)  that should be imported in the app. When the app have imported the contacts, I disable the acces. 

So for the Signal app it should be possible to talk with the people that are in the inbox list without contact acces.

So the case should be: 
1. Create a account and import contacts.
2. Chat with people that have Signal.
3. Close the Signal app. 
4. Disable to access to the contacts in iOS settings.
5. When I open the app again I should be able to use the app with the contacts that are in the inbox list.

I think It should not be that hard to implement this functionality. The main change should be in the `blockingContactDialog` function. in the [OWSContactsManager.m](https://github.com/WhisperSystems/Signal-iOS/blob/359deb933c46c0d7df6bb1fd4a29f166b5d3bda5/Signal/src/contact/OWSContactsManager.m) file.

Thanks.

**Comment by josephlord** [comment]
I would be interested in having a look at this if it is something that the core team would be supportive of including. 

It would be good if it was also possible to add contacts with just a number and a text label without adding to the system contacts. Would he core team support that too?

**Comment by mat1th** [comment]
@FredericJacobs 
I've build the app by my self with the [blockingContactDialog](https://github.com/WhisperSystems/Signal-iOS/blob/6d757d3a50a81b39058f5c4ab43741096219a08e/Signal/src/contact/OWSContactsManager.m#L150) function disabled. The app works still fine. The only thing is that the names of the contacts are gone. You see the phone number of the contacts. But that is as expected. 

I think this wil be a improvement to the app.

**Comment by jamesacampbell** [comment]
This really needs to be offered as an optional feature and to stop forcing users to share their contact info. Unusable otherwise. Shame on you guys.

**Comment by robertp82** [comment]
I love Signal but it's extremely frustrating that some of my friends won't use it solely because of the Contacts list requirement. With reasoning such as "I can't use an app that gives out my clients' information in my contacts." If there were a way to opt-out and manually add some contacts, it would be extremely helpful.

**Comment by mat1th** [comment]
When you delete this case statement the app works without contact acces; 
```
   case kABAuthorizationStatusDenied: {
            UIAlertController *controller =
                [UIAlertController alertControllerWithTitle:NSLocalizedString(@"AB_PERMISSION_MISSING_TITLE", nil)
                                                    message:NSLocalizedString(@"AB_PERMISSION_MISSING_BODY", nil)
                                             preferredStyle:UIAlertControllerStyleAlert];

            [controller addAction:[UIAlertAction
                                      actionWithTitle:NSLocalizedString(@"AB_PERMISSION_MISSING_ACTION", nil)
                                                style:UIAlertActionStyleDefault
                                              handler:^(UIAlertAction *action) {
                                                [[UIApplication sharedApplication]
                                                    openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
                                              }]];

            [[[UIApplication sharedApplication] keyWindow]
                    .rootViewController presentViewController:controller
                                                     animated:YES
                                                   completion:nil];
            break;
        }

```

I't located in the [OWSContactsManager.m](https://github.com/WhisperSystems/Signal-iOS/blob/6d757d3a50a81b39058f5c4ab43741096219a08e/Signal/src/contact/OWSContactsManager.m#L150) file;

**Comment by jamesacampbell** [comment]
@mat1th thanks for this, I can at least build it myself manually with my iOS dev license and use it this way for now until it is updated.

**Comment by robertp82** [comment]
@mat1th if you're building yourself, does that mean push notifications won't work? I see that mentioned in the known issues. Thanks for the info.

**Comment by mat1th** [comment]
Yes push notifications doesn't work when you build it your self. So someone who signed the  Contributor agreement should create a pull request so everybody can use the app without the contact access.

**Comment by ThePowerOfDreams** [comment]
Absolutely mandatory for many. Consider this comment my upvote!

**Comment by mat1th** [comment]
With the newest iOS update (1.12.1) it's not nesesery to give the app access to the contacts :tada: 
So this issue could be closed;

**Comment by michaelkirk** [comment]
In 2.12, thanks @mat1th

**Comment by egberts** [comment]
What’s the issue number associated with being able to enter in a new phone number while access to contact is disabled on iOS?
