### ISSUE TITLE
Can receive not send / 1way messaging; alert of "unregistered number" when sending to saved contact

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1618]
- [X] I have searched open and closed issues for duplicates, related: https://github.com/WhisperSystems/Signal-iOS/issues/1430 but different as this issue is for contacts saved to the address book

----------------------------------------

### Bug description
When replying to some contact's there is an alert of "unregistered number"

### Steps to reproduce
- Alice is saved in iPhone contact list
- Alice does not show up in the Signal contact list
- receive a Signal message from Alice
- type response to Alice and hit send

**Actual result:** See alert of "unregistered number"
**Expected result:** message sends

### Screenshots

N/A

### Device info

**Device**: various
**iOS version**: 10+
**Signal version:** 2.6.6+

### Link to debug log

Log 1: https://gist.github.com/87115b80a947260fde9bc83c9b9108f1 
Log 2: https://gist.github.com/202788d346f0314fc81e6e718d61e10f 
Log 3: (ios 10.3) https://gist.github.com/anonymous/f6643af0950a324947615b32cdf5d663 
Log 4: https://gist.github.com/e1c52d1bcf65bced3eaa5ec0cb92eee6 
Log 5: https://gist.github.com/anonymous/c59c378e3c9e3f1f1454c896bd02bac1
Log 6: https://gist.github.com/anonymous/68006bc5d752d49ef7cf922ae3853434

Work around:
Delete all contact information of this contact on YOUR phone then re-add contact.

**Comment by michaelkirk** [comment]
When the recipient receives the message, do they see the thread as from "Alice" or from some phone number that looks like Alice's?

If the later, it would be good to get an example of what the discrepancy between the number appearing in Signal and the number stored in the Address Book.

Also, in future reports can you verify if the user has multiple numbers associated with the contact?

**Comment by riyapenn** [comment]
@michaelkirk Thread had displayed "Alice" and no other number associated with the contact. 

Work around if[ support page steps are not sufficient](https://support.whispersystems.org/hc/en-us/articles/218928858-Why-can-I-only-receive-Signal-messages-) (but can not get debug log as it failed to send): 
1. Tapped on a Signal call icon through the iPhone contact list
2. Canceled the call
3. Messaged this contact
4. Did not see an alert of an unregistered number anymore

**Comment by michaelkirk** [comment]
It seems like there may be at least two different issues at play here.

1. Seems to be related to a contact having multiple numbers, as it can be worked around by manipulating your local contacts.

2. Seems to be related to a SNAFU with the intended recipients registration process (e.g. either they never successfully registered with APN or were subsequently removed. No amount of manipulating your local contacts would solve this problem.

In the case of #2, a debug log for the "unregistered" recipient would be helpful. Registering for push notifications should happen every time they launch the app, but for debug purposes it might be easiest if they force the push notification update in settings -> advanced, then submit a debug log.

**Comment by riyapenn** [comment]
User with no apn id: https://gist.github.com/231cb37df4f2d74cbcdaa62ba5524246

**Comment by michaelkirk** [comment]
@riyapenn  can you double check that this user did "re-register for push notifications" before submitting this log? 

I'd expect to see something about "SyncPushTokensJob"

**Comment by riyapenn** [comment]
Re-registering yielded no action the app (expected would be a pop up). 

Other logs (adding more through EDITS):
1. https://gist.github.com/1c669d0d5152d66ebf70550c035a3eae

**Comment by ebelinski** [comment]
I'm having this issue as well. My primary phone is using Signal from the App Store and my secondary phone is using Signal installed from Xcode. My secondary phone is able to send messages to my primary phone, and they are successfully received. But my primary phone can't send back messages, and I see the "Unregistered Number" alert. I posted details [here](https://whispersystems.discoursehosting.net/t/trouble-using-signal-for-ios-installed-through-xcode-on-one-phone-with-signal-installed-through-app-store-on-another-phone/705), as @michaelkirk has seen. 

For me as well, re-registering on my secondary phone had no effect at all.

**Comment by ebelinski** [comment]
A user named Brett replied to me [here](https://whispersystems.discoursehosting.net/t/trouble-using-signal-for-ios-installed-through-xcode-on-one-phone-with-signal-installed-through-app-store-on-another-phone/705/17?u=ebelinski) and offered a workaround for making this work. I followed his suggestion for adding `@"fetchesMessages" : @(YES)` to the attributes in `TSAttributes.m`, and now my problem is completely solved. Based on the way he described the problem, I think this may be an issue only for Xcode builds when the push capability is turned off, and only for physical devices (not simulator). He also suggests a few possibilities for fixing this issue, which I think are definitely worth exploring.

**Comment by michaelkirk** [comment]
Thanks for following up @ebelinski 

@riyapenn for future reports can you verify if the user experiencing this behavior installed via the app store vs. building it themselves via xcode?

**Comment by riyapenn** [comment]
Not sure if there is another issue covering this, so I may be adding to the wrong place. 
Log after re-registering on version 2.11.3 https://gist.github.com/anonymous/5fb05a2142ee6a311092d00cbd82ba73 user has " encountered an error when trying to update my OS to 10.3.1"

**Comment by lovetheguitar** [comment]
This problem still occurs on iOS 12! iPhone 8

**Comment by michaelkirk-signal** [comment]
@lovetheguitar - typically this indicates a problem with the *recipient*, not the sender.

In your scenario, were you the sender who saw this message? Or were you the recipient, and someone else say this message while trying to message you?

Could you get a link to a debug log from the recipient, and submit it to support, referencing this comment?

**Comment by lovetheguitar** [comment]
@michaelkirk-signal Thank you for your quick reply! For a short while it looked like the problem was fixed after my friend reinstalled the app on his Android phone, but recently it started to happen again.
Here is his debug log: https://debuglogs.org/4c3e8b0c506b3e65635ba76b4adb60989c5c9c447d4c181fdd6811ac8bfed5e3

It's pretty weird. Sometimes I am able to contact him, but as soon as he replies (or even before that, maybe as soon as he is connected to the internet) I cannot send him any message anymore. Funny enough, he is still able to send me messages and I receive them, but cannot reply since it says he is unregistered.

**Comment by lovetheguitar** [comment]
No reaction, still happening. :/

**Comment by michaelkirk** [comment]
This typically indicates a problem with the account of the person you are failing to send to.

Could you have them follow up?
