### ISSUE TITLE
Removing someone from a group

### ISSUE THREAD

**Issue by wiedo** [WhisperSystems/Signal-iOS#1621]
When you create a group you can't remove a person from it anymore. 

Steps to reproduce:
 - create a group with three or more persons
 - try to remove one person from the group

**Comment by michaelkirk** [comment]
You've never been able to remove someone from a group. Signal has no notion of "group admins". Either the user can choose to leave, or you can create a new group without that user.

**Comment by freekvh** [comment]
I'd like to reopen this, people in a group may get a new phone number and bam we need another group or we get constant errors that delivery failed. This is pretty annoying when you have groups with traveling people with changing phone number. Why not just allow removal?

**Comment by c-taylor** [comment]
I'd like to see this open too: There's a plethora of reasons why someone may hand back, lose a certain device/number.

Only current option is to delete the group and re-add everybody...

**Comment by norpol** [comment]
I'm also running into this issue, a friend of mine got a new phone number and now sending messages to their old number keeps failing.

**Comment by Recompense1776** [comment]
@michaelkirk 

How does one "leave" the group?  Everyone has different messaging apps and do not belong to Signal?

**Comment by NassimBounouas** [comment]
I'm joining to requesters, it's pretty annoying to get messages in failure in a big group because of a member got a new phone number.

**Comment by FelixHen** [comment]
send failed. This is annoying AF.
