### ISSUE TITLE
User prompted to re-register but still receives notifications, OS keychain corrupts/loses the database decryption key

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1627]
- [ X ] I have searched open and closed issues for duplicates most relevant: 

----------------------------------------

### Bug description
User still receiving notifications for Signal, but when opening Signal they are prompted to re-register; last opened Signal probably the night before (before battery died)

### Steps to reproduce
1. Phone died
2. Left it charging all night
3. Turn on phone
4. Received notifications of incoming messages and saw a badge count
5. Opened Signal

**Actual result:** See registration page prompting to re-register
**Expected result:** Normal behavior of messaging

### Device info

**Device**: iPhone 7+
**iOS version**: 10.2
**Signal version:** 2.6.12

### Link to debug log

User 1: https://gist.github.com/cad2e42437d0414720b8abbada725d07
User 2: https://gist.github.com/46a4401eae612a451c16753fbfa7a9bf 
User 3: https://gist.github.com/cf4aa713af70a0b47cef23c82b159df1 
User 4: https://gist.github.com/e3f38da03854e96615f8d084c6aa3596 
User 5: https://gist.github.com/3308be2ff38dc008032751643527c414 
User 6: https://gist.github.com/80011e66dc06f5c7691c6a69cbf4dc48

**Comment by michaelkirk** [comment]
Maybe related to this: https://forums.developer.apple.com/thread/4743?start=105&tstart=0

**Comment by FredericJacobs** [comment]
+1 user report on this

**Comment by riyapenn** [comment]
Resurfacing? https://gist.github.com/anonymous/c0d452ba95da30279244b2371d1632f8

**Comment by riyapenn** [comment]
User on 2.6.15 is stating this is resurfacing.  https://gist.github.com/anonymous/6ccbe5903127eec4599bc523356ba42a
