### ISSUE TITLE
can't find my safety number

### ISSUE THREAD

**Issue by leahbannon** [WhisperSystems/Signal-iOS#1637]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
There does not seem to be a way for me to find my own safety number. I've heard that sometimes it pops up when a new safety number is initiated, but this did not happen for me. The FAQs describe options for finding it that are no longer relevant to the current design.

### Steps to reproduce
- look for safety number
- it's nowhere to be found
- :(

**Actual result:** n/a
**Expected result:** I need to find my own safety number so that I confirm it for my contacts.

### Device info

**Device**: iPhone 7 plus
**iOS version**: 10.2.1
**Signal version:** 2.6.12

**Comment by michaelkirk** [comment]
@leahbannon it sounds like there is some confusion. To clarify, safety numbers are not the same as public keys. Whereas each user technically has their own public identity key, safety numbers exist *per* conversation. 

So, you and anyone you've communicated with over Signal share the same distinct safety number. 
read more here: https://support.whispersystems.org/hc/en-us/articles/213134107-How-do-I-verify-the-person-I-m-sending-messages-to-is-who-they-say-they-are-
