### ISSUE TITLE
New Phone (iPhone 7), Security numbers accepted, still cannot send messages to group.

### ISSUE THREAD

**Issue by laurenbenichou** [WhisperSystems/Signal-iOS#1644]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I've recently changed my phone. I did a backup and restored it to my new phone (iPhone 7). I signed into Signal. No groups were showing. So, I went on my desktop app and asked my friends to accept my safety numbers. I started receiving messages but still can't send any messages from my phone. The input is non-existent and the group name shows up as 'New Group'. I can still receive messages. I can only send them from the desktop app. All the groups members have accepted my new safety numbers.

### Steps to reproduce
- Get a new phone
- Open signal
- Sign in with existing account where you previously had an ongoing group convo.
- ask you friend to send you messages so that the 'New Group' appear. 
- Accept safety numbers, still no way to send messages.

**Actual result:** I cannot type messages. Cannot send messages to this particular group. Group name remains 'New Group'.

**Expected result:** I should be able to type and send messages from my phone. The name of the group should appear.

### Screenshots
![img_1611](https://cloud.githubusercontent.com/assets/5431395/22312189/b34b8090-e30b-11e6-9bed-093c2596e2e0.PNG)

![img_1612](https://cloud.githubusercontent.com/assets/5431395/22312194/b7e54032-e30b-11e6-8864-313ba2c4645e.PNG)

### Device info

**Device**: iPhone 7
**iOS version**: 10.2.1
**Signal version:** 2.6.13

### Link to debug log
https://gist.github.com/7e6624f0c64a698424d936c3ae2a80f9

**Comment by laurenbenichou** [comment]
https://gist.github.com/7e6624f0c64a698424d936c3ae2a80f9

**Comment by liliakai** [comment]
Should be fixed by #1638.

For now, someone else in the group must send a group update to populate the group's name and members on your new phone.

**Comment by michaelkirk** [comment]
This was fixed in 2.11

**Comment by neta1o** [comment]
I had this same issue today on an iPhone 8 iOS 11.2.5 and latest Signal app.  Unfortunately I'm the group creator on many of the groups so seems I just need to wait until individuals in the group message before I message.  Desktop app shows everything fine but phone doesn't.
