### ISSUE TITLE
Feature request: Webhooks for push notifications in compiled from source app

### ISSUE THREAD

**Issue by alist** [WhisperSystems/Signal-iOS#1654]
I have compiled Signal-iOS from source, and I would like to enable push notifications for myself. 

I have my own webserver available publicly on the internet, which would be able to send notifications to my phone. 

If `Signal-Server` was able to accept a URL to ping when I receive new messages, I would be able to trigger notifications to iOS (by registering notifications with my server, [here](https://github.com/WhisperSystems/SignalServiceKit/blob/1824af5335d8faa9f30eed40f0e1dc8198650ceb/src/Network/API/Requests/TSRegisterForPushRequest.m#L17) and [here](https://github.com/WhisperSystems/SignalServiceKit/blob/52762a1be93054ff9bffba15792ec4457b552830/src/Account/TSAccountManager.m#L121), instead of with WhisperSystems)… The webhook could be a POST request providing the same information requested in _Settings > Notifications_.

This update would require both `Signal-iOS` and `Signal-Server` updates, as well as a subsequent `Signal-Android` update.

If you are not interested in performing this update, I would appreciate a pointer to the `Signal-Server` code where I could implement this as a pull request (though I am more experienced with iOS). 

Best,
Alex

**Comment by michaelkirk** [comment]
We're not going to do this. You can, of course, fork the Signal-Server code. Try asking on the forum https://whispersystems.discoursehosting.net/  or mailing list https://lists.riseup.net/www/info/whispersystems for development tips.
