### ISSUE TITLE
Conversation thread randomly scrolls up after opening and leaving phone idle

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1690]
- [X] I have searched open and closed issues for duplicates, related to https://github.com/WhisperSystems/Signal-iOS/issues/1221? I'm being hopeful in saying this bug unexpectedly added https://github.com/WhisperSystems/Signal-iOS/issues/638, although unlikely. 

----------------------------------------

### Bug description
Select a conversation and leave it idle for a few seconds, it randomly goes up a few messages without my intervention

### Steps to reproduce
- Select conversation thread
- do nothing else but view the thread

**Actual result:** sometimes conversation thread scrolls up to a random point
**Expected result:** nothing happens without user interaction or new messages/calls

### Device info

**Device**: iPhone 5S
**iOS version**: 10.2.1
**Signal version:** 2.6.15

### Link to debug log

https://gist.github.com/640f19781a6175c0cc5f7ca6d3a88c2c 
v 2.9.0.5: https://gist.github.com/e13a6b1bf51f13d08506bf49744b1837

**Comment by big-r81** [comment]
@riyapenn @michaelkirk

I can not confirm this on beta 2.13.0.13 or beta 2.13.1.0!

**Comment by michaelkirk** [comment]
Great - Thanks @big-r81 

@charlesmchen revamped auto-scrolling in the 2.13 release. Sounds like this was fixed in the process. 

Closing for now and we can re-open if it reappears.

**Comment by johns582** [comment]
This issue was reintroduced in the version just prior to 3.3.0
