### ISSUE TITLE
Two-step verification for re-registration (like in Telegram)

### ISSUE THREAD

**Issue by anatoli26** [WhisperSystems/Signal-iOS#1703]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

Subj, implement additional (optional) protection of the account for re-registration, i.e. a SMS verification code + a previously configured password. 

![img_3519](https://cloud.githubusercontent.com/assets/22968420/22615400/e4b247d6-ea72-11e6-8078-177cd64baf2c.PNG)

**Comment by 2-4601** [comment]
That probably makes a lot of sense with Telegram which does not have any kind of long term cryptographic identities.

**Comment by anatoli26** [comment]
What do you mean by long-term crypto id? Telegram has a similar e2e crypto as Signal for secret chats. 

Say I can intercept a SMS for your number (quite simple actually). What would stop me from hijacking your account, at least temporarily? Some of your contacts could ignore the keys change without questioning, some others could be convinced. So why not to prevent this completely for those who do care, especially as the implementation for this feature is trivial?

**Comment by 2-4601** [comment]
This issue is the same as https://github.com/WhisperSystems/Signal-Android/issues/5599

If you want to discuss more about the subject, the [forum](https://whispersystems.discoursehosting.net/) or mailing list are best suited for it.
