### ISSUE TITLE
debug log stops recording

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1708]
### Bug description

New entries stop recording to debug log. I've only seen this once but wanted to start taking notes in case it occurs again.

### Steps to reproduce

After using the app for days

go to settings > advanced > submit debug log

**Actual result:** A couple of old logs, but no recent logs

**Expected result:** The last three days of logs.

### Device info

**Device**: iPhone 5.3
**iOS version**: 10.2.1
**Signal version:** 2.6.13.1, 2.7.0.1

### Link to debug log

https://gist.github.com/anonymous/1da6ecc5b9362962cb8b5cb120bc99e7

Note the long gap before the final day. Initially the 2017-02-06 21-03.log was not included in the generated debug log, but after toggling logging off and then generating a new log, it was included.

Maybe related to:

870fb96
907e122

**Comment by riyapenn** [comment]
Toggling the "Enable Debug Log" re-triggers logging information.  Will post more logs to this comment via edits
User 1: https://gist.github.com/anonymous/5bcac587c4ce5fe90cfdb9fbc36b8628

**Comment by riyapenn** [comment]
Is becoming an issue where I can not get useful logs (for other issues) from users without asking them to re-enable, then send in a log after experiencing the issue again.

**Comment by charlesmchen** [comment]
Fixed this in https://github.com/WhisperSystems/Signal-iOS/pull/1841

Sorry Riya - Debug Logs are broken in production right now.  It might even be worth doing a hotfix to 2.8.1.0 that just takes this change.
