### ISSUE TITLE
Unregistering RedPhone

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#171]

**Comment by corbett** [comment]
what is meant by this issue?

**Comment by FredericJacobs** [comment]
Currently, the unregistering works but is TextSecure only. RedPhone is not unregistered when unregistering from Signal.

**Comment by corbett** [comment]
why did you close this issue in that case?

**Comment by FredericJacobs** [comment]
Mistake, sorry.

**Comment by corbett** [comment]
FYI to future fixers something like doesn't work as we don't quite understand the RedPhone server's expectations cc @moxie0 

if
+ (RPAPICall*)unregister {
    RPAPICall *apiCall         = [self defaultAPICall];
    apiCall.method             = HTTP_DELETE;
    apiCall.endPoint           = @"/apn";
    return apiCall;
}

then, chaining API calls when the user clicks unregister

 case kUnregisterCell:
                [TSAccountManager unregisterTextSecureWithSuccess:^{
                    
                    [[RPServerRequestsManager sharedInstance]performRequest:[RPAPICall unregister] success:^(NSURLSessionDataTask *task, id responseObject) {
                        [[TSStorageManager sharedManager] wipe];
                        exit(0);
                    } failure:^(NSURLSessionDataTask *task, NSError *error) {
                        
                        DDLogError(@"Redphone registration failed with information %@", error.description);
                        SignalAlertView(@"Failed to unregister RedPhone component of Signal", @"");
                    }];

                    
                } failure:^(NSError *error) {
                    SignalAlertView(@"Failed to unregister TextSecure component of Signal", @"");
                }];
                break;

**Comment by corbett** [comment]
I think the relevant code is https://github.com/WhisperSystems/RedPhone/blob/5c73c0a17ec7d85af580d594342646b17f7b6947/src/org/thoughtcrime/redphone/signaling/signals/GCMUnregistrationSignal.java where there is a "gcm/"+registrationId. I will try that.

**Comment by corbett** [comment]
update I have now tried this strategy with both the registrationId and the push token  with and HTTP_DELETE call. not much more I can do by way of guessing without input from @moxie0

**Comment by moxie0** [comment]
Delete works, but it's not HTTP
