### ISSUE TITLE
Frequent connectivity problems for Signal only (Qatar)

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-iOS#1711]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
A friend of mine living in Qatar recently got all kinds of problems with Signal on iOS.

Oftentimes (strangely not always),
- messages are not sent,
- messages are not received,
- attachments cannot get downloaded.

Additionally, after reinstalling Signal, he had to try really hard (many attempts over a period of a couple of days) to receive the registration/verification SMS (verification calls also wouldn't work).

Everything else on his phone seems to work fine.

I know for sure that Qatar is blocking many websites, but I'm not sure about Signal yet.

Potentially related to #1633 

### Device info

**Device**: iPhone 5c
**iOS version**: 10.2.1
**Signal version:** 2.6.15.0

### Link to debug log
https://gist.github.com/anonymous/5ee6f7b16acf1c67c737ba15a7bf93de

**Comment by michaelkirk** [comment]
User is unable to reach the Signal Service. Could be censorship or just a bad or no network. 

It would be good to know if the user can reach https://www.google.com.qa/ or https://whispersystems.org

**Comment by RiseT** [comment]
The user can reach both URLs.

While I agree that it looks like a bad network, the interesting thing is that this only happens with Signal. All others apps don't seem to have these kind of connectivity problems.

Here's another log:
https://gist.github.com/anonymous/d7b8c8b8f32e77e06aae6e9b50b7400f#file-org-whispersystems-signal-2017-03-06-13-02-log

Note that Signal is not even capable of uploading the logs in this case.

**Comment by RiseT** [comment]
Fixed by https://github.com/WhisperSystems/Signal-iOS/commit/8ff14a3f6a386550b8634dc74428672873a36673
