### ISSUE TITLE
Screen doesn't go off next to ear during outgoing call in 2.7.0.5

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#1714]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When placing an audio call from an iphone with webrtc calls activated to an iphone with webrtc also activated, the outgoing iphone doesn't switch off the call screen as a reaction to the proximity sensor.

The iphone receiving the call does switch off the screen in both callkit and signal's call screen.

When a redphone call is placed, the screen goes off in the outgoing iphone as expected.

### Steps to reproduce
- place a webrtc call from one device to the other
- answer the call in the other phone
- place the calling device next to your ear 

**Actual result:** Screen of iphone placing the call doesn't switch off
**Expected result:** Screen of iphone placing the call should go off when in contact to ear.  

### Device info

**Device**: iPhone5s -> iPhone6s
**iOS version**: 10.2.1 -> 10.2.1
**Signal version:** 2.7.0.5 -> 2.7.0.5

PS. Though sound quality for a webrtc call seems better compared to redphone, I cannot hear a great difference.

**Comment by iadmir** [comment]
Same issue on iPhone 5S 
iOS 10.2.1
Signal version: 2.7.1

Debug log
https://gist.github.com/5b6a158b6dbd2ceb4c3fc5989b46750c

**Comment by NicolasCGN** [comment]
Same behaviour with 2.8.0.4
