### ISSUE TITLE
No way to fix typos in phone number when registering app.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1727]
In onboarding flow, If typo in setting device number, there's currently no way to “navigate back” and change the phone number.

As pointed out by Moxie today, in addition to typos it’s easy to mistype some international phone numbers (ie. forget to append a 9 for mobile devices after the country code).

**Comment by michaelkirk** [comment]
If I'm understanding, this actually does already exist. But it's arguably not discoverable enough. For example, I often first tap on my actual phone number when I want to change it, which triggers the "call me instead"

![image](https://cloud.githubusercontent.com/assets/217057/22745469/a428c36e-edee-11e6-96e0-031fd987f778.png)

My first reaction is that call me instead should be a button like "request code again"

And we combine the "Change number" and "+111111111111" elements.

**Comment by charlesmchen** [comment]
@michaelkirk What about a classic "back button" in the upper left hand of the view?  That's where users are trained to look for a "go back" during this kind of multi-page interaction. Ideally, a back arrow would be small enough that it would require any other changes to the layout of this view. 

Another issue with the existing "change number" and "call me instead" UI elements is that they are hidden when the keyboard is active, i.e. when the "verification code" text field is selected.

**Comment by michaelkirk** [comment]
Yup. Agreed all around @charlesmchen

**Comment by charlesmchen** [comment]
* The stakes are high here, since by definition users aren't invested in the app yet. Even small problems with our onboarding will directly affect how many people successfully create accounts and become users.
* "Call me instead" and "change number/back" are core interactions - I think we're making a mistake by placing them where they will often be hidden by the keyboard. Users will often select the text field while they wait for the verification code to arrive. When it doesn't arrive, they'll be stuck.
* It's always hard to design iOS layouts that work when the keyboard is active since there's so little screen real estate left on our smallest form factors (Currently iPhone 5/SE?).  The current design uses a huge amount of space for the Signal logo at the top of the screen.  I suggest that we remove it/resize it so that all controls appear at all times on all devices (if possible).  We're already hiding this logo on some form factors, but there's still "wasted" space that we can make better use of.

### iPhone 6S

![screen shot 2017-02-08 at 12 14 33 pm](https://cloud.githubusercontent.com/assets/625803/22748467/309abe70-edf8-11e6-859e-828fb6d91fc0.png)

### iPhone SE

![screen shot 2017-02-08 at 2 20 25 pm](https://cloud.githubusercontent.com/assets/625803/22753346/d6c1ddc2-ee09-11e6-82b2-80c3abaaab74.png)

Thoughts @michaelkirk @riyapenn ?

**Comment by michaelkirk** [comment]
I'm ok with making space for these important actions. Keep in mind that the layout is intended to be consistent across the several signup screens.

**Comment by charlesmchen** [comment]
> Keep in mind that the layout is intended to be consistent across the several signup screens.

Right, I guess I'm advocating that we either make this view inconsistent - or change all of them.  I prefer the former?

**Comment by michaelkirk** [comment]
I believe this was completed by #1740. Feel free to re-open if you had other plans @charlesmchen
