### ISSUE TITLE
Simplify interactions around attachments

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1728]
* It should be very easy to view/play a image, video or audio attachment from conversation view.
* It should be very easy to save a image, video or audio attachment from conversation view or "attachment view".
* It should be very easy to dismiss "attachment view".

Different messaging apps use different gestures for these actions - we should be permissive and accept multiple gestures.  Additionally, in some cases we may want to use the "any touch" gesture recognizer which is faster than a tap.

**Comment by michaelkirk** [comment]
I agree with this, but it would be good to propose more specific changes before forging ahead here.

**Comment by charlesmchen** [comment]
@michaelkirk Good point:

Proposed changes:

* Swipe-up to dismiss "photo attachment view" and "video attachment view". This is a common interaction in other clients.
* Double-tap (or more taps, and taps with multiple fingers) to dismiss those same views. Many users don't distinguish between tap and double-tap and/or perform those gestures sloppily.  Currently double tap with a single touch zooms a photo which is unlikely to be the intent - and is redundant with pinch-to-zoom.
* Long press shows "copy/delete/save" in conversation view but not in "photo attachment view" and "video attachment view".  It should work in both.
* "Copy/delete/save" controls are positioned outside the image/video, which is not consistent with other apps.  It should appear just above/below the touch. Current positioning is also ambiguous about which attachment will be affected, since the controls can easily appear above a different attachment.
* Audio attachment's "play" button sometimes disappears if pressed.  
* Tapping the audio attachment's "play" button doesn't work - you have to tap the waveform.
* "Photo attachment view" and "video attachment view" animate in. First, I think these animations are slow and unnecessary - they make interacting with multiple attachments cumbersome.  The animations should either be much faster or removed. Secondly, these animations are inconsistent. Photos "drop down from above" while video "drop in and zoom in from upper-left hand corner."  If we retain these animations, they should be consistent.
* "Video attachment view" has a black square-cornered letterbox background and a toolbar with a "done" button. "Image attachment view" has a semi-transparent background, rounded corners and no toolbar or "done" button. I thing we should make them consistent, probably by adopting the video style.
* Unlike image and video attachments, there's no way to make the audio attachment play in full screen mode.  We don't need to change this, but its inconsistent.  If we went fullscreen, it'd be much easier to scrub the audio.  

Thoughts @michaelkirk ?

**Comment by riyapenn** [comment]
Looks like significant changes but may need coordination with a couple of other issues i.e. https://github.com/WhisperSystems/Signal-iOS/issues/1233 and design.  

However usability issues for current design (as you have included above) centered around https://github.com/WhisperSystems/Signal-iOS/issues/1010 and https://github.com/WhisperSystems/Signal-iOS/issues/1072 sound like starting points.

**Comment by charlesmchen** [comment]
* Although the pragmatic short-term fix is to dismiss the image attachment view with a "swipe" gesture recognizer, in the long run it'd be nice to use a "pan" gesture recognizer so that the gesture animates and thus indicates its effect and is cancellable.
* It'd also be nice in (a hypothetical future) "combined image/video attachment view" to allow users to left- and right-swipe through the media in this conversation.  WhatsApp and iMessage both let you do this and it's quite convenient for media-heavy conversations.

**Comment by charlesmchen** [comment]
I completed about half of this work over the weekend in https://github.com/WhisperSystems/Signal-iOS/pull/1751.

I've opened a new issue to track the remaining work: https://github.com/WhisperSystems/Signal-iOS/issues/1760
