### ISSUE TITLE
Incorrect layout for images with unusual aspect ratios.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1749]
In conversation view, tall and wide images aren't always laid out properly. This issue seems to affect scroll state mostly.

edit by @michaelkirk

This was related to messages with extreme AR, e.g. really short/wide messages and really tall/skinny.

**Comment by michaelkirk** [comment]
example image attachments or a screenshot would be good to clarify what you mean.

**Comment by TreatyOfRome** [comment]
Screenshot from a photo taken with and received from a Samsung Galaxy S7 EDGE. 
![fullsizerender](https://cloud.githubusercontent.com/assets/26620973/24492319/80d8adae-151a-11e7-84f8-d3a0e231c9a2.jpg)


When selecting another photo from this conversation, closing it and scrolling back to the conversation view with this photo, the aspect ratio is correct again. 
![fullsizerender2](https://cloud.githubusercontent.com/assets/26620973/24492236/2e6806fa-151a-11e7-8073-0bbcc631244c.jpg)

When closing Signal (double tap home button, swipe up) the aspect ratio is back to the wrong aspect ratio as seen in the first screenshot. Opening and closing this particular photo does not correct the aspect ratio. 

I cannot reproduce this with all photo's received from this Samsung. Some have unusual aspect ratio's, some don't. 

Device: iPhone 6S
iOS version: 10.3
Signal version: 2.9.0

**Comment by big-r81** [comment]
Hi,
i can confirm this behavior.

- after uploading the image upload indicator is hiding and sometimes the pictures get squeezed or squashed
- sometimes old pictures getting distored too - after sending a new picture!
- viewing a picture (fullscreen) and closing full screen shows sometimes wrong images aspect ratios
- scrolling the thread will show sometimes wrong image aspect ratios

----------

- leaving a conversation and entering the same conversation can help to show images with correct aspect ratios (not alle images are shown correct)
- long-pressing on an image with wrong aspect ratio shows correct, after showing the menu (copy/delete/save/share)

Until now, i can't give a 100% instruction for reproducing the error(s).

Device IPhone 6
iOS version 10.3
Signal version 2.9.1

**Comment by charlesmchen** [comment]
Fixed in the forthcoming release.

**Comment by stark226** [comment]
Hi, I'm stuck on similar issue, I know it is old stuff for you, but I'm still working on an app that is based on old signal version.  Could you give me some help, hint or indication? here you can find my question on stack. [https://stackoverflow.com/questions/78607380/swift-version-of-signal-derived-app-scrolling-messages-causes-message-bubbles-n](url) an image
![JnJwi](https://github.com/signalapp/Signal-iOS/assets/6348412/71123780-2ac4-4b71-a53f-68cb1e722ae6)
