### ISSUE TITLE
Dedupe incoming messages by timestamp

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1759]
### Bug description

Occasionally, especially in a group setting, we'll see duplicated incoming messages. Usually this can be traced back to the sender repeatedly sending their message because of a previously perceived  failure to send.

### Steps to reproduce
I'm not exactly sure here, but I think it's like this:

- Start a group with Alice Android, Ivan iOS, and Wally Whatever.
- Alice sends a "hello" message to the group, which successfully sends to Ivan, but fails to send to Wally (for whatever reason. Maybe keychange?)
- Alice retries to send to Wally

**Actual result:** Ivan sees two "hello" messages from Alice. One for the original send attempt, and one for the retry.

**Expected result:** Ivan should only see one "hello" message. The second-received message should be silently discarded based on (sender, device, timestamp).

**Comment by 2-4601** [comment]
You can reproduce this with https://github.com/WhisperSystems/Signal-Android/issues/2639
I.e. get in a bad coverage area, try sending group messages and when they fail hit those resend buttons.

I think the Android counterpart is this: https://github.com/WhisperSystems/Signal-Android/commit/7e51d61c7900e9d57c15eb6a6d595103bfdb7f79

**Comment by michaelkirk** [comment]
Will be in the next release

Solved by https://github.com/WhisperSystems/SignalServiceKit/pull/119
