### ISSUE TITLE
Write Push Notification (iOS7 and iOS8) fake implementations for simulator

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#176]

**Comment by FredericJacobs** [comment]
This is pretty neat. https://github.com/acoomans/SimulatorRemoteNotifications

**Comment by corbett** [comment]
Cool!

On Mon, Jan 19, 2015 at 7:29 AM, Frederic Jacobs <notifications@github.com>
wrote:

> This is pretty neat.
> https://github.com/acoomans/SimulatorRemoteNotifications
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/176#issuecomment-70530799>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by michaelkirk** [comment]
Closing this as I'm not sure what the application is. Feel free to re-open with an application.

There are some existing test fakes in https://github.com/WhisperSystems/SignalServiceKit/blob/master/tests/TestSupport/Fakes/OWSFakeNetworkManager.h
