### ISSUE TITLE
MITM attack or bug?

### ISSUE THREAD

**Issue by taoeffect** [WhisperSystems/Signal-iOS#1765]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

A friend got a new phone. I decided to verify the "safety number" in person since I was nearby.

1. We both opened our Signal apps (both on iOS)
2. I pull up the safety number by going into the message view and clicking on the "Verify Safety Number" button. I had previously attempted to send them a message, and that's how I got that button.
3. They, having not been aware of these message attempts, opened up the message view to point to my contact, and tapped on my name to bring up my safety number.

The safety numbers did not match.

They then attempted to send me a message, and got the same verify safety number message that I got. This time the safety numbers did match. The new number that was displayed on their phone was now the same as what my phone was showing.

So I do not understand. Since this was a brand new phone of theirs, from where did their app get the safety number to show when they manually tapped on my name in the menubar at the top? And why was it different then, than after they tried messaging me?

Unfortunately they did not get a screenshot of the original (incorrect) number. Also, I did not have the insight to have them accept the invalid number and see what might happen from there.

**Comment by michaelkirk** [comment]
Can you both submit debug logs?

Settings > Advanced > submit debug log

**Comment by taoeffect** [comment]
@michaelkirk If the debug log was disabled, is it still worth enabling it now and sending it?

**Comment by michaelkirk** [comment]
A little tricky to follow the details of your report, but it sounds like what's happening is that they got a new device, re-registered Signal, so that when you contacted them, you were rightly shown a safety-number-changed notification.

> @michaelkirk If the debug log was disabled, is it still worth enabling it now and sending it?

Definitely less useful at that point, but it would still tell me what version you and your partner are running.

**Comment by michaelkirk** [comment]
To be clear, I need to know which version both you and your partner are running.

**Comment by taoeffect** [comment]
@michaelkirk Just sent mine to your support email, the subject contains `id:9999`. I'll ask them to do the same.

**Comment by taoeffect** [comment]
@michaelkirk Just sent you their log in a followup to that same email thread. Looks like they had it enabled, and theirs was the problem phone, so hopefully should be of use to you.

**Comment by taoeffect** [comment]
@michaelkirk You'll want to look at yesterday's log, somewhere around 5pm-ish (west coast time) or so, if memory serves.

**Comment by michaelkirk** [comment]
Thanks for the logs.

Your friend is running a really old version. This sounds similar to an issue resolved last year (in November IIRC), which would ensure you couldn't see safety numbers until after exchanging messages. 

Could you ask your friend to update and see if it's reproducible?

**Comment by taoeffect** [comment]
Updating should not help them reproduce this because the only way to reproduce this would be for them to re-install that old version of the app afresh. How they'd go about doing that I'm not even sure. If they were to update they wouldn't get any sort of prompt, it would just continue as before, with the current security number.

**Comment by taoeffect** [comment]
FYI: I asked how they got such an old version given that they got their phone just recently. It seems like they think they either somehow got an outdated version from the AppStore (unlikely), or it was the version that iTunes restored for them.

**Comment by michaelkirk** [comment]
> or it was the version that iTunes restored for them.

This is plausible.

> Updating should not help them reproduce this because the only way to reproduce this would be for them to re-install that old version of the app afresh

Again, it sounds like your friend was running a really old version of the app and hit some confusing behavior that could occur before messages had been exchanged - this was fixed last year. Having them update their client will fix the problem. If not please reopen the issue.

Thanks for the details.
