### ISSUE TITLE
Ensure proper ordering of messages blocked by safety number changes.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1778]
We're now ordering by `receivedAt` and `receivedAtDate`. I suspect that messages blocked by safety number changes will be instantiated as TSIncomingMessages _after_ the safety number change is accepted, so they'll end up with a `receivedAtDate` that reflects "acceptance time", not "receipt time."  We should fix that.

**Comment by michaelkirk** [comment]
@charlesmchen  Was this fixed by: https://github.com/WhisperSystems/SignalServiceKit/commit/427f225df9be0b6789af95b28f500d451722fe29?

**Comment by charlesmchen** [comment]
@michaelkirk I'm not sure, but I doubt it.  `[TSMessage receivedAtDate]` is set when the message is decrypted, not when the message is received. I'm guessing that we don't decrypt messages until the user accepts the safety number change?

**Comment by michaelkirk** [comment]
fixed in 2.13.0
