### ISSUE TITLE
No outgoing call ring

### ISSUE THREAD

**Issue by iadmir** [WhisperSystems/Signal-iOS#1792]
- [x] I have searched open and closed issues for duplicates

----------------------------------------
### Bug description
After placing call can't hear any ring tone
### Steps to reproduce
- Enable video calling and CallKit
- Make a call

**Actual result:** No outgoing call ring in both stages (Connecting,  Ringing)
**Expected result:** Outgoing call ring

### Device info

**Device**: iPhone 5S, iPhone 5
**iOS version**: 10.2.1
**Signal version:** 2.7.1, 2.7.0

**Comment by michaelkirk** [comment]
Will be in the next release, thanks!

(solved by https://github.com/WhisperSystems/Signal-iOS/pull/1811)
