### ISSUE TITLE
Back button on new message screen doesn't work.

### ISSUE THREAD

**Issue by darrenw** [WhisperSystems/Signal-iOS#1794]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The back button on MessageComposeTableViewController doesn't work.
I'm not particularly used to Storyboard based development but I believe the issue is that MessageComposeTableViewController is being modally presented in a navigationcontroller, and the taps on the back button it gets from calling 'useOWSBackButton' call popViewController, which doesn't dismiss the modal and so it goes nowhere.

### Steps to reproduce
- Launch signal.
- Hit the 'new message button in the top right'
- Hit the back button on the resulting screen.

**Actual result:** Nothing happens.
**Expected result:**  The new message screen should disappear and go back to the main screen.

### Device info
**Signal version:** Master built off commit 5cd1d17056dab08b5b0f30487a632746bfae61b2

**Comment by charlesmchen** [comment]
@darrenw Fixed in https://github.com/WhisperSystems/Signal-iOS/pull/1813.  Fix will ship in next release (1-2 weeks).
