### ISSUE TITLE
iPhone feels very hot during a WebRTC audio call (& battery issues)

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#1802]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
iPhone 4S feels very hot during a WebRTC audio call (video disabled on both ends). RedPhone calls don't have this effect.
Is the video being captured even though it is not enabled? I guess this would explain the heat... that phone also heats up during facetime video calls but not on facetime audio calls.

### Device info
**Device**: iPhone 4S
**iOS version**: 9.3.5
**Signal version:** 2.7.1

### Link to debug log
Don't have one because it's not my device but I guess I could somehow manage to get one :)

**Comment by iadmir** [comment]
Same issue on iPhone 5 
iOS 10.2
Signal 2.7.0

**Comment by 2-4601** [comment]
Corresponding issue at the Android repo: https://github.com/WhisperSystems/Signal-Android/issues/6259 and fix https://github.com/WhisperSystems/Signal-Android/commit/cb9f225f5962d399f48b65d5f855e11f146cbbcb

**Comment by RiseT** [comment]
Potentially fixed by https://github.com/WhisperSystems/Signal-iOS/commit/e3eca4db7b6a4d70723d1e21b7c4ee4b2a46563e...?

**Comment by michaelkirk** [comment]
@RiseT - It should help, thanks for watching.

**Comment by 2-4601** [comment]
Definitely fixed the heat issue on the said iPhone 4S :clap:
