### ISSUE TITLE
enable video call (beta) setting is not saved

### ISSUE THREAD

**Issue by drderkummer** [WhisperSystems/Signal-iOS#1808]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I just called a friend who is travelling and is using the iOS app. We tried to have a video call (which btw is working like a charm with other friends who are using android) but she is not able to use it from her iphone. When she tries to enable the video call (beta) in the settings menu the setting is not saved after leaving the screen and thus the possibility to use video functionality during the call is not available.

### Steps to reproduce
- go to settings/additional settings/enable "video call (beta)
- call someone (video functionality not available during call)

**Actual result:** Video call not available
**Expected result:** Video call option should be available

### Device info
**Device**: iPhone 5
**iOS version**: most recent
**Signal version:** most recent

**Comment by JohanDoe** [comment]
I think the issue as closed in #1787 is still troubling some of us (like me)

@drderkummer in the meantime you might want to try what I did as described in #1787: play around with the submit debug log toggle. And wait a few seconds before going back to settings.

**Comment by drderkummer** [comment]
#1787 sounds similar. Sorry that i didn't find it. I wrote my friend the possible solution and will let you know if it worked. Thanks for your help.

**Comment by charlesmchen** [comment]
@JohanDoe @drderkummer Hi there. Yes, this issue has been fixed but we haven't shipped the fix yet.  In the meantime, please try waiting a few seconds after enabling WebRTC calling before leaving the settings dialog. Thanks for your patience.

**Comment by drderkummer** [comment]
Wonderful! That's good to hear. Waiting a few seconds did the magic. Thank you for your quick response!
