### ISSUE TITLE
When contact access is restricted, error message next action goes to wrong permission screen

### ISSUE THREAD

**Issue by zachware** [WhisperSystems/Signal-iOS#1819]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
In situations where access to contacts has been restricted, Signal throws an unpassable error alert "Sorry! Signal requires access to your contacts..." 

Clicking OK opens Settings/Signal when in fact the Contact access settings are not in that screen but rather in Settings/Privacy/Contacts. There is not ability to give permissions unless the application requests it.

In this case instead of redirecting to Settings the application should explicitly request permission to access contacts as it does on first load. 

### Steps to reproduce
- Go to Settings/Privacy/Contacts. 
- Remove Signal.
- Open signal.
- Click OK with error message.

**Actual result:** 
Clicking OK opens Settings/Signal when in fact the Contact access settings are not in that screen but rather in Settings/Privacy/Contacts. There is not ability to give permissions unless the application requests it.

**Expected result:** 
Some sequence should in fact request contact access as on first load and the application will be usable again.

### Device info

**Device**: iPhone 6s Plus
**iOS version**: 10.2.1
**Signal version:** 2.7.1

### Link to debug log
Cannot access.

**Comment by michaelkirk** [comment]
We can only show that initial prompt one time. This is an OS restriction.

But what you are describing sounds strange - we should be taking you to the settings specific to Signal, and I've just verified that's what I see on an iOS 10.2 device. 

Can you send a screenshot of what you see before tapping the alert in Signal, and then another once you've tapped the alert?

**Comment by michaelkirk** [comment]
please re-open with screenshot if this is still an issue.
