### ISSUE TITLE
"the request timed out" - sending pictures keeps failing

### ISSUE THREAD

**Issue by xtihx** [WhisperSystems/Signal-iOS#1820]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I recently discovered that sending pictures from my phone in either signal group chats as well as private converstions keeps failing.

### Steps to reproduce
- i restarted app and iphone
- i tried different pictures in different chats
- pictures are taken with my phone
- i choose pictures and see the "uploading..." message for 60seconds
- i receive the "sending failed. tap to retry" message
- i try to re-send
- same result.
- i delete message and chose pitcture again from phone library.
- same result.

**Actual result:** 
I'm not able to send any pictures.
**Expected result:** 
Share pictures in chats as i'm used to.

### Device info

**Device**: iPhone 5c
**iOS version**: 10.2.1
**Signal version:** 2.7.1

### Link to debug log
Log URL: https://gist.github.com/40bcb47abc2cba87a72865c3e823cdbe

**Comment by riyapenn** [comment]
Attachments are back! One of our providers was suffering a major outage that is causing attachment sending to fail in Signal. All messaging has resumed to normal. Closing as this should no longer be an issue.
