### ISSUE TITLE
Incorrect country code by country name when registering, prevents registration

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1821]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Countries have incorrect [country code listed for registration](https://github.com/WhisperSystems/Signal-iOS/blob/c7ee430790898110f575adbda5bf34000b32242f/Signal/src/view%20controllers/CountryCodeViewController.h)

### Steps to reproduce
- Install Signal
- See registration screen
- Tap Country Code to edit country code
- Choose country listed, with incorrect country code of +0 i.e. Kosovo should be + 383
- Typing in entire phone number (country code without +) yields "Registration Error"

**Actual result:** Country code is listed as +0 and can not edit
**Expected result:** Country code to be editable manually or have correct code listed

### Screenshots
 
![screen shot 2017-03-01 at 4 55 20 pm](https://cloud.githubusercontent.com/assets/4898366/23488189/e6583726-fe9f-11e6-896a-1688889c5900.png)

# Summary of misused +0 as country code

Country | Country Code | Comments
------- | -------- | --------
Antarctica |  +672
Bouvet Island | +55
Canary Islands | +34
Ceuta & Melilla | +34
Diego Garcia | +246
French Southern Territories | +262
Kosovo | +383
Pitcairn Islands | +64
So. Georgia & So. Sandwich | +500
U.S Outlying Islands | +1

### Device info

**Device**: iPhone 5C
**iOS version**: 10.2.1
**Signal version:** 2.7.1

**Comment by michaelkirk** [comment]
Fixed in the next release.
