### ISSUE TITLE
Ability to save images

### ISSUE THREAD

**Issue by alex** [WhisperSystems/Signal-iOS#1824]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

I was sent an image in a Signal conversation. I would like to save it to my device. This is possible on Signal on Android, but not on iOS.

**Comment by iadmir** [comment]
Is possible on iOS too, long tap on image and choose "Save".

**Comment by charlesmchen** [comment]
@iadmir @alex In the conversation view or in the attachment view, you should be able to long press and save image attachments.

**Comment by michaelkirk** [comment]
What about exposing a visible save button when viewing attachments "full screen"?
