### ISSUE TITLE
Feature request: jumbomoji

### ISSUE THREAD

**Issue by zstal** [WhisperSystems/Signal-iOS#1828]
- [x] I have searched open and closed issues for duplicates
----------------------------------------

### Description
If your message contains only emoji, they should appear larger.

- It's a proven thing, implemented in Slack, WhatsApp and iMessage.
- It could serve as a replacement for stickers and GIFs until they land in the iOS version.
- Looks good, is probably cheap to implement and would help entice new users to the platform.

### Screenshots

From Slack's help pages:
![image](https://cloud.githubusercontent.com/assets/3130702/23623020/2b5e24b6-02a1-11e7-920d-8f9c3e9da38f.png)

Update May 2017: This is now live on Signal-Android & Signal-Desktop.

**Comment by jschneier** [comment]
I had the same idea and got pretty deep into the weeds of JSQMessagesViewController, was going to open an issue but [found this recent issue](https://github.com/jessesquires/JSQMessagesViewController/issues/2033) unfortunately.

**Comment by Aktariel** [comment]
Sounds like we need a "Can'tFix" or an "Upstream Issue" tag.

**Comment by zstal** [comment]
Now that JSQMessagesViewController is being removed, I think this feature request can be revisited to bring feature parity to iOS.

**Comment by charlesmchen** [comment]
This feature is complete and will ship in v2.19.
