### ISSUE TITLE
We need to improve effort to ensure message ordering.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1840]
See screenshots.

Repro 1:

* Send attachment A.
* Send message B.

Expected: A will be delivered before B.
Observed: B will typically be delivered before A.

___We should enqueue messages in the order in which they are sent and upload them in serial order - unless a given message exhausts its retries and fails.___

Repro 2:

* Enable network link conditioner in "very bad network" mode (which will cause frequent network errors).  It's worth noting that this mode reflects common network conditions for mobile users.
* Send messages A, B, C, D, E, F, G in rapid sequence (should each have a different, very short text body).

Expected: A, B, C, etc. will be delivered in order.
Observed: Messages will arrive in nearly random order.

___We should enqueue messages in the order in which they are sent and upload them in serial order - unless a given message exhausts its retries and fails.___

### Sender

![img_4298](https://cloud.githubusercontent.com/assets/625803/23836245/3861daf6-0754-11e7-9dfd-ea0a9ce3340f.PNG)

### Recipient

<img width="246" alt="screen shot 2017-03-12 at 6 45 47 pm" src="https://cloud.githubusercontent.com/assets/625803/23836246/3e68ea34-0754-11e7-9ac8-f8abe0f35f09.png">

**Comment by michaelkirk** [comment]
closed with 
https://github.com/WhisperSystems/SignalServiceKit/issues/131
