### ISSUE TITLE
Call gets dropped when I try to call out 

### ISSUE THREAD

**Issue by realayo** [WhisperSystems/Signal-iOS#1844]
Call gets dropped whenever I try make a video or audio call to another signal user. Text messages work fine. 

- Re-installed signal
- Re-register for push notifications

When I try to call, it shows connecting, then call gets dropped and there's "Login Failed" in red for about 3 seconds.
When I try to Re-register for push notification, I get "Failed to re-register for push notifications. Request failed: unauthorized (401)" error

iPhone 6s
iOS Version: 10.2.1
Signal Version: 2.8.1

**Comment by michaelkirk** [comment]
@realayo - sounds like a redphone call. Could you try after both you and your partner have upgraded to latest signal?

Please re-open if this is still an issue.

**Comment by realayo** [comment]
I have upgraded to 2.8.2. I can receive calls but I still get the "login failed" message when I try to call out.

**Comment by michaelkirk** [comment]
Can you send a screenshot of the "login failed"?

When call's fail, are you calling the same person who called you?

Can you also submit a debug log immediately after a call fails? (settings > advanced > submit)

**Comment by realayo** [comment]
![img_7290](https://cloud.githubusercontent.com/assets/18899718/24008143/106bdae0-0a71-11e7-8a13-d526c41e528a.PNG)
Yes. I get the error when I try to call back or I'm calling.

Log URL: https://gist.github.com/24fd73df524ebed47943babbdedcafb7

**Comment by michaelkirk** [comment]
The screenshot reveals that you are using our old calling system (aka "red phone"), which, for some reason or another, you aren't able to authenticate with.

Unrelated to this, we have recently replaced Redphone with a higher quality calling system. It looks like your contact (whether Android or iOS) needs to update. When you're both on up-to-date versions, you should see a new call screen, an indication that you're on the modern calling system.

I'm closing this issue, but please re-open if you can reproduce after your partner updates. If you *do* continue to have issues, we'll need to know if they are running Android or iOS, which version, and a debug log from them.
