### ISSUE TITLE
Can only place RedPhone calls to a certain Android device

### ISSUE THREAD

**Issue by tge-linee** [WhisperSystems/Signal-iOS#1858]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Same issue as drescribed in https://whispersystems.discoursehosting.net/t/videocalling-withios-not-possible/876
When I place a call to a certain Android device I see the old (RedPhone) call screen on both devices. I can place a WebRTC call to other devices.

Both phones had the beta calling function enabled before the update.

### Steps to reproduce
- place a call

**Actual result:** It's a RedPhone call
**Expected result:** I should be a WebRTC call

### Device info

**Device**: iPhone 5
**iOS version**: 10.2.1
**Signal version:** 2.8.2

**Device**: Nexus 5X
**Android version**: 7.1.1
**Signal version:** 3.31.4

### Link to debug log

iPhone: https://gist.github.com/171da87f64ccf2ca4b81eecbb608c034
Android: https://gist.github.com/6afe516a3e56c7efdbb5563be2640984

**Comment by michaelkirk** [comment]
Interesting. Which call screen do you see when the Android phone calls the iOS phone?

**Comment by tge-linee** [comment]
WebRTC

**Comment by michaelkirk** [comment]
Before placing the call we do a capabilities check - looks like your Android device hasn't properly reported that it's WebRTC capable. I'm not sure how to force Signal-Android to re-report it's capabilities other than re-registering... I'll get back to you.

**Comment by tge-linee** [comment]
Ah, so this probably belongs in the Android repository. I'll file a bug over there. Now that 4.0.0 kicked the RedPhone code, I'm not able to receive calls anymore.

**Comment by michaelkirk** [comment]
Fixed in v2.9.0
