### ISSUE TITLE
UX issue with answering calls from locked screen

### ISSUE THREAD

**Issue by i7u** [WhisperSystems/Signal-iOS#186]
Answering incoming calls when the phone is locked is non-intuitive. Signal rings, the user swipes to unlock the phone and... nothing. Signal is no longer ringing, nor is it in the foreground. From the POV of the recipient, they have missed the call. At the same time, the initiator of the call is wondering why they won't answer as the call keeps ringing and ringing.

The user must notice/learn that they need to swipe _on the Signal notification itself_ to answer the call, which is
1. non-obvious
2. difficult to achieve for sight-impaired users

Signal should continue ringing after the phone has been unlocked, and either bring itself in the foreground or give users visual cues to answer the call.

**Comment by corbett** [comment]
seems to be closed @FredericJacobs
