### ISSUE TITLE
Echo on video calls

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1879]
- [X] I have searched open and closed issues for duplicates.  [Relevant Android issue + comment](https://github.com/WhisperSystems/Signal-Android/issues/6241#issuecomment-283013705) 
----------------------------------------

### Bug description
Feedback/Echo on speaker's own device when speaking

### Steps to reproduce
- Have a connected Signal voice call
- Switch to video
- Try with/without headphones (no difference)

**Actual result:** Echo where speaker on iOS hears themselves 
**Expected result:** No echo

### Device info

**Device**: iPhone 5S
**iOS version**: 10.2.1
**Signal version:** 2.8.3

### Link to debug log

Iphone on which the echo occurs: 
https://gist.github.com/b484f3c7c45e28c8a194ede5c631ec3b

Android (Cyanogenmod) Phone, no echo: 
https://gist.github.com/64460d633ce5c7fa976a979c63e4c1bc

**Comment by michaelkirk** [comment]
I think when you hear echos it's because the *remote* side doesn't have working echo cancellation (e.g. the cyaogenmod user), but you could verify this by calling someone from that same iPhone setup who is *known* to have working echo cancellation and see how it goes.

**Comment by michaelkirk** [comment]
LMK if you can reproduce the echo when the *source* of the echo is iOS.

Otherwise, I'm assuming this is an issue with CM not doing echo cancellation properly. Feel free to reopen if you disagree @riyapenn.
