### ISSUE TITLE
CBR option not added to session description

### ISSUE THREAD

**Issue by raphaelrobert** [WhisperSystems/Signal-iOS#1885]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

CBR option is not added to the session description.

### Details

In https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/call/PeerConnectionClient.swift#L777 the function `replacingOccurrences` doesn't seem to take the regex into account and `cbr=1` is not added to the session description.

Expected output: `a=fmtp:111 minptime=10;useinbandfec=1;cbr=1`
Actual output: `a=fmtp:111 minptime=10;useinbandfec=1`

**Possible fix**

`let regexCbr = try! NSRegularExpression(pattern:"(a=fmtp:111 ((?!cbr=).)*)\r?\n", options:.caseInsensitive)`

`description = regexCbr.stringByReplacingMatches(in:description, options: [], range: NSMakeRange(0, description.characters.count), withTemplate:"$1;cbr=1\r\n")`

The same is true for the audio levels in line 781.

**Possible fix**

`let regexAudioLevel = try! NSRegularExpression(pattern:".+urn:ietf:params:rtp-hdrext:ssrc-audio-level.*\r?\n", options:.caseInsensitive)`

`description = regexAudioLevel.stringByReplacingMatches(in:description, options: [], range: NSMakeRange(0, description.characters.count), withTemplate:"")`

**Comment by michaelkirk** [comment]
In https://github.com/WhisperSystems/Signal-iOS/commit/0c8da2865e9d88b329c9bd603bc99bbbe462576c.

Thanks!
