### ISSUE TITLE
Can place outgoing call with microphone permission disabled

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1886]
- [X] I have searched open and closed issues for duplicates 

----------------------------------------

### Bug description
One-sided conversations as result of users not having the microphone permission enabled

### Steps to reproduce
- Alice installs Signal
- Select a contact, Bob
- Place outgoing call to Bob
- Respond to prompt for camera permission
- Deny prompt for microphone permission

**Actual result:** Call continues, Bob can not hear Alice
**Expected result:** Call does not go through because microphone permission was disabled. Alert/prompt to enable microphone permission.

### Device info

**Device**: iPhone 5C
**iOS version**: 10.2.1
**Signal version:** 2.8.3

### Link to debug log

https://gist.github.com/95c2d5f7041b2ef6fc97ce559da7045e

Different user: https://gist.github.com/anonymous/58edae1b0a4a58eb9c5dbf45b27a0982

**Comment by michaelkirk** [comment]
In https://github.com/WhisperSystems/Signal-iOS/pull/1892
