### ISSUE TITLE
Incorrect Timestamp Labels after Extended Backgrounding

### ISSUE THREAD

**Issue by aquishix** [WhisperSystems/Signal-iOS#1888]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Timestamp labels are not updating correctly upon putting the app back in the foreground after an extended period.

### Steps to reproduce
- Have a text message conversation with someone.
- Leave the app on the conversation window.
- Press the home button to put the app into the background.
- Turn the screen off.
- Wait until the next day.
- Go back to the app. (I did it by tapping the app's shortcut on the home screen.)

**Actual result:** It will display an incorrect day label on existing messages.  E.g., "Today 1:20 PM"
**Expected result:** It should update the day label upon waking.  E.g., "Yesterday 1:20PM"

### Screenshots
Kinda hard to take a screenshot of one's phone, but I could do it with my old phone tomorrow and update this github issue.

### Device info
**Device**: iPhone 6S Plus
**iOS version**: 10.2.1
**Signal version:** 2.8.3

**Comment by michaelkirk** [comment]
Fixed by https://github.com/WhisperSystems/Signal-iOS/pull/1962
