### ISSUE TITLE
Add calltime label

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#19]
People are used to have call-time label. Historically, I believe they made sense from a billing perspective too but they are probably a "nice to have"

**Comment by abolishme** [comment]
Does this mean the length of a call should be reflected in the conversation history note, which now just says `You called Moxie Marlinspike (Today, 3:12 PM)`, or that a users entire call log with all contacts should be listed somewhere?

**Comment by FredericJacobs** [comment]
The goal was to display the amount of time the current call was taking, and eventually add the total call time to the call entry in the conversation view.

**Comment by vv01f** [comment]
maybe like `(Today, 3:12 PM +0:24:17)`
