### ISSUE TITLE
Visual representation of class structures?

### ISSUE THREAD

**Issue by gavia** [WhisperSystems/Signal-iOS#190]
There are a lot of classes to understand. Has anyone created a visual representation of the class structures and how they interact with each other?

**Comment by FredericJacobs** [comment]
Here's a visual representation of the class structure. Not planning to maintain a representation, but you can generate your own with `objc_dep`.
http://cl.ly/ZLmA/download/Pods.png

**Comment by Strilanc** [comment]
Generally these representations have to be structured in some way for them to make sense. For example, making a nested graph with nodes for each folder (and then going into the code and cutting cycles).

Not sure it would be worth the effort investment.

**Comment by FredericJacobs** [comment]
Classes are being restructured at a steady pace these days. Also trying to refactor to reduce coupling as much as possible. Not planning to maintain such a representation, for now.
