### ISSUE TITLE
Community locked out of participating in #346 (mute some group convos)

### ISSUE THREAD

**Issue by jm3** [WhisperSystems/Signal-iOS#1900]
Quick minor maintenance issue: #346 is a key UX issue (available in Twitter, Telegram, FB Messenger, Messages, etc.), but was locked by mods due to some community contributors "bumping" the thread.

Moderator has issued a warning against bumping threads, so I think the message is clear. And enough time has passed that GitHub Issues how feature "reactmoji", so community members can vote on issues **without** bumping threads. Since we're living in the future, I think this key issue can be unlocked. As an avid Signal user fan, I'd love it if I and other community members can at a MINIMUM register our support for the feature. Thanks in advance :)

**Comment by hask** [comment]
+1

**Comment by klyonrad** [comment]
> Please don't bump issues.

Please do not abandon **essential** feature requests without any explanation what's blocking the implementation or how other people might help.

**Comment by TreatyOfRome** [comment]
This issue, including #346 (locked) has been implemented. Issues can be closed. :tada:
