### ISSUE TITLE
Bluetooth headset/car not working if you initiate the call

### ISSUE THREAD

**Issue by Deadlocklucifer** [WhisperSystems/Signal-iOS#1902]
Since the call kit integration, I'm only able to patch the call through the car if I'm receiving the call. 

Otherwise there is no way I can ascertain to connect headsets/cars.

**Comment by simpowich** [comment]
I have the same problem! Latest signal and ios, using the bluetooth handsfree in an VW passat -14.

**Comment by alimakki** [comment]
Similar issue with bluetooth headsets:

When initiating or receiving calls, audio isn't routed correctly through the headset.

**Comment by TreatyOfRome** [comment]
A lot of bluetooth issues have been addressed in Signal 2.14.0. Issue could be closed?

**Comment by michaelkirk** [comment]
Should be working as of 2.14.0.
