### ISSUE TITLE
 Love call privacy

### ISSUE THREAD

**Issue by Deadlocklucifer** [WhisperSystems/Signal-iOS#1926]
There is a pervasive issue of parties putting a call on speaker or Bluetooth to record both ends of the conversation. 

Can we have a toggle switch in the call screen to disable speaker phones, Bluetooth connections and the like. Forcing a conversation to stay on the ear piece alone?

**Comment by Deadlocklucifer** [comment]
Subject is supposed to be voice call privacy

**Comment by michaelkirk** [comment]
Thanks for the idea, but I don't think we're going to do this.

We would be cluttering up the call screen for a feature that very few people would want to use.

Most people want to use bluetooth/speakerphone for legitimate reasons. Allowing Alice to break Bob's UX at the flip of a switch is going to be a *really* tough sell.

And regardless of the above concerns, all we'd be doing is making it *ever-so-slightly* more inconvenient to record a conversation. It's not actually harder to record a conversation from the earpiece.
