### ISSUE TITLE
Unable to play back audio messages

### ISSUE THREAD

**Issue by Gulci** [WhisperSystems/Signal-iOS#1967]
The ability to play back audio messages was broken from version 2.9.2 to 2.10.0. Tapping only reveals the share dialog. 

 Old version:
![img_0844](https://cloud.githubusercontent.com/assets/8071536/24884990/fa6025a0-1e00-11e7-9abc-ca9a24c226c6.PNG)

New version:
![img_0843](https://cloud.githubusercontent.com/assets/8071536/24885001/061d2fd2-1e01-11e7-8e30-4acf4ac8bfb9.PNG)

**Comment by anatoli26** [comment]
Same here, iPhone 6S with iOS 10.3.1, Signal 2.10.

**Comment by michaelkirk** [comment]
Thanks for reporting, this will be fixed in the 2.10.1 release.
