### ISSUE TITLE
Signal with TextSecure beta

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#198]
Is there a place where I can have my friends register to beta test the integration of TS into Signal? Is anything being done via testflight or something?

**Comment by sammcj** [comment]
Any update on getting hold of the beta?

**Comment by corbett** [comment]
we did a highly limited beta for logistical reasons. future betas (and of
course the launch) may in general be wider

On Mon, Feb 2, 2015 at 10:26 PM, Sam <notifications@github.com> wrote:

> Any update on getting hold of the beta?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/198#issuecomment-72600568>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
