### ISSUE TITLE
Reinstalling Signal makes you lose access to all your groups

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#1988]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
There are many scenarios where you might need to remove signal temporarily (i.e. when crossing an interesting border). This comes with a great cost for heavy Signal users and that means they're going to lose access to all of the groups they're part of. 

### Steps to reproduce
- Join a bunch of groups
- Reinstall Signal
- *Sad panda*

**Actual result:** You lose access to all groups you are part of.

**Expected result:** You should be automatically re-joining groups with the new safety numbers (of course with a warning to other members that your Safety Numbers has changed.

**Comment by michaelkirk** [comment]
With the upcoming 2.12 release, you will be automatically rejoined to an existing group upon receiving a message from someone in that group via the "group info request".

It's contingent on other parties in the group being online (eventually) and being on a client which supports group info requests (which is any Android client, and any iOS client running 2.12.*) or later.
