### ISSUE TITLE
Crash when trying to delete call log in coversation

### ISSUE THREAD

**Issue by iadmir** [WhisperSystems/Signal-iOS#2015]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
App crash when trying to delete call log in conversation window

### Steps to reproduce
- Open Signal app
- Open conversation with call logs
- Long tap on call record

**Actual result:** Crash immediately
**Expected result:** Extend menu with option to delete call log

### Device info

**Device**: iPhone 5S
**iOS version**: 10.3.1
**Signal version:** 2.11.0

**Comment by charlesmchen** [comment]
Thank you @iadmir This has been fixed and will ship with the forthcoming release.
