### ISSUE TITLE
no text can be send when image sending is progress

### ISSUE THREAD

**Issue by arekm** [WhisperSystems/Signal-iOS#2034]
- [ x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

When I send image from signal on quite slow or bad connection sending it can takes like 10-20 minutes for single photo. The problem is that while sending is in progress I can't send any text. Have to wait for image to be send.

See no reason for such block because sending text is very fast. Sending photo can be (and is here) very slow.

### Steps to reproduce
- get very slow connection
- send image from one device to another
- see that while image is being send no text can be send

### Device info
**Device**: iphone 6S
**iOS version**: 10.3.1
**Signal version:** 2.10.1

**Comment by michaelkirk** [comment]
This is intentional. It's definitely a tradeoff, but we've concluded that it's more important to enforce the order of the conversation than it is to allow people to fire off a quick text without waiting for upload.

**Comment by arekm** [comment]
Ok, so the only solution is to debug that very slow images upload (10-20 minutes). Stalling conversation for that long is not good.
