### ISSUE TITLE
speaker mode switches off when call starts

### ISSUE THREAD

**Issue by richlv** [WhisperSystems/Signal-iOS#2039]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
if enabling the speaker mode while dialling, it switches to non-speaker mode when call starts, but the speaker button does not indicate this change

### Steps to reproduce
- call somebody
- tap the speaker button while dialling in progress
- wait for the call to be established

**Actual result:** speaker mode is disabled when the call starts, but the button does not indicate that
**Expected result:** speaker mode does not get disabled

### Device info
**Device**: iPhone 6
**iOS version**: 9.3.5
**Signal version:** 2.10.1

### Link to debug log

https://gist.github.com/227587e4b8483ad0217d8752cf58827b

**Comment by michaelkirk** [comment]
Thanks @richlv - fixed in 2.11.3

**Comment by richlv** [comment]
yay, thank you a lot for the fix :)
