### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by sontdhust** [WhisperSystems/Signal-iOS#2050]
Provide Swift code as much as possible, useful for people who are not familiar with Objective-C

**Comment by sontdhust** [comment]
I'm currently working on it and pull request will be available soon.

**Comment by FeuRenard** [comment]
You may want to have a look at this forum thread:
https://whispersystems.discoursehosting.net/t/adopt-swift-programming-language-for-ios-version-of-signal/679

**Comment by sontdhust** [comment]
@FeuRenard got it! But can I keep this issue for reference purpose only, buddy?

**Comment by FeuRenard** [comment]
This isn't my repository, so I have no say in it.

**Comment by michaelkirk** [comment]
We prefer swift for most new features, but we aren't accepting PR's that just rewrite working objc code to swift, to avoid the risk of something getting lost in translation.
