### ISSUE TITLE
Feature request: confirm the selected photo to be send

### ISSUE THREAD

**Issue by basnijholt** [WhisperSystems/Signal-iOS#2052]
Right now clicking on a thumbnail when sending photos results in it being sent immediately without confirming whether you selected the right photo.

I suggest that one should first see the full-size photo and confirm it.

Since I often have a series of similar photos, this frequently leads me to send a photo that I didn't intend to send.

**Comment by charlesmchen** [comment]
@basnijholt this has been addressed and will ship with our next release.

**Comment by basnijholt** [comment]
That is great, thanks 👍
