### ISSUE TITLE
Slow start up after recent commits, since 2nd May

### ISSUE THREAD

**Issue by chanying2** [WhisperSystems/Signal-iOS#2076]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Since a few days, I think since a commit on 2nd May 2017, something in the startup sequence of the application has changed and loading of the contacts has dramatically slowed down. It takes about 17 seconds to load the contacts, about 2000 contacts. 

### Steps to reproduce
- just start the application with a build after 2nd May, event todays latest on master, with contacts more than 1000. 

**Actual result:** takes 17 seconds for app to settle down and to let you do something. it is hanging until then.
**Expected result:** it should take 1 or 2 seconds, like it was, a few days ago.

### Device info

**Device**: iPhone7
**iOS version**: 10.3.1
**Signal version:** latest on master since 2nd May, even todays head.

**Comment by charlesmchen** [comment]
Thanks @chanying2 . This has been fixed:

* https://github.com/WhisperSystems/SignalServiceKit/pull/203
* https://github.com/WhisperSystems/Signal-iOS/pull/2074
