### ISSUE TITLE
Test multiple deviceIds messaging.

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#211]

**Comment by lordmortis** [comment]
Is this around adding new devices to the account on iOS? Is the flow for this still changing due to the browser extension or will the workflow from there work? (Was thinking of trying to do this?)

**Comment by mailinglists35** [comment]
can this happen sometime? i don't feel like i'm truly safe using Signal by activating the account with a phone number...

**Comment by alexander-sibert** [comment]
I also don't want identify by phone number. Do it like Threema with generated with random ID. I think phone number and E-Mail address should be "optional".
