### ISSUE TITLE
Debug log is filled with parsing issues 

### ISSUE THREAD

**Issue by m3dialoud** [WhisperSystems/Signal-iOS#2133]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I have been noticing a lot more crashing and kernel issues after video calling was enabled. Also, now that you can send arbitrary files via Signal, this is also a concern to the security of the app. I've noticed an immense amount of issues since then as well. I've noticed messages do not disappear anymore like they should. For some reason if I change mine to 5 seconds, the other person says they changed theirs to 30 right away. I ask to make sure they're not doing it and they aren't.. My most recent debug log shows a lot of parsing issues. Please look at the debug log as it shows a scary amount of issues. 

### Steps to reproduce
- Normal use eventually triggers these crashes. 
- I tapped the back button twice on accident and that triggered a crash. 

### Device info

**Device**: iPhone 7 Plus
**iOS version**: 10.3.2
**Signal version:** 2.11.4 

### Link to debug log

https://gist.github.com/e09b3bc98e9f4deae7c367aaa276146c

**Comment by michaelkirk** [comment]
The parsing issues in your log just means you have contacts in your address book with malformed phone numbers.

Can you clarify what issues you are having with arbitrary files support? If there is not a bug to report, but you want to have a discussion about the security implications, that seems better suited for the community forum: https://whispersystems.discoursehosting.net/

Regarding the disappearing messages issue, can you clarify step by step, what happened and what you expected to happen? It sounds like

Initially you and your friend had disappearing messages enabled for 30 seconds.
You selected to change it to 5 seconds
Your friend took no action, but saw a notification that disappearing messages was changed to 30 seconds.

Is that correct? If not could you clarify?

Also, do you or your friend have linked desktop devices? In your clarification of the steps, can you include on which device (iOS/android/desktop) each action was taken?

And if you see this again, debug logs from as many affected parties/devices as possible would be helpful. As well as the time that the behavior in questions occurred.

Also, in the future, please open a separate github issue for each report you want to make, it confuses the discussion to be talking about three different things in one thread.

**Comment by michaelkirk** [comment]
Please re-open if you can add the requested details.
