### ISSUE TITLE
promise kit is using swift 3.0.2

### ISSUE THREAD

**Issue by nikhilwhizdhavale** [WhisperSystems/Signal-iOS#2151]
Which xcode version is ideal for this code to run. I get the following error while compiling
/Users/whizphone/Documents/WhisperSystems/Signal-iOS/Signal/src/Jobs/MessageFetcherJob.swift:6:8: Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Users/whizphone/Documents/WhisperSystems/Signal-iOS/Carthage/Build/iOS/PromiseKit.framework/Modules/PromiseKit.swiftmodule/x86_64.swiftmodule

**Comment by charlesmchen** [comment]
@nikhilwhizdhavale 

I believe this can be resolved by doing:
```
git submodule update --init
carthage build --platform iOS
```
or simply:
```
make dependencies
```

**Comment by nikhilwhizdhavale** [comment]
No this was solved by checking xcodebuild -version. I check the version used for command line tools.

**Comment by nikhilwhizdhavale** [comment]
No this was solved by checking xcodebuild -version. I check the version used for command line tools.
