### ISSUE TITLE
Flicker at inbox view on (cold launch) start

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#2168]
### Bug description
If Signal starts (cold start) the inbox view flicker 3 or more times.

1. The inbox is shown with phone numbers (1s flicker)
2. The phone numbers are replaced with the name (2nd flicker)
3. The contact pictures are (re-)painted (3rd flicker)

### Steps to reproduce
- view your open apps
- swipe up Signal to close
- start Signal

**Actual result:** flicker at start
**Expected result:** inbox view should resolve all phone numbers and pictures before showing the view itself

### Device info

**Device**: iPhone 6
**iOS version**: 10.3.2
**Signal version:** 2.12.2

**Comment by michaelkirk** [comment]
Fixed by https://github.com/WhisperSystems/Signal-iOS/pull/2386 (will be released with 2.16.0)
