### ISSUE TITLE
Integrate Crash Reporting

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#217]
I think [`PLCrashReporter`](https://www.plcrashreporter.org/) is the most appropriate.

**Comment by FredericJacobs** [comment]
So annoying they only distribute a binary version of the pod which is unacceptable in our setting.

**Comment by FredericJacobs** [comment]
Looks like we'll have to write a Podspec to build PLCrashReporter from source. Not that hard I think since we made the OpenSSL one :see_no_evil:

**Comment by FredericJacobs** [comment]
Thank you @alloy <3 https://gist.github.com/alloy/8471404

**Comment by alloy** [comment]
@FredericJacobs I know I’ve built it from source once, but this doesn’t seem to be that podspec, this podspec still uses the binary build :-/ I.e. it uses `vendored_framework`.

**Comment by alloy** [comment]
@FredericJacobs I can’t easily find a gist or whatever with that earlier example, so I don’t remember how involved it was. Possibly building the lib with `xcodebuild` as you suggested is the best solution.

**Comment by FredericJacobs** [comment]
@alloy: Any chance you can still find it? I found this but it seems incomplete.
https://gist.github.com/dlo/7995850

**Comment by FredericJacobs** [comment]
Looks like Apple is going to take care of most of this. We probably don't want to have another logging system for crashes.
http://9to5mac.com/2015/02/23/xcode-crash-log-reporter/
