### ISSUE TITLE
call not dropped but one party can't hear other

### ISSUE THREAD

**Issue by corbett** [WhisperSystems/Signal-iOS#22]
"I used Signal on a call yesterday with an Android user, worked great for about 5 minutes, very low latency. Then he couldn't hear me any more, though I heard him. "

regarding the person who could not be heard whether they could have accidentally pushed the mute button
"Guess I can't rule it out but I was using wired earbud/mic setup so unlikely. "

**Comment by mmkassem** [comment]
This happens to me, I am using Signal on iOS and the other side is using RedPhone. They can only hear me for the first few seconds but I can keep hearing them regardless of who initiated the call.

**Comment by mmkassem** [comment]
I am facing this problem with two RedPhone users and always producible (they can only hear me for the first few seconds and then they cannot hear anything but I continue to hear them).

**Comment by GenomeAnalysts** [comment]
I'm seeing a problem that I think matches this issue. Text messaging works as expected. But regardless of whether A calls B in Signal or B calls A, A can hear B talking, but B cannot hear A talking. Using Android version 3.11.1.

**Comment by riyapenn** [comment]
@GenomeAnalysts Make sure you have checked microphone permissions and firewall restrictions, see: http://support.whispersystems.org/hc/en-us/articles/216479567-Why-does-my-call-never-ring-Why-do-I-only-hear-the-sonar-sound-Why-can-t-I-hear-on-the-call-.

**Comment by TreatyOfRome** [comment]
Could be closed due to implementation of WebRTC calling?

**Comment by michaelkirk** [comment]
Thanks @TreatyOfRome 

Closing since we've replaced our calling system. If you continue to have the issue, please reopen, including a debug log (from both parties if possible) right after the incident occurs.
