### ISSUE TITLE
Signal on iOS makes phone very hot and drains the battery quickly

### ISSUE THREAD

**Issue by mightybyte** [WhisperSystems/Signal-iOS#2243]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When I have the Signal app open, the right side of my phone gets very hot and the battery drains very quickly.  I checked the battery usage and it says that Signal has used 52% with the description "Background Activity"

### Steps to reproduce
- Open Signal
- From the inbox, tap on a non-group conversation
- Tap the contact's name at the top of the screen
- Tap "Verify Safety Number"
- Tap the camera icon at the bottom to scan a code
- Tap the "X" to close the scan code screen.  Do this immediately...don't leave the scan code screen open very long.
- Tap "Back" at the top left
- Tap "<" at the top left
- Now you're back to the inbox
- Don't do anything else...wait approximately 1 minute move the conversation list once or twice to make sure the phone doesn't go to sleep.

**Actual result:** Within only a minute or so the phone gets noticeably hot on the right edge.  If you leave it open longer, the phone gets very hot.
**Expected result:** Just having Signal open should not kill my battery and make my phone very hot.

After you do this sequence of steps once, you don't have to do it again.  As long as you don't kill the whole Signal app, every time you open Signal it will drain your battery and make your phone hot very quickly.  On my phone the heat seems to be radiating from the upper right corner of the phone near the camera.  It radiates most noticeably down the right side of the phone.

### Device info

**Device**: iPhone 6s
**iOS version**: 10.1
**Signal version:** 2.12.2

### Link to debug log
https://gist.github.com/anonymous/1b263e26acb3b705129958ead0073595

New debug log

https://gist.github.com/anonymous/c76c8da2c69e71e1da5251499cc4f6ba

**Comment by michaelkirk** [comment]
Thanks for the report.

That debug log looks conspicuously empty. Do you keep your phone unlocked and the app running in the foreground for long periods of time (like hours or multiple days or something)?

Otherwise, would you mind killing Signal (double tap home, swipe up on Signal), relaunching, seeing if it gets hot, and submitting another debug log? Hopefully we can get more complete information.

**Comment by mightybyte** [comment]
I suspect the debug log is empty because I wasn't doing anything in the app.  Simply having it open (and the phone not locked) caused the problem.  Long periods of time is not the issue.  I had it open for only a few minutes...a totally plausible amount of time for a chat app to be open.  And in that time it totally demolished my battery life.

I tried killing signal and that did seem to stop the problem.  After killing it and reopening, my phone did not get hot as I described above.  But I did some more experimentation and I think I figured out how to reliably cause it.  I remembered that I had verified a security code around the time I started noticing it made my phone hot.  Opening the "Verify Safety Number" screen, and then turning the camera on seems to reliably cause the problem.  After you've done this once, if you don't kill the app, the app seems to drain your battery any time it is open even if you don't go to the safety number verification screen again.  Perhaps you're not killing the QR code detection thread?

I will update the issue description with these new steps to reproduce.

**Comment by ksylvan** [comment]
Reproduced this on an iPhone 7 Plus, running iOS 10.3.3. https://gist.github.com/23bb1e363d176003d3b0ffd6f092bb06

**Comment by kambiz-aghaiepour** [comment]
Same here with iPhone 6s, running iOS 10.3.3.
https://gist.github.com/anonymous/1ca7221e4b61ed1987c4504f0181f8fd

**Comment by kambiz-aghaiepour** [comment]
We need the "Bro" app so for every percentage of battery life that's drained from my battery with the signal app in the foreground on my iPhone you get a "Bro" sent to you.

**Comment by michaelkirk** [comment]
Seems like the common thread is that you've all used the fingerprint scanner - that's a good hint. Thanks @mightybyte.

**Comment by kambiz-aghaiepour** [comment]
I got into the habit of swiping the app away in the hopes that it would not drain the battery.  However it seems to be a problem regardless.  I have a battery case (official apple case) on my iphone 6s.  But the phone and the case were at 100% batter in the morning.  I went for a bicycle ride using strava (on the iWatch) for 45 minutes and when I got back the battery case was fully drained.

For the time being I've uninstalled signal as much as I want to use it.  I would be happy to reinstall and run further testing if you identify a possible fix and can push an updated package.

**Comment by michaelkirk** [comment]
@kambiz-aghaiepour have you noticed any pattern on when the battery drains? e.g. after scanning safety numbers? Or can you reproduce this by simply launching the app and letting it idle?

**Comment by mightybyte** [comment]
@kambiz-aghaiepour Killing Signal by double clicking the home button and swiping Signal up pretty definitively fixes the problem for me.  You might want to do some deeper investigation.  You may have other apps that are killing your battery.

**Comment by ksylvan** [comment]
I also see faster battery drain with Signal installed. On my iPhone 7plus, I reproduced the problem with scanning the safety numbers detailed above; when that happens, the battery seems to be dropping 1% charge every 15 seconds. I got out of that mode by killing and restarting the app. 

Then I charged my phone to 100% and just went about my day responding to occasional Signal messages. In 24 hours, Signal is about 24% of my battery use.

**Comment by ksylvan** [comment]
![img_1584](https://user-images.githubusercontent.com/1226059/27485799-0fd86e8a-57e3-11e7-87aa-7f2e07b18de9.PNG)

**Comment by mightybyte** [comment]
@ksylvan Interesting.  In the last 24 hours I'm showing 6% battery use for Signal with 3 min on screen and 4 min background.  This doesn't seem unreasonable to me, but I haven't done a fingerprint scan in that time.

**Comment by kambiz-aghaiepour** [comment]
I had done a swipe away (and even a reboot) when I went for a ride.  I may have simply received group messages during the time I was out (within 1 hour the case battery was fully drained).
If there is anything specific you'd like me to try I'm happy to do it.  (I will have to reinstall if you have a suggestion to try).

**Comment by kambiz-aghaiepour** [comment]
Also when you say you haven't done a fingerprint scan, are you saying you use the number keylock?  I use the fingerprint scanner constantly in that I have the unlock tied to fingerprint scanner.

**Comment by michaelkirk** [comment]
> Then I charged my phone to 100% and just went about my day responding to occasional Signal messages. In 24 hours, Signal is about 24% of my battery use.

Thanks for the screenshot @ksylvan. Your screenshot shows Signal was in the foreground for 2.7 hours in the last 24hrs. Does that seem accurate? Is that what you mean by "responding to occasional Signal message"?

**Comment by ksylvan** [comment]
That number seems high. I get messages and I respond and there's a few back and forth exchanges then a lull.

**Comment by michaelkirk** [comment]
> Also when you say you haven't done a fingerprint scan, are you saying you use the number keylock? I use the fingerprint scanner constantly in that I have the unlock tied to fingerprint scanner.

Sorry, by "fingerprint scan" I meant the "verifying safety number" screen, where you scan the other persons QR code to verify privacy.

Though I did some profiling with the QR code scanning screen, and verified it's reasonable. There is a spike while your camera is capturing video, which is unavoidable, but then it goes down when you leave that screen.

<img width="1219" alt="screen shot 2017-06-23 at 9 39 41 am" src="https://user-images.githubusercontent.com/217057/27486306-21643556-57fe-11e7-92d9-c7e1b014073e.png">

(I repeated the exercise, hence the two "energy usage" bumps.)


> I had done a swipe away (and even a reboot) when I went for a ride. I may have simply received group messages during the time I was out (within 1 hour the case battery was fully drained).
If there is anything specific you'd like me to try I'm happy to do it. (I will have to reinstall if you have a suggestion to try).

Would you be interested in seeing if you have better luck with the latest beta? We have made a number of general optimizations for the upcoming release which may alleviate this, e.g. in the case you are using the app for multiple hours in a day, but we haven't (yet) found a smoking gun that would account for a bunch of battery drain when you're not using the app. To sign up for the beta email your request to support@whispersystems.org

We're definitely interested in getting any serious battery issues addressed immediately as well as generally improving it over the long term. If you find Signal is using an inordinate amount of battery in the future, could you submit a debug log to this thread as soon as you notice (and then I'd recommend swipe-killing and restarting Signal in case you were in some degraded state).

**Comment by ksylvan** [comment]
Thanks. Sent a message to try the beta.

**Comment by kambiz-aghaiepour** [comment]
I will do the same.

**Comment by ksylvan** [comment]
Much better battery usage with the latest beta. Thank you.

**Comment by ksylvan** [comment]
Any timeline on when the current beta will be promoted to public release? I have friends I want to install Signal but I can't recommend the App currently in the App Store.

**Comment by ksylvan** [comment]
Settings -> Battery > Last 24 hours is now showing:

Signal now showing Signal using 5% (21 min on screen - 7 min background).

And I'm no longer seeing the quick battery drain.

**Comment by mightybyte** [comment]
The beta solves this problem for me as well.

**Comment by ksylvan** [comment]
Seems like this is fixed, and the code has even pushed out into the Prod version?

**Comment by mailinglists35** [comment]
@michaelkirk 
>Though I did some profiling

whoa, I want to do that profiling too. how can I do it on my device? I am frequently expriencing keyboard lagging when typing in Signal. do I need beta or something? I am jailbroken so I can run additional debugging tools if you have them
