### ISSUE TITLE
PromiseKit Framework Issue

### ISSUE THREAD

**Issue by developweb10** [WhisperSystems/Signal-iOS#2272]
I am getting PromiseKit framework issue in app. this framework missing when i clone code. Also i tried to solve this issue to add pod 'PromiseKit' but getting issue & not able to install this swift framework in objective-c

**Comment by michaelkirk** [comment]
Hi @developweb10. We don't use github as a support forum.

Please take a look at https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md

And if that doesn't answer your questions, try the community forum: https://whispersystems.discoursehosting.net/
