### ISSUE TITLE
Can't see sent time with Unread Messages bar

### ISSUE THREAD

**Issue by jschneier** [WhisperSystems/Signal-iOS#2274]
- [x] I have searched open and closed issues for duplicates

As the title says, the UNREAD MESSAGES covers up what time the message was sent at which is quite useful to know.

iPhone SE
Signal 2.13.0.16
iOS 10.3.2

**Comment by michaelkirk** [comment]
Fixed in https://github.com/WhisperSystems/Signal-iOS/pull/2280

Thanks!
