### ISSUE TITLE
Badges not populating

### ISSUE THREAD

**Issue by jschneier** [WhisperSystems/Signal-iOS#2275]
- [x] I have searched open and closed issues for duplicates

I upgraded to the newest version and the badge doesn't populate which makes it very difficult to know when I have new messages.

iPhone SE
Signal 2.13.0.16
iOS 10.3.2

**Comment by michaelkirk** [comment]
Thanks for the report.

Fixed in https://github.com/WhisperSystems/Signal-iOS/pull/2277

Will be released in 2.13.1 as soon as App Store approves.
