### ISSUE TITLE
Install and run signal-iOS with own server

### ISSUE THREAD

**Issue by nwios** [WhisperSystems/Signal-iOS#2282]
- [√] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I've tried to running signal-iOS with own server details, we have already configured the server with same signal server requirements and I was add the url at TSConstants class in textSecureServerURL but when I run the application then I putted the phone number then when I clicked Activate this devices I had this issue in Xcode console: 

> 2017-07-02 06:47:12:814 Signal[10060:373631] [TSNetworkManager] Making request: <TSRequestVerificationCodeRequest: 0x608000220d40> { URL: v1/accounts/sms/code/+9665XXXXXXXXX?client=ios }
> 2017-07-02 06:47:12:814 Signal[10060:373631] [OWSSignalService] using default HTTPSessionManager
> 2017-07-02 06:47:13:441 Signal[10060:373631] The network request failed because of a connectivity error.
> 2017-07-02 06:47:13:441 Signal[10060:373631] [TSAccountManager] Failed to request verification code request with error:Error Domain=org.whispersystems.signal.networkManager Code=0 "Signal was unable to connect to the internet. Please try from another WiFi network or use mobile data." UserInfo={NSLocalizedDescription=Signal was unable to connect to the internet. Please try from another WiFi network or use mobile data., NSLocalizedRecoverySuggestion=Please check you're online and try again.}

### Steps to reproduce
- Change URL at textSecureServerURL in TSConstants class.
- Run App.
- Change the country to Saudi Arabia.
- Enter my number.
- Click Activate this device. 

![simulator screen shot jul 2 2017 6 48 07 am](https://user-images.githubusercontent.com/2043377/27767139-4b372cc8-5ef5-11e7-9e27-b03869668774.png)

**Actual result:** The app not work when I changed the url. 
**Expected result:** the app should be request from server to sending an OTP to my phone. 

### Device info

**Device**: iPhone
**iOS version**: 10.2
**Signal version:** 2.13.1

Please could you tell me How can I solve that?

**Comment by michaelkirk** [comment]
Sorry @nwios but we don't have time to personally support people trying to set up the Signal server.  You could see if someone on the forums can help: https://whispersystems.discoursehosting.net

**Comment by roberthopman** [comment]
@nwios did discover more information regarding this issue?

**Comment by Pibcrement** [comment]
@roberthopman @nwios any updates so far? Ran into the same problem.

**Comment by biplabbh** [comment]
Hello my friend, would you please guide me on the below case:

I want to customize the signal-ios app and server both at our end. So I went to your git hub site and I have found so many source related to iOS. 

I know that the client code can be taken from 

https://github.com/signalapp/Signal-iOS 

and we can build in xcode.

Other than this I have found many things like 
Signal-Server, Signal-Pods, gcm-sender-async, SignalMetadataKit, libsignal-service-java, SignalProtocolKit, SignalCoreKit, signal-webrtc-ios, signal-webrtc-ios-artifacts, Signal-Carthage, ContactDiscoveryService, WebSocket-Resources etc..and many more

So from the above which services do we need for making the customization in the server part at our end. (Only for IOS part, android not needed)


If you please help me it would be great!

**Comment by michaelkirk-signal** [comment]
We don't use Github for developer support. As mentioned above, use the community forums for that:

https://community.signalusers.org/
