### ISSUE TITLE
iTunes back up missing data

### ISSUE THREAD

**Issue by u90umbridge** [WhisperSystems/Signal-iOS#2290]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
A new phone and back up from iTunes but my convos are missing from this app. Restore is fine for other apps with ios 10.3.2.

### Steps to reproduce
- Back up old phone
- restore new phone

**Actual result:** no data from old phone on new phone
**Expected result:**  convos from old phone on the new phone

### Device info

**Device**: iPhone 7 **iOS version**: 10.3.2
**Signal version:** 2.13.10

**Comment by charlesmchen** [comment]
@u90umbridge This is by design to protect your data from being accessed via the backups.

**Comment by u90umbridge** [comment]
Back ups in itunes encrypted with a long password and computer hard drive is also encrypted with file vault 2. Firm ware password activeted. Why not allowed to back up to restore my data?

**Comment by u90umbridge** [comment]
Why you decide what I can not do with my data? :(

**Comment by NiklasBr** [comment]
This is a sad state off affairs when people who claim to be security conscious refuse to let us access our own data, the [*A* in the C-I-A triad ](https://en.wikipedia.org/wiki/Information_security#Availability)is sorely missing here. Though I know @FredericJacobs said he worked on this a while ago, don't know of any progress though.

Also, see #967.

**Comment by fiveangle** [comment]
Guess we need to find an alternative to Signal which doesn't throw the baby out with the bathwater.

What's the best alternative others know about today ?

**Comment by NiklasBr** [comment]
I would say [Telegram](https://telegram.org/), [Matrix](https://matrix.org/), or [Keybase](https://keybase.io/) are all pretty good alternatives here.

**Comment by zsalab** [comment]
I just lost all of my messages because of this silly thing. Why I can not decide on backing up my data with my iOS? This is nonsense, I will stop the donation and encourage all of my friends to do it (as I encouraged them to start using Signal and donate). This is just unacceptable!
