### ISSUE TITLE
Sending Voice Notes (record audio attachments)

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#230]
(description by @michaelkirk)

Voice notes are recorded audio attachments, sent asynchronously. You can see this feature in use in iMessage, WhatsApp, and Signal-Android (as of this week :wink:)

There is some definite design work to be done here, and there is a wide array of interfaces for recording voice notes on other messaging platforms.

Design details that must be addressed:

0. Entry point. How does the user access this feature? 
1. It must be cancelable
2. User must have indication of when they are recording. Often this is implemented as a "hold to record", releasing stops the recording process.
3. Ideally the audio would be reviewable before sending as well, but given that it's cancelable it's not *strictly* necessary for the first pass.

Once the audio is recorded, we should be able to send it using the existing:

```
- (void)sendMessageAttachment:(NSData *)attachmentData ofType:(NSString *)attachmentType
```

## Notes

There was an earlier attempt at this feature on Signal-iOS which was never released - your guess is as good as mine as to why.

## Performance

The current waveform library might be too heavy, using it is negotiable. Make sure a conversation with many long voice notes can still scroll smoothly.

Verify sane memory consumption while recording and sending. It's conceivable that the existing API (`sendMessageAttachment:(NSData *)...`), which is not stream based, will have to be replaced with something that is.

### Formats

- iOS should send m4a
- Android sends m4a
- Desktop will send mp3

**Comment by corbett** [comment]
changing this to core feature label as is in Android app functionality

**Comment by corbett** [comment]
updated with support for audio receiving

**Comment by corbett** [comment]
audio sending (via record) will be supported in 2.1

**Comment by joyceyan** [comment]
See PR #595 for a mockup I did for recording audio messages

**Comment by iliketurtlesbro** [comment]
May I recommend that you guys use the opus codec for audio messages?

**Comment by likyng** [comment]
Is this change incorporated into Signal already (as suggested in PR #694 )? The functionality does not yet show up for me yet.

**Comment by michaelkirk** [comment]
@likyng receiving/playing audio from another client is supported, but you cannot yet send audio.

**Comment by anatoli26** [comment]
Hi, could you please let us (the users) know what's the status of this feature? Any ETA? Thanks!

**Comment by AykutCevik** [comment]
Hi at all, any progress here? I searched for "voice messages" and found this thread, which is over 2 years old. Will this feature implemented? I got people to use Signal but this feature is missing on iOS unfortunately, so they are complaining about it to me :)

**Comment by michaelkirk** [comment]
This is an important feature, but there's a few things that have priority first.

Reminder to please not bump issues as it spams everyone subscribed to the repo. If you want to be informed about the status, subscribe to the issue and you'll be among the first to know.

**Comment by michaelkirk** [comment]
This will be in the next release (2.12)

See https://github.com/WhisperSystems/Signal-iOS/commit/6a4a08d3eee80d156269b07e51c9d0b3d0ce6320
