### ISSUE TITLE
The push alert isn't presented. 

### ISSUE THREAD

**Issue by nwios** [WhisperSystems/Signal-iOS#2312]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Since of apple released iOS 10 we have a big issue with UIUserNotificationSettings for presented push notifications alert and UIUserNotificationSettings has been deprecated, I'm tried to solve this issue manually by replacing UIUserNotificationSettings with UNUserNotificationCenter at pushManager classes but I couldn't to reach up the successfully way, did anyone having this problem before? or did anyone solve it? 
  
### Steps to reproduce
- Installing the app on 2 iPhone.
- Register with different numbers(A,B).
- I sent a message to (B) number from (A) number. 

**Actual result:** 
- The app is presented the messages only when has been opened. 

**Expected result:** 
- iPhone with (B) number can't presented alert for notifications from (A) number when the app did enter in background.

### Device info
**Device**: 6 | 6S
**iOS version**: 10.2 | 10.3.2
**Signal version:** 2.13.1

**Comment by michaelkirk** [comment]
@nwios - please clarify: Are you experiencing this behavior in an appstore build or did you build it from source yourself? 

You will not be able to receive push notifications in a developer build of Signal per Apple's code signing restrictions.

If you are having trouble receiving push notifications with versions of Signal installed via the app store or test flight, can you submit a debug log from the recipient?

**Comment by nwios** [comment]
@michaelkirk The behavior has happened when I build the project from the GitHub source, I have Integrated the signal with own server and everything working fine expect the receiving push notification alert to my iPhone. 

- Did you mean to solving the issue it should be linking the app with distribution certificates? 

But when I search about it and most of answers says, you should be using UNUserNotificationCenter instead of UIUserNotificationSettings with iOS 10 because the last one is deprecated. 

So let us try to build the app with distribution certificates at client and server side then I will get back to you if the issue still doesn't work or what I do to getting the issue down.

**Comment by michaelkirk** [comment]
Sorry @nwios, but we don't use Github as a support forum, so I'm going to close this issue. If you have more development questions, try asking on the community forum at:
https://whispersystems.discoursehosting.net/

But it sounds like you are hitting a basic Apple security mechanism for remote notifications. You will not be able to receive push notifications unless it's appropriately signed for **your** remote notifications, and the appropriate certificate is installed on your server.

You can read more here:
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1
