### ISSUE TITLE
how you add calls and messages from contacts adressbook ?

### ISSUE THREAD

**Issue by amineghabi** [WhisperSystems/Signal-iOS#2315]
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by michaelkirk** [comment]
Hi @amineghabi - we don't use github as a support forum. Try the community forum at https://whispersystems.discoursehosting.net/ or contacting support@whispersystems.org
