### ISSUE TITLE
Improved group management + group fingerprint UX

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#233]

**Comment by corbett** [comment]
can we discuss what improvements are meant by this issue ?

**Comment by FredericJacobs** [comment]
I can think of:
1) [ ] When adding participants to a group, "Add people" can be selected and crashes the app.
2) [ ] Tapping a group member in the participants list should open a private conversation with that member and I should be able to verify key from there.
3) [ ]  Group update messages are not working as intended. Messages regarding members leaving or joining are not displayed, only "Group updated"
4) [ ] Image should not be changed if I edit the group name or other attributes.

**Comment by corbett** [comment]
ok... great yes these make sense...

**Comment by FredericJacobs** [comment]
I can also think of 
[ ] If no image selected, don't upload the UI placeholder blue camera icon.

**Comment by corbett** [comment]
there were two issues with "Group update messages are not working as intended."
a) the code which did this (caveat: that the TSInfoMessage cells do not expanding to display the message being JSQDisplayedMessageCollectionViews) somehow disappeared from master probably in a bad merge. I have redone a PR for that: https://github.com/WhisperSystems/Signal-iOS/pull/300
b) re:caveat, to change the info messages we will have to go into ```JSQMessagesViewController.h```/```JSQDisplayedMessageCollectionViewCell.xib``` internals. I am loathe to do that but I see @dtsbourg has done before. an alternative would be not to rely on this message class. 
thoughts?
