### ISSUE TITLE
Project Does not Build

### ISSUE THREAD

**Issue by ajaybeniwal** [WhisperSystems/Signal-iOS#2339]
- [x] I have searched open and closed issues for duplicates

----------------------------------------
### Screenshots
![screen shot 2017-07-19 at 4 22 54 pm](https://user-images.githubusercontent.com/658004/28357583-8f84a9c6-6c9e-11e7-9ad0-b3ddc28c65b8.png)

**Comment by lidongyuan** [comment]
I have same problem, do you find the solution?

**Comment by michaelkirk** [comment]
Sorry folks, but we don't use GitHub as a support forum. Maybe you can try on the public forum?

https://whispersystems.discoursehosting.net/

But my first thought is to make sure you're on an up to date XCode.

**Comment by lidongyuan** [comment]
my Xcode is Version 8.2.1 (8C1002), Your mean which version is right?
