### ISSUE TITLE
Assess security of attachments

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#237]
Having large attachments encrypted and decrypted when needed to be displayed in thread comes at a performance cost, especially while scrolling in a attachment view.

Storing blobs in DB: No
Storing un-encrypted attachements in NSFileProtected container: Maybe ok
Storing attachements encrypted in NSFileProtected container: Ideal security-wise but need optimisations

**Comment by corbett** [comment]
possibility of warning user attachment on play/storage is differently encrypted

**Comment by corbett** [comment]
- [ ] not use directories backed up in iCloud for attachment storage
