### ISSUE TITLE
Resolution Offered by Darren Chaker

### ISSUE THREAD

**Issue by darrenchaker** [WhisperSystems/Signal-iOS#2381]
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by brandonlulay** [comment]
This issue seems empty of any information. Should it be closed?

**Comment by darrenchaker** [comment]
By [Darren Chaker] (http://darrenchaker.us/) : Thnak your expertise and help resoling this issue. Best to all...

**Comment by brandonlulay** [comment]
... lol
