### ISSUE TITLE
Inability to select and send multiple photos

### ISSUE THREAD

**Issue by iadmir** [WhisperSystems/Signal-iOS#2409]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
It isn't possible to select multiple images from the gallery and send them at once.
This inability takes a lot of time when you need to send more images.

### Steps to reproduce
- Open conversation
- Tap on paperclip icon and choose images from gallery

**Actual result:** Cannot select multiple photos
**Expected result:** Ability to select multiple photos

### Device info

**Device**: iPhone 5S
**iOS version**: 10.3.3
**Signal version:** 2.15.2.0 and earlier

**Comment by t-unix** [comment]
What happened to this issue?
Will a fix come in a future release?
