### ISSUE TITLE
Still receive push notifications and badges for a muted group

### ISSUE THREAD

**Issue by jschneier** [WhisperSystems/Signal-iOS#2418]
As the title says. Latest Signal, latest iOS, iPhone SE. I _just_ upgraded to the bugfix release which only just became available but don't see anything in the release notes about this issue. I haven't received a message in that group since then.

**Comment by michaelkirk** [comment]
Two questions...

1. Can you open Signal and go to Settings > Notifications and tell me how you've configured your background notifications? 

i.e. is it:

- Sender name & message, 
- Sender name only
- No name or message

2. Are the lockscreen notifications generic, e.g. do they just say "New Message" or do they have the actual content of the message?

**Comment by jschneier** [comment]
1. Sender name & message
2. Full content I believe (will need to have someone message the group to confirm)

**Comment by jschneier** [comment]
This looks much better since the most recent update. The only thing I see now is badges are updated anyway -- I only see this once I unlock the phone.

**Comment by michaelkirk** [comment]
> > Are the lockscreen notifications generic, e.g. do they just say "New Message" or do they have the actual content of the message?
>
> Full content I believe (will need to have someone message the group to confirm)

@jschneier have you been able to confirm if, when a notification for a muted group erroneously appears, that you're seeing the actual contents of the message, or just a generic "New Message" on your lockscreen?


And can you clarify, are you receiving a notification every time someone messages in that group, or just some of the time?

**Comment by jschneier** [comment]
This seems mostly fixed.
