### ISSUE TITLE
Sound/vibrate notifications for when application runs in foreground.

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#244]

**Comment by corbett** [comment]
you have an in progress label for this Fred? update on progress or info to hand over the issue to me?

**Comment by corbett** [comment]
@abolishme what about when in conversation if there is an incoming message in the inbox in another conversation adding a number to the signal icon in the nav bar?

**Comment by taoeffect** [comment]
Can't wait for this! :)

**Comment by taoeffect** [comment]
Oh wait, just noticed the title. For me vibrate doesn't work when the phone is asleep and in vibrate mode. Are you folks aware of that problem as well or should I open another issue?

**Comment by FredericJacobs** [comment]
Uh? You mean when you get the push? I don't think we have any control over that on iOS.

**Comment by taoeffect** [comment]
> Uh? You mean when you get the push? I don't think we have any control over that on iOS.

I just tested it right now. When I get a call, the phone vibrates once, and that's it. It's supposed to keep vibrating.

**Comment by FredericJacobs** [comment]
Oh, there is no way to do that. No third party app can do that I believe. There's just no API for that.

**Comment by taoeffect** [comment]
> Oh, there is no way to do that. No third party app can do that I believe. There's just no API for that.

Darn. Well, I just filed rdar://20008371 for this. Probably will be a dup. Hope they fix it!

**Comment by BBKrWw** [comment]
When you're in a conversation and a message is sent to a conversation in the background. There is no apparent notification. Same if you are in the inbox - the bolder text shows, but there is no sound/vibrate. I need to test a bit more, but that appears to be what is happening for me.
