### ISSUE TITLE
Messages timer begins when they haven't been seen?

### ISSUE THREAD

**Issue by 9mm** [WhisperSystems/Signal-iOS#2443]
I'm using the latest version of Signal, latest iOS.

When self-destructing messages is enabled, it says it waits until they're seen in the little description (on the settings page) but in practice, it seems to just start the timer immediately, which means the person won't see it if they're not right by their phone. What is the desired behavior here?

**Comment by michaelkirk** [comment]
If you send a disappearing message with a 10s duration, it will disappear *for you* 10s after you send it.

Your partners copy of the message will delete 10s after they see it.

**Comment by 9mm** [comment]
Nice thanks! I was mislead because I asked my friend if he saw my message and he said "no", but he never told me he didnt look in the first place XD
