### ISSUE TITLE
Multiple timer changes causes an indent

### ISSUE THREAD

**Issue by 9mm** [WhisperSystems/Signal-iOS#2444]
Latest Signal, latest iOS.

If you change the self-destruction timer, it creates an indented line of text like "XYZ changed the time to 5 minutes"

Then if you type, the messages go below.. then disappear.

The problem is, once you change the time again, it creates a new "xyz changed the..." line, except this time the text is indented again (doubly indented now instead of 1x).

None of the words line up anymore because its imporoperly indented. Each time the timer is changed, it gets further indented so now its like this:

    xyz changed the time to 5 minutes
      xyz changed the time to 30 minutes
      xyz changed the time to 5 minutes

**Comment by michaelkirk** [comment]
I can't reproduce this. Can you supply a screenshot?

**Comment by 9mm** [comment]
![alignment](https://user-images.githubusercontent.com/1386207/29487459-46511f3c-84c7-11e7-8a3a-6612d2397812.jpg)

**Comment by michaelkirk** [comment]
Switch it back to 1 minute and I think you'll see what you are experiencing is the consequence of centered text vs word wrap vs slightly different string lengths.

**Comment by 9mm** [comment]
You are correct, that "1 minute" line goes back to normal

**Comment by 9mm** [comment]
Dont you want them to all line up though? I noticed the issue is closed, its quite hard on the eyes, but I guess that's me liking clean UI's

**Comment by 9mm** [comment]
Or not even line up, but maybe smaller text, or left aligned, or something. I realize this isnt important, but it does look weird when you have 10 of them on the screen and theyre all hap hazard
