### ISSUE TITLE
Profiles?

### ISSUE THREAD

**Issue by Rogier777** [WhisperSystems/Signal-iOS#2446]
Sorry for using this issues section as a place to ask a question, but as my question is related to current development I thought it was the appropriate place... Looking at the code and specific pull requests, I saw that the implementation of user profiles is well on the way. I was wondering if this future feature will replicate that of other messengers like Whatsapp, where a person's profile name and picture could be changed and be watched by others, or that it will also be part of the registration flow where the name of a profile or an associated key or token can be handed over to people who want to add you on Signal, instead of giving your mobile phone number (highly requested feature by a lot of people). Thanks guys, keep up the good work @michaelkirk @charlesmchen

**Comment by michaelkirk** [comment]
Hey @Rogier777 we don't use Github as a discussion forum. Unless you are reporting a bug or requesting a feature, please use the forum at https://whispersystems.discoursehosting.net
