### ISSUE TITLE
Debug Log incomplete?

### ISSUE THREAD

**Issue by lorenzhs** [WhisperSystems/Signal-iOS#2472]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I just submitted a debug log but it doesn't contain any messages newer than yesterday night (24.08.2017 21:37). It was 10:53 on 25.08.2017 at the time of submission, so over 13 hours missing in the log. The log: https://gist.github.com/anonymous/1b3b9ba06ca3f2fd2ceaa118f0b35d3d

### Steps to reproduce
- unknown?
- submit debug log

**Actual result:** Log ends 13 hours and 16 minutes too early
**Expected result:** Log contains the most recent messages

### Device info

**Device**: iPhone 7
**iOS version**: 10.3.3
**Signal version:** 2.15.3.2

### Link to debug log

https://gist.github.com/anonymous/1b3b9ba06ca3f2fd2ceaa118f0b35d3d

**Comment by michaelkirk** [comment]
It indeed looks truncated. We include a sentinel line just before uploading to be sure we've captured everything.

If you try again is it still truncated? Did you see any sign of error while uploading?

**Comment by michaelkirk** [comment]
Not that I can blame you for missing it because I did too, but it seems like just the *display* of your log was just truncated (by gist.github.com). Scrolling to the top of that file shows: 

<img width="1246" alt="screen shot 2017-08-28 at 7 18 22 pm" src="https://user-images.githubusercontent.com/217057/29797571-da76c102-8c25-11e7-8084-c7ef243a7f25.png">


Clicking through, it looks complete:
```
2017/08/25 10:51:48:911  [SyncPushTokensJob] lastAppVersion: Optional("2.15.3"), currentAppVersion: Optional("2.15.3")
2017/08/25 10:51:48:911  [SyncPushTokensJob] Sending new tokens to account servers. pushToken: 7e0715fece0ada3afa32873301141797d2c9d9bfe0512add2b01e64d5c73a4cc, voipToken: d3b78b8e50419714bc87aa7c3cadbca7b4d4f0f40345b30e4146b2b0c52bad4e
2017/08/25 10:51:48:914  [TSNetworkManager] Making request: <TSRegisterForPushRequest: 0x170821e00> { URL: v1/accounts/apn }
2017/08/25 10:51:50:268  [AccountManager] Successfully updated text secure push tokens.
2017/08/25 10:51:50:268  [SyncPushTokensJob] Recording new push tokens. pushToken: 7e0715fece0ada3afa32873301141797d2c9d9bfe0512add2b01e64d5c73a4cc, voipToken: d3b78b8e50419714bc87aa7c3cadbca7b4d4f0f40345b30e4146b2b0c52bad4e
2017/08/25 10:51:52:355  [AdvancedSettingsTableViewController] Submitting debug logs
```

**Comment by lorenzhs** [comment]
GitHub does not show that bar for me, so looks like this is their bug :) The file is truncated even more when I click "raw". This is bonkers but not a Signal bug - thanks for checking it out!
![screenshot from 2017-08-29 10-21-24](https://user-images.githubusercontent.com/142205/29811474-da78aade-8ca3-11e7-973c-cb60dfe4bfb2.png)
