### ISSUE TITLE
Group avatar fixes

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#249]
- [ ] Avatars (TSAttachmentStreams) should have a YapDatabase relationship to the group they belong to, and be deleted when the avatar is changed or the group is deleted.
- [x] Group avatars should be properly compressed/resized.

**Comment by corbett** [comment]
@FredericJacobs  I am not as adept in the YapDatabase relationship regime yet to be confident I will do the right thing for part a) of this issue. if it seems easy to you and/or you can give me a TLDR of how this works that would be helpful. otherwise I will dive in soon.

**Comment by corbett** [comment]
working on a) of this issue now.

**Comment by FredericJacobs** [comment]
You can see the `TSInteraction` relationship to a thread.

I always write a test to see if it works like I expect it to: https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/test/textsecure/TSMessageStorageTests.m#L74

**Comment by corbett** [comment]
cool yes I see that, I was more basing my work on the TSAttachmentStream setup. I'm unclear the purpose of the structs... e.g.

extern const struct TSMessageRelationships {
    __unsafe_unretained NSString *threadUniqueId;
} TSMessageRelationships;

**Comment by FredericJacobs** [comment]
Uhm, it's not really necessary in this case. Don't bother doing a struct.

**Comment by corbett** [comment]
yes, that's what I concluded.

**Comment by FredericJacobs** [comment]
In this case: 
`TSAttachmentStream < ---- RELATIONSHIP --- > TSGroupThread`

**Comment by corbett** [comment]
I took a more of a glance at this today. actually the group avatar is
stored as a UIImage blob in the GroupModel. I wrote a test case and it is
correctly deleted. now whether we should actually store the group avatars
as tsattachmentstreams instead is another question.

On Sun, Jan 4, 2015 at 11:56 PM, Frederic Jacobs <notifications@github.com>
wrote:

> In this case:
> TSAttachmentStream < ---- RELATIONSHIP --- > TSGroupThread
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/249#issuecomment-68655709>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment]
that said with the current approach, the TSAttachmentStream isn't deleted
as soon as the UIImage makes it into the groupmodel associated with a
thread (to be consistent it should be)

but that said, the GroupModel should probably not store the UIImage. once
so refactored this issue will again become relevant.

-
On Mon, Jan 5, 2015 at 12:23 AM, Christine Corbett Moran <
christine.corbett@gmail.com> wrote:

> I took a more of a glance at this today. actually the group avatar is
> stored as a UIImage blob in the GroupModel. I wrote a test case and it is
> correctly deleted. now whether we should actually store the group avatars
> as tsattachmentstreams instead is another question.
>
> On Sun, Jan 4, 2015 at 11:56 PM, Frederic Jacobs <notifications@github.com
> > wrote:
>
>> In this case:
>> TSAttachmentStream < ---- RELATIONSHIP --- > TSGroupThread
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WhisperSystems/Signal-iOS/issues/249#issuecomment-68655709>
>> .
>>
>
>
>
> --
> Dr. Corbett Moran
> Rockets @ http://www.spacex.com
> Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
> Dev @ http://circleof6app.com
> Dev @ https://whispersystems.org
> www.christinecorbettmoran.com
>
>


-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
