### ISSUE TITLE
Add button to re-register push tokens in advanced settings

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#253]

**Comment by corbett** [comment]
this is not a setting on Android.

**Comment by FredericJacobs** [comment]
But in Android you can re-register just for push, without changing identity key. What iOS can't do.

**Comment by corbett** [comment]
I don't see where that is in the settings. general android settings or in
app settings?

On Wed, Jan 7, 2015 at 10:02 AM, Frederic Jacobs <notifications@github.com>
wrote:

> But in Android you can re-register just for push, without changing
> identity key. What iOS can't do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/253#issuecomment-69001109>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
First option: Push messages

**Comment by corbett** [comment]
yep I see it "you will need to re-register your phone number to use push
messages again in the future". so this re-registering of the phone number
does not change the identity key if it is as you say. we would have the
same button, only it would immediately go to the re-registering with a new
push token without changing anything else.

On Wed, Jan 7, 2015 at 10:20 AM, Frederic Jacobs <notifications@github.com>
wrote:

> First option: Push messages
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/253#issuecomment-69003024>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Yeah, Signal users with RedPhone had already this issue where they couldn't get any push. They reinstalled the app and that fixed it. But Signal with RedPhone was pretty ephemeral. You don't want to have users do that when it deletes their discussions, settings, keying material ...
It should be somewhere deep in the settings though.
