### ISSUE TITLE
Missing dummy.h

### ISSUE THREAD

**Issue by SalmanGhumsani** [WhisperSystems/Signal-iOS#2531]
Simply I am going to run this repository but I am getting the error missing dummy.m in all pod files even I installed all the missing pod.

![screen shot 2017-09-14 at 6 39 30 pm](https://user-images.githubusercontent.com/25687810/30431493-53b370fc-997c-11e7-8c1c-84bbc448d7e7.png)

**Comment by charlesmchen** [comment]
@SalmanGhumsani Please read https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md
