### ISSUE TITLE
WebRTC/RTCMacros.h file not found and failed to import Signal-Bridging-Header.h

### ISSUE THREAD

**Issue by timt** [WhisperSystems/Signal-iOS#2536]
carthage version: 025.0
xcodebuild -version: 8.3.3

### Bug description
I clone the latest from the repository, run carthage update (or pod install) and tried to build/run in xCode and see these errors.

.../Signal-iOS/Libraries/WebRTC/RTCAudioSession.h:14:9: error: 'WebRTC/RTCMacros.h' file not found
#import "WebRTC/RTCMacros.h"
^
:0: error: failed to import bridging header '.../Signal-iOS/Signal/src/Signal-Bridging-Header.h'

### Steps to reproduce
- git clone https://github.com/WhisperSystems/Signal-iOS.git
- cd Signal-iOS
- carthage update
- open Signal-iOS in xcode and build

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Following errors show:
.../Signal-iOS/Libraries/WebRTC/RTCAudioSession.h:14:9: error: 'WebRTC/RTCMacros.h' file not found
#import "WebRTC/RTCMacros.h"
^
:0: error: failed to import bridging header '.../Signal-iOS/Signal/src/Signal-Bridging-Header.h'

**Comment by big-r81** [comment]
Please read the [building](https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md)  instructions.

**Comment by timt** [comment]
Awesome thanks
