### ISSUE TITLE
Profile Avatar Upload Limited to "Moments"

### ISSUE THREAD

**Issue by acoffman** [WhisperSystems/Signal-iOS#2552]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When uploading an avatar image for the new profile feature, clicking "Photo Library" takes you straight to the "Moments" album in iOS. This album doesn't contain all photos and thus limits what you can upload. On the other hand, if you click "Photo Library" when attaching an image to a message, it has the expected effect of taking you to the album selection screen.

### Steps to reproduce
- Click settings -> Edit Profile -> Avatar -> Photo Library

**Actual result:** "Moments" is opened with no way to navigate to other albums
**Expected result:** "Photos" is opened as when attaching a photo to a message

### Device info

**Device**: iPhone 7
**iOS version**: 10.3.3
**Signal version:** 2.16.0.20

### Link to debug log
Happy to provide one if needed, but it doesn't seem required for this issue?

Thanks!

**Comment by michaelkirk** [comment]
Thanks for reporting - this will be fixed in 2.16.1.
