### ISSUE TITLE
Objections to bring TS changes to master?

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#259]
I started working on the textSecure branch because I was breaking original functionality and wanted the code on `master` to be working.

All the previous features of the app (v1.x) are now also working on the textSecure branch and it's usable. I think we can merge textSecure into master and then continue with the feature branches git workflow.

@corbett: Let me know your thoughts on this.

**Comment by corbett** [comment]
@fredericjacobs sure, this will make it clearer to new contributors too.

On Sat, Jan 3, 2015 at 1:09 PM, Frederic Jacobs <notifications@github.com>
wrote:

> I started working on the textSecure branch because I was breaking original
> functionality and wanted the code on master to be working.
>
> All the previous features of the app (v1.x) are now also working on the
> textSecure branch and it's usable. I think we can merge textSecure into
> master and then continue with the feature branches git workflow.
>
> @corbett <https://github.com/corbett>: Let me know your thoughts on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/259>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
