### ISSUE TITLE
Console not print any log in debug mode 

### ISSUE THREAD

**Issue by SalmanGhumsani** [WhisperSystems/Signal-iOS#2616]
I have successfully able to run the project and CocoaLumberjack not print any log
The code snippet is written in didFinishLaunching and I am sure the compiler goes in `#ifdef DEBUG` but no luck :(
What should I do? any help would be appreciated. :)

```
#ifdef DEBUG
    // Specified at Product -> Scheme -> Edit Scheme -> Test -> Arguments -> Environment to avoid things like
    // the phone directory being looked up during tests.
    loggingIsEnabled = TRUE;
    [DebugLogger.sharedLogger enableTTYLogging];
#elif RELEASE
    loggingIsEnabled = PropertyListPreferences.loggingIsEnabled;
#endif
    if (loggingIsEnabled) {
        [DebugLogger.sharedLogger enableFileLogging];
    }
```

**Comment by michaelkirk** [comment]
Hey @SalmanGhumsani we use Github to collect user facing bugs and feature requests, not for developer support questions. 

Could you move this question to the forum? https://whispersystems.discoursehosting.net/

I'm not sure what your setup is, but it is not at all uncommon that xcode fails to connect to the device TTY.  In my experience, simply trying again, or restart xcode, see if you can reproduce the problem on different devices/simulators, etc.
