### ISSUE TITLE
Resending message doesn't work

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-iOS#2635]
### Bug description
When you have no internet connection and your message fails to send, there's that small dialog "Sending failed. Tap for info.". But it doesn't work most times for me. 

### Steps to reproduce
- turn off your internet connection
- send a message and let it fail
- try to tap on the message or "Tap for info."

**Actual result:** 
nothing happens
**Expected result:** 
The dialog to resend the message should come up

### Device info
**Device**: iPhone 6
**iOS version**: 11.1 
**Signal version:** 2.17.0.8

### Link to debug log
https://gist.github.com/f9e3f49e500c0eaa3f71c54e261d1142

**Comment by charlesmchen** [comment]
Thanks for the report @Mihahn .  The fix for this is in the next release.

**Comment by Mihahn** [comment]
@charlesmchen it's not fixed in 2.18.0.3 (if this is "the next release").
