### ISSUE TITLE
Not able to return from document picker

### ISSUE THREAD

**Issue by TreatyOfRome** [WhisperSystems/Signal-iOS#2653]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
If I open the document picker in a conversation view, iOS 11 brings me to the new 'Files' app. From here, there is no possibilty to cancel or return to the conversation view, other than double tap home - swipe up. 

### Steps to reproduce
- in message/conversation view
- tapping the paperclip -> Document to attach a file
- tap 'Browse' to open the new iOS 11 'Files' app

**Actual result:** Not being able to return to the conversation view.
**Expected result:** Being able to tap a 'Back' button to return to the message view.

### Screenshots
![signal 1](https://user-images.githubusercontent.com/26620973/31652440-9e88f4de-b30e-11e7-924e-997938632bba.png)
![signal 2](https://user-images.githubusercontent.com/26620973/31652442-a13f0830-b30e-11e7-8eb7-8bcfbcaabdf7.png)
![signal 3](https://user-images.githubusercontent.com/26620973/31652469-bd853af0-b30e-11e7-95bd-4dc959884720.PNG)

### Device info
**Device**: iPhone 6S
**iOS version**: 11.0.3
**Signal version:** 2.17.1.1

### Link to debug log
---

**Comment by TreatyOfRome** [comment]
Did some further testing. When adding a 'Document' to a Whatsapp conversation, I am taken to the same 'Files'app. Instead, a 'Cancel' button (just text) is presented in the upper right corner of the screen which brings me back to the Whatsapp conversation.

When Signal brings me to the 'Files' app, I can tap the same area (which is blank), and it brings me back to the Signal conversation. So the button is apparently there, but not visible (or just white text on white background).

**Comment by michaelkirk** [comment]
Fixed in 2.18.0 with 0cd56d4bcce27dede3a3fc2141a7aed3709f65f5

**Comment by bhooshanpatil** [comment]
//for ios 11 //

-(void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls{
    
    NSLog(@"IOS 11");

/*your methods here*/
    
}
