### ISSUE TITLE
Disable debugging logs ... doesn't disable logging.

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#266]
Missing code from UI: https://github.com/WhisperSystems/Signal-iOS/blob/3ddfd9159756b337a0489830b9697f0af44c6695/Signal/src/view%20controllers/SettingsViewController.m#L228

**Comment by dtsbourg** [comment]
I'll add it back

**Comment by FredericJacobs** [comment]
Notice that when the logging is disabled, people shouldn't be able to send a debug log, because it's going to be empty anyways.

**Comment by corbett** [comment]
@dtsbourg you mentioned a fix, has it been PR'ed/merged or timeline?

**Comment by FredericJacobs** [comment]
merged this
