### ISSUE TITLE
Messages in group chat fail to send

### ISSUE THREAD

**Issue by danburd** [WhisperSystems/Signal-iOS#2672]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Messages in group chat fail to send in iOS. After attempting to send a message to the group, user receives error stating "Sending failed. Tap for more info."

### Steps to reproduce
-Send message to group chat 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

-Message does not send
-User receives error below each attempted sent message stating "Sending failed. Tap for more info."

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

-Message sends without error

### Screenshots
Can provide if helpful

### Device info
**Device**: iPhone 5S
**iOS version**: 11.0.3
**Signal version:** 2.17.1.1

### Link to debug log
https://gist.github.com/393708b76c07446eb49a24e44d76a006

**Comment by danburd** [comment]
Clarifications:

-Phone has good wifi and mobile data connection.
-Tapping for more info yields no response from the Signal app.

**Comment by michaelkirk** [comment]
> -Tapping for more info yields no response from the Signal app.

So when you tap on the failed message you don't see an actionsheet with error details or the ability to resend?

This has been intermittently reporting, but we're making some changes to address this in 2.19.


> -Phone has good wifi and mobile data connection.

The only sending errors I see are lots of "Signal was unable to connect to the internet. Please try from another WiFi network or use mobile data."

Starting around 2017/10/19 13:19:46:040 (your local time)
https://gist.github.com/anonymous/393708b76c07446eb49a24e44d76a006#file-org-whispersystems-signal-2017-10-19-17-07-log-L450

Does that correspond to the time of erroneous behavior?

Otherwise, if you can point me to the log time around when this happened and I can look more closely.

**Comment by danburd** [comment]
Thank you for your response. Here's a redacted screenshot -- I couldn't provide it earlier since I was on mobile.

![img_1827 redacted](https://user-images.githubusercontent.com/4601223/31813104-35358dfc-b553-11e7-8894-cd9a07e5f774.png)

> So when you tap on the failed message you don't see an actionsheet with error details or the ability to resend?

Correct. The app behaves as if "more info" had not been tapped.

> Starting around 2017/10/19 13:19:46:040 ... Does that correspond to the time of erroneous behavior?

Correct. The user (a friend of mine) verified that the phone's internet connection was functioning through another app immediately after receiving the error.

Also, my friend reports that most messages he attempts to send go through normally, but that this issue has cropped up from time to time at unpredictable intervals, at least over the last few weeks.

Let me know if there's any other information I can provide or tests that could be run to figure out why Signal might be erroneously concluding that there is no connectivity.

**Comment by chronoslynx** [comment]
I can corroborate this. I would send a debug log, But on iOS 11.1 public beta 5 (build 15B93) I see ```Failed to submit debug log: The operation couldn't be completed (PastelogKit error 10001.)```

**Comment by 3WfMeCuUqzgXBh** [comment]
Yep I experience this too not just in group chats in any chat. Has been going on for a while now, it never happened in previous versions.

**Comment by michaelkirk** [comment]
> Yep I experience this too not just in group chats in any chat. Has been going on for a while now, it never happened in previous versions.

Please submit a debug log if you have an inexplicable failure to send.

> I can corroborate this. I would send a debug log, But on iOS 11.1 public beta 5 (build 15B93) I see Failed to submit debug log: The operation couldn't be completed (PastelogKit error 10001.)

That means uploading your log to gist.github.com failed, which likely means an issue with your network.

**Comment by michaelkirk** [comment]
> -Tapping for more info yields no response from the Signal app.

This has been addressed in 2.19

If you have more inexplicable failures to send, please re-open with a fresh debug log immediately after the failure occurs.
