### ISSUE TITLE
Add Unknown Number to address book

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#268]
Signal shouldn't be how you edit your address book. We don't have the ressources to do that but it would be nice to be able to add someone who messaged you on Signal to the address book.

**Comment by joyceyan** [comment]
It looks like this has been implemented? If you get a message from someone who is not in your address book, tapping on their number (which is listed in lieu of their name) will pull up a view that lets you add the number to either an existing contact or create a new contact with that number.

**Comment by FredericJacobs** [comment]
@joyceyan: Correct. I did early this week.

**Comment by corbett** [comment]
Thanks for pointing this out Joyce! We should close the issue then Fred

**Comment by FredericJacobs** [comment]
I believe it was closed: `corbett closed this 23 days ago`

**Comment by corbett** [comment]
ok.. sorry=0 was on my mobile.

On Sun, Feb 22, 2015 at 7:55 AM, Frederic Jacobs <notifications@github.com>
wrote:

> I believe it was closed: corbett closed this 23 days ago
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/268#issuecomment-75441757>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
