### ISSUE TITLE
"Uploading attachment" text is included in outgoing picture messages

### ISSUE THREAD

**Issue by jlund** [WhisperSystems/Signal-iOS#270]
When you send an image from within Signal, the "Uploading attachment" text appears while the image is being sent. This text is then replaced by the image itself once the transfer is complete. I haven't tested Signal to Signal yet, but picture messages sent to Android TextSecure users include the "Uploading attachment" text above the image itself.

**Comment by FredericJacobs** [comment]
Ha, that's interesting behaviour. cc @mcginty
I know why this is happening and will fix it.

The protocol supports multiple attachements + body. But we only support displaying an attachment at the time.
