### ISSUE TITLE
Decide and adapt push strategy

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#272]

**Comment by FiloSottile** [comment]
Now I'm seeing the notifications appear and quickly get dismissed automatically.

**Comment by FredericJacobs** [comment]
@corbett: In short, background fetch is too unreliable. Background decrypt won't work at a larger scale.
Server will have to count number of messages awaiting delivery that are not delivery receipts and send that as a badge in the push notification. Sad, but that's one of the limitations of iOS.

**Comment by corbett** [comment]
ok, so my understanding of that summary is that
a) the server takes care of the issue
b) we could close this issue in that case?

On Wed, Jan 7, 2015 at 10:31 AM, Frederic Jacobs <notifications@github.com>
wrote:

> @corbett <https://github.com/corbett>: In short, background fetch is too
> unreliable. Background decrypt won't work at a larger scale.
> Server will have to count number of messages awaiting delivery that are
> not delivery receipts and send that as a badge in the push notification.
> Sad, but that's one of the limitations of iOS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/272#issuecomment-69004232>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
No, we'll have to adapt the code base with the new push strategy and this issue represents that adaptation imo.

**Comment by corbett** [comment]
OK. so I still have not enough information to do anything about the issue
(including priority for launch and needed changes). as you are not working
on the codebase this month you will have to do a download of that
information to me.

On Wed, Jan 7, 2015 at 10:36 AM, Frederic Jacobs <notifications@github.com>
wrote:

> No, we'll have to adapt the code base with the new push strategy and this
> issue represents that adaptation imo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/272#issuecomment-69004717>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
@corbett: Everything is in the backlog when you get to read that and you'll be with the oracle (@moxie0) soon that will implement it server-side.

**Comment by corbett** [comment]
ok... I am just not sure I will get to read the backlog! I will ask Moxie I
guess, in general I prefer any issue to have enough information for a
arbitrary implementer to give it a go. I try to document my progress in
issues to help facilitate that.

On Wed, Jan 7, 2015 at 10:41 AM, Frederic Jacobs <notifications@github.com>
wrote:

> @corbett <https://github.com/corbett>: Everything is in the backlog when
> you get to read that and you'll be with the oracle (@moxie0
> <https://github.com/moxie0>) soon that will implement it server-side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/272#issuecomment-69005188>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment]
OK, after some discussions I think I get the issue. still am unable to read mentioned logs, but it seems we'll be able to remove some logic on the client side and simplify things, once some changes on the server are made. this will improve performance. I've assigned the issue to me.

**Comment by NicolasCGN** [comment]
Is there an API for the app to check whether background update is active?
If yes, when background update is off, the server sends normal notifications. With background update active, the server can send a silent notification with the payload, the app decrypts the message on background and shows the decrypted message as a local notification.

You could explain under Signal (App) -> Settings -> Notification Display Style that the options "NO PREVIEW WITH NAME" and "PREVIEW WITH NAME" are only possible with background update active.

If it's too complex to implement (there is not such an API or server must be adapted), you could put off background decryption.

**Comment by corbett** [comment]
this issue has already been decided.

On Wed, Jan 7, 2015 at 11:51 AM, NicolasCGN <notifications@github.com>
wrote:

> Is there an API for the app to check whether background update is active?
> If yes, when background update is off, the server sends normal
> notifications. With background update active, the server can send a silent
> notification with the payload, the app decrypts the message on background
> and shows the decrypted message as a local notification.
>
> You could explain under Signal (App) -> Settings -> Notification Display
> Style that the options "NO PREVIEW WITH NAME" and "PREVIEW WITH NAME" are
> only possible with background update active.
>
> If it's too complex to implement (there is not such an API or server must
> be adapted), you could put off background decryption.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/272#issuecomment-69012141>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
