### ISSUE TITLE
iOS8 Photo Library Media attachments fail 

### ISSUE THREAD

**Issue by aaqwtqrb** [WhisperSystems/Signal-iOS#2733]
When attaching photos from Photo Library iOS Signal application crashes

- Load Signal App 
- Click on any contact from Signal Contact List
- Click on Paperclip to attach
- Select Photo Library
- Select any image
- Click Green Button

Result: Application crashes

Expected result is that image will be attached to the message. This used to work before 2.17

Device: Iphone 6
IOS: 8.4.1
Signal: 2.17.1 and 2.18.1 both show this issue
Photo Library also has over 12000 photos but was not an issue before version 2.17

**Comment by charlesmchen** [comment]
This issue will be fixed in the next release.
