### ISSUE TITLE
short-circuiting the network and the protocol when user creates thread with themselves

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#274]
That never goes on well.

**Comment by corbett** [comment]
we've had this discussion on Android, apparently people like sending
messages to themselves. and protocol wise, it should be allowed.

On Mon, Jan 5, 2015 at 12:10 AM, Frederic Jacobs <notifications@github.com>
wrote:

> That never goes on well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/274>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Well, because I enforce timestamp as messageId in the database, we can't have a incoming and outgoing message with the same id and I don't feel like having a workaround to allow this.

**Comment by corbett** [comment]
This isn't what we decided in previous meetings with the Android folks. That said I think it is kind of silly! Still FYI we should bring up for discussion

**Comment by BoerenkoolMetWorst** [comment]
I don't see the benefit of allowing to message yourself on the same device, but messaging yourself on another device can be quite handy. For example, I sometimes send long links to myself on Telegram from my iPhone to Desktop so I don't have to copy them manually.

**Comment by moxie0** [comment]
We just shove the outgoing message into the database as an incoming message, short-circuiting the network and the protocol.

**Comment by corbett** [comment]
Makes sense we can do that too

**Comment by corbett** [comment]
this now functions as on Android https://github.com/WhisperSystems/Signal-iOS/pull/305
