### ISSUE TITLE
after last few updates in 2017, app is no longer responsive on iphone SE

### ISSUE THREAD

**Issue by mailinglists35** [WhisperSystems/Signal-iOS#2746]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
After several updates to the app in app store, using the app feels like my phone has been downgraded from an iPhone SE to an iPhone 4s

### Steps to reproduce
- travel in time in 2016 (thank you apple for not allowing downgrades). I think even early 2017 the app was still decent (not very fast but usable)
- install the app
- return to 2017
- update the app

**Actual result:** app behaves like it's running on my old 4s phone. especially on the activity that I spend most of the time using the app: typing
**Expected result:**  I expect software updates to bring faster UI response on all supported hardware

### Device info

**Device**: iPhone SE (two devices, not just one)
**iOS version**: 10.2
**Signal version:** latest available from app store

### Link to debug log

there is nothing in the debug log relevant to app performance. it only debugs connections to signal servers.

**Comment by michaelkirk** [comment]
No time machine necessary, we've made some big improvements in the forthcoming 2.19 release which should significantly speed up the conversation view, and laid the groundwork for more improvements to come.

If you are OK with running less stable software, e.g. more likely to crash or lose data, you can sign up for the forthcoming beta by emailing support@whispersystems.org with the subject "Sign me up for the Signal iOS Beta"

If you still have issues after installing 2.19, feel free to re-open and we can dig deeper.
