### ISSUE TITLE
Sending Failed, Tap for info does nothing 

### ISSUE THREAD

**Issue by wdormann** [WhisperSystems/Signal-iOS#2747]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

When a message fails to send, Signal says to tap for more info.  In the past, this allowed me to resend the message. But with the current version, tapping the message don't see nothing. 

### Steps to reproduce
- Send a message with no wireless coverage 
- Wait for message that the sending failed 
- Tap that message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Nothing happens 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Option to resend the message is presented 

### Device info

**Device**: iPhone 6s
**iOS version**: 11.1
**Signal version:** 2.18.2

**Comment by charlesmchen** [comment]
Hi @wdormann .  This has been fixed and will ship in the v2.19 release.

**Comment by charlesmchen** [comment]
Hi @wdormann .  This has been fixed and will ship in the v2.19 release.
