### ISSUE TITLE
Bug in deleting attachments from self-shadow contacts

### ISSUE THREAD

**Issue by gsbabil** [WhisperSystems/Signal-iOS#2748]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

Signal allows sending messages/attachments to self, if there exists
a contact in the iOS address-book with the same number that was use
to register with Signal.

For example, if the number +12101114455 was used to register with
Signal, and there exists a contact in iOS address-book with the name
"John Doe" with +12101114455, both Signal-iOS and Signal-Desktop
will allow exchanging messages/attachments with John Doe.

Once a message is sent to such a "self-shadow" contact, it'll make
the round-trip through the server, and immediately echo-back the
same message or attachment under the same conversation thread.

This unexpected side-effect is in fact great for testing, debugging,
and even saving small notes-to-self as future records. This could
may be even be considered as a serious feature to be implemented
with other bells-and-whistles in the future.

However, there's a bug with exchanging attachment with such
self-shadow contacts. As mentioned above, both messages and
attachments can be sent/received without any issue. But if a
previously sent/received attachment exchanged with a self-shadow
contact is deleted, the remaining sent/received attachment record in
the local iOS database is corrupted.

### Steps to reproduce

1. Register a Signal account, for example with +12101114455.

2. Create an iOS contact called "John Doe" and add +12101114455 to
   this contact.

3. Send an image to "John Doe". The echo-back of the attachment will
   be received immediately and show up in the conversation-view.

4. Now delete either the sent or the received attachment.

5. Try to open the sent/received attachment after step 4.

6. Go back to recent-conversation-view, and come back to the
   conversation-view with John Doe. The remaining sent/received
   attachment will not show up anymore.

**Actual result:**

Corrupted local database as described in step 5 and 6 above.

**Expected result:**

The expected behavior is to have the attachment that was _not_
deleted to show up in the conversation-view with John Doe.

### Screenshots

![signal](https://user-images.githubusercontent.com/1061108/32665482-1fb163be-c680-11e7-8171-8b81b504b548.jpg)

### Device info

 - **Device**         : iPhone 6
 - **iOS version**    : 11.1.1
 - **Signal version** : 2.18.2.1

### Link to debug log

https://gist.github.com/anonymous/cb1ec56ef5d3c5d74f828b811b0e0e4c

**Comment by charlesmchen** [comment]
This has been fixed and will be released in v2.19.  Thanks @gsbabil

**Comment by gsbabil** [comment]
Hi @charlesmchen 

Thanks. I'm on `2.19.2.0` at the moment and can confirm that the issue is resolved for new messages exchanged with self-shadow contacts.

However, deleting the previously sent/received item to a self-shadow contact (exchanged prior to version 2.19.2.0), and then trying to open the remaining sent/received item from the conversation-view now leads to a crash.

Please find the debug log collected immediately after such a crash [here](https://gist.github.com/anonymous/0ea4be00a58b8cac55526b83a851ff69). This is reproducible 100% on my iOS device.

Thank you.
