### ISSUE TITLE
Registering UI messed up on iPhone 4S

### ISSUE THREAD

**Issue by BoerenkoolMetWorst** [WhisperSystems/Signal-iOS#275]
The "Okay, let's do this!" button/text is partially covering the lowest text blob about storage encryption on the smaller screen of the 4S. (iOS 8.1.2, Signal 2.0.7)

**Comment by dtsbourg** [comment]
@BoerenkoolMetWorst Thanks for the feedback, I'll fix that now !

**Comment by FredericJacobs** [comment]
Ok, thanks Dylan.

**Comment by corbett** [comment]
@dtsbourg you mentioned a fix, has this been PR'd/timeline

**Comment by FredericJacobs** [comment]
Merged
