### ISSUE TITLE
Upload / Encryption indicator for Media Sharing

### ISSUE THREAD

**Issue by flowgrow** [WhisperSystems/Signal-iOS#276]
I suggest, instead of just writing "Uploading attachment" that there would be a status bar, which shows the current percentage. And maybe (I don't know how long encryption takes) also showing an encryption status bar.
I made a quick mockup using font awesome for the icons:
![sending attachment mockup](https://cloud.githubusercontent.com/assets/2501377/5616691/529789fa-9507-11e4-8a81-5e35da3cd780.png)

PS:
I don't know which iOS API invoke this and which don't, it would be nice to have the rotating internet indicator next to the wifi/4G logo, when uploading an image. right now it feels like it's not uploading at all.. especially when sending uncompressed images.

**Comment by FredericJacobs** [comment]
Thanks @flowgrow, this looks really nice. I've been thinking about a few ways to implement progress indicators but have not yet had the time to work on that.

**Comment by corbett** [comment]
I can do some of this...

**Comment by flowgrow** [comment]
glad, that you guys like it!
thanks for inviting me to the beta and all the great work, that you do

**Comment by corbett** [comment]
yes well the first step will be to have a progress indicator of any sort
and then we will hope to even improve on the design.

On Mon, Jan 5, 2015 at 7:46 PM, Florian <notifications@github.com> wrote:

> glad, that you guys like it!
> thanks for inviting me to the beta and all the great work, that you do
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/276#issuecomment-68764626>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Thankfully, AFNetworking, the network library, has tons of useful features to make that simple to implement.

**Comment by corbett** [comment]
this has been implemented
