### ISSUE TITLE
Shredding dialog is cut and badly padded

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#278]
![2015-01-04 19 25 30](https://cloud.githubusercontent.com/assets/1225294/5622009/62e338ea-9534-11e4-8e95-02f785ecc338.png)

**Comment by corbett** [comment]
@dtsbourg this was closed as referenced in a commit of yours, has it been PR'ed/merged or timeline?

**Comment by FredericJacobs** [comment]
Merged
