### ISSUE TITLE
After tweeting the fingerprint the UI does not reset

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#279]
* Tap "Share Fingerprint"
* *button turns grey, since it's tapped*
* *send tweet*
* *button does not turn back white*

![2015-01-04 19 27 04](https://cloud.githubusercontent.com/assets/1225294/5622022/a3662058-9534-11e4-92b5-a33b1576cb11.png)

**Comment by FiloSottile** [comment]
Same with "Submit Debug Log"

**Comment by dtsbourg** [comment]
This will be fixed when we refactor the settings into menus :) 
See #252
