### ISSUE TITLE
Layout for iPhone X missing

### ISSUE THREAD

**Issue by ericmeltzer** [WhisperSystems/Signal-iOS#2807]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
On the iPhone X, signal's layout doesn't fill the screen

### Steps to reproduce
- Open Signal on an iPhone X

**Actual result:** The layout doesn't fill the screen
**Expected result:** The layout should fill the entire screen: 

### Device info

**Device**: iPhone X
**iOS version**: 11.1.1 
**Signal version:**2.18.2.1

**Comment by michaelkirk** [comment]
This is fixed in the next release - 2.19.
