### ISSUE TITLE
Autocorrect bubble appears under the keyboard, making it harder to click

### ISSUE THREAD

**Issue by cevn** [WhisperSystems/Signal-iOS#2811]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When you write text that is autocorrect and you want to undo the autocorrect, the bubble goes "down" instead of "up", resulting in a bubble which is partially covered by the keyboard. 

### Steps to reproduce
- start messaging someone and write autocorrected text 

**Actual result:** bubble goes "down" 
**Expected result:** bubble goes "up"

### Screenshots
![b9ac7abf-5639-4294-917a-f765e151c3b6](https://user-images.githubusercontent.com/4663020/33277745-72f45998-d367-11e7-9eb0-24087edfcf32.png)
### Device info

**Device**: iPhone X
**iOS version**: 11.1.2
**Signal version:** 2.18.2.1

### Link to debug log
Probably not necessary

**Comment by michaelkirk** [comment]
Can you update to 2.19 and see if the problem persists?

**Comment by cevn** [comment]
Bug is gone. Thanks!
