### ISSUE TITLE
Missing separator in conversations view

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#283]
Notice how there is no grey horizontal rule between Anna and George.

Also, there should not be one under the last entry.

![2015-01-05 23 54 31](https://cloud.githubusercontent.com/assets/1225294/5622169/c409ae86-9536-11e4-832c-a0565199fcb4.png)

**Comment by corbett** [comment]
@dtsbourg this was closed as referenced in a commit of yours, has it been PR'ed/merged or timeline?

**Comment by FredericJacobs** [comment]
Merged.
