### ISSUE TITLE
Crash when attempting to Save Image

### ISSUE THREAD

**Issue by codeslinger** [WhisperSystems/Signal-iOS#2836]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
App crashes when attempting to Save Image on images sent in a conversation.

### Steps to reproduce
- Send an image to someone else or have one sent to you
- Tap the image
- Tap the box with the arrow through it at the bottom
- Tap 'Save Image'

**Actual result:** The app crashes
**Expected result:** The image is saved and the app does not crash

### Device info
**Device**: iPhone X
**iOS version**: 11.1.2
**Signal version:** 2.19.0.22

### Link to debug log
https://gist.github.com/anonymous/f5b580095e725439511631f7448caa8c

**Comment by charlesmchen** [comment]
This should be resolved in v2.19.1.  Unfortunately due to a bug in the app store our app isn't available for the download at the moment. We're working on it.
