### ISSUE TITLE
安装不了了

### ISSUE THREAD

**Issue by iambonboncat** [WhisperSystems/Signal-iOS#2837]

**Comment by iambonboncat** [comment]
This item is no longer available.

**Comment by michaelkirk** [comment]
We’re aware of this issue, and have filed a bug with Apple.

Seems like a problem processing our submission. Hopefully they’ll address it soon.

**Comment by michaelkirk** [comment]
Apple has addressed this.

> Apple has resolved the App Store issue that was preventing some iOS users from installing Signal. Thank you for your support.
https://twitter.com/whispersystems/status/936686074465869825
