### ISSUE TITLE
Search box in Contacts view is not centered

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#284]
It has more space on its right than on its left.

**Comment by dtsbourg** [comment]
Not quite sure why that happens, it seems to update on appear. I'll take a look.

**Comment by dtsbourg** [comment]
I haven't figured out why this happens yet, any ideas welcome @corbett :) 
The search bar is added programmatically and frame should be handled by default. From what I could see it seemed to be re-centered right after the view appears, but idk why this offset appears.

**Comment by corbett** [comment]
contacts view is no longer present
