### ISSUE TITLE
iPhone X, signal calls still not working after UPDATE

### ISSUE THREAD

**Issue by wozney** [WhisperSystems/Signal-iOS#2843]
Signal call feature still not working after update.

Submitted request 8 days ago, updated to new signal and still not working.

Any help would be appreciated.

Check previous post for logs

**Comment by rocknjohn** [comment]
Duplicate of your ticket at https://github.com/WhisperSystems/Signal-iOS/issues/2809.  Kindly close this duplicate ticket to save the devs' time so they can spend more time resolving bugs and less maintaining the issue tracker. Thanks
