### ISSUE TITLE
Update github project setting's URL to https://signal.org

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#2844]
The https://whispersystems.org domain now redirects to https://signal.org

For consistent branding, we should update the github project settings URL from `https://whispersystems.org` to `https://signal.org` so this URL is shown at the top of the this repo.

**Comment by michaelkirk** [comment]
Done, thanks.

**Comment by rocknjohn** [comment]
The perfectionist in me wants to remove the trailing slash :)
