### ISSUE TITLE
Explain Warnings about Insecure or Unavailable Sessions

### ISSUE THREAD

**Issue by mxmerz** [WhisperSystems/Signal-iOS#287]
In a chat between iOS and Android devices, the Android user can cancel the encryption and continue the chat with unencrypted text messages.

When a friend tried this out in a chat with me (him on Android, me on iOS), I received a red “No available session for contact” and a yellow “Secure session ended.” warning. When I received these warnings, it was not clear to me why they happened and what I could do about it. Afterwards, I think the encryption went back up, but never saw something like a green badge saying “Everything’s fine and encrypted again” to assure me that my messages were secure.

**Comment by FredericJacobs** [comment]
Well, on iOS, there is just no way to send or receive plaintext messages. I'm not sure how this should be addressed but I really don't want iOS signal to support plaintext because that would lead to confusion. Everything on Signal should be encrypted, no exceptions.

**Comment by mxmerz** [comment]
I absolutely do not want to send or receive plaintext messages, I just think that the app could explain to the user what happens and why it happens. (I did not understand why these messages popped up until two days later (yesterday) when my friend explained & showed it to me.) Also, after I received these warnings I wasn’t sure whether the chat was still encrypted, so maybe show some message to the user saying that the problem was solved?

Again, just for the user experience.

**Comment by FredericJacobs** [comment]
How can an Android user send unencrypted messages over the push channel? That sounds like a bug. I will investigate that.

**Comment by moxie0** [comment]
There isn't, OP is confused.

**Comment by mxmerz** [comment]
Yes, I am confused and I am sorry, I think I am propably still not clearly communicating my problem. I'll try again:
My point is not that the functionality of Signal is somehow broken, my point is that the app needs better error messages to not confuse it's users.
Here are the messages I received in the middle of a chat:
![image](https://cloud.githubusercontent.com/assets/1419619/5643289/ab8c8a2e-9656-11e4-8c95-aab6f9ad0228.jpg)
If you would have asked me then what these error messages mean for the security of my chat, I would have answered that the security is now somehow compromised. I now suspect that that was not the case, but I think the app should make that absolutely clear to the user (by, for example, showing a green message stating "Secure session re-established" or something like that).

**Comment by FredericJacobs** [comment]
Oh, I see. It's indeed an issue that we're warning about session resets and don't have a visual indication that it's being reset.

Probably renaming the `Secure session ended.` message to `Secure session was reset` would make more sense.

**Comment by corbett** [comment]
closes https://github.com/WhisperSystems/Signal-iOS/pull/297
