### ISSUE TITLE
Module 'CocoaLumberjack' not found

### ISSUE THREAD

**Issue by theilgaard** [WhisperSystems/Signal-iOS#2873]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I have cloned the project and run pod install. I then attempt to build the project in Xcode, but the build fails with "Module 'CocoaLumberjack' not found" in the file SignalMessaging-Prefix.pch.

### Steps to reproduce
- Clone project off github
- Run `pod install`
- Attempt to build in Xcode

**Actual result:** Error: "Module 'CocoaLumberjack' not found" on line 11 at @import CocoaLumberjack; 
**Expected result:** No error.

### Screenshots
![screen shot 2017-12-11 at 15 22 32](https://user-images.githubusercontent.com/1464129/33835574-3725857e-de87-11e7-93a3-83a17a490166.png)

**Comment by michaelkirk** [comment]
Based on your "steps to reproduce" it seems like you aren't following the instructions in BUILDING.md? Can you start there?

We are in the middle of shuffling lots of things around, so if something in those instructions is broken, let us know (or better yet open a PR) and we can address it.

**Comment by theilgaard** [comment]
Thanks @michaelkirk , I completely overlooked it!

After installing Carthage from brew, and installing bundler (as described here http://bundler.io/), and finally running make dependencies, I get an error on a missing Contact.h file. 

### Steps to reproduce
- Clone project off github
- Install Carthage
- Install Bundler
- make dependencies
- Attempt to build in Xcode

**Actual result:** Error: 'SignalServiceKit/Contact.h' file not found
**Expected result:** No error.

### Screenshots
![screen shot 2017-12-12 at 11 37 47](https://user-images.githubusercontent.com/1464129/33880197-30a3d14c-df31-11e7-9cf6-5f6edba25878.png)

**Comment by michaelkirk** [comment]
What version of Xcode are you using?

**Comment by theilgaard** [comment]
It was another self-induced issue, I opened the project from Xcode, and not through the term with `open Signal.xcworkspace` as described in BUILDING.md

Thanks for quick response!
