### ISSUE TITLE
Add Ability To Select Photos By Album

### ISSUE THREAD

**Issue by mxmerz** [WhisperSystems/Signal-iOS#288]
At the moment, if I want to send a photo, I can only take a new photo or select photos from the album “Moments”. It would be nice to have the ability to also browse photos by their album, for example “Camera Roll”, “My Photo Stream”, “Favorites“, or user-created albums.

**Comment by dtsbourg** [comment]
Agreed that would make sense. I will add this !

**Comment by corbett** [comment]
@dtsbourg this was closed as referenced in a commit of yours, has it been PR'ed/merged or timeline?

**Comment by dtsbourg** [comment]
@corbett My bad, I figured the contributions would be cherry picked off my branch seeing as you guys are working at WBoC, and I don't know where design conflicts lie. I will rebase and PR this afternoon.

**Comment by corbett** [comment]
oh sorry, Fred is scaling back for a few weeks, it's only me, (he'll be
here soon though!) and I can work with whatever workflow you prefer but you
have to let me know as we haven't worked at the same time before

On Thu, Jan 15, 2015 at 7:55 PM, Dylan Bourgeois <notifications@github.com>
wrote:

> @corbett <https://github.com/corbett> My bad, I figured the contributions
> would be cherry picked off my branch seeing as you guys are working at
> WBoC, and I don't know where design conflicts lie. I will rebase and PR
> this afternoon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/288#issuecomment-70211645>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Merged. 
@corbett: I'm working on guiding @dtsbourg's contributions since we see each other almost daily at EPFL.
