### ISSUE TITLE
[2.19.3.1 Beta] UI Blocking after start

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#2885]
- [y] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
If you start (cold-start) the app and try to immediately scroll after the list of conversations are shown, the UI is blocked while scrolling. It seems something is loading in the background and is blocking the UI.

### Steps to reproduce
- kill the app
- launch Signal
- scroll immediately after conversation list is shown

**Actual result:** 
UI is blocked
**Expected result:** UI should not be blocked

### Device info

**Device**: iPhone 
**iOS version**: 10.3.3
**Signal version:** 2.19.3.1 Beta

**Comment by michaelkirk** [comment]
Thanks for the report. This is addressed in #2887, and will be available in the next beta, 2.19.3.2

**Comment by big-r81** [comment]
Fixed and working in 2.19.3.3

**Comment by michaelkirk** [comment]
Thanks @big-r81
