### ISSUE TITLE
Not showing correct thread after receiving a notification (Beta 2.0.7)

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#289]
Both with locked and unlocked iphone, when I sweep or select a notificacion of a new message, the app doesn't open in the correct thread but on the last seen one.

**Comment by FredericJacobs** [comment]
@corbett : It's not implemented yet and will likely not be implementable given the outcomes of #272. Best we can do is show thread view.

**Comment by corbett** [comment]
OK, I will be unable to check the logs for #272 for awhile/ever so I'm not sure what the outcomes are but I will take your word for it.
