### ISSUE TITLE
Notifications don't show sender name

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#290]
I have the notification style on "No preview with name", but all I see is "You got a new message!"

**Comment by dtsbourg** [comment]
I have noticed this as well, I'm investigating it.

**Comment by FiloSottile** [comment]
Same also when activating the preview.

**Comment by FiloSottile** [comment]
Actually, the "With preview" option works correctly.

**Comment by FredericJacobs** [comment]
Closing this, still figuring out how to do push properly with OS restrictions.
Will be discussed in #272
