### ISSUE TITLE
Iran is not listed in Censorship Circumvention Locations!

### ISSUE THREAD

**Issue by khashyarkh** [WhisperSystems/Signal-iOS#2903]
Signal is Filtered in Iran as of 20 hours ago...

I hope we realize that Iran is a country with 81 million population.
https://en.wikipedia.org/wiki/Iran

**Signal version:** 2.19.3

**Comment by michaelkirk** [comment]
Please see https://github.com/WhisperSystems/Signal-Android/issues/7311 for the authoritative response. Unfortunately simply adding Iran to that list won't fix anything.
