### ISSUE TITLE
[Feature Request] Pure Black Theme

### ISSUE THREAD

**Issue by BrokenHope** [WhisperSystems/Signal-iOS#2933]
Any chance of a pure black theme for Signal for use on the iPhone X?

Something similar to the black theme they added in Telegram would be good.

**Comment by NinebitX** [comment]
Dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1019?

**Comment by michaelkirk** [comment]
closing as dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1019
