### ISSUE TITLE
Strings on Transifex not up to date

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#294]
Hi, I am a translator on Transifex.
A friend of mine is testing Signal with textsecure, and I noticed that some strings on his phone are still in English. I logged into Transifex to translate them but I couldn't find them.
Could you please upload all the strings you use in the app? It would be cool to release Signal with textsecure already translated the day of launch.
Thank you.

**Comment by manhole11** [comment]
Also -- there are two resources called "Italian" in the list. https://www.transifex.com/projects/p/signal-ios/

**Comment by FredericJacobs** [comment]
Fixed
