### ISSUE TITLE
Cannot build app on Xcode

### ISSUE THREAD

**Issue by kausstud** [WhisperSystems/Signal-iOS#2945]
I having an issue on building the app on Xcode after cloning the repo.

I followed the instructions on Building.md file and pod installed successfully but i'm still getting an error .. it crashes on the logo screen after running the app.

<img width="1437" alt="screen shot 2018-01-18 at 11 24 33 pm" src="https://user-images.githubusercontent.com/35579004/35120718-1b840b06-fcaa-11e7-826d-75eaec75edef.png">

![screen shot 2018-01-18 at 11 26 34 pm](https://user-images.githubusercontent.com/35579004/35120781-4b50d9ae-fcaa-11e7-87ab-45839d84d705.png)

Xcode Version 9.2 (9C40b)
OS : Sierra 10.12.6

**Comment by michaelkirk** [comment]
Closing this as I haven't heard back.

The forums are probably a better place for developer support anyway: https://whispersystems.discoursehosting.net/

**Comment by acemeow** [comment]
I just cloned and built the app as instruction, but I too encounter same difficulties on my real device.

Xcode Version 9.2 (9C40b)
OS: High Sierra 10.13.3
iPhone 5, iOS 10.3.3

**Comment by michaelkirk** [comment]
@acemeow - you're going to have to provide some details. 

What's the issue?
What's the error? 

You say trouble on your real deice - does that mean it works on simulator?

**Comment by acemeow** [comment]
Both simulator and real device failed.

After following instruction Building.md, changing all the signing and capabilities accordingly, make dependencies/pod install all looks fine. But Signal app fail to run on my real device and simulators. They all have identical error output " [OWSFileSystem] Failed to create directory: (null)"

This is the output from running on my iPhone5:
![28124769_1982608648440426_2144759145_o](https://user-images.githubusercontent.com/14994111/36245785-bbae37f0-1267-11e8-9f2e-d5aefe40c78d.png)

and this is the out put from running on iPhone6 simulator:
![28124913_1982897598411531_720328473_o](https://user-images.githubusercontent.com/14994111/36246329-3540c8ba-126a-11e8-9fea-5c21a645b883.png)

No matter on simulator or real device, they all end stuck right here:
![28054280_1982896815078276_1278219097_n](https://user-images.githubusercontent.com/14994111/36246378-8966d5ec-126a-11e8-95af-3dd541dff4d2.png)

**Comment by michaelkirk** [comment]
@acemeow - The forums are a better place for developer support: https://whispersystems.discoursehosting.net/
