### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Firdaus89** [WhisperSystems/Signal-iOS#2949]
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by Firdaus89** [comment]
How to use this file??

**Comment by michaelkirk** [comment]
Please fill out the issue template before reopening.

If you need help, contact support@whispersystems.org
