### ISSUE TITLE
swift 4

### ISSUE THREAD

**Issue by nikhilwhizdhavale** [WhisperSystems/Signal-iOS#2952]
are there any plans to update code to swift 4 ? Not the objective C code but swift code @michaelkirk

**Comment by michaelkirk** [comment]
To keep notification traffic down for our subscribers, we do not use Github for discussion, just for reporting bugs/ feature requests. In the future please use the community forums for questions like this.

community forum: https://whispersystems.discoursehosting.net/

But yes, new code is written as Swift 4 while Swift 3 code gets updated as it's touched for other reasons.
