### ISSUE TITLE
archived threads do not appear in archived tab.

### ISSUE THREAD

**Issue by corbett** [WhisperSystems/Signal-iOS#296]

**Comment by FredericJacobs** [comment]
Could you reproduce it?

**Comment by corbett** [comment]
I can only reproduce it. I've never seen any textsecure threads in the
archived tab under any circumstances, whether my beta, an install from
master, a reinstall, etc.

On Wed, Jan 7, 2015 at 10:02 AM, Frederic Jacobs <notifications@github.com>
wrote:

> Could you reproduce it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/296#issuecomment-69001090>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Feature doesn't seem buggy, just confusing UX.

**Comment by corbett** [comment]
agreed.

On Wed, Jan 7, 2015 at 10:28 AM, Frederic Jacobs <notifications@github.com>
wrote:

> Closed #296 <https://github.com/WhisperSystems/Signal-iOS/issues/296>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/296#event-215207280>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
