### ISSUE TITLE
New Fingerprint Format

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#298]

**Comment by corbett** [comment]
will this be for 2.0 launch or will we wait? what is the roadmap for android making the change?

**Comment by FredericJacobs** [comment]
No. I think this is an easy change and we want to do it before launch. I would actually love to work on this in Hawaii :)

**Comment by corbett** [comment]
OK but it involves updating the android client first (as otherwise Signal
would launch with inconsistent fingerprints, so I'll mark for this release
but also mark as blocked.

On Wed, Jan 7, 2015 at 11:37 AM, Frederic Jacobs <notifications@github.com>
wrote:

> No. I think this is an easy change and we want to do it before launch. I
> would actually love to work on this in Hawaii :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/298#issuecomment-69010908>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
We're not blocked. As agreed with @mcginty and @trevp we have the specification and word list. So I think we're good. Of course, we'll need both implementations to test.

**Comment by corbett** [comment]
Yes we can proceed with implementing but we can't launch with this feature until they do, and if they haven't by the time we launch 2.0 we should use the consistent one. That's what I mean by blocked

**Comment by trevp** [comment]
Fred I would check with moxie to see the status and schedule for this idea.

Trevor

**Comment by corbett** [comment]
yep, absolutely we will sync up. it's good to have this documented in an
issue, and we can work on it in parallel but should coordinate launch.

On Wed, Jan 7, 2015 at 4:03 PM, trevp <notifications@github.com> wrote:

>
> Fred I would check with moxie to see the status and schedule for this
> idea.
>
> Trevor
>
> > On Jan 7, 2015, at 2:37 PM, Christine Corbett Moran <
> notifications@github.com> wrote:
> >
> > Yes we can proceed with implementing but we can't launch with this
> feature until they do, and if they haven't by the time we launch 2.0 we
> should use the consistent one. That's what I mean by blocked
> >
> > Sent from my iPhone
> >
> > > On Jan 7, 2015, at 14:29, Frederic Jacobs <notifications@github.com>
> wrote:
> > >
> > > We're not blocked. As agreed with @mcginty and @trevp we have the
> specification and word list. So I think we're good. Of course, we'll need
> both implementations to test.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/298#issuecomment-69043164>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by maxbrandes** [comment]
Don't know if this is the right place, but this is related to the fingerpint thing.

I have compared the fingerprint with my contact (via camera) and the app said "verified". But then, nothing changes. You should include a coloring system, the lock-icon should turn green when verified, and red or orange when not (and it is possible for a MITM attack)

**Comment by corbett** [comment]
So we will not be exposing this in the UI.

On Sun, Jan 11, 2015 at 11:48 PM, maxbrandes <notifications@github.com>
wrote:

> Don't know if this is the right place, but this is related to the
> fingerpint thing.
>
> I have compared the fingerprint with my contact (via camera) and the app
> said "verified". But then, nothing changes. You should include a coloring
> system, the lock-icon should turn green when verified, and red or orange
> when not (and it is possible for a MITM attack)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/298#issuecomment-69547201>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by maxbrandes** [comment]
I am sure you have discussed this through. But I think, that especially "not so tech-savy" users of signal will lose track of which conversations have been "verified" and with whom they haven't verified yet. If you don't change a color or indicate somehow in the UI, then think about a small comment under both fingerprints stating "verified", or "secured"...

**Comment by joostrijneveld** [comment]
It seems that the title of this issue does not reflect the discussion, but I would like to add that such an indicator (even in a somewhat 'hidden' place) seems quite crucial to the whole 'verifying fingerprints' process. I was surprised not see one appear, considering that the process is so similar to that of TextSecure for Android, and a lock icon did appear there. I guess not exposing any crypto-related information to the casual user is a choice you could argue for or against, but I really cannot think of anything against showing this information on the fingerprint info screen.

**Comment by FredericJacobs** [comment]
What kind of indicator are you talking about?

**Comment by joostrijneveld** [comment]
What @maxbrandes mentioned in the comments above; something that shows that a fingerprint has been verified in the past. If I recall correctly, TextSecure displays that with a lock icon besides a contact name, but as @maxbrandes suggests, even a simple 'Verified!' on the fingerprint screen would be great.

**Comment by moxie0** [comment]
@joostrijneveld We're not going to do that, TextSecure doesn't either.

**Comment by michaelkirk** [comment]
Any details to fill in about what work this issue represents @FredericJacobs ?

And what is it "blocked" on?

**Comment by michaelkirk** [comment]
closed in https://github.com/WhisperSystems/Signal-iOS/pull/1365
