### ISSUE TITLE
Group picture not attached when creating a new group (beta 2.0.7)

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#299]
When I create a new group chat and I select a picture, a group name, members, and finally press "Create", the group chat is created and members are added but the picture I selected for the group is missing.

When updating the newly-created group chat, I can select a picture again and it works.

**Comment by corbett** [comment]
this is linked to #249. the avatar will appear but only after the upload is complete. #249's completion will show everything as soon as you create it client side.
