### ISSUE TITLE
Support landscape mode

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-iOS#302]
It would be nice to use Signal (especially the keyboard) in landscape mode, like most other messengers and the Android version of TextSecure support it.

**Comment by abolishme** [comment]
i agree @rmueller83, and i've put some thought into how it would look, although it would likely for the 4.7" screen and larger.

**Comment by lorenzhs** [comment]
It would be splendid if Signal were to rotate when viewing media at the least. I'm not sure if this is possible in isolation, but it'd be much appreciated!

**Comment by mcmenace** [comment]
Last comment is 10 month old. Any progress on landscape mode on IOS?

**Comment by anatoli26** [comment]
As @lorenzhs said, the possibility to at least rotate the media to full-screen should be added. Now if I press full-screen on a video, it continues reproducing (sound) but disappears visually. This should be posted as a new bug probably.

**Comment by portenkirchner** [comment]
Would like that landscape photos would turn in landscape mode.

**Comment by richlv** [comment]
Image rotation has been recently added in the iOS version, text input still pending.

**Comment by amirian** [comment]
So what about Android? Do you have a plan? When would that be released?

**Comment by u32i64** [comment]
#### Signal iOS already supports full landscape mode starting from version `2.35.0`.

---

@amirian For Signal Android, you should probably refer to the [signalapp/Signal-Android](https://github.com/signalapp/Signal-Android) repository instead.
