### ISSUE TITLE
Image description is missing

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-iOS#303]
If I send an image from TextSecure Android with an additional text, the text is not displayed on iOS Signal.

![ts1](https://cloud.githubusercontent.com/assets/2698076/5650656/b0f1d75e-96a0-11e4-8a3e-1470efd6f4c9.png)

![ts2](https://cloud.githubusercontent.com/assets/2698076/5650658/b544adae-96a0-11e4-9af0-2e1d3f19b31b.PNG)

**Comment by corbett** [comment]
thanks, yes this is a known issue on our end, I will do some work to fix
it.

On Wed, Jan 7, 2015 at 6:10 PM, rmueller83 <notifications@github.com> wrote:

> If I send an image from TextSecure Android with an additional text, the
> text is not displayed on iOS Signal.
>
> [image: ts1]
> <https://cloud.githubusercontent.com/assets/2698076/5650656/b0f1d75e-96a0-11e4-8a3e-1470efd6f4c9.png>
>
> [image: ts2]
> <https://cloud.githubusercontent.com/assets/2698076/5650658/b544adae-96a0-11e4-9af0-2e1d3f19b31b.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/303>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment]
@jackflips
