### ISSUE TITLE
Double lock screen notification

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-iOS#304]
If I receive a new message, I get two notifications on the lock screen: the message itself plus "You got a new message!".
The latter seems needless to me, wasting lock screen space.

![ts3](https://cloud.githubusercontent.com/assets/2698076/5650814/0e5c9a18-96a2-11e4-8bd3-84e9d43a2b20.PNG)

**Comment by FredericJacobs** [comment]
Still doing work on this. See #272
