### ISSUE TITLE
Add possibility to share your location in a message

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#306]
Please add the possibility to share your (GPS) location in a message with the recipients and have the location represented by a pin on a map. Users that receive the message can read how far they are from the sender by a text label next attached to the Pin on the map. 

Thx for all the work on Signal. Looking good!

Johan.

**Comment by FredericJacobs** [comment]
Signal is a privacy app. We are not planning to geolocate every message. Location sharing feature is being considered.

**Comment by JohanDoe** [comment]
Hi - still happily using Signal. Indeed - geolocation of every message would be bad idea.

Any news on the possibility of adding location sharing feature? Still begin considered? Useful to answer the ubiquitous 'where are you?' question.
