### ISSUE TITLE
Hyperlinks not selectable until copied

### ISSUE THREAD

**Issue by mr100percent** [WhisperSystems/Signal-iOS#307]
Hyperlink URLs that are received as messages are not converted into clickable underlined links until the message is highlighted and copied to clipboard. Once copied, the link becomes underlined and clickable.

**Comment by mr100percent** [comment]
Should mention this is app version 2.0.7 on iOS 8.1.2 on iPhone 6

**Comment by prvcy** [comment]
I am also experiencing this issue with 2.0.7 on 8.1.1 on iPhone 6

**Comment by FredericJacobs** [comment]
This is a known issue. In short, it's about a performance/usability tradeoff.

**Comment by abolishme** [comment]
i 100% agree that links should be signified and tappable to launch in safari
