### ISSUE TITLE
Notification of a message with only photo is empty

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#309]
The iOS notification of an incoming message containing only a photo has empty text. It says:

[quote]
Signal now
'User name' : 
[end of quote]

I suggest that - depending on the notifications settings set - an incoming photo is notified as:

[quote]
Signal now
'User name' has sent you a photo
[end quote]

Thanks again and all the best, Johan.

**Comment by FredericJacobs** [comment]
Already handling push related issues in #272
