### ISSUE TITLE
Frequently updating title of group results in app crash

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#310]
The following user behavior crashes the app:

Create a group and have several messages in it (*). Now update the name of the group several times. Use long names for the group with special characters, increasing the length of the group name (e.g #updatecrash0) At some point the app crashes. It seems random when, difficult to find a pattern. But a crash usually happens within 10-20 tries. 

Device: iPhone6,2
iOS Version: 8.1.2
Language: en (English)
Signal version 2.0.7

(*) Haven't been able to reproduce this bug with an empty group. Not sure if this is absolutely necessary to reproduce the bug though.

**Comment by FredericJacobs** [comment]
It's a side-effect of other things that were addressed. (Race condition in the DB code I believe)

Feel free to re-open if you can reproduce this again in future versions.
