### ISSUE TITLE
Inconsistent registered phone number between users

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#311]
The following results in inconsistent Signal *registered* phone numbers between users. 

Alice and Bob install Signal on their iPhones. 
Alice registers with +123
Bob registers with +321
Alice and Bob happily exchange messages
Bob wishes to uses Signal on his iPad instead of on his iPhone to communicate with Alice (Bob has not deregistered on his iPhone)
Bob registers Signal on his iPad using his iPhone's telephone nr (i.e +321)
Bob sends a new message to Alice
Alice cannot decrypt Bob's messages anymore.
Alice gets a message that new keys should be accepted from Bob (or something similar / can't remember). She accepts the new keys. 
Alice can decrypt Bob's new messages. 

So far, so good. 
However: 
- Bob's Signal app on iPad mentions +321 (his iPhone nr) as his *registered* phone number
- Alice's Signal app on iPhone mentions a totally different phone nr (+999) as Bob's *registered* phone nr with Bob's iPhone nr (+321) as his 'secondary phone nr'. The nr +999 is actually Bob's 'work' number in Alice's iPhone contacts app (and the first entry in iOS Contacts app)
- If Alice deletes Bob's +999 number in her iOS contacts, Bob's registered phone nr is still +999 in her Signal app and the number +321 is still the secondary phone nr. 

Hope this is clear, 
Best
Johan

**Comment by corbett** [comment]
is +999 a registered signal number to any device?

**Comment by JohanDoe** [comment]
No, +999 was never registered to any device.

**Comment by corbett** [comment]
ok thanks for the clarification

On Mon, Jan 12, 2015 at 9:34 PM, JohanDoe <notifications@github.com> wrote:

> No, +999 was never registered to any device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/311#issuecomment-69706023>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by JohanDoe** [comment]
Not sure if this is relevant. But after Bob deleted +999 as a tel nr from his own contact of himself on his iPad, Alice's signal app now correctly identifies Bob's registered phone nr.

**Comment by FredericJacobs** [comment]
This was addressed weeks ago. You can now tap a contact to header to see what number you're chatting with.

More advanced multiple identifier support will come later.
