### ISSUE TITLE
Swiping left on a conversation deletes without user confirmation

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#312]
In the overview of conversations if you swipe left, you see a red cross appear on the right, suggesting you should press this cross to confirm the deletion of the conversation.

However, if you swipe left 'too much' the conversation just disappears without the possibility to confirm. If you accidentally swiped a certain conversation, it is gone. 

I suggest that swiping left always allows the user to confirm the possible deletion (i.e. to press the red cross), regardless of how forceful the swipe to the left is.

**Comment by abolishme** [comment]
this enhancement will be made!

**Comment by JohanDoe** [comment]
Nice! Tx and best.

**Comment by FredericJacobs** [comment]
Fixed and implemented.
