### ISSUE TITLE
Deleting a group without reading new entries does not update unread count

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#313]
The following results in the unread count (red nr on the middle icon in the bottom) to stay on 'X' unread even though there are no unread messages anymore. 

Alice has Signal running in the background
Her friend sends her X messages in a group
Alice is notified and opens Signal, the icon below in the middle has a nice red 'X' button added to it, indicating the number of unread messages left. 
She is fed up with all these messages however and just deletes the group without 'entering' the conversation (delete via a swipe left)
No unread conversations are left, as the remaining messages were read previously. 

However: the icon in the middle below still has its nice red 'X' button, wrongfully suggesting that there are still X messages unread.

**Comment by FredericJacobs** [comment]
It would be good to have a test for groups chats. We should just [copy-paste](https://github.com/WhisperSystems/Signal-iOS/blob/e58f9bf96608fc6c959d00f927d7991b051a3a00/Signal/test/textsecure/TSMessageStorageTests.m#L74) the this test, adapt it for groups and see what's going wrong.

**Comment by FredericJacobs** [comment]
That was addressed in a refactor + tests written.
