### ISSUE TITLE
Timestamp forgery attacks

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#315]
Since we consider that timestamps are unique in the DB, and that timestamps can be chosen by the sender. We should check that storing a message does not override another message in the database. 

This has security implications.

If someone in a group for instance says something I don't like, I could send a message with the same timestamp and the original message would be erased from all the databases of the participants. This is just an example, there are many other ones.

Hence, *we need to check, before writing into the database on message retrieval on the socket* that the messageId doesn't already exist. If so, we should log the fact that there is a timestamp collision and then discard the message. With millisecond precision, unintentional collisions are very very unlikely.

Does this make sense?

**Comment by corbett** [comment]
This does make sense to me. I would say that we should bury the call in a wrapper so that it is really impossible to write a message with a time stamp with this property without checking first

**Comment by corbett** [comment]
Thanks

**Comment by FredericJacobs** [comment]
You can overwrite the `saveWithTransaction:` method on an IncomingMessage, and check if condition is match, if so, call to `super` or something like that.

**Comment by FredericJacobs** [comment]
You need to make sure that this works even in cases where we might mutate some properties of the message afterwards. (Edit the status of the message to read or add attachments to it)
That's why I suggested to sanitize the inputs directly when processing it on the socket.
