### ISSUE TITLE
Show progress when uploading a picture (video, audio)

### ISSUE THREAD

**Issue by maxbrandes** [WhisperSystems/Signal-iOS#316]
When uploading (also for downloads) a picture, signal only shows "uploading attachment". For areas with poor data coverage, it would be awesome if you also show the progress 

Further ideas
- give the possibility to cancel the upload
- Instead of only showing the text "uploading attachment", show the picture (with progress bar and possibility to cancel), so that I see what I have chosen

**Comment by corbett** [comment]
this is a duplicate issue

On Sun, Jan 11, 2015 at 11:53 PM, maxbrandes <notifications@github.com>
wrote:

> When uploading a picture, signal only shows "uploading attachment". For
> areas with poor data coverage, it would be awesome if you also show the
> progress
>
> Further ideas
>
>    - give the possibility to cancel the upload
>    - Instead of only showing the text "uploading attachment", show the
>    picture (with progress bar and possibility to cancel), so that I see what I
>    have chosen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/316>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
