### ISSUE TITLE
Feature request: Forward text and/or pictures (video, audio) to others

### ISSUE THREAD

**Issue by maxbrandes** [WhisperSystems/Signal-iOS#317]
Since I can save pictures to the phone (and resent them afterwards), why not implement a feature to easily forward pictures (video, audio) to other users or groups?

**Comment by corbett** [comment]
that sounds neat

On Mon, Jan 12, 2015 at 12:06 AM, maxbrandes <notifications@github.com>
wrote:

> Since I can save pictures to the phone (and resent them afterwards), why
> not implement a feature to easily forward pictures (video, audio) to other
> users or groups?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/317>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by abolishme** [comment]
it would have to survive a rigorous feature design discussion but maybe we should have it

**Comment by maxbrandes** [comment]
And if you decide to have it, think about implementing it in a way that allows the user to select multiple messages (text, audio, video) in a chat to forward :-)  [WhatsApp allows only forwarding one "thing" a time, Telegram let's you select multiple]

**Comment by TheStash** [comment]
Please if you are going to implement this feature, allow users to put a settings to their conversations that block their communication from being forwarded, because this would probably leak what they are communicating.

On the other hand, allow users to choose to be excluded themselves from mass-forwarding (broadcasts), which simply results in spam... to avoid this i block the user on WhatsApp, i think it would be better if i excluded myself from mass-forwarding rather than blocking all communication with this person.

**Comment by maxbrandes** [comment]
Makes no sence to disallow forwarding, because at the moment you can simply save incoming pictures and videos to your phone....so it's easy for you the afterwards forward ist --> So my feature request is just for more easier and intuitive usage of the app

**Comment by TheStash** [comment]
@maxbrandes i'm with you that forwarding is beneficial, and there are many ways people can leak your conversation that Signal doesn't protect from (Ex: taking screenshots then sending them, copy/pasting what you write, and what you've stated like saving media then sending), but those methods are workarounds that Signal could simply state are limitations they can't tackle, but sometimes one of the conversation participants intends to tell this info to only the people he is having a conversation with, so enabling this feature wouldn't make forwarding intuitive, so it will just limit forwarding and respecting user privacy needs.
