### ISSUE TITLE
2.0_0a Launch Screen for 5 & 5s

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#322]
![5s](https://cloud.githubusercontent.com/assets/3347534/5729665/0ec87fe0-9b42-11e4-912e-58ebea5c5872.png)

**Comment by corbett** [comment]
are these wrong in the current app? there are also 4 of them 
iPhone Portrait iOS8 Retina HD 5.5, 4.7, iPhone Portrait iOS 7/8 2x, Retina 4

**Comment by FredericJacobs** [comment]
If @abolishme didn't change them since november, I'm pretty sure we already have them.

**Comment by corbett** [comment]
The blue is wrong besides the designers want the naming convention fixed

**Comment by corbett** [comment]
- [ ] image needed @abolishme
