### ISSUE TITLE
2.0_1.0 Registration Screen

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#325]
![_1 0](https://cloud.githubusercontent.com/assets/3347534/5730088/6ca2d2b6-9b45-11e4-8614-59a09ebd90b2.jpg)

**Comment by corbett** [comment]
I still don't have enough information to get started here. missing assets and have no idea what the blue should be etc.

**Comment by corbett** [comment]
https://www.dropbox.com/s/upgsbbq9v09bw7s/_1.0a_signal_icon%401x.pdf?dl=0

**Comment by corbett** [comment]
https://github.com/WhisperSystems/Signal-iOS/issues/342

**Comment by corbett** [comment]
@abolishme for the Phone number section, what should we have before the user enters their number there?

**Comment by abolishme** [comment]
[ ] Status bar should be "Light" with white text
[ ] Keypad should be "Light" keypad.
[ ] Keypad should leave 36 points (i think) below the send code button [_1.0d] when pushing content up
[ ] Country Name ("United States") should reflect changes from selection
[ ] Tapping Country Code ("+1") should also open selector
[ ] Format input for north american numbers if you want to be stupid and make me happy => (xxx) xxx-xxxx

**Comment by corbett** [comment]
- [ ] error view for this (can't connect tto server for example) @abolishme

**Comment by corbett** [comment]
-[ ] Country Code ("+1")  constraints need to be updated now that it is a button @abolishme

**Comment by corbett** [comment]
- [ ] approve keyboard handling @abolishme

**Comment by FredericJacobs** [comment]
![img_0005](https://cloud.githubusercontent.com/assets/400296/5889211/227fc2ba-a3c0-11e4-9bee-1436821c90a9.PNG)

Manual code entry needs to be fixed

**Comment by corbett** [comment]
-[ ] updated on 4s?
