### ISSUE TITLE
2.0_1.0b Registration Country Code Selection

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#327]
![_1 0b_country_code_button](https://cloud.githubusercontent.com/assets/3347534/5732417/69dc65c8-9b5f-11e4-91be-3a1f98b3b0fe.jpg)
Attempt to detect the country code of the device, allow user to tap the country code to reveal a system UI selection input.

**Comment by corbett** [comment]
fonts?

**Comment by abolishme** [comment]
Country: Black, Helvetica Medium 36
Code: Global Blue, Helvetica Neue Regular 40

**Comment by corbett** [comment]
@abolishme there is no option for Helvetica Medium. do you mean Neue still?

**Comment by abolishme** [comment]
sorry, yes.
