### ISSUE TITLE
2.0_1.0c Registration Phone Number Input

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#328]
![_1 0c_phone_number_input](https://cloud.githubusercontent.com/assets/3347534/5732421/85f01c50-9b5f-11e4-82d1-d23539dffe25.jpg)
Should use detected country code to format the user-input phone number based on list of supported formatting styles. If no style is available, fallback to "XXXXXXXXX" style.

**Comment by abolishme** [comment]
Phone Number Label: Black, Helvetica Neue Medium 36
Phone Number Input: #4d4d4d, Helvetica Neue Regular 40

**Comment by corbett** [comment]
fonts? and pre-phone number enter text/font?

**Comment by abolishme** [comment]
placeholder: "Enter Number"
