### ISSUE TITLE
2.0_1.0d Registration Verification Code Button

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#329]
![_1 0d_verification_request_code_button](https://cloud.githubusercontent.com/assets/3347534/5732469/53db69f8-9b60-11e4-9f6b-d42c4ba97c26.jpg)
Should initiate the process by which a user receives a verification PIN and custom URL scheme link via SMS from the registration server.

Should advance user to the Verification screen [_1.1].

**Comment by corbett** [comment]
font?

**Comment by abolishme** [comment]
White, Helvetica Neue Medium 32

**Comment by corbett** [comment]
336 x 47
