### ISSUE TITLE
2.0_1.1 Verification Screen

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#331]
![_1 1_verification](https://cloud.githubusercontent.com/assets/3347534/5734009/ad2a4c44-9b7a-11e4-917e-ada42be325f8.jpg)
After the user has attempted to register their number, they should receive a verification pin via SMS. That pin is entered on this screen and authenticated. If successful, the user is shown the Conversations screen [_2.0].

**Comment by corbett** [comment]
missing a "send again" option

**Comment by corbett** [comment]
if you want that arrow < I will also need it as an asset, and the color.

**Comment by abolishme** [comment]
light blue: #5cb0f1
text: global blue
