### ISSUE TITLE
'Mute' button for groups

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#346]
I suggest introducing a 'mute/unmute ' button for a specific group in order to disable/enable notifications coming in to this specific group. 

Best,
Johan

**Comment by FredericJacobs** [comment]
This won't be possible with new push strategy. cc @moxie0

**Comment by JohanDoe** [comment]
Hi Frederic,

I think this is a very unfortunate from a usability perspective. My groups have >100 messages a day. I wish to be notified of one on one messages, but not of every single group message. 

From a user perspective I would say this is a severe drawback from the notification strategy. 'Mute' functionality is ubiquitous for groups in most popular messengers. 

Any way to reconsider not closing this?

Thanks

Best 
Johan

**Comment by iliketurtlesbro** [comment]
I manage a medium sized group in Telegram right now, and I would like to migrate the group to Signal, but the members of my group (and myself included) would love to be able to optionally mute notifications from said group. If this feature is not going to be possible in Signal, can anyone suggest a workaround?

**Comment by FredericJacobs** [comment]
We're working on making it possible!

This is something we want to work on but takes time to get it done right, circumventing iOS restrictions.

**Comment by skoops** [comment]
Any news on this topic? It's really annoying to be forced to enable ALL notifications if all i want is to be notified in a single conversation and not the group conversation with several dozen messages a day, which I don't need to see immediately

**Comment by danielmackey1** [comment]
I understand there's some sort of a problem with push notifications not
being specific to groups. But is it possible for the client to ignore
certain notifications or something?

**Comment by skoops** [comment]
So it seems that nobody cares about this feature, but this is a major show stopper for large user groups. When I cannot mute a mass-group-conversation for 1h/1d/7d or whatever time span, I'm not going to move the entire group into the signal ecosystem.
If you want people to use good crypto you need to provide them with good usability or they will stay with whatsapp and whatnot because somehow THEY CAN achieve these features and you can't
Signar for ios is frustrating

**Comment by bram2000** [comment]
I have to agree with skoops here. I am trying to convince a large group of Whatsapp users to move over to Signal, but the lack of "Conversation Mute" support is a showstopper for them (it's a high traffic group).

**Comment by michaelkirk** [comment]
Please don't bump issues.

**Comment by michaelkirk** [comment]
This was added a while back. Accessible via conversation settings.
