### ISSUE TITLE
Groups: add 'delete all' and 'delete selected' messages option 

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#347]
Some of my groups tend to send a lot (>100) of messages on a daily basis. 

It would thus be helpful not to have to delete all messages in a group one by one. An option that allows you to 'delete all' or select multiple messages to delete would be helpful. 

Best
Johan

**Comment by FredericJacobs** [comment]
You can hold the message bubble to delete a specific message. We won't work on multiple message selection until the next big refactoring of the messages view.
