### ISSUE TITLE
_2.0_1.0^1 Country Code Modal

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#357]
![_country_code_modal](https://cloud.githubusercontent.com/assets/3347534/5771927/589ddc52-9d16-11e4-9c90-fade93515fbf.jpg)

I can make assets for the search field if it isn't available otherwise. 

- [x] Cell height: 50pts, align text to vertical center.
- [x] "Cancel:: Global Blue, Regular 20pt
- [x] "Choose Country Code": Black, Bold 20pt
- [x] Country Name: Black, Medium 19pt
- [x] Country Code: #808080 Medium 20pt

**Comment by corbett** [comment]
- [ ] screenshot needed
- [ ] crash on search bar
- [ ] test on iPhone 5/6/6+
