### ISSUE TITLE
App crashes, when signal was totally closed and opening it via notification

### ISSUE THREAD

**Issue by maxbrandes** [WhisperSystems/Signal-iOS#359]
Crash Report: https://gist.github.com/49be67aee32fc466d4b0

Issue: signal app crashes

How to reproduce it: Close signal app completely (not available in the multitasking bar). Then receive a message an click on the notification. Signal app opens, but after seeing the logo, the app crashes.  Both lockscreen notification and notification in the unlocked status of ios are affected.

When it's working: If signal app is running in background, opening signal through notifications works

**Comment by corbett** [comment]
thanks for the report

On Thu, Jan 15, 2015 at 11:39 PM, maxbrandes <notifications@github.com>
wrote:

> Crash Report: https://gist.github.com/49be67aee32fc466d4b0
>
> Issue: signal app crashes
>
> How to reproduce it: Close signal app completely (not available in the
> multitasking bar). Then receive a message an click on the notification.
> Signal app opens, but after seeing the logo, the app crashes. Both
> lockscreen notification and notification in the unlocked status of ios are
> affected.
>
> When it's working: If signal app is running in background, opening signal
> through notifications works
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/359>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by maxbrandes** [comment]
testet it further. Calls are no problem with the procedure described above. Issue only arrises when sending messages (no groups, single chats).

Possible hint: I have set the notifications to decrypt the messages. When signal is completly closed, the messages won't get decrypted and this is exactly the way of having the app beeing crashed --> opening signal via notifications. When signal is in background, the notifications of friend A get decrypted and app wont't crash. Notifications from friend B won't get decrypted (he is sending them from an ipad2), but app don't crash...
