### ISSUE TITLE
2.0_5.0 Conversation Detail

### ISSUE THREAD

**Issue by uxyoko** [WhisperSystems/Signal-iOS#364]
![contact-details-guide](https://cloud.githubusercontent.com/assets/3347534/5848098/c45f73e8-a1a2-11e4-9492-6a46bf195c24.jpg)
![contact-details](https://cloud.githubusercontent.com/assets/3347534/5848099/c6d0dfea-a1a2-11e4-8c84-bcf03fe77e67.jpg)

**Comment by corbett** [comment]
- [ ] screenshot needed
- [ ] this view needs complete stylizing within JSQ
- [ ] test on iPhone 5/6/6+
