### ISSUE TITLE
2.0_5.1 Group Conversation Detail

### ISSUE THREAD

**Issue by uxyoko** [WhisperSystems/Signal-iOS#365]

**Comment by corbett** [comment]
- [ ] screenshot needed
- [ ] hide menu dropdown on push to this view
- [ ] confirm view OK

**Comment by corbett** [comment]
- [ ] update messages need improved @jackflips

**Comment by corbett** [comment]
- [ ] center update/leave/members vertically

**Comment by corbett** [comment]
- [ ] update call messages
- [ ] update group messages.
