### ISSUE TITLE
2.0_6.2 Active Call

### ISSUE THREAD

**Issue by uxyoko** [WhisperSystems/Signal-iOS#370]
![photo jan 21 2 12 45 pm](https://cloud.githubusercontent.com/assets/3347534/5848017/c6cb5774-a1a1-11e4-88a2-f132779a7e5d.png)

**Comment by corbett** [comment]
- [ ] screenshot needed
- [ ] add "safewords" explanation 
- [ ] test on iPhone 5/6/6+
