### ISSUE TITLE
2.0_7.0 Settings

### ISSUE THREAD

**Issue by uxyoko** [WhisperSystems/Signal-iOS#371]
![13-signal-settings](https://cloud.githubusercontent.com/assets/3347534/5812709/01fb9e86-a03e-11e4-9372-f640a9f76ef5.jpg)

**Comment by corbett** [comment]
- [ ] add an image of this view for reference

- [ ] delete account button row not resized
- [ ] Name, change, and phone number positioned incorrectly
- [ ] check on iPhone 6/6+

possibly:
- [ ] refactor to have single view
- [ ] add only the settings tyler has design

**Comment by abolishme** [comment]
Name/number/change correctly positioned, but the *row height* is being "dynamically set" @corbett

**Comment by corbett** [comment]
can we get rid of settings change @abolishme what is the use case of that vs. destroy account
