### ISSUE TITLE
Prevent telephone calls from taking priority

### ISSUE THREAD

**Issue by csoghoian** [WhisperSystems/Signal-iOS#401]
The calls I get via Signal are vastly more important than the calls I get via telephone. However, if I am on a Signal call, and someone dials my phone number, it will interrupt my Signal call for several seconds.

It would be really nice if there were a way for Signal to force all regular telephone calls to go straight to voicemail while a Signal call is in progress.

**Comment by FredericJacobs** [comment]
This would require to use CoreTelephony private APIs, and Apple would never approve that on the store. So sadly, this would be a feature only working on jailbroken iPhones.

I will however file a radar about this on Apple's bug tracking system.
