### ISSUE TITLE
Feature request: standard invite via e-mail/sms

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#402]
Please add the possibility to invite non signal users in your contacts via e-mail / sms. The 'invite' would (depending on the choice of the user) open mail or iMessage with a predefined text and link where signal can be downloaded. 

Best, Johan

**Comment by corbett** [comment]
this feature will be in place.

c

On Mon, Jan 19, 2015 at 8:04 AM, JohanDoe <notifications@github.com> wrote:

> Please add the possibility to invite non signal users in your contacts via
> e-mail / sms. The 'invite' would (depending on the choice of the user) open
> mail or iMessage with a predefined text and link where signal can be
> downloaded.
>
> Best, Johan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/402>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by JohanDoe** [comment]
Nice. Tx.
