### ISSUE TITLE
Empty bubbles after lock / unlock 

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#421]
Hi,

Sometimes when I lock my phone with signal in the foreground and then unlock it after more then 1 minute I get empty bubbles as evidenced by screenshot. These bubbles fill themselves after a short while. 

Not exactly sure how to reproduce this, as it doesn't always happen when locking / unlocking. It happens regularly enough unfortunately. 

Best
Johan
![image](https://cloud.githubusercontent.com/assets/10408552/5826797/ea3785e0-a0f5-11e4-8dd7-c5a1f31cdfb8.jpg)

**Comment by JohanDoe** [comment]
Just verified that bug also happens when switching between apps while in a signal conversation. So not only between lock/unlocking.

**Comment by maxbrandes** [comment]
Also facing this bug from time to time.

**Comment by FredericJacobs** [comment]
Haven't seen this in a while.

**Comment by maxbrandes** [comment]
Might want to have a look at this issue again. Faced it 2 minutes ago.

https://gist.github.com/5241ca7142720741596c
j.mp/signalbubble

**Comment by FredericJacobs** [comment]
That's a really old build ;)

**Comment by maxbrandes** [comment]
Faced it again. New stable build...

https://gist.github.com/b0e789168b819e755c87
www.j.mp/signal-2

**Comment by elpres** [comment]
I've had this (or something very similar) happen too. Following steps were involved:

* A friend and I have sent each other several messages
* I exited the app with that that conversation still showing
* The next day I opened Signal. The bubbles contracted visibly (I imagine iOS has stored a screenshot at exiting and showed it again for a fraction of a second upon reopening the app, which then refreshed the display). They weren't completely empty; you could still see small portions of the top parts of some letters.

**Comment by FredericJacobs** [comment]
Yeah, it's definitely the same rendering bug. I will look into it this next week.

**Comment by JohanDoe** [comment]
Maybe this helps to debug / reproduce it. I had the bug again - and noticed that signal was still 'loading': the thin blue line was visible and not finished. Once it finished the bubbles extended to the right size (still empty though). Went out of conversation and back in again and all was fine. Text appeared.

**Comment by xawita** [comment]
Still happening...

https://gist.github.com/anonymous/f325a67305158a10797b

![image](https://cloud.githubusercontent.com/assets/11395761/6792249/983292d4-d1b6-11e4-828d-e29df9123ce8.jpg)

![image](https://cloud.githubusercontent.com/assets/11395761/6792250/986718d8-d1b6-11e4-9501-c381b5483b33.jpg)

**Comment by danielschonfeld** [comment]
Does anyone have any further ideas on how to reproduce reliably ?

**Comment by askielboe** [comment]
I've found a way to reliably active these glitches using the SwiftKey keyboard - see #881. I have a suspicion that it may be related to that way the keyboard appears on the screen.

**Comment by elpres** [comment]
Can confirm custom keyboard (Swype) being in use when I've seen this glitch happen.

**Comment by nnpcYvIVl** [comment]
Happened to me again today. Was using the latest iOS release and the standard English keyboard. Still haven't found a way to reproduce.

**Comment by xortim** [comment]
About 50% of iPhone users I've tried converting to Signal have experienced this. This is a severe bug and preventing adoption of an otherwise great product.

**Comment by strugee** [comment]
From the descriptions of this happening when turning off the phone and switching away to another app - combined with the fact that it can't be reliably reproduced - it seems to me like it's happening when iOS puts the app to sleep and then it's woken up again. Could that be it?

**Comment by michaelkirk** [comment]
There were a number of reasons this could happen, but all known reasons have been addressed in the upcoming 2.19 release. Please reopen if you can reproduce.
