### ISSUE TITLE
Explain what WhisperSystems knows about Signal users

### ISSUE THREAD

**Issue by runasand** [WhisperSystems/Signal-iOS#47]
I'm not sure if this has been documented anywhere, but I would love to see a post that explains what WhisperSystems knows about Signal users. How many users there are? Where they are in the world? Real phone numbers? Who they call and when?

**Comment by corbett** [comment]
support.whispersystems.org

**Comment by runasand** [comment]
I would love to see the articles be updated with information about what you can see as well, not just what you do not have access to. Think that would be possible?

**Comment by corbett** [comment]
Sure just the place for that discussion is not in our github issues, either support or on the mailing list. We are trying to use the issues as task management. We will reopen issues as we have bandwidth to address them
