### ISSUE TITLE
can't register / different numbers, same device / error domain

### ISSUE THREAD

**Issue by peterpanondrugs** [WhisperSystems/Signal-iOS#474]
iphone4, 7.1.2

it says where you put your verfication code: 
"Error Domain=com.alamofi..."
cant receive sms or voice code.

**Comment by FredericJacobs** [comment]
Can you tell me what network you tried on? 3G? WiFi? Switch network if possible and see if that resolves it.

**Comment by peterpanondrugs** [comment]
Wifi! tried several, but didnt work...

**Comment by peterpanondrugs** [comment]
He tried different network he said. It works now. Thread can be closed. Thx.
