### ISSUE TITLE
Audio quality

### ISSUE THREAD

**Issue by hubert3** [WhisperSystems/Signal-iOS#50]
Subjective audio quality and latency is good but not as good as Facetime Audio.

Facetime Audio sounds like it uses a much higher sampling rate whereas Signal iOS sounds more like traditional 8 KHz POTS sampling rate.

Tested between two iPhone 5s, both on LTE cellular in the same location in Australia.

**Comment by indolering** [comment]
> Well, you need to be careful about those optimizations as they might result in information leaks to an attacker about who is speaking or what someone is saying.

Do you any formal analysis of this threat?  Most of the size-channel attacks I've seen on size in other areas are fairly brittle and the usability hit to Signal is pretty severe.

That being said, the command-line encoder has a [hard CBR mode](https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html) for this exact scenario.

**Comment by indolering** [comment]
> Do you any formal analysis of this threat?

I looked into this and the answer is [yes](http://www.cs.unc.edu/~fabian/papers/foniks-oak11.pdf): you can reconstruct phonemes from raw packet data.  The [Opus RFC](https://tools.ietf.org/html/rfc6716#section-2.1.8) suggests using CBR mode and changing the encoding rate based on network conditions.  This, of course, is not limited to Opus, it could be done with Speex as well.

**Comment by riyapenn** [comment]
This may belong to this other issue: https://github.com/WhisperSystems/Signal-iOS/issues/22.  User reporting of no sound on either side: 
Alice (on Android): https://gist.github.com/65217ece7eb1a154c4dd1ecf48d1cb8d
Bob (on iOS): https://gist.github.com/66fbdbd86e00a1f6ebdb0b7b7aafba2f

**Comment by indolering** [comment]
@riyapenn Yes, there are several related bugs.  This one best captures the core issue.

**Comment by Cormak** [comment]
I have a feeling that Opus isn't supported by Signal because iOS doesn't support Opus. 

It's a pity because the call quality would be so much better if we had Opus.

**Comment by indolering** [comment]
**If you are frustrated by Signal's audio quality, just star the top post.**

> I have a feeling that Opus isn't supported by Signal because iOS doesn't support Opus.

That's correct, although I doubt the Signal team would reject a PR offering protocol negotiation or software decoding of Opus on iOS.

That being said, the issues raised by @Cormak and @riyapenn have been covered at length in other tickets.  I would suggest this thread be locked to contributors to the project as no productive input appears to be taking place.

**Comment by michaelkirk** [comment]
Will be in 2.7.0

> I have a feeling that Opus isn't supported by Signal because iOS doesn't support Opus.

Opus is included in the WebRTC framework, which we're using in beta now, and will be in the app store soon.
