### ISSUE TITLE
Design consistency

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#502]
Hi,
first of all, I love Signal. And thank you for the 3534k commits you push daily.
However, there's one problem. You guys are always saying that you care about design, but there's one issue I see... Signal on iOS and TextSecure on Android have different icons. Is this intentional? I get that the different names are just temporary, but TS is now getting a new design and I was hoping to see the same icon as on iOS.
Feedback from my friends made me aware that the situation is already *very* confusing (with apps called signal, redphone, textsecure, one being able to make calls only, etc etc..), and I feel like using different logos won't help.

**Comment by corbett** [comment]
we are gradually moving towards design consistency which you will see in the latest version of the code/next beta. we will have even more consistency when the android apps merge into Signal. something we are taking care of and is on the roadmap, definitely an important consideration

**Comment by manhole11** [comment]
So which one will be the final logo? :)

**Comment by corbett** [comment]
neither
