### ISSUE TITLE
2.0 - Add people should be a tableviewheader

### ISSUE THREAD

**Issue by helveticade** [WhisperSystems/Signal-iOS#506]
Current execution could be mistaken as a search field. Will update with suggestions
![screen shot 2015-01-25 at 10 38 06 am](https://cloud.githubusercontent.com/assets/737950/5893194/c6033494-a47e-11e4-945b-c05295bdd89f.png)

**Comment by corbett** [comment]
fixed via 638dfae6682a7c00d27399985cb02386da195404
