### ISSUE TITLE
Signal (with textsecure) doesn't get notifications

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#515]
A friend of mine is testing Signal (the latest beta). The app has many bugs you've probably been solving, though I have one question. My friend never seems to get notifications when I text him. Or sometimes he gets them after several hours. Is this normal? Is this Apple's fault? Is there any setting he is supposed to change to get timely notifications? If so, you should probably tell the users what to do on their first install.
Thanks!

**Comment by FredericJacobs** [comment]
We're working on better push support. We're aware of issues and working to address those.
