### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#525]

**Comment by corbett** [comment]
did some prototyping here
https://github.com/Flipboard/FLAnimatedImage available as a pod looks good
can change TSAttachmentAdapter to display, with the caveat that at the time the data is saved if it is a GIF it should not be saved as a UIImage but rather NSData.

**Comment by j4jonathan** [comment]
Support for GIFKeyboard on iOS would be great. It would need the ability to paste the GIF in rather than attach it.

**Comment by rainerzufall** [comment]
I really think this should get more priority, since Android users have already the animated GIF support and it is a bad UX if you have features working for just one plattform...

**Comment by BoerenkoolMetWorst** [comment]
In addition to the fact that iOS users cannot send GIFs, they also cannot play GIFs sent by Android users, so perhaps this could be included in the next update.

**Comment by breakthecode** [comment]
So, when will this be available for iOS-users then?

**Comment by FredericJacobs** [comment]
@breakthecode when you do a pull-request

**Comment by mammuth** [comment]
@FredericJacobs maybe you could give some insights what's ToDo at @mikeokner 's PR (https://github.com/WhisperSystems/Signal-iOS/pull/886)

**Comment by mikeokner** [comment]
@mammuth: I got in touch with @FredericJacobs a week or two ago who said he wants support for gifs in the full-screen attachment viewer as well. I just haven't had a chance to get to it yet. Hoping to find the time in the next week or so.

**Comment by vollLASER** [comment]
I'm looking really forward to this feature. Would be the first ios Messenger with gif support as far as I know.

**Comment by FredericJacobs** [comment]
@vollLASER : I think you mean the last one ;)

**Comment by vollLASER** [comment]
@FredericJacobs  haha ;) ..yeah bad for them. You can tell with a GIF more than with 100 words ;) IMO

**Comment by michaelkirk** [comment]
Seems like this should be closed.

Resolved with: https://github.com/WhisperSystems/Signal-iOS/pull/886

**Comment by paul-schulze** [comment]
Today I (Android user) sent some GIF images in a Signal group. 

The iPhone user (iOS 9.2.1 and Signal 2.2) only sees still images while the Android users see the animated GIFs.

**Comment by michaelkirk** [comment]
Animated GIF support is not in the appstore release yet. It's in master
though, so I expect it in the next release.

Or if your friend is brave they can compile the latest Signal-iOS from
Github. =)
