### ISSUE TITLE
Bug with Rocket Emoji 🚀

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#530]

**Comment by corbett** [comment]
- [ ] write tests for emoji / unicode support focusing on characters at the beginning or end of a message as well.

**Comment by corbett** [comment]
waiting on response from bug report to google.

**Comment by FredericJacobs** [comment]
Fix deployed to testing branch

**Comment by corbett** [comment]
🚀🚀🚀🚀🚀🚀🚀
