### ISSUE TITLE
If identity key change, only have one "Identity Key Changed" message.

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#531]

**Comment by corbett** [comment]
- [ ] more generally we want a good flow for this in groups as well

**Comment by abolishme** [comment]
I need some clarification on what this means, design-wise.

**Comment by FredericJacobs** [comment]
What this means, is that if I get three messages from a contact that changed identity key, those will appear as three different conflicts.

When you tap them however, all messages encrypted with the new key you accepted will be decrypted.

**Comment by michaelkirk** [comment]
replaced by #1107
