### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by corbett** [WhisperSystems/Signal-iOS#539]
Global issue meta thread for feature requests. When a feature is requested via an issue it will be first closed (but discussion can continue there). Later when an issue warrants implementation it will be moved (reopened) to an issue of its own. This is to keep the issue feed clean. This page is intended to link to all feature requests such that they do not get lost. When they are removed from this page and closed, that means the feature is not slated for release now or in the future.

**Comment by corbett** [comment]
Feature reguest: Show shared media in one place (per chat)

**Comment by corbett** [comment]
@abolishme if you want to comment on priority of features or actually go ahead and close some issues go ahead.

**Comment by abolishme** [comment]
adding this to my list @corbett, what i'll probably do is propose milestones.

**Comment by FredericJacobs** [comment]
Will re-open those who are appropriate

**Comment by justauserid** [comment]
Is there a place where one can know what features 

- are being worked upon
- what features are on various roadmaps, release plans
- any way to vote on features

**Comment by Penguin-Guru** [comment]
I don't think this explicitly checks any of those boxes, but it seems like that sort of information is available here depending on the topic: https://whispersystems.discoursehosting.net/c/feature-requests/17

**Comment by justauserid** [comment]
Damn. I thought it was this one https://community.signalusers.org
