### ISSUE TITLE
Implement quick-reply custom dropdown

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#540]
If user recieves a message from conversation A while in conversation B, should display a custom dropdown with a truncated message. Tapping on this message should jump to conversation B, swiping down on it should expand dropdown to full message and a quick reply field, expanding keyboard.

**Comment by corbett** [comment]
it would be helpful to have a mockup of this @abolishme

**Comment by matth3w** [comment]
It looks like this was added in iOS 9, but isn't documented very well. I have found how a couple of others have implemented it here: [http://blog.thinktapwork.com/post/124915888534/ios-9-in-line-replies](url) and here: [http://fancypixel.github.io/blog/2015/06/11/ios9-notifications-and-text-input/](url)

**Comment by michaelkirk** [comment]
This is implemented using system notifications. I don't think we should implement anything beyond that, per standard platform conventions.
