### ISSUE TITLE
New beta release v2.0.11 crashes on startup

### ISSUE THREAD

**Issue by mxmerz** [WhisperSystems/Signal-iOS#558]
I installed the new release, now the app crashes on startup. If I tap on the app icon, the Signal logo is shown for part of a second and then I’m back on the home screen. Restarting app and restarting iPhone didn’t help.

iPhone 6
iOS 8.1.2 (12B440)

**Comment by FredericJacobs** [comment]
We are aware of the issue. The migration code from the previous beta has been kind of rushed, resulting in crashes in some cases. We will not spend additional time on that.

Reinstalling should work.
