### ISSUE TITLE
Broken animation when leaving fingerprint scan view

### ISSUE THREAD

**Issue by sschritt** [WhisperSystems/Signal-iOS#560]
When pressing the "X" in the fingerprint scan view (where the QR code is shown) the screen dissolves back to the message view but then at the end of the animation the gray fingerprint overlay is (correctly) shown again.

Beta release v2.0.11
iPhone 5S
iOS 8.1.2 (12B440)

**Comment by JohanDoe** [comment]
Where do I find this finger print scan view option? Was in previous release but can't find it myself in 2.0.11

**Comment by sschritt** [comment]
The key verification can be triggered by long pressing the contact's name in the navigation bar.
Sign up for free

**Comment by JohanDoe** [comment]
Aha! Tx. Was looking everywhere for it but didn't think of this. Guess it makes sense to 'hide ' this for most users.

**Comment by FredericJacobs** [comment]
Fixed.
