### ISSUE TITLE
v2.0.11 Question- what happened to contact list / key verification?

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#561]
Hi

Question - What happened to contact overview view and the key verification process that was in the previous versions? 
Will this come back?

**Comment by sschritt** [comment]
The key verification can be triggered by long pressing the contact's name in the navigation bar.

**Comment by JohanDoe** [comment]
Aha! Tx. Was looking everywhere for it but didn't think of this. Guess it makes sense to 'hide ' this for most users.
