### ISSUE TITLE
Signal logo in registration screen overlays status bar on 4'' screens

### ISSUE THREAD

**Issue by sschritt** [WhisperSystems/Signal-iOS#563]
![signalv2 0 11](https://cloud.githubusercontent.com/assets/10422786/5988390/d8167154-a966-11e4-9616-3cda596dab01.PNG)

v2.0.11
iPhone 5S
iOS 8.1.2 (12B440)

**Comment by FredericJacobs** [comment]
This is part of the 98 issues list and was assigned to @abolishme
