### ISSUE TITLE
Decoding message in notifications not possible?

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#564]
Has this setting disappeared in the New 2.0.11? I liked it. 

Or is this the 'enable screen security' feature? If so, this does not work for me. I only get 'You have new message' notification. If not, what does that setting actually do?

**Comment by corbett** [comment]
This setting is gone for now. The settings page will be improved upon

**Comment by JohanDoe** [comment]
Ok. Tx. Personally happy that this will come back. :-)

**Comment by JohanDoe** [comment]
Closing issue.
