### ISSUE TITLE
Can't destroy account

### ISSUE THREAD

**Issue by jackflips** [WhisperSystems/Signal-iOS#568]
Tried to destroy my account and get a modal error that says "Failed to unregister TextSecure component of Signal"

**Comment by jackflips** [comment]
Fixed by deleting test version of Signal that I had still installed and reinstalling the beta version.

**Comment by FredericJacobs** [comment]
What version were you running before? The one from the WBoC?

**Comment by jackflips** [comment]
I had the previous version of the beta on my phone which was overwritten by the new version, and the build from WBoC.

**Comment by FredericJacobs** [comment]
Uhm, this does appear to be the case for some people who were on the previous beta. Some issue in the migration code from last beta (won't fix). Thanks for the report though.
