### ISSUE TITLE
calls not possible in beta 2.0.11

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#570]
Since the last upgrade from beta 2.0.7 to beta 2.0.11 I can initiate phone calls, but no audio is transmitted. On the debug log I can read "Error connecting to socket Error Domain=NSPOSIXErrorDomain Code=57 "The operation couldn’t be completed. Socket is not connected""

**Comment by FredericJacobs** [comment]
Uhm, that's unrelated.
Can you email me a full debugging log: fred@whispersystems.org?

**Comment by FredericJacobs** [comment]
Ok, so something went wrong in the migration. Please re-install the app. The testing of the beta migration has been done in a rush. Sorry for the inconvenience.
