### ISSUE TITLE
former bar with socket status replaced by bar in light blue in beta 2.0.11

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#571]
Although the colour bar is not present any more in beta 2.0.11, when opening the app, a light blue bar can be seen for a second where the former socket status bar was. After a second the bar disappears 
![fullsizerender-1](https://cloud.githubusercontent.com/assets/10416484/5992216/f8179460-aa1f-11e4-9ebf-170bb1176718.jpg)

**Comment by FredericJacobs** [comment]
This is intended behaviour, not a bug.

**Comment by NicolasCGN** [comment]
OK! is then a kind of progress bar (light blue/grey) when connecting?

**Comment by FredericJacobs** [comment]
Yeah, it's intended to be really subtle and indicate progress in establishing a connection.
