### ISSUE TITLE
Make it impossible to send encrypted messages to Signal users who are on iOS

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#572]
Hello,
a friend of mine is testing Signal on iOS. I have TextSecure on Android and I have the option to send him encrypted SMSs. However, I remember that Signal on iOS only does chat messages, and doesn't manage SMSs, correct? If so, I think Android users should not be allowed to send encrypted SMSs to iOS users.
Not sure I was supposed to post this here or in the TextSecure repository.

**Comment by corbett** [comment]
There is no way for an android to know if the user it is sending to is on
iOS or Android at the moment. On Android, we will be phasing out encrypted
SMS support so this will be a non-issue
c

On Tue, Feb 3, 2015 at 9:29 AM, Manhole <notifications@github.com> wrote:

> Hello,
> a friend of mine is testing Signal on iOS. I have TextSecure on Android
> and I have the option to send him encrypted SMSs. However, I remember that
> Signal on iOS only does chat messages, and doesn't manage SMSs, correct? If
> so, I think Android users should not be allowed to send encrypted SMSs to
> iOS users.
> Not sure I was supposed to post this here or in the TextSecure repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/572>.
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Actually @mcginty should look into this. We have a "supportsSMS" flag set to FALSE for iOS users during registration and contact intersection.

**Comment by corbett** [comment]
oh, I didn't realize we had that! good point! in anywise the issue should
go away long term.

On Tue, Feb 3, 2015 at 1:35 PM, Frederic Jacobs <notifications@github.com>
wrote:

> Actually @mcginty <https://github.com/mcginty> should look into this. We
> have a "supportsSMS" flag set to FALSE for iOS users during registration
> and contact intersection.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/572#issuecomment-72739960>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com
