### ISSUE TITLE
Sending message to self duplicates message

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#573]
It is possible to send a message to yourself. If you send a message to yourself (not as part of a recipient of a group, but directly to yourself), then each message is duplicated. You receive a reply from yourself with the same text/photo.

Suggestion: disable possibility to send messages to self or fix duplicate messages.

**Comment by FredericJacobs** [comment]
This is intended behaviour. We want the user to be able to echo messages to himself.
