### ISSUE TITLE
Not possible to receive messages after change of identity

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#574]
After destroying my account and re-registering, I cannot receive messages from another iOS beta tester. I only get the error: no available session for contact.

Under Android I can end the secure session with the user and start a new one. With beta 2.0.7 I could delete all key material and start a new session. With 2.0.11 is not possible any more.

Is this a bug? or is there an option to reset the secure session?

**Comment by FredericJacobs** [comment]
Long press nav bar ==> Long press anywhere on screen ==> "Shred keying material".

**Comment by NicolasCGN** [comment]
Thanks! IMO, when the user just reads the warning "no available session for contact" doesn't know what to do and the user sending the message has no automatic feedback that the message cannot be read.

The protocol foresees sending a delivery receipt to sender when one message was read (and properly decrypted), but what about when the message was received but couldn't be decrypted?

The sender could receive a warning sign next to the message (as in iMessage) and when clicking on it be presented with the options to restart the session and/or resend the message.

Would that be feasible?

**Comment by FredericJacobs** [comment]
I'll discuss this with other Open Whisper Systems member. This is not supposed to happen (thanks to the `recipientId` property in the protocol buffers), will check what's going on.

**Comment by FredericJacobs** [comment]
Found the issue!

The bug is being addressed and clients will now prevent those messages to be sent to a wrong identity key.
