### ISSUE TITLE
Support swipe left to right to get back in navigation

### ISSUE THREAD

**Issue by abcdev** [WhisperSystems/Signal-iOS#575]
The latest beta doesn't support the expected behavior in navigation controllers.
E.g. when a specific chat is opened, swiping left to right to get back to the chat overview.

This gesture is almost essential on large devices (iPhone 5 and up) as tapping the upper left corner is a unnecessary hassle.

**Comment by FredericJacobs** [comment]
Thanks for bringing that up. It's a point that came up in many discussions with other testers too. @jlund mentioned it to me but I didn't open an issue for it.
