### ISSUE TITLE
Message received in a group chat just after updating that group hanges Signal

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#576]
I can reproduce the following problem:

I update a group chat from android (new avatar or new title) and I write ritght afterwards a message in this group chat.
When I get the notification on the iPhone and sweep it, Signal (beta 2.0.11) opens but becomes unresponsive. After killing the app and oening it again the group avatar is lost and the message sent from android ist not displayed.

**Comment by FredericJacobs** [comment]
This is not related to group chats. It was a race condition in the database code. Thanks for the report!

**Comment by NicolasCGN** [comment]
Thank you! I could also reproduce the problem when sending a photo from Android and directly afterwards 2 or 3 messages. When I open Signal the app freezes and the photo cannot be downloaded. The messages are received though.
