### ISSUE TITLE
Is avatar in inbox overview vertically centred?

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#578]
A question - not sure if it's the right place or appreciated but it's a UX issue that's been bugging me since 2.0.11. 

Can it be that the avatar in the inbox overview is not vertically centred between the two thin grey lines? But centred vertically in the row? And because the thin grey line is a couple of pixels above the row bottom, the avatar seems vertically misplaced? This is especially visible for the last row, when you have only two conversations in your inbox and thus a big grey (ugly) area as background. 

Sorry if too nitty gritty. Let me know if this kind of question / feedback is misplaced here. 

Best,
Johan

**Comment by FredericJacobs** [comment]
Wondering what @abolishme thinks of the alignement.

**Comment by JohanDoe** [comment]
Maybe it already helps if you don't have this grey background behind the rows? It's especially noticeable  for the last row when you have only few conversations and see half of the screen with grey background.

**Comment by TheStash** [comment]
I'm not sure if it is the right place to post this or not, but it has to do with the UX of the conversations view (inbox/archive); the the conversation and the name of the contact appearing in the inbox/archive views are too small for the naked eye to comfortably read, i'm on iPhone 4S so definitely those are the smallest screens supported, but i've compared it with similar screens on WhatsApp and Telegram and both use bigger fonts and are more comfortable to the eye... one more thing, they both use a higher alignment for the contact name which gives more space for text beneath.

**Comment by JohanDoe** [comment]
On iPhone 5s. I would agree with the (too small) font size comment.

**Comment by JimLoose** [comment]
![](https://cloud.githubusercontent.com/assets/195000/6543583/65e56582-c521-11e4-8b05-10a51e298cf5.jpg)

**Comment by TheStash** [comment]
@FredericJacobs did your commit fix the "the conversation and the name of the contact appearing in the inbox/archive views are too small for the naked eye to comfortably read" comment too or should i file another issue for it?

**Comment by FredericJacobs** [comment]
In 2.1 we'll be transitioning to Dynamic Type.

**Comment by TheStash** [comment]
Great, and thank you for your efforts :-)
