### ISSUE TITLE
navigation flaws and UX/UI confusion

### ISSUE THREAD

**Issue by abcdev** [WhisperSystems/Signal-iOS#579]
I've spend quite some time exploring the latest beta and took some notes concerning problems the average user will probably face in day to day usage.
iPhone5s 8.1.2 (Signal 2.0 Beta 1/31)

##### Recipient Information / Interaction
Don't hide it and enable user interaction! 
The only way to get to the contact information of a recipient seems to be:
  1. Make sure you are in a group with them
  2. Go to the members view via group info overlay
  3. Select them in the list

A far more suitable option would be to also have the "group information" metaphor in the 1 to 1 chat views.
Signal wouldn't have to hide key verification and the contact information view would be accessible in a appropriate way. The overlay could state something like: [  Call  Verify  More   ]

Users expect to find buttons with the same function at the same places.
I have noticed that calling a Signal v1.0.8 / Redphone only user leaves the chat view with the call icon in the upper right corner. Doing the same with an Signal 2.0 or android user that uses both, textsecure and redphone, the call icon is visible as long as I don't type anything in the textfield. Placing a call requires you to either:
- Delete your input
- Go back to the Inbox pretending you want to start a new conversation and press the call icon

(your input will be lost either way see "Keep state (keyboard text input)")

##### Branding < Usability
The Signal icon can't be part of the navigation stack!
This is the first serious iOS project I have seen where the app icon is used in the navigation stack and as view title.
The available main views are the "Inbox" and "Archive" (or other suitable strings) but not an icon.
*Q: If i have a chat view open already where will I end up if i tap the signal icon back button?*
The navigation stack is not made for having a nice translation only. It's main purpose is providing information about where we're coming from and going to. Otherwise you could use a modal view without a semantic difference.

Another point is the textsecure send icon vs "Send" as string but I will bring that up in  #577

##### Keep state (keyboard text input)
It is very disturbing to lose unfinished inputs when switching between chats. While every serious "competing" messaging app and the system app keeps it.

**Comment by abolishme** [comment]
> A far more suitable option would be to also have the "group information" metaphor in the 1 to 1 chat views.

believe it or not, this was in a previous version, and for some reason this was taken out over WBOC. it will return in a future release.

**Comment by abolishme** [comment]
> Placing a call requires you to either:

> Delete your input
> Go back to the Inbox pretending you want to start a new conversation and press the call icon
(your input will be lost either way see "Keep state (keyboard text input)")

You are absolutely right. Another deviation from the design that i really can't explain, but the call icon will be moving to the upper right of the navigation bar for this release. In a future release it will be in the 1-to-1 options dropdown.

**Comment by abolishme** [comment]
> It is very disturbing to lose unfinished inputs when switching between chats. While every serious "competing" messaging app and the system app keeps it.

as far as i'm concerned, that's a bug.

**Comment by FredericJacobs** [comment]
Working on saving drafts.
