### ISSUE TITLE
Remove audio stretch buffer padding when upstream fix is completed

### ISSUE THREAD

**Issue by Strilanc** [WhisperSystems/Signal-iOS#58]
This issue represents the [note in AudioStretcher.m](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/audio/incall_audio/processing/AudioStretcher.m#L39) that defensive padding of a buffer can be removed when a bug is fixed in spandsp.

**Comment by FredericJacobs** [comment]
@Strilanc: Any updates yet?

**Comment by Strilanc** [comment]
No updates yet.

**Comment by FredericJacobs** [comment]
@Strilanc : I assume the upstream fix is unlikely to be published?

**Comment by Strilanc** [comment]
I agree.
