### ISSUE TITLE
No connection when trying to call RedPhone from Signal-iOS

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/Signal-iOS#587]
I tried to call my RedPhone on Nexus 5 with Cyanogenmod Snapshot M11 from Signal-iOS on iPhone 4S with iOS 8.1.3 but never got connected. 
The Call Timed Out with the Message: 
2015/02/10 12:37:08:999  Recipient unavailable: (null), 1

I the opposite direction (RedPhone->Signal-iOS) there is no Problem. The phone rings shortly after calling and everything works fine.

I also tried to re-register my RedPhone Number but nothing changed.

**Comment by moxie0** [comment]
For support questions please use the support center: http://support.whispersystems.org
