### ISSUE TITLE
Connection speed

### ISSUE THREAD

**Issue by maxbrandes** [WhisperSystems/Signal-iOS#588]
When opening or reopening signal, it needs quite some time till the app has connected to the server and till I am able to read the new messsage...

Is that something you also face?

iPhone 5s/Vodafone DE, no difference between 3G/4G and WiFi.

**Comment by FredericJacobs** [comment]
The WebSocket Secure handshake is a regular TLS handshake and can take some time before establishing the websocket connection. This is normal.

**Comment by maxbrandes** [comment]
Thanks to the update 2.0.1, (at least) the perceived speed good improved :+1:
