### ISSUE TITLE
Codebase cleanup

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#610]
After a few weeks long rush, I'm planning to do some code cleanups, especially in the view controllers that have been re-designed three times and have a bunch of unused code too.

Planning to gradually add small refactorings to the https://github.com/WhisperSystems/Signal-iOS/tree/unused_and_cleanups branch and then merge it in a week or two.

**Comment by abolishme** [comment]
Also, could @FredericJacobs and I go through at some point and consolidate the view controllers to play nicely with the naming conventions I've built? Then I can go through and build some design documentation for future collaborators and refer more clearly to each view/segue etc.

For reference, here is [some beta documentation](https://www.pixelapse.com/openwhispersystems/projects/signal-ios/views/--2/assets/docs/nomenclature.md) I'd like to finalize and make more available to contributors.

**Comment by FredericJacobs** [comment]
I guess this will be incremental
