### ISSUE TITLE
Port MessagesViewController to Atlas

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#617]
Investigating switching to [Atlas](https://atlas.layer.com/) for better performance and features and we know for sure that it's going to be maintained. Licenses are compatible.

**Comment by corbett** [comment]
Ah looks promising

**Comment by chrisballinger** [comment]
Unfortunately Atlas pulls in Layer's binary blob SDK (LayerKit) as a hard dependency.

**Comment by FredericJacobs** [comment]
@chrisballinger I quickly looked at it but I think you can easily use Atlas without LayerKit (that we obviously don't need).
