### ISSUE TITLE
Feature Request: More Visual Differentiation for Unsent Messages

### ISSUE THREAD

**Issue by ussjoin** [WhisperSystems/Signal-iOS#622]
For messages that aren't being delivered, it displays in a light blue, but doesn't indicate

* What happened (it's not clear that it's unsent)
* Why it happened
* That I can resend

Tapping on it indicates that I can resend, and that's the first visual indication I have that the message is actually broken. But no idea why.

Suggestion: iOS Messaging has a big red exclamation mark that is tappable when messages are not sent. Use that, or something prettier in line with your design ideas.

**Comment by riyapenn** [comment]
Similar: https://github.com/WhisperSystems/Signal-iOS/issues/860
