### ISSUE TITLE
Website doesn't mention Signal

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#623]
It's been a while since Signal was released, and now that it became Signal 2.0 it is extremely important that it gets some visibility on the website's home page.
I've heard a new website is "being worked on", but even after winter break of code I can't see what "work" has been brought forth. Not a hater, just an observer.

**Comment by FredericJacobs** [comment]
Same as #620

**Comment by manhole11** [comment]
Uhm, no?

**Comment by FredericJacobs** [comment]
I meant same as https://github.com/WhisperSystems/whispersystems.org/issues/40
