### ISSUE TITLE
Unable to initial phone call with text partner.

### ISSUE THREAD

**Issue by dav92178** [WhisperSystems/Signal-iOS#627]
I'm unable to initiate a phone call, but I was able to receive a call from the other side. What can I do to help troubleshoot this issue?

I think it could be an issue related to having Google Voice integrated.

1) I have an open text conversation with the other person.
2) Text messages are flowing freely without any issue between us.
3) I am unable to initiate call; when pressing the phone icon, nothing happens on my side.
4) When the other person initiates a call, it is connected nearly instantaneously.

Please do not close this again w/ out actually trying to fix/troubleshoot my issue. I'm fairly technical and offering to run through a few scenarios to get this functional for others that could experience the same issue. If you're unfamiliar w/ Google Voice and the associated technological limitations that it can impose, then please allow someone else who is more experienced assist me with this.

Thank you!

**Comment by FredericJacobs** [comment]
This was probably fixed with time. Probably due to bloomfilter synching latency.
