### ISSUE TITLE
Aim for iOS 7.1 backward compatibility?

### ISSUE THREAD

**Issue by mro** [WhisperSystems/Signal-iOS#629]
I know it may sound odd, aiming to support a device as old as the iPhone4, but it's about millions of devices out there in the wild which can't update to iOS 8.0.

How are you guys feeling about that?

**Comment by acoffman** [comment]
This looks like a dupe of #614 and the answer seems to be "no."

**Comment by alex42ka** [comment]
Would be really great. It's the most substantial argument against TextSecure as our main Messaging App at work.

**Comment by FredericJacobs** [comment]
Discussion happens in #614
