### ISSUE TITLE
microphone permission alert repeats on start = annoying

### ISSUE THREAD

**Issue by JimLoose** [WhisperSystems/Signal-iOS#630]
**Case**
Some user never give any app microphone permissions and like to use Signal for Messaging only.

**Problem**
Every app-start triggers the following message (with forced confirmation)

![img_8598](https://cloud.githubusercontent.com/assets/195000/6453420/fdfd8ea4-c13d-11e4-8541-5248a451d3c6.PNG)

**Solution**
- show a light info message in the phone tab + directly switch to the messaging tab :-)
- trigger this message only once :-)

**Comment by FredericJacobs** [comment]
Thanks, we will address this in 2.0.2 along with a revamped management of permissions.

**Comment by JimLoose** [comment]
Hint: you can directly link to the microphone settings (if it is deactivated) - to give user a quick link to toggle these settings!

Some user have deactivated access to the microphone temporary to prevent apps like Shazam to use backdoors and activate it.
