### ISSUE TITLE
Add comment field grows without limit 

### ISSUE THREAD

**Issue by manishvij** [WhisperSystems/Signal-iOS#633]
1. Create new message
2. Tap comment text field 
3. Tap return button several times 

Result: height grows unbounded 
Expect: limit to n lines == half the view height minus keyboard height

**Comment by FredericJacobs** [comment]
This is intended behaviour, not a bug.

**Comment by manishvij** [comment]
Odd design: blocks view, blocks scrolling. Can't refer back to message. Breaks what worked before returns.

**Comment by FredericJacobs** [comment]
Same behaviour as iMessage?

![img_1094](https://cloud.githubusercontent.com/assets/400296/6462460/acb01992-c1a9-11e4-9c84-5301c497f63b.PNG)

**Comment by manishvij** [comment]
BRB, filing a Radar with Apple ;) WhatsApp, Instagram and Vine limit height, but this is low pri, I agree. Thanks for having a look.
