### ISSUE TITLE
Don't force banner and sound notify 

### ISSUE THREAD

**Issue by manishvij** [WhisperSystems/Signal-iOS#634]
1. iOS home - Settings - Notifications - Signal
2. Turn off banners and sounds 
3. Switch to Signal

Result: repeated UIAlertViews
Expect: you don't need these permissions and I leave them off for iMessage too (hate interrupts). I leave badges visible and keep app on home screen.

**Comment by samer** [comment]
:+1: Came here to report the same thing.

**Comment by FredericJacobs** [comment]
Same as #630
