### ISSUE TITLE
Tab icons have poor usability  

### ISSUE THREAD

**Issue by manishvij** [WhisperSystems/Signal-iOS#635]
Default tabs are a blank circle when no read messages (incomprehensible) and a check mark (implies either Ok or a status saying something was done). 

Should be a home icon with a badge, and a list or clock or history or folder icon.

**Comment by helveticade** [comment]
+1 on this. And to extend:

- No badging on archived tab makes the tabs hard to understand.
- Both tabs have similar shape/silhouette and can't be read at a glance.
- Neither tab uses any visual cue to explain itself.
- Lack of text label decreases readability.
- Archive tab looks more like a todo list icon than an archive.

**Comment by CameronBanga** [comment]
+1. Does archive need as prominent of a button? Maybe I'm just odd, but don't see it as being that prevalent, especially in a chat app designed around security.

**Comment by cdroms** [comment]
+1 ^^^ re: archive button

**Comment by rocknjohn** [comment]
Linking to related issue: https://github.com/WhisperSystems/Signal-iOS/issues/675 where I suggested removing the archive to improve usability or if the archive is kept to at least hide both the inbox and archive buttons when no conversations exist, so the user isn't shown buttons that don't do anything.
