### ISSUE TITLE
New conversation icon is confusing

### ISSUE THREAD

**Issue by cdroms** [WhisperSystems/Signal-iOS#636]
A suggestion would be to make the 'new conversation' icon a 'compose icon' as opposed to a '+' icon. The '+' icon is usually reserved for adding new contacts, thus it was confusing for me when I first loaded the application.

**Comment by derekhardwick** [comment]
Similarly, to add a group I click on the plus icon, then "group plus" icon, then the plus icon again.  That final plus should maybe be 'done', 'create', or checkbox icon.

**Comment by abolishme** [comment]
The plus icon is going to stay. Some peers that also use plus to initiate private conversations: instagram DMs, Twitter DMs, Pinterest DMs.
