### ISSUE TITLE
Too many important features hidden behind unclear tap and hold gesture. 

### ISSUE THREAD

**Issue by CameronBanga** [WhisperSystems/Signal-iOS#637]
On iPad, apologies for crummy short issue, but it seems as if too many important tasks in the app are hidden behind a vague tap and hold gesture. 

Viewing fingerprints requires holding on the conversing parties name, and shredding keying material by holding the overlay. These are two of the most important features of the app, and I got lucky to find them. Should ideally be more obvious as to how to perform these actions.

**Comment by corbett** [comment]
They are designed to be hidden currently, unlocked by advanced users. The
design may be changed in the future.

C

On Mon, Mar 2, 2015 at 9:17 PM, Cameron Banga <notifications@github.com>
wrote:

> On iPad, apologies for crummy short issue, but it seems as if too many
> important tasks in the app are hidden behind a vague tap and hold gesture.
>
> Viewing fingerprints requires holding on the conversing parties name, and
> shredding keying material by holding the overlay. These are two of the most
> important features of the app, and I got lucky to find them. Should ideally
> be more obvious as to how to perform these actions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/637>.
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by pkirkovsky** [comment]
@corbett What's the reasoning behind hiding these features? Key verification using an out-of-band method is one of the first things users should perform when setting up secure communications. In fact, key verification is emphasized and displayed prominently by other secure chat methods (e.g. OTR via Adium).

**Comment by 2-4601** [comment]
See the development ideology: https://whispersystems.discoursehosting.net/t/development-ideology/26

Best place to continue this discussion is probably at https://whispersystems.discoursehosting.net/c/development

**Comment by michaelkirk** [comment]
The hidden longpress gestures have been removed and replaced with explicit menu items.
