### ISSUE TITLE
Some contacts listed twice in group member list

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [WhisperSystems/Signal-iOS#639]
On signal for iOS some people are listed twice in a groups member list. For the same group the list appears fine in TextSecure on android.

Also this behaviour is not constant. A person that used to appear twice suddenly was only listed once and a new person appeared twice.

All double people use iOS.

**Comment by FredericJacobs** [comment]
Fixed in the build that was sent yesterday to Apple!
