### ISSUE TITLE
User can't sync with the directory but can exchange encrypted messages

### ISSUE THREAD

**Issue by zmanian** [WhisperSystems/Signal-iOS#640]
Fresh install.

Sending a message from an Android user doesn't force the user directory to sync?

![textsecure-2015-03-02-222141](https://cloud.githubusercontent.com/assets/93434/6457658/dfccc216-c12d-11e4-8754-1d6c4b4f84b6.png)

User reports directory sync seems to be failing pervasively.

![textsecure-2015-03-02-221702-1](https://cloud.githubusercontent.com/assets/93434/6457734/df3b9808-c12e-11e4-8587-a1e7f19f03d9.png)
![textsecure-2015-03-02-221801](https://cloud.githubusercontent.com/assets/93434/6457736/e07f22ac-c12e-11e4-8cc3-3ea1b06ca5c2.png)

**Comment by vingtdeux** [comment]
This was reported under #620. It seems like the 2nd message goes through/syncs the contacts.

**Comment by zmanian** [comment]
This user isn't seeing any contacts sync. New message window while we have an active chat.

![textsecure-2015-03-02-231358](https://cloud.githubusercontent.com/assets/93434/6457937/462d8618-c132-11e4-90b1-7be480e2a4fc.jpeg)

**Comment by vingtdeux** [comment]
Ah, sorry about that, I missed the line of text between the images; looks like 620+.

**Comment by FredericJacobs** [comment]
See #620
