### ISSUE TITLE
Granular settings for notifications

### ISSUE THREAD

**Issue by samer** [WhisperSystems/Signal-iOS#643]
It would be great to be able to toggle notifications separately for individual chats, group chats and most importantly, voice calls. As an example of how that could be implemented from a UX / UI point of view, here is how whatsapp does it:

![20950116-en-01](https://cloud.githubusercontent.com/assets/554078/6459980/1bb4a410-c19c-11e4-9cce-d073285ff202.jpg)

**Comment by vv01f** [comment]
additionally per-user would be nice, if possible with the setting from ios conacts
but I guess this is locked away

**Comment by FredericJacobs** [comment]
This is technically really difficult to achieve in a safe way. I'm going to write a post on this and add it here when published.

**Comment by FredericJacobs** [comment]
Fix merged in master!

**Comment by Geblaat** [comment]
Working nice :) It Would stil be interesting to have a blog post on this ;)

**Comment by samer** [comment]
@FredericJacobs: as outlined in the first message, would it be possible to toggle notifications separately for individual chats, group chats and voice calls?

**Comment by FredericJacobs** [comment]
@samer: We're going to roll out fine-grained notification settings over time.
