### ISSUE TITLE
Add a force language setting

### ISSUE THREAD

**Issue by fabriceroux** [WhisperSystems/Signal-iOS#645]
I did my best to translate Signal strings from english to french. I want to believe I have the proper technical background to do this translation (technology, cryptography,...).

But in some cases, I was unable to imagine the app context to bring the best translation. In these cases, I aimed for the middle ground between two (or more) possible translations.

It would be great to have a setting to force the language. A setting in Settings / Signal / Signal settings would do the trick. By default it should be set on "Obey system settings".

**Comment by vv01f** [comment]
as there are updates for ranslations that may be included soon this sounds like a natural thing to do now :)

**Comment by FredericJacobs** [comment]
Not going to happen. Change your phone language instead to test the given language.
