### ISSUE TITLE
Delivered and read messages

### ISSUE THREAD

**Issue by gonzalezb** [WhisperSystems/Signal-iOS#651]
It would be nice to see you add a small delivered to the bottom of a message when it gets delivered and a option to use read when the user reads said message.

**Comment by thenktor** [comment]
There is a "delivered" notification at the bottom of **all** messages, but I agree that this should be shown independently for **each** message.
About the read notification: read here https://github.com/WhisperSystems/TextSecure/issues/957

**Comment by FredericJacobs** [comment]
The delivered tag is done like in iMessage. I don't think we want read receipts, at least for now.

**Comment by thenktor** [comment]
Indeed, just noticed it :+1:  I actually don't use iMessage, I'm used to TextSecure and Threema ;)

**Comment by FredericJacobs** [comment]
We're sticking to this design. No read receipts for now.

**Comment by thomasrive** [comment]
An option for "sending read receipts" with the default being off would allow people to choose to send read receipts while respecting users privacy.
