### ISSUE TITLE
Make 'archive' optional or remove altogether?

### ISSUE THREAD

**Issue by joostrijneveld** [WhisperSystems/Signal-iOS#652]
I spoke to several people who had been greatly anticipating Signal today, but none of us really understood the problem the 'archive' functionality is trying to solve. It is one of the most prominent UI elements, as it has resulted in a full-width bar with two mysterious dots in the 'Conversations' view, as well as swipe actions when dragging conversations, but it's purpose is quite unclear.

I personally do not know of any other messaging apps that have this feature, and I cannot think of a reason why they should. Does a typical Signal user really have so many conversations open that they would need an archive? What is the argument against having inactive conversations simply snow under and be pushed down the list as more active conversations move to the top? I vaguely recognise the 'Inbox zero' idea here, but that does not really seem to fit a messaging app.

Perhaps it is worth considering making this feature optional, or, for the sake of simplicity, removing it altogether.. In any case, I'm very interested in the design rationale behind this one.

**Comment by helveticade** [comment]
+1

**Comment by cdroms** [comment]
Considering that the default 'Messages' app doesn't even have an archive feature, it does come across as a generally confusing concept. Using 'Messages', you don't archive messages as soon as you've read them, you just keep them in the same thread/conversation and go back through that thread if you need to find it again.

There's also the thought that a lot of Signal users wouldn't want their messages archived anyway, for security reasons. It seems to be go against the grain of what Signal is about as a whole.

Can anyone who's apart of building the app clarify why this feature exists, maybe I'm missing something? :/

**Comment by abolishme** [comment]
Signal's "archive" (which would be more clearly described as inactive conversations) is the same thing as the native Messages app's list of messages. Signal's "inbox" view is just a layer on top of that idea which functions as a more effective implementation of what many apps consider "favorites". 

You can think of signal's inbox as a kind of hub for all of the conversations you're interested in referring to in the present. There are reasons why we might want more than just unread messages to "float to the top": maybe we know someone texted us an address last month and we want to refer to it a few times today, or maybe I remember I wanted to talk to my mom, but it's 3 am and i should wait to call. Or maybe i'm just always talking to my roommates ... the inbox serves as a kind of "pinned conversation" so you don't have to scroll through many conversations every time you want to reopen a dialogue with someone.

Right now, the feature set for this paradigm is relatively bare, but on the roadmap are lots of powerful tools, and we're planning on moving forward in that direction.

For users who wish to delete a conversation, it's simple: swipe left to delete just like most native iOS apps.
