### ISSUE TITLE
Unclear that it won't work without access to contacts

### ISSUE THREAD

**Issue by rvwise** [WhisperSystems/Signal-iOS#653]
It looks like message replies can't be sent if the app doesn't have access to contacts. It says "User is unregistered" (which could be myself or the user I'm sending to BTW). The dialog that asks for access to contacts should say that it's a prerequisite for replying to messages.

**Comment by FredericJacobs** [comment]
Fixed in https://github.com/WhisperSystems/Signal-iOS/commit/c95f190140ba00048983d07289082e497d702947
