### ISSUE TITLE
Messages displayed out of sequence due to clock skew

### ISSUE THREAD

**Issue by hubert3** [WhisperSystems/Signal-iOS#655]
A friend messaged me at 15:50 but his message was dated 15:57 (7 minutes in the future).

I don't know if this is due to clock skew on his iPhone or on a Whisper Systems server.

My reply to him (correctly dated 15:50) was then displayed ABOVE his initial message to me, as if I had initiated the conversation, which was confusing.

It would seem to make most sense to use the time a message was received as the displayed timestamp and also to determine the order messages are shown in.

**Comment by FredericJacobs** [comment]
Thanks, the fix has already been submitted to Apple. Merged in codebase as 7aad5c5971f9305fd4be7905e38b7d9fd10d12c6
