### ISSUE TITLE
Show number of unread messages per conversation

### ISSUE THREAD

**Issue by thenktor** [WhisperSystems/Signal-iOS#657]
IMHO it would be better to see the number of unread messages for each conversation. At the moment the difference between read and unread conversations is just the colour of the text: black vs. grey (IIRC). So an unread message easily is missed.

**Comment by FredericJacobs** [comment]
We previously had this in the design then was lost in a redesign. I do agree that a better indication of unread messages would be helpful.
cc @abolishme

**Comment by abolishme** [comment]
Working on a design solution for this.

**Comment by michaelkirk** [comment]
Do you mean showing it in the index like this:
![image](https://cloud.githubusercontent.com/assets/217057/14499526/86621ab6-0153-11e6-947d-8a0ac1935bf8.png)

Or do you mean something once you're IN the thread?

a'la gitter
![image](https://cloud.githubusercontent.com/assets/217057/14499692/28d7b580-0154-11e6-98ad-9bed52bf2970.png)

**Comment by FredericJacobs** [comment]
Back in Mar 2015, we didn't have that index already.

This issue has been addressed.
