### ISSUE TITLE
Attempt to send text and image together sends image only (text is deleted)

### ISSUE THREAD

**Issue by vingtdeux** [WhisperSystems/Signal-iOS#670]
To reproduce: 
1. Type text into New Message field, hit return (not send)
2. Tap the paperclip, select a photo
...the photo is sent and the text disappears.

I see "text and image together (android has capability of sending)" from #439 as being in 2.0, but I haven't been able to send both at once. I also tried selecting a photo first to see if I could add text after, without success.

If users aren't supposed to send both at once, disabling the paperclip once the text box is non-null would be more user-friendly. However, being able to send both would be preferable!

**Comment by FredericJacobs** [comment]
It's already fixed in 2.0.1 that's been submitted to Apple.
