### ISSUE TITLE
Suggest changing "Destroy Account" to "Delete Acccount"

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#674]
After showing the app to a non-technical user I guided them on how to delete their account while we were troubleshooting. Their response: "I'm scared to click Destroy Account". When I tell them it means Delete Account, they say "Oh OK".

"Delete Account" is more familiar language and would make the app feel easier and more accessible to the broadest possible audience.

**Comment by FredericJacobs** [comment]
@abolishme is in charge of wording, I will let him comment.

**Comment by fabriceroux** [comment]
To remove all doubt you might want to go to "Delete my account". As in this function doesn't destroy other users accounts.
