### ISSUE TITLE
Remove archive to simplify UI

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#675]
The UI would be much easier to use and understand if it just had an inbox and not an inbox and an archive.

Please don't take it the wrong way. I love Signal.

I'm a technical user and when I first tried the app and there was an empty conversation list I was clicking the empty blue dot (like what does that mean?) and the checkbox and seeing nothing change. A similarly technical Tor contributor described the UI as "confusing". I think it really comes down to the inbox vs archive.

The UI could be greatly simplified if it only had an inbox. This is the simplest UI possible and is widely used and understood by users (iMessage, Facebook messenger, What's App, etc). The confusion of the archive seems to outweigh the benefit it intends to provide.

If you keep the archive, please hide the two icons at the bottom of the screen if there are no conversations yet so new users are better guided to the "+" to create a new conversation instead of being given the option to click buttons that don't do anything.

**Comment by moxie0** [comment]
Please check existing issues before opening new ones.
