### ISSUE TITLE
Settings have technical terms

### ISSUE THREAD

**Issue by CoolkcaH** [WhisperSystems/Signal-iOS#678]
This is supposed to be a user-friendly app.
The screen security option makes no sense, should be default and not an option, confuses users.

I'm helping with the translation and "fingerprint" is also confusing to users and hard to translate, especially since iPhones have real fingerprint sensors now.
Users don't and should not need to know what a hash is.
It should be called public key or just key.

And it should have clear instructions explaining what it's for...the screen privacy has a sentence explanation that shouldn't be there, but the fingerprint which is more important is not even explained?

Also the ui is inferior to whatsapp but that's another matter.

**Comment by moxie0** [comment]
Hey @CoolkcaH, a four paragraph opinion piece is not particularly useful for us.  Remember, our time is limited, and every time you file an issue, you're creating an email for us to read and process (even when you open an issue with half a subject line, then immediately close it).

What we'd really like here are bugs with precise steps for reproducing.  If you'd like to discuss features, the best place for that is the mailing list.  For what you're talking about here specifically, we're not idiots, and we have a roadmap for where we're going with it that I hope you'll be satisfied with in due time.
