### ISSUE TITLE
Video calls

### ISSUE THREAD

**Issue by micahflee** [WhisperSystems/Signal-iOS#68]
I think it would be great if there were plans to include video calls in Signal, as well as voice and text.

Video calls are one of the nicest features that Silent Circle offers, and as soon as Signal is released for Android and the browser it will be so close to making Silent Circle obsolete.

**Comment by Calefornia** [comment]
What would it take for video calls to be added within a year? Given Signal's rise in popularity, it might be worth revisiting this feature. Thanks!

**Comment by michaelkirk** [comment]
Public in the 2.8.* release.
