### ISSUE TITLE
add/switch to 24h timeformat

### ISSUE THREAD

**Issue by noelk** [WhisperSystems/Signal-iOS#680]
Hello,

the timeformat should be 24h because it is the most common.

https://en.wikipedia.org/wiki/24-hour_clock

Thank you.

**Comment by FredericJacobs** [comment]
Hey @noelk,

The timestamp should show it in your phone's locale.
If that's not the case, it's likely a bug.

Is your phone set to a locale using 12h timeformat?

**Comment by noelk** [comment]
Hello,

locale is de_DE and the time format is 24h. Other apps (messages, threema) show the 24h format only signal show the 12h format thats why I reported it.

thx.

**Comment by abcdev** [comment]
I can confirm that 12h timeformat is applied if:
Language and advanced region language is set to de-DE and Locale is en-US.

I wouldn't consider this being an issue. It is strange that even system apps apply 24h timeformat even though locale/region is en-US. Seems like the **advanced** setting for the region is changing the timeformat / number formatting.
This should be an issue in the JSQMessagesViewController project. JSQMessagesTimestampFormatter class for the curious.

**Comment by noelk** [comment]
My language and region setting are all set to de-DE.
I tested it some more and in a conversation with somebody the timeformat is 24h but in the conversations overview I have 12h (e.g.10:01 vorm. = a.m.)

**Comment by fabriceroux** [comment]
With the region/language France/french and the standard 24h timeformat, Signal shows 12h timestamps.
