### ISSUE TITLE
Phone icon appears in conversations with non-voice contacts

### ISSUE THREAD

**Issue by vingtdeux** [WhisperSystems/Signal-iOS#682]
To reproduce:
1. Scroll through list of contacts until you find one without a phone icon (I'm making the assumption that these are correctly indicative of TextSecure only users)
2. Start or continue a conversation with the contact
3. Note the phone icon at the top right of the screen

I verified that there is no functionality attached to it (other than the visual feedback that it was selected).

**Comment by FredericJacobs** [comment]
This is fixed in 2.0.1 that has been submitted to Apple 5 days ago.

**Comment by vingtdeux** [comment]
Are there 2.0.1 release notes somewhere that I'm missing? I've been searching open and closed issues before submitting new ones. I don't want to waste your time with stuff that has already been addressed; should we just hold off on reporting things until the update becomes available?

**Comment by FredericJacobs** [comment]
Here's the list of closed issues.
https://github.com/WhisperSystems/Signal-iOS/issues?q=milestone%3A2.0.1+is%3Aclosed
