### ISSUE TITLE
Calling ourselves crashes signal

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#684]
I tried to call myself and it crashed Signal, i'm not sure if there is a use case which would utilize calling yourself but at least the app should not crash.

**Comment by JimLoose** [comment]
works flawless in my case (says user busy)

Signal 2.0
iPhone 6
iOS 8.1.3

**Comment by FredericJacobs** [comment]
Hi @TheStash,

I'm unable to reproduce this. Can you email me a crash log?

Thanks,

Frederic
Help for crash logs: bjango.com/help/crashlog/

**Comment by TheStash** [comment]
I'm sorry but i've made a factory reset after posting this bug and the earliest crash report is on the 13th of this month, i've also tried to reproduce and it worked pretty well giving me a busy tone, so feel free to close this issue.

Many thanks.
