### ISSUE TITLE
Registering new phone with same number crashes app

### ISSUE THREAD

**Issue by paintedbicycle** [WhisperSystems/Signal-iOS#685]
Can't access Signal after upgrading phone:

- Just traded in iPhone 5.
- Deleted all content and settings without "Destroy Account".
- Restored content to new phone via iCloud backup.
- Signal didn't sync account, so had to register again.
- App crashes when entering phone number (iPhone 6).

Any way to use the app with this phone number?

**Comment by FredericJacobs** [comment]
We don't support iTunes backup and restore.

Can you email me the crash logs: fred@whispersystems.org
bjango.com/help/crashlog/

**Comment by paintedbicycle** [comment]
See fix: https://github.com/WhisperSystems/Signal-iOS/issues/746
