### ISSUE TITLE
Twitter access not working 

### ISSUE THREAD

**Issue by n13** [WhisperSystems/Signal-iOS#687]
Signal never asked me to connect to Twitter. 

I tried to post on Twitter using the button in settings / about. Got error message that connection to Twitter failed

The app is not allowed to talk to Twitter because it never asked... doesn't show up in the privacy/Twitter settings either.

**Comment by kiliankoe** [comment]
It should work even though it doesn't show up in the system settings. Maybe your connection to Twitter was wonky?

Signal seems to just share content to the system Twitter share extension (if that's what it's called) and not try to post on its own. It shouldn't need its own access for this as far as I can tell.

**Comment by FredericJacobs** [comment]
Hi @n13,

I don't think this is an issue with Signal. It does seem that your Twitter account is not properly connected in the settings.

In the settings app, make sure that under the Twitter section, you have at least one account set up.

**Comment by n13** [comment]
Hi @FredericJacobs - No, that's not it, I have several other apps that show up in my Twitter system settings, and that can post on Twitter. Instagram, and a few others. Signal doesn't even show up in that list which made me think it never requested permissions. As, if I had accidentally denied permission, it would still be in the list, only turned off. But it's not in the list at all.

**Comment by n13** [comment]
Also AFAIK if this app was the first to request Twitter connectivity, then the system would guide me through the steps to set it up.

**Comment by FredericJacobs** [comment]
Sounds more like an iOS bug than a Signal one.
