### ISSUE TITLE
Make it easier to invite non Signal users

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#688]
This is somehow inspired by Android implementation, but since Signal on iOS doesn't support Encrypted SMS/MMS, When i hit the "New Conversation" button why don't you show the list of "Signal users" and "Non-Signal users" and beside every "Non-Signal user" an invite button instead of the call button beside "Signal users", this should help make the invite process seamless and drive more invites.

**Comment by FredericJacobs** [comment]
Agreed that the invite Signal user UX should be improved, it's on the roadmap.

**Comment by Alfinger** [comment]
If you go into 'settings' and 'About' you have the possibility to invite somebody via Twitter. Please add the possibilities for email, text message and other social media or just copy to teh clipboeard. And please also make us able to choose if the link(s) for iOS (Signal) and/or Android (Redphone, Textsecure) shall be sent.

**Comment by qtatspi** [comment]
Hello, 
 when attempting to compose a message to someone, searching by number or name, brings up nothing, just a cancel button, and nowhere can I using Voiceover as well, find an invite button, contacts is allowed under settings>signal, but searching returns nothing, and it appears I can't invite a non-signal contact to the app, it seems like simply searching for someones name or there number would let you message/invite them, but after hitting search, there's simply the edit field and a cancel button.

**Comment by lauraerinmann** [comment]
I'd like to not have to use my contact list to search for registered users.

**Comment by riyapenn** [comment]
Invite through 
1. Your own composed message or copy paste of 
I'm inviting you to install Signal! Here's the link: https://signal.org/install
2. Signal > Message compose icon (top right) > Invite Friends to Signal > Choose Message or Mail > choose contact > Select Done > Send SMS/MMS message or email
3. Signal > Settings wheel (top left) > Invite Your Friends > Choose Message or Mail > choose contact > Select Done > Send SMS/MMS message or email
