### ISSUE TITLE
Verification failure!

### ISSUE THREAD

**Issue by jamesroot** [WhisperSystems/Signal-iOS#689]
Hi,

I downloaded the much hyped Signal 2.0 on my Jailbroken iPhone 5, running iOS 8.1.2, I get the verification code, but on entering the code to verify account all that happens is that the circle keeps revolving ad infinitum, I tried to verify the account after doing a fresh install, tried to use different numbers, but nothing seems to work.
 Could it be something from Signal's end or am I doing something wrong, anybody else experienced this issue ?

Thanks lads.

**Comment by FredericJacobs** [comment]
Can you go to the Notifications settings and check the permissions just for signup? (including badges and sounds)

This is a known bug. Feel free to reopen if that didn't fix it.
