### ISSUE TITLE
If the Government fake my phone number?

### ISSUE THREAD

**Issue by FrankZhang002** [WhisperSystems/Signal-iOS#690]
Hi, 

I know the signal app requires a phone number, but if the government block my phone, and fake my phone number, is there any chance they can active my account in another phone? and pretend as me contact my friends ?

and How do I use this app on my iPad?

**Comment by moxie0** [comment]
Hey @FrankZhang002 this is an issue tracker, not a discussion forum.  The best place for support questions is the support center: http://support.whispersystems.org  Thanks!
