### ISSUE TITLE
Messages arrive out of order 

### ISSUE THREAD

**Issue by zarniwoop123** [WhisperSystems/Signal-iOS#691]
I saw a notification banner on my lock screen dated from a few hours ago. I opened up my conversation window to look at one of my conversations. The message I sent earlier was below the message my friend wrote in response to my first message. 

Below is a link to a screenshot (I couldn't upload it to github for some reason):

https://i.imgur.com/kOYi0p9.png

The blue message was sent before the grey one, but they don't appear in that order.

**Comment by FredericJacobs** [comment]
Should be fixed in 2.0.1 when Apple makes up their mind and approves it.
