### ISSUE TITLE
Missing Message Timestamp

### ISSUE THREAD

**Issue by xawita** [WhisperSystems/Signal-iOS#695]
There isn't a timestamp per each message. Eg whatsapp:

![image](https://cloud.githubusercontent.com/assets/11395761/6563066/97e82bcc-c69e-11e4-85a0-7fa447518b22.jpg)

**Comment by FredericJacobs** [comment]
This was an intended design decision. We might have detail views in the future for individual messages but currently there is no plan to support this.

**Comment by xawita** [comment]
Could you please elaborate on the design decision? This is present in Textsecure. Shouldn't the interface be consistent across devices and operating systems?

**Comment by FredericJacobs** [comment]
@xawita: We made the decision not to clutter the interface with timestamps for messages that have fewer than 5 minutes between them. Eventually, you will be able to long tap a message to get more details about it but we're not there yet.

**Comment by thenktor** [comment]
Not seeing timestamps and als not knowing about the 5 minute limit IMHO is horrible. In iMessage it is at least possible to see the time stamps of all messages by swiping left (better than nothing).
