### ISSUE TITLE
Message Preview

### ISSUE THREAD

**Issue by xawita** [WhisperSystems/Signal-iOS#697]
No option to show message preview intead of default 'New Message!'

![image](https://cloud.githubusercontent.com/assets/11395761/6563368/e970eec8-c6a0-11e4-801a-f61f79025c55.jpg)

Eg whatsapp:

![image](https://cloud.githubusercontent.com/assets/11395761/6563372/f4fea050-c6a0-11e4-8e15-4e65c733cfa7.jpg)

**Comment by tmoehle** [comment]
The push notification probably cannot display parts of your message because your message is encrypted as long as the App isn't running.

**Comment by acoffman** [comment]
I believe this is a dupe of #643 and #631.

**Comment by FredericJacobs** [comment]
Yep
