### ISSUE TITLE
No Edit nor Confirmation Before Photo/Video is Sent

### ISSUE THREAD

**Issue by xawita** [WhisperSystems/Signal-iOS#698]
When sending photo/video there is no option to confirm media selection before sending. They are immediately sent when clicked on.
Option to edit before sending would also come handy.

Eg .

![image](https://cloud.githubusercontent.com/assets/11395761/6563617/d74cffdc-c6a2-11e4-8c10-58b36a55d254.jpg)

**Comment by aaronraimist** [comment]
I don't have a developer account (so I can't test this) but it seems like you could change ```picker.allowsEditing = NO;``` to ```YES``` in these [two methods](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/view%20controllers/MessagesViewController.m#L1116) (```- (void)takePictureOrVideo``` and ```-(void)chooseFromLibrary {```) to fix this problem.

**Comment by FredericJacobs** [comment]
Replaced by #858
