### ISSUE TITLE
Add Opus Voice codec for calls

### ISSUE THREAD

**Issue by tmoehle** [WhisperSystems/Signal-iOS#699]
Hey, 

it would be amazing if you could add the opus voice codec for calls. Both ends could negotiate their codec capabilities and if both parties support opus you'd have a much better audio quality.

Thanks!

**Comment by rmueller83** [comment]
See also https://github.com/WhisperSystems/RedPhone/issues/69

**Comment by FredericJacobs** [comment]
Duplicate of #50
