### ISSUE TITLE
Message corrupted when containing 0x80 as the last byte of last character

### ISSUE THREAD

**Issue by shellmayr** [WhisperSystems/Signal-iOS#703]
This might be the same bug that was fixed with Issue #530 (Bug with Rocket Emoji), but since I have no familiarity with the codebase, this might already be solved but not yet in production. If so, please ignore this issue.

In version 2.0, any message that contains a character or emoji that has 0x80 as its last byte is corrupted due to what I see as an issue surrounding [removePadding] (https://github.com/WhisperSystems/Signal-iOS/blob/456d1c479addd83ac44a7c4322878e98aaf148b5/Signal/src/textsecure/Util/NSData%2BmessagePadding.m#L13-30), in which the last byte of the last character is mistaken for padding and also removed, resulting in a corrupted message.
This happens for the following characters when placed at the end of a message:
- LATIN CAPITAL LETTER A WITH GRAVE, UTF-8 xC3/x80

and Emoji:
- weary cat face \xF0\x9F\x99\x80
- rocket \xF0\x9F\x9A\x80	
- bath \xF0\x9F\x9B\x80	
- black left pointing triangle \xE2\x97\x80
- black sun with rays \xE2\x98\x80	
- cyclone \xF0\x9F\x8C\x80	
- four leaf clover \xF0\x9F\x8D\x80
- ribbon \xF0\x9F\x8E\x80
- basketball and hoop \xF0\x9F\x8F\x80	
- eyes \xF0\x9F\x91\x80	
- skull \xF0\x9F\x92\x80	
- dvd \xF0\x9F\x93\x80	
- grinning face \xF0\x9F\x98\x80
- rat \xF0\x9F\x90\x80	
- twisted rightwards arrows \xF0\x9F\x94\x80

**Comment by FredericJacobs** [comment]
This has been addressed in #530 and fix is under review by Apple
