### ISSUE TITLE
Ability to save and delete videos

### ISSUE THREAD

**Issue by lskjdf22** [WhisperSystems/Signal-iOS#704]
Pictures are currently savable. It would be nice to be able to save a video locally as well. There may be a way to do this in the UI, but it is not apparent to me.

**Comment by FredericJacobs** [comment]
No. It is currently not possible. Neither is it to delete a video. Still wondering about the UX of this. Probably just long tapping the video in the conversation view.

**Comment by fxer** [comment]
Is there something about adding the save option to videos that is much more difficult than adding it to still images on iOS?

**Comment by yaelwrites** [comment]
Assuming this feature is still unavailable?

**Comment by michaelkirk** [comment]
closed long ago in #1105
