### ISSUE TITLE
German translation: Send button says "Se...en"

### ISSUE THREAD

**Issue by sschritt** [WhisperSystems/Signal-iOS#709]
Signal 2.0.1 / iPhone 5s

**Comment by fabriceroux** [comment]
You can add french to the list of languages with an issue there:
"Envoyer" becomes "E...yer".

**Comment by Geblaat** [comment]
Same for Dutch "Versturen" becomes "Ve...en". (iPhone 4s btw.)
Dutch iMessage uses "Stuur" instead of "Versturen", so that would be a better choice, but doesn't fix it for other translations.

**Comment by TheStash** [comment]
Guys, you can help translate the app here: https://www.transifex.com/projects/p/signal-ios/

**Comment by Geblaat** [comment]
@TheStash I did, but that doesn't fix longer words not being displayed properly. For example Envoyer is displayed just fine in iMessage when you set your system language to French.

**Comment by maxbrandes** [comment]
Same problem with displaying words in new groups

www.j.mp/signaltext
