### ISSUE TITLE
Signal ios cannot Text my Contacts Usinig Signal

### ISSUE THREAD

**Issue by ScottsExpress** [WhisperSystems/Signal-iOS#715]
I cannot text my Signal Contacts. The only icon I see is Call.   My Name is highlighted ony Contact List. my other Signal Comtacts are lighter 
Why can I call my Comtacts but not text thru Signal but Can Only call? 
Do contact have to be loged in to text?

**Comment by s72785** [comment]
older versions than 2.0 (u need iOS 8 fot that I guess) have been able to call only. what version do you have for the app and for iOS ?

**Comment by FredericJacobs** [comment]
I see two possible cases:
1) They just signed up, and Signal is not aware yet they signed up. Pull-to-refresh in the contacts view will reload your contact list.
2) They haven't upgraded yet to Signal 2.0 and thus their version of Signal only supports calling, no text messaging.

**Comment by dbuenzli** [comment]
It seems that I have the same problem with iOS 8.1.2. and Signal 2.0.1. Shouldn't I at least be able to have encrypted soliloquies ?

**Comment by FredericJacobs** [comment]
I believe you're falling in one of both cases I mentioned above. If it's not the case, feel free to re-open.

**Comment by dbuenzli** [comment]
@FredericJacobs, I don't think I fall in the mentioned cases. I tried to pull to refresh but still I'm not able to text myself --- does the app allow this ? Other than that I have a single other contact which I'm not able to text either to but he could indeed be in 2).
