### ISSUE TITLE
Clearing your history will remove you from your group memberships + No way to text existing groups after clearing your messages.

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#718]
Details:
1. I was enrolled as a member of a group
2. I decided i wanted to clear my history
3. Conversations inbox was clear (=no way to write messages to existing groups)
4. Sending a message from other group members would not get through; actually i received a message after i cleared it but when i opened the app nothing showed up, sent another two messages while Signal was opened but didn't get any messages.
5. I was still showing up on Android devices as a group member.
6. Re-adding me to the group fixed the issue.

It would be nice to have the scenario described above as a "Panic" button but not as a clear history button.

Thank you, and sorry for writing too much bugs but i just want to help.

**Comment by FredericJacobs** [comment]
Yeah, that's intended behaviour. A clearing history wipes your group memberships. That's intended behaviour. I'll add it to the warning before clearing.

**Comment by joostrijneveld** [comment]
Point 5 seems problematic, though; being listed as a group member but not actually receiving messages seems undesirable, right?

**Comment by FredericJacobs** [comment]
@joostrijneveld: 5 is addressed now by sending a leave message when you're resetting your history.
https://github.com/WhisperSystems/Signal-iOS/commit/b03f3bb868b2575f9beb301e56dad33390900309#diff-a60452bce6568f21cb3e17c5af34c7f5R78

**Comment by TheStash** [comment]
@FredericJacobs can you help me understand the rationale behind removing group membership just by clearing history? I think deleting your account is ok to remove you from group membership as in #701 but most chat applications handle clearing history as just clearing history.

**Comment by FredericJacobs** [comment]
Still thinking about what options we want to have and what their goal is.

**Comment by JohanDoe** [comment]
May I suggest an edit button *within* a conversation - wether it is a group or not - to select and delete (all) messages to clear history. Deleting the group conversation would be still mean leaving the group (after warning). 

See how telegram does it.

**Comment by michaelkirk** [comment]
Two steps in the immediate.

1.) Clearer copy.
2.) "Are you sure?" should be an alert, not an action sheet.

**Comment by fracture-point** [comment]
This is also (separately) an issue when e.g. my phone breaks (or I upgrade to a new phone).  My group membership is lost, though in this instance, my "clearing" of messages was not intentional, as described in the OP.  

When I get a new phone, I can't see a group to which I was previously a member.  Even if that was intended functionality, it gets quirky - if someone else in that group sends a message, I receive it, but it lists as from an "Unknown group" and I can't see any member details.  My preference here would be to see the group in my contact list until I voluntarily leave the group.

**Comment by JasperWeiss** [comment]
I found the group membership system to be rather quirky as well. I reinstalled signal after which I still received messages from the group with no way to reply (the message box is just frozen) and there's no way to leave the group ether. WhatsApp handles this much better in terms of UX, not sure if it made any compromises for it though.

**Comment by pchaitat** [comment]
It happened to me too.  I cleared chat history.  Then, I could receive ongoing conversation in all groups, but I didn't see the sender name, nor I could send message to the group.  Not  until I asked someone in that group to re-add me back.

**Comment by michaelkirk** [comment]
As of 2.11, you should be able to respond to groups that message you, even if your device didn't previously know about the group.
