### ISSUE TITLE
ENHANCEMENT: eliminate infinite pop-ups when sound is disabled

### ISSUE THREAD

**Issue by astrostl** [WhisperSystems/Signal-iOS#719]
If push notifications are enabled while sounds are disabled, the following pop-up appears *every single time the app is opened*.  Can this be changed to a singleton or a setting for those that don't use sound?

```
Action Required

Signal requires push notification alerts and sounds to be enabled to work properly. Please change it in the Settings app >> Notification Center >> Signal.
```

Thanks for everything you do!

**Comment by FredericJacobs** [comment]
Duplicate of #630 that is part of the next release (2.0.2)
