### ISSUE TITLE
Multiple AddressBooks Support

### ISSUE THREAD

**Issue by mmkassem** [WhisperSystems/Signal-iOS#720]
When using multiple contacts accounts (ex. iCloud, Google, ...etc), a contact info can be duplicated and appears more than once in Signal. It is better to show only one contact per phone number especially if both the name and the phone number match

**Comment by riyapenn** [comment]
Similar to https://github.com/WhisperSystems/Signal-iOS/issues/624

**Comment by michaelkirk** [comment]
Fixed in next release with https://github.com/WhisperSystems/Signal-iOS/commit/06ca3c92909e59c47320a9cc2bb6333222b2368e#diff-8418c8ea3481450157e2ef89c76ed1c1R382
