### ISSUE TITLE
Message reply scrolling hides input dialogue & send button (iOS8 iPhone 6)

### ISSUE THREAD

**Issue by tim-way** [WhisperSystems/Signal-iOS#723]
I think have noticed a bug while replying to a message in Signal.

Using an iPhone 6 iOS 8.2 (I haven't tested others)

When replying to a message, if you scroll up to read older threads, when you scroll back down the text input dialogue is impossible to get to, along with the send button. 

The only way to continue writing is to copy text written, go back a screen and then return, paste and continue writing remembering not to scroll.

**Comment by FredericJacobs** [comment]
Can you elaborate on "text input dialogue is impossible to get to, along with the send button"?

I don't see the behaviour you're describing.

**Comment by tim-way** [comment]
I will try to describe better:

While replying to a conversation with a long thread.

Write your long reply in the usual way.

Then swipe up to read some old threads.

Tap back to continue writing. Then swipe back up.

There is a moment when you can use the "thread" section in the top half of screen to swipe up and down the keyboard (meaning if the keyboard is not being displayed, you can swipe down the thread, which results in showing the keyboard).

This is where I got stuck, so I correct my original message, there is a way to return to typing, but I just found it while trying to better describe to you the issue.

Perhaps this is not a bug but an intended feature of the keyboard? It seems a little odd to me which is why I wanted to let you know.

Anyway, thank you for a great app.

**Comment by FredericJacobs** [comment]
Well, the fact that when you swipe down on the keyboard area, the keyboard gets dismissed is intended behaviour.

Then you have to tap the message again to get the keyboard again.
