### ISSUE TITLE
Invite button on empty contacts view doesn't work

### ISSUE THREAD

**Issue by Geblaat** [WhisperSystems/Signal-iOS#724]
(iOS 8.2, Signal 2.0.1, iPhone 4S)
When you have some Signal contacts, you can manually type a number of a contact without Signal and  then press a pop-up to invite via SMS.
However, when you press the compose button when you have 0 contacts with Signal, the contact input field immediately disappears and is replaced with a message saying you have no Signal contacts, why don't you invite someone, but when you press the invite contact button it doesn't do anything and just goes back to the main Signal window.

**Comment by misiekmgo** [comment]
Hi :)

Did You find any solution. Right now for IOS 8.3 this does not work all the time - on some handests it is ok but on some still not - any news in this area ?

**Comment by trqx** [comment]
Hi, I can confirm that issue is still present on iOS 8.4.
