### ISSUE TITLE
iPod Touch: Signal (iOS) Contact List - Initial Import then Failure

### ISSUE THREAD

**Issue by edaugherty111** [WhisperSystems/Signal-iOS#725]
I recently purchased an iPod Touch and loaded Signal on it. After the initial install, Signal was able to load my Contact list and I was able to initiate calls and texts. After adding a third contact to my iOS contact list, Signal erased all the previous contacts and now states "None of your contacts have Signal!"

I am able to call and text from previous conversations. I cannot initiate new conversations. If I want to "add" someone to my conversation list, I have them call/text me first. My conversation list includes their phone numbers, but does not match it to their names as I've put them in my iOS contact list.

Some information:
- iPod Touch (5th Generation)
- iOS 8.2
- Signal 2.0.1

Specific Actions:
- Bought iPod
- Updated to iOS 8.2
- Installed Signal (2.0.1)
- Created two contacts in iOS contact list.
- * One contact uses Signal (iOS)
- * Other contact uses Redphone/Textsecure
- Signal Successfully imported contact list.
- Had friend install Redphone/Textsecure on his phone.
- Created a new contact for friend in iOS Contact List.
- Signal contact did not refresh right away.
- Waited 24 hours.
- Signal no longer has any contacts in Signal Contact list.
- Click the Refresh/Reload icon in upper right hand corner.
- Signal states "None of your contacts have Signal!"

Note: I've searched "Contact List not Loading" and found older conversations from 2014 w/ bug fixes. I created a new Question as this appears to be a new problem.

Cheers! I love how this works otherwise!

Originally posted at: http://support.whispersystems.org/customer/en/portal/questions/11523073-ipod-touch-signal-ios-contact-list-initial-import-then-failure?new=11523073

**Comment by edaugherty111** [comment]
Figured it out!

My contact list holds the cell numbers of my friends like so:

(555)123-4567

I changed that to:

+1(555)123-4567

Note: Signal would not import contacts with numbers like:
(555)123-4567
or
1(555)123-4567

You had to add the plus (+) mark in front of the 1 followed by the area code and local number. The plus mark (+) was key.

Note: I am in the US. So I used +1.

**Comment by FredericJacobs** [comment]
This is a well known issue. We're using the SIM location to guess the local prefix. 2.0.3 should have a fallback for devices without SIM to the system's locale.

**Comment by TheStash** [comment]
@FredericJacobs wouldn't it be better to detect using IP address since some users may not use their default local?

**Comment by edaugherty111** [comment]
Thanks, @FredericJacobs ! - I'll update my Support Ticket with this as well.

@TheStash - I use a global VPN, so my IP address is not indicative of the appropriate local prefix either. Perhaps just a selector in settings or setup. (Enter your phone number w/ country code. - With good UI/UX ;) )

**Comment by feorlen** [comment]
I just updated to 2.0.1 and have what looks like a similar problem. When I looked at my current conversations, only one still had the contact's name from my address book. And I can only see that contact now. I didn't change anything other than update the app.

**Comment by FredericJacobs** [comment]
@feorlen What device are you running Signal on? Does it currently have a SIM card in it?

**Comment by feorlen** [comment]
@FredericJacobs it's an iPhone on 8.1.3, with a working Italian SIM. I had checked the app right before updating, and then again immediately after. Both the current conversations at the time included the +1 for a US number, although only one still shows the recipient's name.
