### ISSUE TITLE
Make it possible to switch between the call screen and conversation view while on a call

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#727]
If you are texting a Signal contact and then decided to call him, the call screen dominates and there is  no way to text the same user/other users while having the call, Skype handles this in a better way; by clicking a back button from the call screen you go to the conversation view, while clicking the call log in the conversation view returns you go to the call screen.

**Comment by FredericJacobs** [comment]
This is a bug tracker. Not appropriate for random feature requests.
This is not going to happen anytime soon. Leads to way too many edge cases.
