### ISSUE TITLE
Cannot make calls after upgrading from Signal 2.0 to Signal 2.0.1

### ISSUE THREAD

**Issue by khorberg** [WhisperSystems/Signal-iOS#731]
After upgrading to signal 2.0.1 the little phone icon on the top right hand has disappeared for all my contacts. I can send and receive texts, and I can receive calls, but I have no way to make a call anymore. This has been going on for a week. I have iOS 8.

**Comment by FredericJacobs** [comment]
Hi @khorberg,

Sorry to hear that.
1) Do you have empty space on your iPhone?
2) Did you try "pull to refresh" on the contacts list? Does that succeed?

**Comment by khorberg** [comment]
I had to pull to refresh the contacts list a couple times, but it finally worked. I am now able to make calls to my contacts. Thank you!

**Comment by FredericJacobs** [comment]
Sorry for the inconvenience!
