### ISSUE TITLE
New message UX on iOS needs work

### ISSUE THREAD

**Issue by lordmortis** [WhisperSystems/Signal-iOS#734]
When I receive new messages via Signal, I get a notification saying "New message!" - Now I understand that if this notification is being generated server side, we can't get the message text as it will need to be decrypted on the client. It also appears that on Android, users get the text of the message? 

The next thing that happens is the client is taking up to a minute to retrieve the new messages after starting it. 

I was intending on trying to fix this myself and then submitting a pull request, but then of course (courtesy of your build notes and me refreshing my memory) - this is very hard for me to fix because the live servers all use production push certs etc. 

Excuse my ignorance if any of the following seems wrong (and i'd be totally up for being schooled in how things actually work - i'd like to help out on this project!)

I did notice that if you get a remote notification that's not a phone call the socket manager starts connecting and you stay active for 20 seconds before shutting down. It also looks like the local notification system isn't used at all?

Would it be possible for the flow to be something like this:
1. Server sends silent remote notification to a user if a new message is sent to them.
2. App wakes up and begins connecting in the background.
3. If messages are received, post local notifications with (optionally?) more information about the message (i.e. text and which conversation it's in)

I guess the only issue with this might be if the device is locked, we no longer have access to the decryption keys? 

I also suspect some extra latency is occurring because i'm connecting from Australia.

**Comment by lordmortis** [comment]
Also noticed that if you are the app, there are no notifications so it can be easy to miss a message

**Comment by FredericJacobs** [comment]
> Also noticed that if you are in the app, there are no notifications so it can be easy to miss a message

That will be fixed in a release that's currently submitted for review to Apple. As of your other points, we're currently investigating options.

**Comment by lordmortis** [comment]
Okay, it looks like something is timing out somewhere - when i start the app again, i've got all the new messages - but i'm not always getting the notifications :/ Is there any logging or anything i can send you to help track this?
