### ISSUE TITLE
App repeatedly asks for microphone access

### ISSUE THREAD

**Issue by ddccffvv** [WhisperSystems/Signal-iOS#741]
I'd like to use signal only for text messaging, not for voice.
As such, I didn't give the app permission to access my microphone.

Each time I open Signal, I have to tap ok on the "Action Required" popup which reminds me to allow access to the microphone.
Maybe a better way of handling this is only showing the popup when the user tries to do something voice related?

**Comment by FredericJacobs** [comment]
Duplicate of #630. Fixed in an upcoming release.

**Comment by ddccffvv** [comment]
Thanks!
