### ISSUE TITLE
Loading contacts at the background instead of foreground

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#744]
After the the 2.0.1 update clicking the "new chat" button (+) would show you "Loading Contacts... Sit tight"... i understand that the rationale behind this change is that it would prevent the user from scrolling down to update his contact list which i think is pretty good, but wouldn't it be better if this action happened in the background while showing the user his contact list that was already loaded from previous sessions and update the contact list as the loading happens? i think this would give a better user experience than waiting to see your contacts.

**Comment by FredericJacobs** [comment]
That behaviour was exceptional. Since 2.0.1, we changed how contacts are actually stored. This resulted on having to clear the cache and reload all contacts on first launch. You won't see that screen again if you have at least one RedPhone/TextSecure contact.

**Comment by TheStash** [comment]
I have around 40 contacts and keeps on doing this every time i use the "new message" button.

**Comment by FredericJacobs** [comment]
Can you go to the new message view, swipe to refresh and wait for completion, close the view, and open it again? Does it still show "Loading contacts ..."?

**Comment by TheStash** [comment]
1. Opened the app and went to new message view
2. It automatically said "Loading Contacts"... waited for it to complete
3. Swiped down for it to complete, it did.
4. Closed the new message view
5. Went to new message view; contacts were there
6. Switched the app (Not Shutdown), and Locked the device (Not turning it off).
7. Unlocked the device, opened the app, then new message view.. said "Loading Contacts".
8. Switched the app, then returned to it, then new message view...the list was loaded.
9. Shut down the device, opened signal, then new message view... the list was loaded and above it loading as if i've swiped down although i haven't.

Many thanks.

**Comment by FredericJacobs** [comment]
Fixed cache issue.

**Comment by TheStash** [comment]
Thank you :-)
