### ISSUE TITLE
Arabic interface is missing

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#747]
I already have my iPhone language set to English, i've tried changing the language to Arabic to see the changes after the update, after changing the language the app still was displayed in English, i thought this might be because i already have the app open, so i closed Signal, switched to English, then to Arabic, opened the App... the App interface was still in English... i'm not sure if this affects other translations too or was Arabic excluded until the "Right-to-Left" release?

Thank you

**Comment by FredericJacobs** [comment]
Yeah, I decided to take out the Arabic, Hebrew and Farsi translations until the release on the roadmap with full RTL support since it was currently looking really weird and buggy.
