### ISSUE TITLE
UI scaling on iOS 8 / iPhone 6+

### ISSUE THREAD

**Issue by sammcj** [WhisperSystems/Signal-iOS#748]
Call me crazy but for Signal's UI seems strangely 'large' on the iPhone 6+.

The UI doesn't appear iOS native on any device that I've seen so it could be that the framework is simply 'different' from what I've become used to, but on the 6+'s larger display it feels as though your browsing a web page with the zoomed in a few sizes.  

Feel free to close the issue if I'm the only one reporting this - perhaps I've been conditioned or the likes.

**Comment by sammcj** [comment]
Actually - someone just pointed out to me that the app uses 'JSQMessagesView' - which both of us have seen in other apps and they too had a clunky feel to them. 

Perhaps there is an updated version available?

**Comment by sammcj** [comment]
Actually - someone just pointed out to me that the app uses 'JSQMessagesView' - which both of us have seen in other apps and they too had a clunky feel to them. 

I can see here that it looks like at least part of the app is setup for iOS7 rather than iOS8: https://github.com/WhisperSystems/Signal-iOS/blob/master/Podfile#L1

Perhaps there is an updated version available?

**Comment by tomtastic** [comment]
Can we include making allowances for scaling in use on iPads too, where the scaled up iPhone view is less than awesome.

**Comment by FredericJacobs** [comment]
Working on #471, that will implement Dynamic Type and should address this.
