### ISSUE TITLE
making call

### ISSUE THREAD

**Issue by mustafa880** [WhisperSystems/Signal-iOS#749]
Hello,
Now we have source code but when we build the application in Xcode using our certificate to sign it we can't make and receive call between two devices at the same time..
I'm just wondering if the code is only for studying purpose or we can use the code and sign it with our certificate and use it normally?

Thank you.

**Comment by FredericJacobs** [comment]
Phone calls signaling is relying on Apple push notifications. This depends on code signing. Nothing we can do about it. You can however make outgoing calls and do all of the messaging stuff. You just can't get the push.

**Comment by mustafa880** [comment]
This is so frustrating :(
We wish that you can find a solution to this problem in order to take advantage of it like we do in Android please..

Thank you very much
