### ISSUE TITLE
Text for empty archive and conversation view not centered

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#750]
The text for an empty archive and/or conversation view is not vertically centered on iPhone 5S. It is too low. Apparently, there is a fixed height constraint instead of a vertical center constraint? This is evidenced by fact that on iPhone 4S the text is even lower at the bottom. 

See screenshots (for iPhone 5S, Signal 2.0.2)

![conv_view2](https://cloud.githubusercontent.com/assets/10408552/6960113/d115455e-d91f-11e4-8647-2ef1a430f0b5.jpg)
![conv_view](https://cloud.githubusercontent.com/assets/10408552/6960115/d4d987fe-d91f-11e4-8f95-07e19fde8e30.jpg)

**Comment by abolishme** [comment]
These empty states will be improved in a future release.
