### ISSUE TITLE
Back arrow is aligned too far left

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#753]
When viewing an individual conversation, the back arrow is too far left.

It isn't balanced from the outter edges with the phone icon. It also isn't in a similar position as the Settings cog when viewing the conversation list or the X when viewing the settings page.

**Comment by FredericJacobs** [comment]
The array is positioned by UIKit, the iOS UI library. We are not planning to override the defaults of that layout. Other icons might be aligned for consistency though.
