### ISSUE TITLE
Photos selected for group conversation are skewed

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#756]
When you set a photo for a group conversation, the photo is skewed. This is particularly visible when you use a 'landscape' photo. I guess that the size of the photos doesn't fit in the square/circle?

Suggestion: use a square/circle to select the area of the photo the user selects as the area to be used for the group photo. Ideally, it would also be possible to zoom in/out of the photo.

**Comment by big-r81** [comment]
A first simple fix (in my dev-version) is to set the UIImageView contentMode to 

- UIViewContentModeScaleAspectFill or
- UIViewContentModeScaleAspectFit or
- UIViewContentModeCenter

For Discussion: Which one to choose?

Is it necessary (functionality) to select a specific image area for a group photo?

**Comment by michaelkirk** [comment]
- UIViewContentModeScaleAspectFit - might have blank content in the frame
 - UIViewContentModeCenter - we have to worry about resolution, e.g. being way too zoomed into a high res image, or having blank content in the frame if it's low res
 - UIViewContentModeScaleAspectFill - preferred

**Comment by big-r81** [comment]
should we implement or use something like https://github.com/ruslanskorb/RSKImageCropper or use only the contentMode property?

**Comment by michaelkirk** [comment]
I’d start with fixing the bug before getting fancy with an image cropper.

**Comment by riyapenn** [comment]
Resurfacing according to user on iOS 8
https://gist.github.com/anonymous/e3377585dea510b96a289807d283b26d
