### ISSUE TITLE
Group membership text notices inconsistent in use of number / name

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#757]
When Alice leaves the group, the remaining members receive the text notification: "Alice has left the group". However, if Alice rejoins, it says. "Group updated. +123456789 joined the group." 

Suggestion: Use the name of the contact who joins the group in text notification to say: "Group updated. Alice joined the group" (in case number is recognized in contacts)

**Comment by mdouglass** [comment]
Took a pass at a fix in https://github.com/WhisperSystems/SignalServiceKit/pull/47
