### ISSUE TITLE
Missing space in Dutch translation between two sentences for group update text notification

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#758]
When a member is added to the group, the Dutch translation mentions:

"Groep bijgewerkt.+123456789 betrad de groep."

There is *no whitespace* between the two sentences in Dutch. The English version on the other hand does have a whitespace between the two sentences.

**Comment by 2-4601** [comment]
You can change this at [Transifex](https://www.transifex.com/projects/p/signal-ios/language/da/).

**Comment by JohanDoe** [comment]
Are you sure? They seem to be two different strings in Transifex (i.e. string 168 and 171) which are concatenated in the code?

**Comment by JohanDoe** [comment]
Ok. I think you're right. The Constant "GROUP_MEMBER_LEFT" has for the English version: "GROUP_MEMBER_LEFT" = " %@ left the group. ". So with the space before _and_ a trailing whitespace. Whilst the Dutch version (and other translations) have: "GROUP_MEMBER_LEFT" = "%@ heeft de groep verlaten."; So no whitespaces before or after. 

I requested access to change in Transifex and will change it when possible for me. 

Tx for pointing it out to me.
