### ISSUE TITLE
When keyboard is open, tapping anywhere in message history area should hide the keyboard

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#760]
This allows a user to more quickly switch between having the keyboard open to compose a message and having the keyboard closed to view the past messages.

This is faster than always needing to slide down the keyboard, which often causes the message history to accidentally scroll which is frustrating from a UX perspective.

Importantly, this suggestion is for the tap and release gesture. Pressing and holding on a message would still do the normal behavior of showing the contextual menu for a message.

(WhatsApp and Threema allow this to see it in action.)

**Comment by FredericJacobs** [comment]
This is a design decision, similar to iMessage.

**Comment by rocknjohn** [comment]
I hope you'll consider it for a future release.

From a usability perspective, this is an aspect of iMessage and Signal that is a frustration point because switching back to the message history is slower than it needs to be and can cause the message history to scroll meaning losing the point in the conversation one was reading.

**Comment by mailinglists35** [comment]
this has been fixed for a while, (contrary to the design decision stated in 2015, they have probably revisited the design since then), but now in the latest ios release this is a regression and again the keyboard does not hide.
