### ISSUE TITLE
Photo/Attachment handling issue

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#762]
iOS Version: 8.2
Signal Version: 2.0.2
Device: iPhone 4S

Issue:
Problem with handling attachment/media... not really sure.

Issue Details:
1. I received some group media messages a couple of days ago (6 Photos), three were downloaded and 3 were still hung up giving "attachment is downloading <!>"
2. I opened the group chat, clicked on "attachment is downloading <!>" to see if it can pull the image from the server... the app crashes.
3. I relaunch the app tried it again, the app didn't crash but there is no feedback from clicking the "attachment is downloading <!>" messages.
4. I scrolled up to see the already downloaded media... the app crashed (several trials).
5. whenever i try to open an already downloaded image... the app crashes (several trials).

Note: same behavior existed even after closing other apps and making a hard reboot.

**Comment by FredericJacobs** [comment]
Part of #440
