### ISSUE TITLE
Crash when entering group members

### ISSUE THREAD

**Issue by cryptomilk** [WhisperSystems/Signal-iOS#763]
If you try to show the members of a group, the application crashes.

From the log it looks like there is an invalid entry for a user.

The number is +049xxxxxx but it should be +49xxxxxxxx which could be the issue. Or it is a user who reregistered with a new key, so a dangling dead entry is now in the group. I can provide a log if you contact me.

**Comment by gladiac** [comment]
Ping!

**Comment by michaelkirk** [comment]
This is a really old issue and I've not heard of it reported since. 

Please reopen with a crash report if you can reproduce.
