### ISSUE TITLE
Signal app on iPad, ring sound problems

### ISSUE THREAD

**Issue by Nerd2k** [WhisperSystems/Signal-iOS#767]
I have the following bug scenarios to report.

Hardware: iPad mini 2 wifi (no cellular)
iOS Version: 8.3
Settings: Signal app is allowed to send messages, send sounds and to access the lock screen

--- Issue #1 ---

Description:
Signal app doesn't make any ring sound for incoming call, when minimised.

--- Issue #2 ---

Description:
Signal app doesn't make any ring sound for incoming call, when iPad is locked (display switched off)

--- Issue #3 ---

Description:
If Signal app is freshly started and active it doesn't make any ring sound for an incoming call. Only after I tried to call anyone else for at least one time, it produces a ring sound if I receive a call later on.

**Comment by FredericJacobs** [comment]
Make sure you are running Signal 2.0.3.

**Comment by Nerd2k** [comment]
Unfortunately I already do.

**Comment by FredericJacobs** [comment]
Are you sure the iPad was not in silent mode for 1 and 2?

**Comment by Nerd2k** [comment]
Ha! That was it! Sorry somehow the device was put in silent mode (the little bell button in the control center was activated). Should have noticed it before as there haven't been any email notification sounds as well. I guess what confused me was that video or audio sound was playing, didn't remember that I configured it that way both audio/video sound and notification sound can be set independent from each other.

Thanks for your kind help! I think this topic can be closed.

**Comment by tecoboot** [comment]
I have same problem. iOS 10.3.1 on iPad Air. Messages do trigger notification sound. Incoming calls are received, iPad awakes correctly.. but very often, no sound. I'll reboot and retry. 

On iPhone 7plus iOS 10.3.1, it works well..

**Comment by tecoboot** [comment]
Reboot doesn't help. Log sent to support.

**Comment by mailinglists35** [comment]
how did you manage to get signal on ipad in 2015? it’s 2019 and only this year they made signal for ipad air as a linked device only, not as native app.

even then, I don’t even have calling buttons, but only messaging! 🤬

**Comment by Nerd2k** [comment]
> how did you manage to get signal on ipad in 2015? it’s 2019 and only this year they made signal for ipad air as a linked device only, not as native app.
> 
> even then, I don’t even have calling buttons, but only messaging! 🤬

Well, I just installed it from the iOs app store. Until iPad support was introduced this year, I had been always using it in this weird zoomed display mode, which you get when you run iPhone apps on an iPad 😄

**Comment by mailinglists35** [comment]
nope, in app store I see only one app for all devices, and when installed on ipad it is the desktop client, not the native iphone small sized full featured app.

**Comment by Nerd2k** [comment]
> nope, in app store I see only one app for all devices, and when installed on ipad it is the linked device client, not the native iphone small sized full featured app.

Yes, it's not the small sized iphone app anymore, since that update. I didn't notice though that it wasn't full featured and that it's not native. Makes sense though, considering the great frequency of crashes and lags the app has ever since that update.
