### ISSUE TITLE
Feature request: change color of "Send" button when pressed

### ISSUE THREAD

**Issue by MrAlexWeber** [WhisperSystems/Signal-iOS#768]
When sending messages using Signal, it's difficult for me to tell if I've missed the tap target for the Send button.

The convention on iMessage and Facebook Messenger appears to be to lighten/fade the text "Send". Making a rough guess, it looks like about 50% opacity.

I suggest Signal adopt this convention.

NB: if, after pressing the button but while keeping my finger on the screen, I slide it away from the button, it fades back to the original color.

Suggested labels: Enhancement, Usability, Design

**Comment by diegode** [comment]
+1
This should happen for other actions too, e.g. when tapping on a conversation while on the conversations list (compare with Whatsapp).

**Comment by michaelkirk** [comment]
For the next release we touched up the color of the send button to make it clearer when it's disabled.
