### ISSUE TITLE
When a call is missed there is now way to know who called you

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#770]
When you miss a call, there is no way in the UI to get who called you, i tried checking the last chat messages to see if there is a log in the chat that indicates who called but i found nothing, even checking the specific contact that called you shows no logs in the chat... i believe since Signal is combination of messages and voice, you either need to dedicate screen showing call logs or log incoming/outgoing calls within chats.

Thanks & keep up the good work :-)

**Comment by FredericJacobs** [comment]
This is going to be addressed properly in an upcoming release

**Comment by TheStash** [comment]
Thank you :+1:
