### ISSUE TITLE
Session being stored indefinitely 

### ISSUE THREAD

**Issue by danielschonfeld** [WhisperSystems/Signal-iOS#771]
Is there a way to coordinate a Bob/Alice roles better so that we don't have to save the session records in the TSStorageManagerSessionStoreCollection collection indefinitely? 

I know the sqlite database is encrypted, but i imagine to myself that when deleting a thread a security conscious user wants to know that all traces of their conversation have been deleted including the existence of the session which among other things has the counter which would indicate how many messages were exchanged for the lifetime of the session.

**Comment by FredericJacobs** [comment]
Sessions have perfect-forward secure properties. The counters are as we say "per-chain". So there is nothing in the session store that leaks the total messages of messages sent.

You can find out more about [our ratcheting scheme on our blog](https://whispersystems.org/blog/advanced-ratcheting/)Sessions have perfect-forward secure properties. The counters are as we say "per-chain". So there is nothing in the session store that leaks the total messages of messages sent.

You can find out more about [our ratcheting scheme on our blog](https://whispersystems.org/blog/advanced-ratcheting/)
