### ISSUE TITLE
Feature request: Apple Watch support

### ISSUE THREAD

**Issue by hubert3** [WhisperSystems/Signal-iOS#774]
Would be nice if Signal messages were displayed on the Watch, including the ability to reply like Messages.

If Watch support is added but the user doesn't want to use it, Signal could be disabled within the Apple Watch companion app on the iPhone, so there shouldn't be any need for additional Watch-related settings within the main Signal app.

**Comment by FredericJacobs** [comment]
I got notifications working on [Apple Watch](https://twitter.com/fredericjacobs/status/593564333122125824). I don't have Apple Watch so I can't do more for now.

**Comment by hubert3** [comment]
Neat. Even just being able to read incoming messages would be a nice start.

**Comment by hubert3** [comment]
Confirm notifications showing message text on the watch are working fine in 2.1.50.

**Comment by gpoul** [comment]
Now with cellular on the apple watch this might become a more interesting feature.

**Comment by kschar** [comment]
Oh yeah - ability to reply, etc on new Apple Watch 3 /LTE is super compelling. I’d rather not have to revert to iMessage just for that 😝

**Comment by kschar** [comment]
Signal rocks!  It’s a required app for use on my team!

**Comment by loganallenc** [comment]
+1. Any plans for this?

**Comment by ventz** [comment]
@Mihahn Any plans/road map for this?

It seems a lot of people want it, and it was first posted in 2015.
Just from glancing at it, it seems watchKit is incredibly simple to add.

There are some good examples here:
```https://books.google.com/books?id=7CwBCwAAQBAJ&pg=SA9-PA164&lpg=SA9-PA164&dq=WatchKit+reply+to+messages&source=bl&ots=4AI5fAsdMj&sig=vDrmk3-mhhqsdONkFTYKc7qT40Q&hl=en&sa=X&ved=0ahUKEwi-ycLMgsDXAhUBUiYKHbZOAGwQ6AEISDAF#v=onepage&q=WatchKit%20reply%20to%20messages&f=false```

Seeing stuff like this:
https://telegram.org/blog/apple-watch

Makes us all really jealous ;)

**Comment by ventz** [comment]
I just saw that signal had a "reply" to message -- unless apple changed their watchKit where "messages" have an auto reply option :-D assuming someone updated and pushed it out? If so 👍  and thank you!

**Comment by ifuchs** [comment]
How about an actual Watch app, that permits composing and sending messages (as opposed to just replies which work now)?

**Comment by cioraneanu** [comment]
+1 for an actual WatchOS app. The Telegram looks really great.

**Comment by KonstantinSchubert** [comment]
Are there any technical barriers to getting signal on the apple watch? Or are there any app store policies they prevent it?

**Comment by FrancescoPerrone** [comment]
I understand this thread is closed, I want however to stress the fact that having Signal working on Apple Watch with cellular in a way that it allows sending/receiving/replying messages would fill a niche in the messaging apps available for Watch at the moment. Alternatives such as Telegram, Viber, and even evil apps likes whatsapp and the like, do not allow to send text natively unless there is already a registered conversation.

**Comment by FrancescoPerrone** [comment]
> +1 for an actual WatchOS app. The Telegram looks really great.

It is alright, but it does not work away from your phone on cellular? did you try?

**Comment by mkonikov** [comment]
+1 to having an actual Apple Watch app - where you can compose messages etc. any hope for that?

**Comment by janoschpelzer** [comment]
Hello, can you reopen this? There still is no Apple Watch app for signal.

**Comment by falcontomto** [comment]
Thanks to the pandemic, people are much more into health and well-being in general, and sales of wearable electronics skyrocketed like never before, and I would expect a watchOS Signal app would be critical if we want to appeal to more users.

**Comment by dallasgroot** [comment]
I would love to learn how to build apps so I can make a watchOS app for signal. This is one thing that’s annoying about it on the go. You can ONLY reply to messages. It’s been 5 years since this was last posted.

**Comment by dallasgroot** [comment]
I would love to learn how to build apps so I can make a watchOS app for signal. This is one thing that’s annoying about it on the go. You can ONLY reply to messages. It’s been 5 years since this was last posted.

**Comment by ianbrandt** [comment]
It looks like #4329 covers the request for a dedicated Apple Watch app.

**Comment by mr-utilman** [comment]
Apple watch support please

**Comment by Lukysoon** [comment]
You can use mautrix + signal-bridge on your server and Watch-The-Matrix project.
