### ISSUE TITLE
Difficult to differentiate different members in a group

### ISSUE THREAD

**Issue by trstnthms** [WhisperSystems/Signal-iOS#779]
When multiple people are messaging within a group, it is difficult to differentiate between each individual person's messages. iMessage and Telegram both solve this quite nicely with the person's picture/first letter of first name next to their messages.

**Comment by riyapenn** [comment]
https://github.com/WhisperSystems/Signal-iOS/issues/736

**Comment by michaelkirk** [comment]
closing (dupe of #736)
