### ISSUE TITLE
Unable to Make Phone Calls

### ISSUE THREAD

**Issue by davidecarroll** [WhisperSystems/Signal-iOS#780]
Hi, 

I'm using Signal 2.0.3 in iOS 8.3 and on the 'new message' interface and in the conversation interface, there is no option to phone contacts. I've attached a screenshot of the problem in the new message interface. 
![signalbug](https://cloud.githubusercontent.com/assets/4964180/7491090/edf42a90-f3dd-11e4-9fba-64d9e91c09e3.jpg)

**Comment by FredericJacobs** [comment]
I believe your iPhone is close to being full. iOS automatically cleans up the cache folder where we store the bloom filter for RedPhone contact intersection. 

How to fix this? Make sure you have some room on your iPhone and scroll to refresh on your contact list and the contacts you can call should appear.

**Comment by davidecarroll** [comment]
Ah, excellent. Thanks.
