### ISSUE TITLE
Bug: clicking on a number without a country code does not lead to info page

### ISSUE THREAD

**Issue by yaelwrites** [WhisperSystems/Signal-iOS#783]
When I am communicating with someone not yet in my contact list, I can normally double-tap on their phone number to open up the info page and add them as a contact.

However, if I text the number without a country code and double-tap on the number to try to open the info page, it is simply adding the country code (+1 in this instance) and will not take me to the info page.

**Comment by FredericJacobs** [comment]
> if I text the number without a country code and double-tap on the number

How can you text the number without a country code? If you receive a message from them, the country code will always be prepended.

**Comment by yaelwrites** [comment]
I entered it in without the country code. It added the country code when I send the message, but when I tap on it to try to change it into a contact, it just alternates between 1-XXX-XXX-XXXX and XXX-XXX-XXXX. 

Could take screenshots and blur out the number if that'd be helpful.

**Comment by FredericJacobs** [comment]
Oh, I see. So when you say 
> I entered it in without the country code.
you mean, you entered it in your address book first?

It's not a bug, we do not allow contact editing from the app, we are just allowing it in the case where the number is not previously know.

You will have to edit that from your contacts app.

Does that answer your question?

**Comment by yaelwrites** [comment]
No, I entered it in the app directly. Otherwise it would be easy for me to edit without the need to cut and paste it into my main contact list. In this instance since I can't I have to go all steampunk and throw back to actual pen and paper.

I'm not sure if that's what you meant.

Sent while bumping into things.

--
Yael Grauer, Freelance Writer
(715) 456-4273
http://yaelwrites.com

**Comment by FredericJacobs** [comment]
How did you enter the number in the app directly? As far as I know there is no way to start a conversation that way!

**Comment by yaelwrites** [comment]
I think I entered it and then clicked on "send SMS message to this number."

Sent while bumping into things.

--
Yael Grauer, Freelance Writer
(715) 456-4273
http://yaelwrites.com

**Comment by FredericJacobs** [comment]
That will send an SMS with a download link to that person. But doesn't make it a Signal user.

**Comment by yaelwrites** [comment]
Okay. Maybe I'm remembering wrong and I added a contact in iOS without a name and am not remembering it... In which case I apologize for wasting your time!

Sent while bumping into things.

--
Yael Grauer, Freelance Writer
(715) 456-4273
http://yaelwrites.com

**Comment by FredericJacobs** [comment]
Hope that solves it. At the bottom of your iOS contacts you might see their phone number in your addressbook.
