### ISSUE TITLE
Finnish translation of MESSAGE_COMPOSEVIEW_TITLE is not used

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#784]
Signal 2.0.3, iPhone 4S, iPhone 5, iOS 8.3

0. Set iOS language to Finnish (if you dare [1])
0. Open a Signal conversation
0. The string on the input box is in English: _'New Message'_ (should be in Finnish: _'Uusi viesti'_)
![rabelais signal](https://cloud.githubusercontent.com/assets/174176/7662641/a0b9e404-fb67-11e4-9171-93aad14bc4c6.jpg)

**Yes, it has been translated. Over two months ago**
The Finnish translation for `MESSAGE_COMPOSEVIEW_TITLE` has been in Signal since version [2.0.1-2](https://github.com/WhisperSystems/Signal-iOS/blob/5aa560c0e3c95ade80c03611903e696ba4c30830/Signal/translations/fi.lproj/Localizable.strings#L199). I also double checked that all the [releases](https://github.com/WhisperSystems/Signal-iOS/releases) starting from 2.0.1 have it. But for some reason it is still not used in 2.0.3. Other translated strings which have been updated at the same time or after it work fine.

I also tried to reproduce this with other non-English languages that have had `MESSAGE_COMPOSEVIEW_TITLE` translated before 2.0.3 was submitted to Apple but none of them had this issue.
The languages I tested were French, German and Chinese (simplified). I planned to test all languages relevant to this issue but had to stop after these three.[1]

Just looking at the `Localizable.strings` files doesn't give any clues why the string is not used.
For example there are no differences in the syntax between the [French](https://github.com/WhisperSystems/Signal-iOS/blob/0f04132b81e4b51b659a0ac6d9c1095aec98e46b/Signal/translations/fr.lproj/Localizable.strings#L205) and [Finnish](https://github.com/WhisperSystems/Signal-iOS/blob/0f04132b81e4b51b659a0ac6d9c1095aec98e46b/Signal/translations/fi.lproj/Localizable.strings#L205) translation files.

Why is just this single string not translated?

----------

_[1] A rant about iOS language settings follows:_
_Changing languages on the fly (i.e. without reboot) should be possible in iOS. And indeed it worked as I expected for French and German. But when I switched to Chinese (simplified) things almost went horribly wrong. After the change the phone decided to go into a setup mode which could not be skipped or quit. It wanted to set up iCloud, Apple ID and Find my iPhone even though they had been already set when the phone was new. I would have probably crapped my pants if the language had been something I did not know anything about. Also because the device was not mine I was putting myself in a very uncomfortable situation and thus decided to stop at this point._

**Comment by FredericJacobs** [comment]
Thanks for this wonderful report. Loved reading it :+1: 

I did build the [latest version on master](https://github.com/WhisperSystems/Signal-iOS/blob/0f04132b81e4b51b659a0ac6d9c1095aec98e46b/Signal/translations/fi.lproj/Localizable.strings#L205) and checked the Finish localization was loading.

It should be fixed in the next release. Sorry for the inconvenience.

**Comment by 2-4601** [comment]
@FredericJacobs This is still not fixed in the latest App Store release 2.1. Could you reopen this?

I can't understand at all what the underlying cause could be.
`MESSAGE_COMPOSEVIEW_TITLE` is a very old string. Why does it not work but all the others do?

**Comment by FredericJacobs** [comment]
Is

**Comment by FredericJacobs** [comment]
It's not `MESSAGE_COMPOSEVIEW_TITLE`. That's another string. I found the issue, gonna try to come up with a solution

**Comment by 2-4601** [comment]
Thanks!
Curiously waiting what causes this strange bug :no_mouth:
