### ISSUE TITLE
Bloomfilter deleted warning

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#785]
Since Apple forced us to store the bloom filter in the cache folder, it occasionally gets deleted if the user's device is running low on storage.

In principle, it is re-fetched on launch of the app but if that request fails the user would have the impression that he's no more able to call people.

We should probably provide actionable warnings to help the user out of this situation.

**Comment by chrisballinger** [comment]
Wow, they didn't even let you store it somewhere in Application Support with NSURLIsExcludedFromBackupKey?

**Comment by FredericJacobs** [comment]
No, it is not user generated content.
