### ISSUE TITLE
Phone number not recognized

### ISSUE THREAD

**Issue by fabianschwarzfritz** [WhisperSystems/Signal-iOS#786]
Hi folks,

I have an iphone 5c and installed Signals recently. A friend texted me on Signals (first message) and even if I have his phone number stored as a contact, Signals did not recognise the contact. We are from Germany and do have German phone numbers.  

When he texted me, the phone number is displayed as "++49 aaa bbbbbbb" but in my contacts the number is stored as "49aaabbbbbbb".  
(++49 = country code; aaa = area code; bbbbbbb = actual phone number)

UPDATE: I do have version 2.0.3

Other systems like Whatsapp or the text iOS messaging app for example recognise the contact correctly. Have this feature implemented would be great!

Bests from Germany,
Fabian

**Comment by FredericJacobs** [comment]
Uhm, that's strange.

Are you sure about the double + format? I have never seen that before.

**Comment by thecure** [comment]
I have the same problem - I have IPhone 5c (which I think is the same as 5s)--
Signal doesn't recognize telephone numbers in my contact list--people have to call me first on Signal (Version 2.1). Then I can call or text them back. I don't get the ++ problem, however.

It says, "None of your contacts have Signal!" when in fact most of my contacts do.

**Comment by riyapenn** [comment]
@thecure When you have a contact call or message you first, what shows up for their identifying information? Is it their number or is it their name?  Can you compare the number that shows up to the number stored in your contact list and make sure they match?

**Comment by abcdev** [comment]
@fabianschwarzfritz as @FredericJacobs pointed out, your stored number is not a valid number format. It is a crossover of national and international phone number both not being valid. There is neither a country code "49" just "+49" and "0049" nor a region code starting with just "49".
(see https://de.wikipedia.org/wiki/Internationale_Telefonvorwahl)

libPhoneNumber-iOS will not fix this malformed number.

**Comment by fabianschwarzfritz** [comment]
Hi! Sorry for leaving this open for so long. @FredericJacobs  you're absolutely right, the "++" is wrong in my phone number. With that changed, it works as expected.
