### ISSUE TITLE
previously sent texts remains in text box even after successfully sent

### ISSUE THREAD

**Issue by yaelwrites** [WhisperSystems/Signal-iOS#787]
Messages I've already sent stay in the message box (even after I've sent them) and have to be erased before texting the same contact.

**Comment by FredericJacobs** [comment]
I've never heard about this issue. Can you reproduce it consistently? Any additional information is welcome.

**Comment by yaelwrites** [comment]
It happens every few days or so but not every time I text. What type of additional information would you want? Can add a screenshot next time it happens.

**Comment by FredericJacobs** [comment]
@yaelwrites Have you seen this again?

**Comment by yaelwrites** [comment]
I saw it again for weeks, but it stopped a few days ago, right around the time when I changed my device name from an emoticon back to text. I am not sure it was related, since it was happening inconsistently, but it seems to have stopped.
