### ISSUE TITLE
No tick mark in active option for notification style under settings (Beta 2.1.25)

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#789]
I would expect to see a tick mark ragged right for marking the option I have active
![img_2055](https://cloud.githubusercontent.com/assets/10416484/7788090/56c48af8-022d-11e5-97e5-a6cc01c1dd52.PNG)

**Comment by FredericJacobs** [comment]
Implemented, thanks!

![img_2019](https://cloud.githubusercontent.com/assets/400296/7789689/c8d41f32-0269-11e5-8cff-1726b6c1df05.PNG)
