### ISSUE TITLE
Word "attachment" not translated when receiving a notification of attachment (Beta 2.1.25)

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#790]
But the background decryption for notifications work flawlessly! thank you very much! 
![img_2052](https://cloud.githubusercontent.com/assets/10416484/7788117/3fde66f0-022e-11e5-8e65-660bed594b6a.PNG)

**Comment by NicolasCGN** [comment]
Interaction options with notifications are also not translated
![fullsizerender](https://cloud.githubusercontent.com/assets/10416484/7788221/75e825ca-0232-11e5-8c1b-0f7123febb4c.jpg)
![fullsizerender-1](https://cloud.githubusercontent.com/assets/10416484/7788224/8033e780-0232-11e5-8063-20380deadb10.jpg)

**Comment by FredericJacobs** [comment]
1) String now on Transifex
2) That was a mistake on my end.

Thanks for reporting!
