### ISSUE TITLE
Notifications of group messages

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#794]
(Beta 2.1.25) Group messages (when option show name and message are active) are notified as New message from %@ in group %@: %@ 

![fullsizerender-2](https://cloud.githubusercontent.com/assets/10416484/7794446/da1db38c-02ca-11e5-9cf4-0fded624fdee.jpg)
 
In order to be consistent with the notifications from single contacts and to save some space, would it be possible to shorten the notification as "%@ in group %@: %@"?.  Without  the part "New message from" that seems redundant when sender and message are shown in the notification.

**Comment by lordmortis** [comment]
I've got a pull request (#796) with a different format for the messages - take a look and see what you think!

**Comment by FredericJacobs** [comment]
Fixed on branch.
