### ISSUE TITLE
Restrictions interfere with asking for Contacts Permission

### ISSUE THREAD

**Issue by BoerenkoolMetWorst** [WhisperSystems/Signal-iOS#799]
If Restrictions are enabled Signal will not ask for contacts permission and doesn't show up in Settings >> Privacy >> Contacts to enable manually:
http://support.whispersystems.org/customer/portal/questions/12716571-solving-the-ios-contacts-problem

**Comment by FredericJacobs** [comment]
@BoerenkoolMetWorst Gebeurt dit ook met andere applicaties?

As far as I know, there is no way to detect if a user denied access to your contacts or if it has restrictions enabled. In both cases, Signal doesn't is told that `APAddressBookAccessDenied`. There are already a few issues open for better support for denied AddressBook permissions.

**Comment by BoerenkoolMetWorst** [comment]
I don't know, I haven't experienced the issue myself or with other apps, as I don't use the Restrictions. However there where multiple users experiencing the problem, and since someone discovered Restrictions were the causation I thought it was worth opening an issue for.
