### ISSUE TITLE
(Beta 2.1.25) Redundant notifications

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#800]
I got two notifications for the same message. One with background decryption and one default notification. So far it happened only once for a single contact.

![img_3458](https://cloud.githubusercontent.com/assets/5073538/7842079/3e2ed8ba-04a1-11e5-9595-b2de5c503225.png)

**Comment by FredericJacobs** [comment]
This might continue to happen. Apple's PushKit framework is quite buggy and we can not reliably get messages decrypted to plain text. Although you should see it less often and eventually not anymore, there is nothing we can do more about it now.

More info on the Apple Dev Forums: https://devforums.apple.com/message/1135227
