### ISSUE TITLE
(Beta 2.1.25) Special Message causes Signal to crash

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#801]
A bug in Apple’s Messages app [1] seems to affect Signal as well. Sending the “power message” to myself crashes Signal. Signal also crashes when entering the conversation containing this message.

-- 
[1] TheAppleByte; Special Message causes iPhones to Restart; http://www.theapplebyte.info/2015/05/26/special-message-causes-iphones-to-restart/

**Comment by FredericJacobs** [comment]
This is an operating system vulnerability. We will not mitigate it since all iOS users who run Signal can update to the patch when Apple publishes it.
