### ISSUE TITLE
sideloaded TextSecure disconnects registered number on Signal

### ISSUE THREAD

**Issue by temp140801** [WhisperSystems/Signal-iOS#802]
- working registered number on Signal 2.0.3 on iOS 8.3 on iPhone 5
- sideload TextSecure 2.14.5 on Android 5.1.1 on Nexus 7 2013 WiFi
- register same number on TextSecure by call back
- Signal network status shown as "offine"
- when attempting delete account in Signal: "Failed to unregister messaging comonent of Signal"
- unregister number via web UI
- uninstall Singal, TextSesure
- reinstall Singal
- register number
- Signal network status shown as "connected"

**Comment by FredericJacobs** [comment]
You number can only be registered at a single place at the time.
