### ISSUE TITLE
Hit enter to send

### ISSUE THREAD

**Issue by gonzalezb** [WhisperSystems/Signal-iOS#803]
It would be nice if we could get the Ability in settings to turn the enter button into a send button like in TextSecure.

**Comment by FredericJacobs** [comment]
I could consider having this as a opt-in feature in the settings.

**Comment by mrphs** [comment]
Yes, this is a huge usability thing. There are times when you want to send a image, are browsing in your gallery and accidentally hit on one image, it would send it right away. instead, it should put the thumbnail of the image in the text-field, then user would add a comment or press send. something like what iMessage does.

**Comment by breadtk** [comment]
+1 on the usability issue. Multiline replies in iOS require the Return button to be pressed.

**Comment by FredericJacobs** [comment]
As mentioned in #858, sending of media will have an option to review before sending. The option of having a sent button on the keyboard is not going to be implemented though. The lack of return key and risk of accidental sending led to that decision.

**Comment by hismayilov** [comment]
this will be very useful especially while using external keyboard.

**Comment by fastman** [comment]
What about sending normal text messages with enter key? (not sending images and no external keyboard)

**Comment by DScibrany** [comment]
> As mentioned in #858, sending of media will have an option to review before sending. The option of having a sent button on the keyboard is not going to be implemented though. The lack of return key and risk of accidental sending led to that decision.

Why is such a feature on Android but cannot be present on iPhone? "Risk" of accidental sending a message is the same and it could be opt-in feature, same as it is on Android. So the user knows he's chosen to do it this way and he's well aware of it. For me, this is one of those strange usability discomforts going from Android to iPhone. Lack of options which are available in the same app on other platforms.
