### ISSUE TITLE
touch conversations to close keyboard

### ISSUE THREAD

**Issue by gonzalezb** [WhisperSystems/Signal-iOS#804]
its inconvenient to have to swipe the keyboard down to close it as it makes the conversations scroll upward. It would be better if you made it close the keyboard when you touch the conversations instead of pulling it down. Allot of other apps use touch conversations to close the keyboard and it works better as its faster and doesn't cause your conversation to start scrolling upward.

**Comment by FredericJacobs** [comment]
This is a design decision, not a bug. We're sticking to the iMessage experience because that is what iOS users know the best.
