### ISSUE TITLE
I want to run the source code on ios sdk 8.1

### ISSUE THREAD

**Issue by azmatkhan87** [WhisperSystems/Signal-iOS#805]
Hi All
     I want to compile the source code on Ios sdk 8.1 but unable to compile it. it raise issue. how to fixed that YapDatabase/YapDatabaseTransaction.h:52:1: Unknown type name 'NS_ASSUME_NONNULL_BEGIN'

Thanx in advance

**Comment by FredericJacobs** [comment]
We always only support the latest iOS SDK on the master branch.
