### ISSUE TITLE
Not all push notifications being received?

### ISSUE THREAD

**Issue by lordmortis** [WhisperSystems/Signal-iOS#806]
I'm missing quite a few messages and I can't work out the pattern. 

There was a Gist I put in my original push notification issue (relinked here for clarity)
https://gist.github.com/anonymous/65eb92ec1c4509e4a2a3

and here's another one from today:
https://gist.github.com/anonymous/54deb5cb5385ff2c591b

I'm not sure how to best assist in tracking this one. Is anyone else seeing this?

**Comment by FredericJacobs** [comment]
@lordmortis You're on the beta right? We are currently working on this.

**Comment by lordmortis** [comment]
yeah I am on the beta. Awesome! Let me know if you need anything!

**Comment by FredericJacobs** [comment]
Sadly the issue appears to be present in all versions of iOS up to now. Hoping that 8.4 will fix the issue.

**Comment by FredericJacobs** [comment]
This should be mitigated in the build that I pushed this morning. Please re-open if it happens again.
