### ISSUE TITLE
(optional) Show the incoming message in the push notification

### ISSUE THREAD

**Issue by gendalus** [WhisperSystems/Signal-iOS#808]
I think it would be great to have the incoming message displayed in the push notification, but only when you opt-in. I think especially users with an Apple Watch would want the possibility to at least read their messages on the watch.

The tricky part could be the setup of the push notification, because apples push servers shouldn't know about the messages. Would it be possible to send a silent push, when receiving a message, wake the app, decrypt the message and send/show a local push notification with the contents of the message?

**Comment by FredericJacobs** [comment]
We are working on this. It's implemented but we are currently working on addressing edge cases before release.
