### ISSUE TITLE
Confusion in missed calls

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#811]
When someone calls me (on Signal) while I'm talking to someone else (on Signal)...

1- I don't get any notifications that someone else is calling me or that I've missed a call.
2- When I accidentally looked at the chat with the person whom I just missed their calls, logs show that I called them, and it's pretty confusing.

**Comment by FredericJacobs** [comment]
@mrphs Thanks Nima for reporting this. It's already fixed on master. Do you want to join our beta program?
If so, drop me a line with your AppleID at fred@whispersystems.org

**Comment by mrphs** [comment]
Thanks! and sorry about the noise.

WRT beta test, I'd love to. But since I teach people how to use this stuff, I should stick to public releases to have the same experience as all other users. I'll hit you up if I managed to get a secondary device.
