### ISSUE TITLE
Can't see who called

### ISSUE THREAD

**Issue by CharlesFarr9** [WhisperSystems/Signal-iOS#815]
If I miss a call on Signal, I cannot see that I missed the call or who called.

**Comment by breadtk** [comment]
It is incredibly helpful if you could attach a screenshot of what you're talking about. Additionally you should also consider including a proposed solution, which this issue doesn't really address.

**Comment by CharlesFarr9** [comment]
Osman

I cannot send you a screenshot because the app does not perform the function that I am saying is missing.  If I miss a call on the Phone app on my iPhone, I can see, via the Recents list, all the calls I have made and received including missed incoming calls in red.

On the equivalent list in Signal I can only see successful calls (incoming and outgoing) and texts, but not missed incoming calls.  That is the shortfall I am referring to.  My proposed solution is that Signal shows missed calls in the same way as Apple’s Phone app.

Paul

**Comment by FredericJacobs** [comment]
Are you referring to behaviour prior to 2.1?

**Comment by CharlesFarr9** [comment]
When was 2.1 issued?  I noticed an upgrade today.  I am talking about behaviour prior to today.  I have not tested it today.
Paul

**Comment by FredericJacobs** [comment]
Today's release addresses missed calls. Example: https://twitter.com/FredericJacobs/status/610750338933620736

**Comment by CharlesFarr9** [comment]
You are quite right.  I just tested it.  I only mentioned it today and you’ve already fixed it. Brilliant.
Thanks
Paul

**Comment by CharlesFarr9** [comment]
Does Redphone now show missed calls?
Paul

**Comment by FredericJacobs** [comment]
Thanks for the feedback.
