### ISSUE TITLE
Cannot answer call on iPhone

### ISSUE THREAD

**Issue by CharlesFarr9** [WhisperSystems/Signal-iOS#816]
If a call comes in on Signal while my iPhone is sleeping, the process of waking it terminates the call.

**Comment by FredericJacobs** [comment]
What iOS version do you have?

**Comment by CharlesFarr9** [comment]
8.3
Paul

**Comment by FredericJacobs** [comment]
The sound of the ringing might stop when you unlock the phone but the vibration will continue and if you open the app you can reply to the call.

I strongly recommend you to swipe the notification message to the left to pick up or hang up a call straight from the lock screen.

**Comment by CharlesFarr9** [comment]
OK.  Thanks.  Will try.
Paul
