### ISSUE TITLE
Prevent the user from typing if message is too long

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/Signal-iOS#818]
I just received a message from a friend on Signal, I'm on textsecure. The message was (I will admit this) very long. However, it was trimmed. One sentence had clearly been cut short by the application (either her or mine) and now they have to resend the rest of the message. I'm assuming that since this happened, it is not clear to the user when the message will be trimmed.

**Comment by FredericJacobs** [comment]
@mcginty : Any guesses?

**Comment by oaim** [comment]
It may be related to https://github.com/WhisperSystems/TextSecure/issues/3362

**Comment by FredericJacobs** [comment]
AFAIK not a Signal-iOS issue.
