### ISSUE TITLE
Screen Security doesn't work?

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#819]
In versions prior to 2.1 Signal wouldn't show the name of the person who is calling or texting you if the screen is locked. Regardless of 'screen securing' setting, whether it's enabled or not.

After updating to 2.1 it shows the name of the people and a preview of the message. Which is super rad btw.

While `screen security` setting doesn't explain what it actually does, I believe the general assumption is that it would disable the preview and only show the name, or even go further and show that you've a message, without showing who is calling/texting you.

And this made me think maybe there should be two options under screen security section:
1- `enable name` (or caller-ID or whatever smarter name, one could come up with :)
2- `enable preview`

**Comment by FredericJacobs** [comment]
Screen security prevents the app switcher to save screenshots of Signal when switching apps.

If you want to hide notification body or sender, you can switch that in the notification settings.

**Comment by mrphs** [comment]
oh snap! I didn't even notice that in-app setting? when was it introduced? or was it always there? thanks for quick response. You rock! :+1:

**Comment by JohanDoe** [comment]
I have always wondered what this setting did. Now I know. Thanks. 

But maybe we should add an explanation under this setting in small letters (like you do in 2.1 under notifications and the 'known bugs in Apple's push framework' text). 

I had always assumed that it was some feature to protect me from people taking screenshots of my message (or notify me that a screenshot was taken as Wickr does on iOS). A feature that was yet to be implemented... ;-)
