### ISSUE TITLE
unable to verify my phone

### ISSUE THREAD

**Issue by olbaolba** [WhisperSystems/Signal-iOS#820]
after upgrading to 2.1 application did not oppen well it tell upgrading signal and nothing. i uninstalled and reinstall it but not able to verify the phone my country is spain i use iphone 5s ios 8.3.
before upgrade signal worked finely.

**Comment by FredericJacobs** [comment]
What do you mean by "not able to verify"? Do you get the verification code?

**Comment by olbaolba** [comment]
Yes i get the verification code and when i enter the code and press verify the phone it is searching but nothing happened no error message.
Sorry my english is not good 


Envoyé de mon iPhone 5S

**Comment by FredericJacobs** [comment]
- Quelle version de iOS utilises-tu?
- Ton iPhone est-il jailbreaké?

**Comment by olbaolba** [comment]
J'utilise iOS 8.3 non jailbreaké et ça a toujours fonctionné jusqu'à ce que j'installe la 2.1
Salut.

Envoyé de mon iPhone 5S

**Comment by olbaolba** [comment]
Salut toujours pas de solution.

Envoyé de mon iPhone 5S

**Comment by FredericJacobs** [comment]
Peux-tu re-essayer en clickant sur le lien qu'il y a dans le SMS?

Ainsi que d'essayer sur un autre réseau?

**Comment by HelenHengruiJiang** [comment]
I got exactly the same issue on iPad Air2 (Germany. It works neither in WiFi nor 3G/4G for me

**Comment by olbaolba** [comment]
oui j'ai essayé le link dans le sms et ça ne fonctionne toujours pas. Je ne l'ai pas encore essayé avec un autre réseau ni avec le 3g mais je le ferai.
Besoin d'aide, merci
--------------------------------------------
En date de : Lun 22.6.15, HelenHengruiJiang <notifications@github.com> a écrit :

 Objet: Re: [Signal-iOS] unable to verify my phone (#820)
 À: "WhisperSystems/Signal-iOS" <Signal-iOS@noreply.github.com>
 Cc: "olbaolba" <bet_suneor@yahoo.fr>
 Date: Lundi 22 juin 2015, 1h12
 
 I got exactly the same issue on
 iPad Air2 (Germany. It works neither in WiFi nor 3G/4G for
 me
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by FredericJacobs** [comment]
@HelenHengruiJiang Try again now.

**Comment by HelenHengruiJiang** [comment]
Works fine for me now (yeah!) Both devices, WiFi as well as 3G

**Comment by olbaolba** [comment]
Ça ne marche pas avec mon wifi. Je vais essayer avec le 3G et je vous tiens au courant.

Envoyé de mon iPhone 5S

**Comment by jeremymasters** [comment]
I have friend in the USA trying to install Signal Sunday night 9pm America/Denver time and they kept getting "could not connect to server" or something like that on both wifi and 4g. Is this related?

**Comment by olbaolba** [comment]
Je n'arrive toujours pas ni avec le wifi ni avec la 3G. Ça ne marche pas avec mon iPhone 5s en Espagne

Envoyé de mon iPhone 5S

**Comment by jeremymasters** [comment]
My friend's iPhone was able to register last night.

**Comment by olbaolba** [comment]
your friend did register with wifi or 3g?
--------------------------------------------
En date de : Mar 23.6.15, jeremymasters <notifications@github.com> a écrit :

 Objet: Re: [Signal-iOS] unable to verify my phone (#820)
 À: "WhisperSystems/Signal-iOS" <Signal-iOS@noreply.github.com>
 Cc: "olbaolba" <bet_suneor@yahoo.fr>
 Date: Mardi 23 juin 2015, 16h51
 
 My friend's iPhone was able
 to register last night.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by jeremymasters** [comment]
Friend did not say which was tried actually.

**Comment by olbaolba** [comment]
j'ai tout essayé et ça ne marche toujours pas. need help

**Comment by HelenHengruiJiang** [comment]
Update: lost connection again... Network status is always  offline, both wifi and 3G 
Log URL: https://gist.github.com/57a42d7c4fd76b3259a6

**Comment by olbaolba** [comment]
Now its works. I finaly can register.
 


     Le Jeudi 25 juin 2015 23h32, HelenHengruiJiang <notifications@github.com> a écrit :
   

 Update: lost connection again... Network status is always offline, both wifi and 3G 
Log URL: https://gist.github.com/57a42d7c4fd76b3259a6
