### ISSUE TITLE
Signal 2.1 suddenly displays message and sender on lock screen

### ISSUE THREAD

**Issue by jooize** [WhisperSystems/Signal-iOS#821]
> Improved notifications - See the message details you expect without sacrificing any privacy.

— Signal 2.1, 16 June 2015

Issue #808 requests the message in push feature, but also asks for it to be opt‐in.

I don't see how it can be an expected change in an app for secure communication to begin displaying message content and sender outside barriers (passcode) without asking. People in more serious situations may consider this a breach of trust.

Understandably, you want to make a user friendly app, but was this a good decision? How about a dialog box for users updating from earlier versions asking at launch if they want more information in push? More code, work, and it's an interruption for the user, but this is a serious change that may go unnoticed until someone gets sent a sensitive message in the wrong environment.

**Comment by FredericJacobs** [comment]
We decided to make this opt-out. The App Store release notes are explaining this change.
- the app needs to be opened before the change to become effective.
- if the phone is rebooted, the keying material won't be in memory and the messages won't be decryptable.

If you want to hide content-body, you can do so in the in-app settings >> Notifications >> Show

**Comment by jooize** [comment]
After thinking about it, I'm not at all comfortable with this change. People leave their phones in plain sight, and this means people in their proximity can now see what I send them by default.

Regardless of whether you want this for usability, I think it's irresponsible not to explicitly alert users of this change. How many people do you know who read the release notes every time before they start an app? I assume automatic updates aren't discouraged from a security viewpoint?

What are your thoughts about this?
