### ISSUE TITLE
Vibration with received message even if "do not disturb" and silent button active

### ISSUE THREAD

**Issue by hgascon** [WhisperSystems/Signal-iOS#824]
In an iPhone 5s, the device still vibrates every time a message is received in a chat with the application open, even if the silent button is turned on and the "do not disturb" function is activated. If the application is closed, the device does not vibrate as expected.

**Comment by FredericJacobs** [comment]
> If the application is closed, the device does not vibrate as expected

The app vibrates on an incoming message doesn't it?

**Comment by hgascon** [comment]
If the phone is blocked and in "do not disturb" function, the new message is displayed but there is no notification, sound or vibration. But if the app is opened and a new message arrives, it does sound or vibrate, even if the "do not disturb" function is still active. Is this the expected behavior?

**Comment by FredericJacobs** [comment]
Yes.

**Comment by FredericJacobs** [comment]
Note that this is a OS-setting. Might be silenced if you switch to "Always".

![img_2269](https://cloud.githubusercontent.com/assets/400296/8254838/eaa2b740-169b-11e5-9be6-036eb6504e7a.PNG)

**Comment by hgascon** [comment]
Yes, the option is set to "Always", that's why I found it strange. I have checked how this is handled in iMessage and it also vibrates with a very short vibration.

**Comment by FredericJacobs** [comment]
We call the system APIs that are handling that. I'm not planning to add any logic to handle the "Do Not Disturb" mode. Leaving that to Apple to device.
