### ISSUE TITLE
Long pressing an image should show "Save/Copy/Delete" options

### ISSUE THREAD

**Issue by rocknjohn** [WhisperSystems/Signal-iOS#825]
When in the conversation view, long pressing on an _unexpanded_ image should show "Save/Copy/Delete" options. This would provide a similar, intuitive behavior to the behavior that already exists for text messages where a user can long press to show "Copy/Delete" options for an individual text message.

**Comment by Zahlentheorie** [comment]
+1

Additionally, can't save sent videos yet.

**Comment by pstasiak** [comment]
I made some investigation. To implement this feature, some changes in pod `JSQMessagesViewController` are needed. I see that there is custom fork in `podfile` by @FredericJacobs. Do you see any potential problem in merging PR that I would make in `JSQMessagesViewController` repository to your fork? Did you made big API changes?

**Comment by michaelkirk** [comment]
closed long ago in #1105
