### ISSUE TITLE
Settings and authentication lost after restoring iOS from backup

### ISSUE THREAD

**Issue by alexschomb** [WhisperSystems/Signal-iOS#826]
I just moved to iOS 8.3 and had to restore my iPhone from iTunes backup. I noticed that all my Signal messages, settings and the authentication is lost and I had to start from scratch again. Most other apps still had their content and opened up like before. Is this a safety measure or a bug?

**Comment by FredericJacobs** [comment]
Right now this is a safety measure.

The issue is that if we let people backup with iTunes their Signal-related files, it would mean that iCloud backup would copy those files too which can be problematic for some users.

We have custom exports of content on the roadmap.

**Comment by alexschomb** [comment]
Cool, thanks for the super fast answer!

**Comment by frederiksnijder** [comment]
Hi Frederic, do you have any info on when you guys are going to add the custom export option?
cheers

**Comment by Sidnicious** [comment]
@FredericJacobs I think there's a better option: encrypt the app data and store the key in the Keychain. Keychain data is only recoverable from encrypted iTunes backups, not iCloud.

See Quinn Taylor's suggestion on the dev forums:
https://forums.developer.apple.com/thread/49317

> One option would be to encrypt your data with a key that you store in the keychain.  That way the data is only meaningful if the keychain key is included in the backup, that is, when the backup is encrypted.
