### ISSUE TITLE
After clearing history logs, all contacts show up as unavailable for messaging, but phone works.

### ISSUE THREAD

**Issue by brailleteeth** [WhisperSystems/Signal-iOS#830]
As in description..
Have initiated several successful voice calls, but all contacts show up as greyed out all of the sudden.
Running 2.1 on unjailbroken iOS 8.3 iPhone 6 16GB.

**Comment by FredericJacobs** [comment]
Make sure to pull to refresh in the new conversation view. They should re-appear. 

A long-term fix will be worked on.

**Comment by brailleteeth** [comment]
Thanks. Quitting app, opening and pulling to refresh seems to do the trick.
