### ISSUE TITLE
Secure screen not working

### ISSUE THREAD

**Issue by Dedal0** [WhisperSystems/Signal-iOS#831]
signal's secure screen feature (no screenshots) is not working in version 2.1 in iphone 5s ios 8.3...

I activated the feature but I can still take screenshots to conversations.

**Comment by FredericJacobs** [comment]
iOS doesn't let you prevent taking screenshots.

`Screen Security` only protects the screen from app switching screenshots on iOS.

**Comment by Dedal0** [comment]
You should try to implement something like alerting the other person as telegram does.

**Comment by FredericJacobs** [comment]
@Dedal0 : Keep in mind that there is no way to technically enforce any of this. Especially with the clients being open-source. In an adversarial threat model, nothing prevents "self-destruction" or screenshotting.
