### ISSUE TITLE
Deleting the last message does not update conversation list snippet

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#833]
1. Open a conversation that has more than one message
1. Delete the last message from that conversation
1. Return back to conversation list
1. The message snippet for that conversation is empty

iPhone 4S
iOS 8.3
Signal 2.1.1

(edit: modified the steps to be more explicit)

**Comment by michaelkirk** [comment]
> 1. Delete the last message from a conversation
> 2. Return back to conversation list
> 3. The message snippet for that conversation is empty

Is this your *desired* behavior, or are these steps to reproduce a bug?

To me, it seems like the desired behavior, and is in fact, what I'm seeing with latest master (2.3). 

Does this video capture the behavior you want to see?
https://vimeo.com/158448243

Are you able to reproduce with Signal 2.3?

**Comment by hubert3** [comment]
I can't seem to delete at all with Signal 2.3

The only action offered when I long press on a message is Copy

**Comment by hubert3** [comment]
Is deleting individual messages new in 2.3?

Signal 2.2 (current App Store version) on iPhone 6s, the only action offered on long press is Copy

**Comment by 2-4601** [comment]
@michaelkirk 
Those are the steps to reproduce the bug on the said device, iOS and Signal version.

> https://vimeo.com/158448243

Seems like that video shows an edge case where the bug coincides with the expected behaviour :)
What happens when you delete a message in a conversation that has more than one message?

> Are you able to reproduce with Signal 2.3?

I don't have 2.3 nor an iPhone :) Also I don't meet the minimum requirements for the SDK.

@hubert3 
Can't remember for sure but I think there's been a bug concerning deletion of messages in general. Deletion of individual messages has worked before though.

**Comment by michaelkirk** [comment]
@2-4601 I think I get it now...

Given a thread like this:

![initial-thread](https://cloud.githubusercontent.com/assets/217057/13686294/048f700e-e6ca-11e5-9732-ebd203c94f89.PNG)

And I see a thread preview like this:

![initial-thread-preview](https://cloud.githubusercontent.com/assets/217057/13686305/0b3f7c00-e6ca-11e5-9b60-550f89ab7bb4.PNG)

When I delete the last message "Final Message", then I see the thread like this:

![thread-with-deleted-message](https://cloud.githubusercontent.com/assets/217057/13686320/13478e92-e6ca-11e5-9a2a-1777d81b3b08.PNG)

And I incorrectly see a blank thread preview like this:

![broken-preview](https://cloud.githubusercontent.com/assets/217057/13686327/18b14e90-e6ca-11e5-9981-0ee510e89092.PNG)

But instead the thread preview **should** be updated to say "Penultimate message"
