### ISSUE TITLE
retry sending links doesn't work

### ISSUE THREAD

**Issue by JimLoose** [WhisperSystems/Signal-iOS#836]
it's better to have a red exclamation mark like in iMessage to retry sending messages, otherwise it doesn't work with links (because they open and cannot be send again)

![bild 2015-07-03 um 12 19 27](https://cloud.githubusercontent.com/assets/195000/8497487/df94cd24-217d-11e5-80d4-fe7ae2278697.png)

**Comment by 2-4601** [comment]
Related #834.

**Comment by JimLoose** [comment]
yea + more or less duplicate!

**Comment by 2-4601** [comment]
Just wanted to tag as related... didn't mean to say this was a duplicate :)
Though I admit the underlying issue is the same.
