### ISSUE TITLE
Skip RedPhone registeration

### ISSUE THREAD

**Issue by ali-nawaz-dev** [WhisperSystems/Signal-iOS#837]
Hi ,

Can anyone help me to skip Red phone registration in Signal iOS app.I am using latest version of code.Also will it effect on app working if it is skipped? If reply will be quick it will be much appreciated.

Thanks

**Comment by FredericJacobs** [comment]
This is a bug tracker, not a software consultancy service.

**Comment by ali-nawaz-dev** [comment]
There should be some comments over code or documentation over wiki showing how code behaving , otherwise I have no need to open this thread here.

**Comment by ali-nawaz-dev** [comment]
I beg your pardon but i think there should be some comments over code or documentation over wiki showing how code behaving , otherwise I have no need to open this thread here.
