### ISSUE TITLE
Onboarding UX could be improved

### ISSUE THREAD

**Issue by laktak** [WhisperSystems/Signal-iOS#840]
- I download the app and launch it
- Signal asks for access to all contacts
  - Since I'm not sure yet I decline.
- Signal asks for my phone number
  - I look for skip/help/etc.

The app should explain why it needs access to my contacts. Does it work without providing access?

There should be an explanation why you need my phone number, what you will use it for and why I need to verify it.

**Comment by riyapenn** [comment]
https://github.com/WhisperSystems/Signal-iOS/issues/665

**Comment by FredericJacobs** [comment]
Fixed in https://github.com/WhisperSystems/Signal-iOS/commit/c95f190140ba00048983d07289082e497d702947
