### ISSUE TITLE
Refresh chat (list)

### ISSUE THREAD

**Issue by Zahlentheorie** [WhisperSystems/Signal-iOS#847]
When a picture wasn't downloaded completely, e.g. caused by bad connection, it is not possible to download it afterwards. What about a pull down function which refreshes the chat (list)?

**Comment by FredericJacobs** [comment]
Attachment download UI should be refined. There are already a few open issues regarding that. Pull-to-refresh is not the appropriate user interaction for that kind of event however. Download progress indicators should be preferred with an option to let users restart a stalled download.

**Comment by Zahlentheorie** [comment]
Really good idea. Thank you.
