### ISSUE TITLE
Registration Error in 2.1.1 (Latest) on iOS 8.3

### ISSUE THREAD

**Issue by metrafonic** [WhisperSystems/Signal-iOS#852]
Im having trouble registering via the iOS app in Norway while trying to get my family to switch over to the service:

##### We couldn't reache the Signal server. Please try again.

Using wifi and 4G give the same results.

How can i assist?

Doing a:
    `curl master.whispersystems.org:31337`
Gives me:
    `curl: (52) Empty reply from server`

**Comment by metrafonic** [comment]
Nmap gave me the following:
Starting Nmap 6.40 ( http://nmap.org ) at 2015-07-14 21:47 CEST
Nmap scan report for master.whispersystems.org (66.175.212.82)
Host is up (0.15s latency).
rDNS record for 66.175.212.82: us-e0.whispersystems.org
PORT      STATE SERVICE
31337/tcp open  Elite

Nmap done: 1 IP address (1 host up) scanned in 0.62 seconds

**Comment by FredericJacobs** [comment]
Hey @metrafonic,

We are currently working on a fix. Affects most users. Will give updates as time passes.

**Comment by cimm** [comment]
I tried Signal a year or so ago and I couldn't register: the infamous "We couldn't reach the Signal server." error. I tried disabling wifi and using 3G or EDGE. Tried different phone numbers on different version of iOS, no luck. Today, a year or so later, I gave it a second try and... exactly the same issue.

People have been reporting this [here](http://support.whispersystems.org/customer/portal/questions/8221929-unable-to-register), [here](http://support.whispersystems.org/customer/portal/questions/11413449-registration-error-on-ios-8-1), [here](http://support.whispersystems.org/customer/portal/questions/12857987-unable-to-update-and-cannot-register-phone), [here](http://support.whispersystems.org/customer/portal/questions/10056179-registration-error), [here](http://support.whispersystems.org/customer/portal/questions/12980938-deleted-app-registration-error) and [here](https://github.com/WhisperSystems/Signal-iOS/issues/130) and all conversations go dark after a while. No solution.

It does work on an Android phone on the same wifi network.

I want to love Signal, RedPhone, TextSecure or however you want to call it and still believe it's the gold standard of text messaging apps but after multiple phones and multiple versions I haven't been able to have a single decent conversation via Signal. So please, please... if you don't care just tell us you don't care so we don't loose hope every time you promise this will be fixed.

Now, it's open source, we don't pay you and you spend your time fixing bugs. I get that. If that's the problem please explain the bug so we can all help improve Signal. That's what open source is all about.

**Comment by v6** [comment]
// , My friend @jay-a-elliot, who cannot post this now, had a previously working Signal on version 2.0. 

Version 2.1 breaks his app. 

![2015-07-14](https://cloud.githubusercontent.com/assets/5750764/8691350/4f331ffe-2a76-11e5-853c-1c025fcb571e.png)

Since 2.0 was working, for him, can he revert back to it and still maintain compatibility with the overall Signal Network?

**Comment by raduzl74** [comment]
Same issues on iOS 8.4 with Signal 2.1.1 - when a call is initiated says "Client Failed!"

**Comment by Zahlentheorie** [comment]
@v6 Same issue on the phone of a friend of mine.
@raduzl74 Same here!

**Comment by moxie0** [comment]
With apologies, there's now an update in the app store which should resolve these issues.

**Comment by cimm** [comment]
@moxie0 Thank you! Care to explain why this happens from time to time? This seems like a recurring issue and it would be nice to understand what is happening. Thank you for your hard work!

**Comment by ndrewh** [comment]
master branch still has this issue...not sure why the fix hasn't been pushed here.

**Comment by v6** [comment]
// , As far as I know, my friend has it working.

**Comment by hubert3** [comment]
Getting the same issue on iPhone 6s iOS 9.0.1 right now after upgrading from iPhone 6 which was working fine.

**Comment by franks42** [comment]
Same registration issue on iphone 6 IOS 9.1 with freshly downloaded signal app from store today.

**Comment by bismuth** [comment]
This issue persist on newest IOS on an iphone 6 with the newest version of the app.

**Comment by FredericJacobs** [comment]
@bismuth @franks42 : Can you retry? Does enabling "Background Fetch" in the settings change anything?

**Comment by bismuth** [comment]
Excellent! This fixed it without enabling Background Fetch, but it took me a few retries before the submitted verification code was accepted. I got two "server replied with status 0" (or something like that) messages before that. But thank you very much!

**Comment by raduzl74** [comment]
Hi,

I tried calling people on Signal but it does not work. Please fix the issue.

Radu

Please excuse brevity and typos. Sent from my iPhone.

**Comment by v6** [comment]
// , Radu, is this the same issue as described here: https://github.com/WhisperSystems/Signal-iOS/issues/852#issue-95005188

?

**Comment by 2-4601** [comment]
@v6 It was most likely this: #1115

**Comment by raduzl74** [comment]
Yes

Radu

Please excuse brevity and typos. Sent from my iPhone.
