### ISSUE TITLE
Turn Off Screen During a Call to Conserve Battery

### ISSUE THREAD

**Issue by caveman1973** [WhisperSystems/Signal-iOS#854]
Just use the sensor to turn screen off to conserve battery and avoid pressing a button by mistake.

**Comment by FredericJacobs** [comment]
@caveman1973 : Isn't this happening? It's supposed to. Detection using proximity sensor should be enabled.

**Comment by caveman1973** [comment]
Sorry, didn't realize it worked like that in latest version.
