### ISSUE TITLE
URGENT: Not working in France.

### ISSUE THREAD

**Issue by gittyfrance** [WhisperSystems/Signal-iOS#855]
Signal/ Redphone is having sudden problems in France since two days ago. Calls can not be initiated from France, yet calls can be received on Redphone. SMS registration confirmation is not working.

Same problem with Signal on iOS. Signal even can't receive calls. After re-installing Signal, even the registration could not be done.

No problem detected with Textsecure or Signal's text messaging system.

The mobile network operator is free.fr for BOTH cases.

Same issue reported on Redphone's Github page.

**Comment by moxie0** [comment]
One issue is enough.  It sounds like you need to update to the latest version of Signal (released 2 days ago).

**Comment by gittyfrance** [comment]
Ok. Trying again. 

However, the Redphone call initialization problem(can receive calls, but not initialize calls) on French carrier Free.fr is still persisting.

Thank you Moxie for this instantaneous reply. :+1:
