### ISSUE TITLE
Resend function is triggered although message was delivered

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#860]
One of my TextSecure contacts occasionally sending me the same messages multiple times because TextSecure incorrectly states that the message was not sent and asks for a resend.  Yesterday, the same happend to me using Signal.  My messages arrived multiple times because I hit resend until Signal stopped asking me to resend the message.   Even though this is affecting only one of my contacts, it turns the resend function into a little spam canon.

**Comment by FredericJacobs** [comment]
Duplicate #951
