### ISSUE TITLE
Need to disable send text message sound on iOS 8 / 9

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [WhisperSystems/Signal-iOS#867]
Every time sending a message, a sound is made. Just like iOS Messages app allows you to disable this (respects the Settings, Sounds, Text Tone = None) , the Signal app should respect this field too or provide another option to disable send message sounds. The current option to disable notifcation sounds DOES NOT prevent the sending text sound, at least on iOS 8 / 9. Another user mentioned this here:

http://support.whispersystems.org/customer/portal/questions/11656891-sound

**Comment by neoxic** [comment]
I'd vote up.

**Comment by danrl** [comment]
Same here. It is annoying. What is the reason for having a sound on *sending* a message anyway? It should be disabled by default.
Of course the app should respect my setting of "Settings, Sounds, Text Tone = None" or at least provide an option disable the sending-sound.

**Comment by stefan-sels-flaconi** [comment]
Tried to disable sound did not find any setting. Does make sounds even iOS phone is in do not disturb mode.

**Comment by riyapenn** [comment]
In the mean time, toggling the silent/vibrate button on the outside of your device will silence your message sending tone. 

@stefan-sels-flaconi Do Not Disturb mode is only set for when your device is locked. See Apple's page here: https://support.apple.com/en-us/HT204321

**Comment by stefan-sels-flaconi** [comment]
@riyapenn true my mistake. But where does it choose the sound from? Will clone & dig later ....

**Comment by stefan-sels-flaconi** [comment]
That hardware button works!! Never used that button as I temporary switch from android to iOS recently!! Thank you!

**Comment by michaelkirk** [comment]
This was solved in the 2.6.5 release thanks to @lazerwalker

**Comment by scottialex** [comment]
Hello, has this been resolved? today is July 2019 and I'm switching from WhatsApp to Signal and I can't find a way to mute the sound when I send a message. In my iOS configuration Sounds & Haptics I have everything disabled and Signal is the only app that's making the sound...

Thank you

**Comment by u32i64** [comment]
@scottialex I think the `Signal Settings -> Notifications -> Play while App is Open` toggle affects **all** sounds related to messages (including sending them) while Signal is open.

Also there's no need to spam the same message to two issues (this (#867) and #998).

**Comment by scottialex** [comment]
Excellent! thank you <3
