### ISSUE TITLE
Call button is too easy to hit

### ISSUE THREAD

**Issue by bkudria** [WhisperSystems/Signal-iOS#868]
I've accidentally initiated an unwanted call many times, because I hit the phone button. This button could really use a confirmation sheet, to confirm the call.

**Comment by vingtdeux** [comment]
+1 

This has happened to me countless times. I'm on the receiving end of these frequently enough that I automatically dismiss calls from people I'm messaging with, assuming they didn't mean to call me. It's nice to have the icon there to be able to get to the calling function efficiently, but a confirmation would be quite helpful.

**Comment by FredericJacobs** [comment]
This is a design decision. Won't change for now but will keep in mind for future design iterations.
