### ISSUE TITLE
ios9 beta2 - signal doesn't work

### ISSUE THREAD

**Issue by JimLoose** [WhisperSystems/Signal-iOS#869]
jfyi (please close this issue, if you are aware of it)

- i upgraded my iphone to ios9 beta 2 and signal worked flawless
- i installed signal on a fresh new vanilla iphone with ios9 beta2 and signal doesn't work anymore ( it can't find my contacts or open the settings in the upper left corner

**Comment by FredericJacobs** [comment]
Aware of it. Can't do anything about it now but will work on iOS9 final release
