### ISSUE TITLE
Explain how this can cost $0

### ISSUE THREAD

**Issue by i7u** [WhisperSystems/Signal-iOS#87]
We have been educating end users for years to be _very_ sceptical of free stuff online. "If you're not paying for it, you ARE the product", etc. As a result, people who are not aware of Free Software or the history of WhisperSystems will naturally be sceptical as to the level of trust they can place on this (amazing) service. It literally sounds too good to be true.

I know it's not trivial, but it would be great to have a short writeup/video explaining how you can pull this off. http://support.whispersystems.org/customer/portal/questions/5836104-how-is-openwhispersystems-paying-for-the-its-server-costs- is not enough and really, just talks about covering costs. Not about the fact you're not in this for the money.

**Comment by corbett** [comment]
support.whispersystems.org
