### ISSUE TITLE
Register Signal with TextSecure using SMS Verification 

### ISSUE THREAD

**Issue by drakula84** [WhisperSystems/Signal-iOS#870]
From what I see when I follow the flow starting in RegistrationViewController code, initial user registration is done with RedPhone using the sms code, then RedPhone returns a token to use when registering with TextSecure server. 

Does anybody know of any effort to get a Signal user register directly (and perhaps only) with TextSecure server? Then, would Signal work as a text only application like TextSecure Android? Would contacts etc. be resolved with TextSecure server without RedPhone?

**Comment by moxie0** [comment]
@drakula84 Welcome to our issue tracker.  Please keep in mind that this is not a discussion forum, if you would like Q&A please see the mailing list or the support center.
