### ISSUE TITLE
Most UI elements are blank on iOS 9

### ISSUE THREAD

**Issue by rex4539** [WhisperSystems/Signal-iOS#872]
Using iOS 9 and most UI elements appear blank.

**Comment by rex4539** [comment]
![img_3428](https://cloud.githubusercontent.com/assets/227442/9348565/a37c25a6-4641-11e5-82eb-d36bd3b7dbfa.jpg)
![img_3429](https://cloud.githubusercontent.com/assets/227442/9348564/a377acc4-4641-11e5-9e52-1d2a5c0a5a86.jpg)

**Comment by FredericJacobs** [comment]
We are well aware of the problem. It's on Apple's end and we will make sure it doesn't happen in final release but we aren't supporting iOS 9 beta software.
