### ISSUE TITLE
Multiple Text Secure/Signal numbers in contact card not well supported

### ISSUE THREAD

**Issue by elfstones65** [WhisperSystems/Signal-iOS#873]
Hi I have a friend called Chris, he has a work number and personal number, both were registered with Text Secure, When adding Chris to a group there is no option choose which number to add, It just adds both. An agent on the forum did mention currently the numbers need to be in different contact cards. Obviously this is counter productive to how contacts work now days vs the old one number per contact cards in the storing numbers on sim card days.

**Comment by riyapenn** [comment]
Similar solution in #721

**Comment by FredericJacobs** [comment]
Replaced by issue proposing solution #721
