### ISSUE TITLE
Unnecessary "View" action in user notification

### ISSUE THREAD

**Issue by kiliankoe** [WhisperSystems/Signal-iOS#875]
When swiping a notification to the left on the lockscreen I get an action labeled view. This is what already happens when swiping any notification to the right.

![screenshot](https://i.imgur.com/FzrYmLR.jpg)

**Comment by FredericJacobs** [comment]
This is a design decision. It will be changed in iOS 9

**Comment by kiliankoe** [comment]
Oh cool, thanks for the heads up! Looking forward to it.
