### ISSUE TITLE
Signal On Linux PC

### ISSUE THREAD

**Issue by PowerPress** [WhisperSystems/Signal-iOS#882]
I love Signal please create a linux version that can be ran from a PC. Additionally could it over TCP so it would support Tails/Tor? I love this app I would feel much more secure if I could run it from a trusted PC instead of depending on baseband hardware that is non open source.

Thanks

**Comment by FredericJacobs** [comment]
This is a bug tracker for Signal on iOS.

Side-note: We are working on a desktop version: https://github.com/WhisperSystems/TextSecure-Browser
