### ISSUE TITLE
Incoming call alert should offer single-touch "Answer" button

### ISSUE THREAD

**Issue by i7u** [WhisperSystems/Signal-iOS#883]
When we receive an incoming call and the user has selected "Alerts" (vs "Banners") in the "Notifications" settings of iOS, a white window pops up.

1. It does not indicate who is calling us.
2. It offers two options: "Reject" and "Options" (loosely translated from the non-English UI I recently observed), so if one wants to, say, answer the call, one needs to tap "Options" and then tap "Answer".

This is cumbersome and breaks the user's expectation that a phone call will provide an accept/deny choice. I believe an "Answer" button should be readily accessible when Signal rings with an incoming call.

**Comment by FredericJacobs** [comment]
It's not possible to show anything else than "Close" and "Options". These are system dialogs we have no control over.
