### ISSUE TITLE
Latest update crashes on launch 

### ISSUE THREAD

**Issue by knesmith** [WhisperSystems/Signal-iOS#888]
Steps to reproduce:
1. Install update
2. Launch Signal
Result: immediate crash. Never see any of the UI.

iPhone 6+ running 8.4.1

**Comment by FredericJacobs** [comment]
I assume you were not registered when that happened?

**Comment by psifertex** [comment]
I had the same problem -- uninstalling and reinstalling fixed it for me.

**Comment by FredericJacobs** [comment]
Fixed on branch.
