### ISSUE TITLE
Some languages not possible to use

### ISSUE THREAD

**Issue by ksl82** [WhisperSystems/Signal-iOS#889]
Since the app relies on the iPhone's language settings, this leaves out some translations that aren't included in iPhone's language options.  Shona would an example.  Any possibility of having a language setting for Signal independent from the phone settings?

**Comment by FredericJacobs** [comment]
iOS localizations depend on the system's setting. Adding an additional localization layer requires additional work that we can't prioritise now.

This also goes against some of our design principles where we would be duplicating settings that already exist in the Settings app. I would love to see Apple add support for Shona and other languages missing in iOS.
