### ISSUE TITLE
iOS 9 Beta testing

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#890]
Apple now allows us to have beta-testing with iOS 9 devices.

If you're running iOS 9 and would like to help us test Signal for iOS 9, feel free to drop me your AppleID at fred@whispersystems.org and I'll add you to the TestFlight testing program.

**Comment by freddymartinez9** [comment]
Is this still needed @FredericJacobs ? I would be willing to help, should I email my AppleID?

**Comment by FredericJacobs** [comment]
We have enough testers for now. Thanks for offering though.
