### ISSUE TITLE
Feature Request: Allow speaker phone before the call is answered

### ISSUE THREAD

**Issue by jackflips** [WhisperSystems/Signal-iOS#895]
It is useful to hear the ringing on speaker phone before the call is answered. I do this often in the regular phone app.

**Comment by mmkassem** [comment]
:+1:

**Comment by ianstrasser** [comment]
👍

**Comment by michaelkirk** [comment]
Please don't bump issues. Feel free to "Add your reaction" to the parent post if you want to voice your support.

**Comment by cwmke** [comment]
I'm a bit confused.  Is this suggestion similar to the proximity sensor used with some phone apps?  For example, when the phone is away from your face, it automatically uses speaker phone.  Am I understanding correctly?

**Comment by ianstrasser** [comment]
Not quite. This is simply a UI/UX issue that can be fixed fairly quickly. When you place a call on a system caller, or with most other VOIP apps, before the other person picks up, you have the option to mute the call, put it on speaker, and so on. However, unlike what users are expecting Signal does not let you do any of these things until the call has been connected.

**Comment by cwmke** [comment]
Thanks for the explanation.  That makes clarifies everything nicely. 😃

**Comment by jackflips** [comment]
@michaelkirk would this contribution be welcome?

**Comment by TreatyOfRome** [comment]
This issue has been resolved. Currently, mute, speaker and video/audio mode switch are available during 'connecting', 'ringing' and 'answered' calling phase.
