### ISSUE TITLE
Rating pop-up translation weirdness.

### ISSUE THREAD

**Issue by Geblaat** [WhisperSystems/Signal-iOS#896]
Today when I open Signal I got a pop-up(assuming it's about adding a rating in the app store), but some untranslated strings are not in English. Shouldn't untranslated strings be shown in English? 
![812710953_52983_13674271321791577277](https://cloud.githubusercontent.com/assets/11456685/9907767/ebb62df2-5c90-11e5-9f78-c0099b3d7d24.jpg)

(iPhone 5, iOS 8.4.1, Signal 2.1.3)

**Comment by FredericJacobs** [comment]
Looks like translation is now up on Transifex. https://www.transifex.com/open-whisper-systems/signal-ios/viewstrings/#nl/localizablestrings-30/29312261

It's more likely an mistake on my end before release where I uploaded the new strings to transifex but forgot to fetch the updated strings. (This is the result of a missing key in the localization file)
