### ISSUE TITLE
iOS 9 fresh install + backup restore / no messages

### ISSUE THREAD

**Issue by temp140801** [WhisperSystems/Signal-iOS#901]
- two existing threads in Signal
- updated to latest Signal
- backup to iTunes x64 Win7
- clean install iOS 9
- restore from backup
- Signal prompts mobile number registration
- "register" with new SMS code
- no chat history, all blank
- can send new messages; not check if received; not tested calls

**Comment by FredericJacobs** [comment]
This is an intended decision to avoid having messages leak to iCloud backups.

We will eventually work on our own backup feature with an additional layer of encryption to prevent leakage of plaintext.

**Comment by NiklasBr** [comment]
Hi @FredericJacobs, any news on your own backup feature? Can I pledge some amount to get it started?

**Comment by NiklasBr** [comment]
@FredericJacobs Any news on the backup feature?

**Comment by u32i64** [comment]
@NiklasBr Backup isn't supported in Signal iOS yet. Here's a more [in-depth explanation why](https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones/1736/182?u=u32i64). However, it has recently become possible to [transfer your data to a new iOS/iPadOS device](https://support.signal.org/hc/en-us/articles/360007059752#ios_restore).

**Comment by NiklasBr** [comment]
I had just read it and found it severly lacking. Which is why I returned hereto ask for an update.
