### ISSUE TITLE
Signals new key detection issue

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/Signal-iOS#903]
I do not use Signal but friends of mine do. I'm reporting what I discovered.

You have a Signal user and a TextSecure user. The TextSecure user gets a new phone so he has a new key. The Signal user doesn't see the change of keys. He is able to read messages from the TextSecure user. If he sends a message to the TextSecure user the TextSecure user can't read it because it was encrypted with the old key from the old phone. To fix it I've tried to end the crypto session on in Signal but it didn't fix it. The Signal user and the TextSecure user both needed to end the session. Then Signal needed to do a refresh of the user list to see the new key and it started to work again.

**Comment by FredericJacobs** [comment]
Not enough information to be actionable.

**Comment by gladiac** [comment]
Why do you close the ticket instead of asking for more information? Did you try to reproduce it?

**Comment by FredericJacobs** [comment]
I see some cases where this might happen and I will look into those but information provided in this ticket doesn't provide any additional actionable information than what we already have in other issues.

**Comment by gladiac** [comment]
Ok, which ticket should I follow then, as this seems to be a duplicate?

**Comment by FredericJacobs** [comment]
I might need some additional debugging information that should remain private, drop me a line at fred@whispersystems.org so we can look into it and get logging material to figure out what's going on.

Keep in mind that this is a bug tracker, not a support forum! As long as it's unclear what the bug is and that there is no actionable information, it's not of any use here.

Support is available at support.whispersystems.org.

**Comment by gladiac** [comment]
I do not own an iPhone. That's why I described how to reproduce the issue. Normally it is better for a developer to reproduce the issue by yourself so you can either attach a debugger or test with changes to the code (adding more debug message).

So are you not able to reproduce the issue yourself? Should I try to reproduce it again like explained in the description of this bug report?
