### ISSUE TITLE
Signal doesn't get group messages after new key has been generated

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/Signal-iOS#904]
Hello,

a friend of mine killed his iPhone with a bucket of water. He was a member of a group X. He gets his new phone, installs Signal. The TextSecure users get a notification sending a message to the group that the Signal user has a new key and they should verify it. They verify the new key of the Signal user. TextSecure users are able to send direct messages to the Signal user, but all messages sent to the group X are not received (or handled) by the Signal.

A new group needs to be created so that Signal receives messages again ...

**Comment by FredericJacobs** [comment]
This is a protocol issue, we are well aware of the situation. Many duplicates in the Signal & TS repos.

**Comment by gladiac** [comment]
So which is the orginal ticket I can follow? The fix would be group management (add possibility to remove a user from a group)?
