### ISSUE TITLE
Signal huge cellular data usage

### ISSUE THREAD

**Issue by mmkassem** [WhisperSystems/Signal-iOS#908]
I was checking my cellular data usage on iOS 9.1 public beta and I found that Signal has used 1.6 GB of data despite that I have only used it a few times. It is 15x what Whatsapp has used in 2 years.

**Comment by liliakai** [comment]
dupe #866

**Comment by ghreat** [comment]
It is still a problem, mine is at 2.4 GB cellular data, and I haven't used it much either. Almost no other apps comes even close to use as much data om my iPhone 6+ with iOS 9.3.1.

**Comment by monomeric** [comment]
Why is this closed? It remains a problem, e.g., receiving a short, 20 character text earlier today used up about 300 kB! iPhone 4S, iOS 9.3.2.
