### ISSUE TITLE
Disable call icon for unregistered number

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#910]
1. Open existing conversation with A
2. After message fails to send to A because of "Unregistered Number"
3. Messaging is disabled (no input field)
4. *BUG* Calling is still enabled.  Disable call icon.

**Comment by FredericJacobs** [comment]
This is because the number is still in the bloomfilter. Not a programming bug. People can still unregister from RedPhone and TextSecure independently for now.
