### ISSUE TITLE
Dropped calls signal-to-signal

### ISSUE THREAD

**Issue by michaelpro** [WhisperSystems/Signal-iOS#912]
This is for iOS 9.0 talking to iOS 8, iPhone 6 Plus, iPhone 6  iPhone 5s. Debug log sent.

**Comment by michaelpro** [comment]
Log URL: https://gist.github.com/200570088f3b2c40d0ba

**Comment by FredericJacobs** [comment]
Noted, thanks

**Comment by michaelpro** [comment]
Calls between three people are dropping very frequently. Most calls last less than a minute. I can arrange for more debug logs. I would also be happy to assist in any testing  of fixes

**Comment by zbroyar** [comment]
Yesterday I had 7 drops in 10 minutes.

**Comment by FredericJacobs** [comment]
A servers-side change addressed this issue.
