### ISSUE TITLE
Cannot delete a message in a conversation

### ISSUE THREAD

**Issue by mmkassem** [WhisperSystems/Signal-iOS#913]
The users should be able to delete a single (or multiple) message(s) they have either sent or received.

iOS 9.1 public beta
Signal 2.1.3

**Comment by michaelkirk** [comment]
I might be misunderstanding, but it seems like this has been around for a while:

Does this video capture the behavior you want to see?
https://vimeo.com/158448243

If not, can you provide more detail?

**Comment by wdormann** [comment]
That shows deleting a failed message.   I see no way of doing that for a successfully sent or received message.
