### ISSUE TITLE
problem installing pod - Error installing SocketRocket

### ISSUE THREAD

**Issue by plenio** [WhisperSystems/Signal-iOS#915]
When I try to compile Signal on Xcode 7, I can't get it to work. 
I try to do pod install, but I get Error installing SocketRocket
When I remove the specific build in the Podfile, everything seems to work.

**Comment by FredericJacobs** [comment]
Make sure to check out the `iOS9` branch. With changes in CocoaPods and dependencies, some things might not resolve on master.
