### ISSUE TITLE
High speed Tor-like systems for v3.0 Milestone

### ISSUE THREAD

**Issue by Baigle** [WhisperSystems/Signal-iOS#916]
http://arxiv.org/abs/1507.05724v1?utm_source=webopsweekly&utm_medium=email

**Comment by FredericJacobs** [comment]
Thanks but this is a research paper. 

We can't do everything at once. Tor's mission is to work on anonymity, we are working on private messaging. If you need circumvention or anonymity, that's Tor's project job.

Side-note: There is currently work being done on porting Tor on iOS but it will take some more time for it to be able to work properly given backgrounding restrictions.

**Comment by Baigle** [comment]
There is an app for it :)
