### ISSUE TITLE
Can't create contact within the app

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#919]
When a new contact messages me and I tap on "create a new contact" I can see the contact info page and can input info, but a there's an object covering the top nav bar that doesn't let me go back or save the contact info.

The only workaround for this, is to close the app.
![signal](https://cloud.githubusercontent.com/assets/453701/10560570/6eb5b8e6-74fe-11e5-8bd8-193d3b0e4e76.png)

**Comment by FredericJacobs** [comment]
It's an iOS9 bug. Thanks for the report, we were already working on this. Closely tied with #898

**Comment by FredericJacobs** [comment]
More info. 
http://stackoverflow.com/questions/32973254/cncontactviewcontroller-forunknowncontact-unusable-destroys-interface

**Comment by michaelkirk** [comment]
Fixed in 2.12
