### ISSUE TITLE
The "ding" sound

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#921]
In the past there was this loud "ding" sound you'd hear right after the connection was established, which in a ear-hurting way :confounded: ;) implied the encryption was in place. But I haven't been hearing it for a while and just recently I've been hearing it in random times usually 10-15mins after the call is initiated. And it makes me wonder every time... Was I just talking in clear all this time?

**Comment by rocknjohn** [comment]
I see this same issue. Call is connected, we talk for a few minutes or more, and then the loud ding for signaling that the connection is secure occurs.

**Comment by caveman1973** [comment]
Same here. Didn't knew it was a "connection established" ring.

**Comment by rocknjohn** [comment]
I believe this can be closed now

**Comment by michaelkirk** [comment]
Thanks @rocknjohn
