### ISSUE TITLE
Invite contact button does not work

### ISSUE THREAD

**Issue by mattiaswillen** [WhisperSystems/Signal-iOS#922]
None of my contacts have Signal so I'd like to invite someone. When I press the Invite contact button in the message compose view, the compose view closes and nothing happens.
1. Open Signal
2. An empty Inbox is shown
3. Tap on the + button
4. The message compose view is shown with an empty contact list
5. Tap on the Invite contact button/link
=> Nothing happens, I'm back at step 2.

Signal has been granted access to contacts and notifications are enabled.

**Comment by roxton** [comment]
I have the same issue on iOS 9.1.

**Comment by Saadat1** [comment]
I have the same problem too and there is not any message view , just can call. I deleted app and reinstall it but the problems persist; iPhone 5s , IOS 9.1.

**Comment by aaugusta** [comment]
Workaround - restart phone. You will appear as the single contact. To invite users, send a message to a manually typed phone number.

**Comment by aaugusta** [comment]
Workaround - restart phone. You will appear as the single contact. To invite users, send a message to a manually typed phone number.

**Comment by pranavbhatt** [comment]
+1

**Comment by FredericJacobs** [comment]
Fixed

**Comment by Ineluctable** [comment]
Has the fix been published? I am still having this issue.
