### ISSUE TITLE
Spinner in contact list doesn’t spin (2.2 beta)

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#927]
Contact discovery seems to work just fine, but the loading spinner appears to be frozen.

**Comment by maltemayer** [comment]
Rebboting the iPhone seems to help.

**Comment by FredericJacobs** [comment]
Was it related to #929, happening in same session? If so, I think they were related to the graphics stack corruption.

**Comment by maltemayer** [comment]
I think the iOS animation bug causes this as well as #929, too.
