### ISSUE TITLE
Some transitions missing (2.2.1 beta)

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#929]
Everything regarding the image selection shows up pretty sudden.
When you want to delete a conversation but swipe back after it’s locked in place and the red trash bin icon is shown.

**Comment by maltemayer** [comment]
Rebooting the iPhone seems to help.

**Comment by FredericJacobs** [comment]
You had a corruption in your graphics stack. I think some graphics operations trigger this but it's a bug in iOS animation libraries. Nothing we can track now and not limited to the beta. Thanks for the report though.
