### ISSUE TITLE
iOS Lockscreen notification of new messages separate

### ISSUE THREAD

**Issue by kwolk** [WhisperSystems/Signal-iOS#932]
I just got two messages on my iDevice and noticed on the lock screen that each notification of a new message is separate, could the notification not be updated with a number?

**Comment by FredericJacobs** [comment]
I'm not sure I understand what the issue is?
You got the notification twice?

**Comment by kwolk** [comment]
If possible the message should only take up one slot, if there's more than one message then this should be signified by a number and not multiple messages in my opinion, which obviously pushes out other messages and just looks like spam .

**Comment by michaelkirk** [comment]
FWIW native iOS message app posts a notification per message. 

![img_0225](https://cloud.githubusercontent.com/assets/217057/13031974/1138d890-d2a7-11e5-8259-676d6e5306fb.PNG)

**Comment by michaelkirk** [comment]
I believe the existing behavior is correct here.
