### ISSUE TITLE
REGISTER_CONTACTS_WELCOME first dialog box

### ISSUE THREAD

**Issue by tallakt** [WhisperSystems/Signal-iOS#935]
After downloading Signal from the App store, I was greeted with a message box saying REGISTER_CONTACTS_WELCOME, REGISTER_CONTACTS_BODY, REGISTER_CONTACTS_CONTINUE

![img_1160](https://cloud.githubusercontent.com/assets/49966/10931972/d3c1e332-82cc-11e5-8d9b-2b8dc0488f15.PNG)

Signal version 2.1.3 / Iphone 6 / iOS 9.1

**Comment by FredericJacobs** [comment]
What language are you using?

**Comment by tallakt** [comment]
Norwegian I guess..

**Comment by FredericJacobs** [comment]
Alright, my bad. Probably my script forgot to update the Norwegian translations. Will fix in next release.

**Comment by tallakt** [comment]
:blue_heart:

**Comment by FredericJacobs** [comment]
Thanks for the report :)

**Comment by svalgaard** [comment]
I have exactly the same issue with my Danish iPhone - I guess that more languages might be missing.
