### ISSUE TITLE
Feature suggestion: Make screenshots useless as evidence

### ISSUE THREAD

**Issue by Joshfindit** [WhisperSystems/Signal-iOS#936]
There are two main ways the security can be compromised:

1. Interception by a third party
2. Leakage by a trusted party

Signal eliminates the possibility of third party Interception, but still allows the trusted party to make a record that can be used to incriminate a sender.

Restricting screenshots is not technically feasible, so how can we make that screenshot useless?

One suggestion: flatten the conversation

An example:

![signal suggestion, no bolding](https://cloud.githubusercontent.com/assets/1937155/10946110/ddbe61ce-82f6-11e5-87be-38a3d3be046b.jpg)

As the conversation is between two people, any important information is passed along successfully without identifying who said what.

To bring in the benefits of delivery status information, other indicators can be used, such as dimming out any information that is not yet shown to both parties:
![signal suggestion with bolding](https://cloud.githubusercontent.com/assets/1937155/10946202/57c61110-82f7-11e5-89b7-a52de95cddb4.jpg)

If implemented, it would need to be set for both parties with no option for either person to change it locally in order to be truly effective.

**Comment by mikeokner** [comment]
IMO this is a bit off in the weeds. A better approach might be something like showing an indicator in the conversation that a screenshot was taken. I can't imagine anyone wanting to use an interface that's borderline unintelligible. There's no "truly effective" way to prevent an intended recipient from sharing something you've sent them, regardless of platform.

**Comment by mxmerz** [comment]
I guess both of these approaches might be [dismissed](https://github.com/WhisperSystems/Signal-iOS/issues/846#issuecomment-122382213) for offering no reliable protection against attackers who use a modified version of Signal.
**Idea, possibly stupid:** Make it very easy for users to produce fake screenshots and thus undermine the credibility of Signal screenshots in general.

**Comment by Joshfindit** [comment]
A modified version of signal wouldn't be deterred by what I proposed. Agreed.

Being able to easily produce fake screenshots would solve the same problem, especially if it meant being able to add your own text to the conversation, so that (non-authoritative) screenshots could be taken the regular way.

**Comment by Joshfindit** [comment]
Also, the ability to delete messages, and change the timestamp.

The more I think about this idea, the more it grows on me.
If either side can take a screenshot which looks different than the other side, which one is the truth?
With the app systematically allowing changes to everything that can be used to verify the messages, there's no way to tell.

**Comment by FredericJacobs** [comment]
This is not going to be implemented.

 You can make an app to generate fake screenshots if you really want this or some Photoshop template ...
