### ISSUE TITLE
Checks aside from gpg key to ensure it's not a MITM? Device ID? I noticed, due to the nature of 'apps'. I can both restore from a backup (titanium backup), without revalidating myself, as well as send message without sim.

### ISSUE THREAD

**Issue by modoj** [WhisperSystems/Signal-iOS#944]
I'm sorry for the vague title, I'm not too sure how to phrase that. My concern is a MITM attack.

I'm only familiar with the Android app, so my apologies if this does not apply to Signal as a whole.

This came out of a conversation with a friend on defeating Signal. I understand that if a pass-phrase is in place (and it should be! What's the point of encryption without a pass-phrase OTHER than to, shoddily, prove your identity), but if one isn't, it defeats the purpose of using whatsoever. With physical access, I could (correct me if I'm wrong here) back up the app, with its database, and gpg key in-tact, place it on another device and effectively MITM. Yes? 

Of course, as said, this depends on the user not using a pass-phrase. Some might say they are asking for it, but it's a users choice, and with opening up such technology to the masses (which I love, and wholeheartedly support, keep up the awesome work! You succeeded in much I have failed to do, get my family to encryption! And it's SOOOO EASY!), many are going to forego the pass-phrase, feeling they are safe enough if no one will have physical access.

Not using a pass-phrase is still useful in most of the ways Signal is, it encrypts the in-transit message and identifies the parties as valid. But it's no-where as secure as it would be if both ends are pass-phrase protected. 

I myself would like to see a way to verify a contacts fingerprint personally, but it's been said that this feature will not be implemented. https://github.com/WhisperSystems/Signal-iOS/issues/739

My suggestions would be a more thorough validation scheme. Check gpg-key against the device-id, or sim card number, or whatever other identifying info, if there isn't a match, ask the user about it, much like Titanium Backup does after first used on a new device, with an old app profile, but instead, have options for the user to re-validate themselves, through e-mail, or text message, what-have-you. I don't have a perfect solution, but I thought it would be best to present the question to spur conversation.

It may seem like overkill since the goal of Signal is to make encryption easier (which, again, I LOVE YOU FOR), but these features would be useful, even if not for the average user, but in an ADVANCED menu option, OPT-IN, rather than OPT-OUT, fashion, much like pass-phrases are, so the app could continue to work as is for those new to encryption, but offer safeguards to those that need sturdier security measures.

This could possibly be presented during the setup guide, just a hint saying "If you're already familiar with how this this and that works, you can use this in the advanced menu"

I'd also like to suggest a more strong worded push for using a pass-phrase during setup, to outline the benefits, and just pushy enough not to be demanding, so to encourage more to use it, but that's for another topic.

I hope I'm not misguided with my assumptions in the way this app works, I have yet to look over the source code, but I have been a huge fan, and have been using it all the time now that I converted family and friends to it. Thanks for hearing me out, even if I am wrong, and a jerk. I love the work you all have done thus far, and can't wait to see where it goes!

**Comment by FredericJacobs** [comment]
You can verify fingerprints manually https://github.com/WhisperSystems/Signal-iOS/wiki/FAQ#can-i-verify-my-contacts-key

Key exports have other open github issues

**Comment by modoj** [comment]
I'm not asking for this to be reopened, but that addresses very little, if any, of my initial concerns. Yes, I know I can verify the fingerprint manually, but my suggestion was for a more robust verification of sender by the application itself, my cross-checking fingerprint against knowable variables such as device id, or sim card serial, which are easily done, and would allow for a more secure system, effectively preventing a MITM, unless the user has in fact lost possession of the device itself. I understand this may not be something Signal would like to address, but neither manual verifications of fingerprints, nor the ability to export keys address this matter, I'm sorry, but I very much feel you were too quick to pass my concern off, and preemptively closed this ticket without wholly understanding or addressing the issue at hand.

**Comment by FredericJacobs** [comment]
This is a bug tracker, not a discussion forum. If you have any ideas to propose, the right place for that is the mailing list.

**Comment by modoj** [comment]
Apologies, I'm new to GitHub, I'm used to the Launchpad format, wherein the mailing list and bug tracker is somewhat combined under "Issues". Since I've seen it used as such on other projects on Github, I assumed it to be appropriate for proposals, and issues as well. I understand that some projects will be more lenient than others when it comes to this.

My issue still stands, and while it may not be a bug, it seems to be a flaw in implementation.
