### ISSUE TITLE
Remove call icon from contact list

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#950]
Remove cal icon from contact list as distinction between calling and messaging will not be needed (once RedPhone is fully unsupported)

1. This is to be in parity with Signal on Android
2. Remove confusion for users who only think of tapping on the call icon and not the name
3. No longer needed to distinguish between calling/messaging as Signal on Android users can communicate both ways.

**Comment by FredericJacobs** [comment]
Sounds good.
