### ISSUE TITLE
Feature request: Align message list with newest conversation at the bottom

### ISSUE THREAD

**Issue by osos** [WhisperSystems/Signal-iOS#952]
A general useability problem on todays smartphones is that many buttons etc are placed topmost on the screen. With a 5" + screen the top is unaccesible with short fingers.

Thus instead of sorting the conversation list with the newest conversations topmost, please consider sorting with conversation bottonmost, just like the messagelist inside the conversation.

This will ensure easy acces to the new incoming messages and newest conversation.

If the "write new message" button can be moved to the bottom as well, that would be great.

**Comment by FredericJacobs** [comment]
This is not something we'll work on.

Apple has reachability to address that issue: http://www.tekrevue.com/tip/reachability-iphone-6/
