### ISSUE TITLE
Registering new keys over iOS breaks other devices without prior notice

### ISSUE THREAD

**Issue by mattrubin** [WhisperSystems/Signal-iOS#959]
After getting a new phone, I installed and registered my number with Signal. There was no indication that the app would stop working on my old phone, but after the new registration, the app on the old phone shows "Network Status: Offline" with no explanation or way of fixing the problem. When I try to "Delete Account", I get a message saying "Failed to unregister messaging component of Signal", again with no way to diagnose or fix the issue.

I see from issue #802 that a number can only be registered in one place at a time. I would propose:
- documenting this fact somewhere it could be easily found by a user who is searching for it before registering on a new device.
- notifying a user when re-registering a number that old registrations of that number will be deactivated.
- showing a more informative message than "Network Status: Offline" to the old account, explaining that the registration has been superseded by a new one.
- Fix the delete account process so it does not fail for an already-unregistered account.

**Comment by rygen** [comment]
Being able to re-register on an old phone is specially desirable in case you only have one mobile number and use the App Store version and are also testing new features / fixes with the app built from the source code. 

Happened to me and could only understand why it wouldn't reconnect after reading this issue. "Re-register for push notifications" throws an error (AlertController): "We couldn't reach the Signal server. Please try again."

**Comment by siccovansas** [comment]
This needs improvement indeed. I installed Signal on an iPad and now the iPhone is offline. I need to reinstall on the iPhone, but I guess this removes all data and Signal on iOS does not seem to support backups/exports (yet), see #967. I should've read the following before I did this, but I didn't: http://support.whispersystems.org/hc/en-us/articles/213240927--Can-I-use-multiple-devices-Why-is-my-device-offline-
Indeed when registering a new device, a warning of the consequences would be very welcome :)

**Comment by ejpcmac** [comment]
@siccovansas: In the past (this summer, I don’t remember exactly which version), encrypting the backup in iTunes allowed to backup Signal data, and restoring the iPhone caused no problem: all was preserved. But now it seems that Signal data is not backed up anymore, even when the backup encryption is on. I had the bad surprise to discover this new behaviour today after unsimlocking my iPhone.

**Comment by mkb** [comment]
This is frustrating and comes at an unfortunate time. I'm glad to see there is already an issue open.

I am busily trying to get more people to use Signal. I'm evangelizing it to everyone I spend time with. When my contacts see a notice saying my safety numbers have changed it makes them nervous and less likely to adopt. Same with disrupting groups.

Please take my statement of frustration and inconvenience as "I'd like you to place high priority on this issue" and not anything more. I know your team is tiny and you've built an amazing product. In software there will always be loose ends. I like Signal and will continue to pitch it to others. 

Still, if you can get this one addressed I'll be a very happy camper. Thanks!

**Comment by strand** [comment]
Hey, this is a real issue, as I found this process hugely unintuitive and Signal failed to meet a implicit expectation I had of messaging apps. The original posts second and third bullet points have potentially easy fixes (I've not worked with ios, but these should be simple view changes.

One immediate change which would improve this issue substantially is adding a message like, "Signal can only be used on one device. Verifying your Signal account on this device will permanently sign you out of any other devices associated with your phone number."

I'd be glad to code up a fix, but am quite busy. I'll check on this thread next Saturday and if the issue is still unaddressed I will start a pull request.

**Comment by Trolldemorted** [comment]
@strand "Signal can only be used on one device" would be incorrect. signal-iOS can have signal-desktop slaves, hopefully soon signal-android slaves and hopefully some day signal-ios slaves.

Something like "By registering this device to Signal, you unlink any prior device that belongs to your phone number" would be correct, and hopefully comprehensible.

**Comment by jackphelps** [comment]
Same issue, following this. 

Switched phones briefly, then switched back; don't see any reason old phone would have lost its access to my signal account, and doesn't seem to be anything I can do to solve it.

**Comment by riyapenn** [comment]
Signal can only be registered with a phone number to one mobile device at a time.  Please refrain from adding "same issue, me too, +1" on GitHub as there is no NEW or actionable information in that comment.  Also refer to the [support page.](https://support.whispersystems.org/hc/en-us/articles/213240927--Can-I-use-multiple-devices-Why-is-my-device-offline-) or contact support@whispersystems.org if you have issues uninstalling/re-installing Signal.

**Comment by michaelkirk** [comment]
In https://github.com/WhisperSystems/Signal-iOS/commit/94d37d9c558bae363503a9665ad3fb99903be4d7

**Comment by yaneurabeya** [comment]
I'm running 2.6.13 and this still hasn't been fixed yet -- can you provide an updated ETA for the fix?

**Comment by strand** [comment]
@yaneurabeya Are messages like 'At this time Signal can only be active on one mobile device per phone number.' not displaying in the signup user flow? I'm just an observor to this project, but I believe multi-device is a large feature which is not currently available, and this change introduced better messaging regarding this to the user.

**Comment by yaneurabeya** [comment]
@strand it didn't, no. The code might have regressed between 2.6.9 and 2.6.13 (or the versioning info is messed up... *shrugs*)

**Comment by shayclatk** [comment]
Qw
