### ISSUE TITLE
iOS push notification security

### ISSUE THREAD

**Issue by slickster514** [WhisperSystems/Signal-iOS#962]
Are iOS push notification previews also encrypted?
If so how?

Regards,
A.Maltese

**Comment by FredericJacobs** [comment]
A push is sent as a trigger to notify the phone that new messages are available.

The phone then fetches the message in the background, decrypts it and generates the notification.

The Apple push notification network only knows when you receive a message but not from who it is coming from or what it contains.

**Comment by slickster514** [comment]
How is this accomplished is the app is not running in the background and has been stopped?

**Comment by Geblaat** [comment]
@slickster514 
The app is woken up by the empty push notification.
