### ISSUE TITLE
Voice messages not rendered

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-iOS#965]
When I send voice messaged to my friends on iOS they receive something that says "unsupported".

**Comment by mmkassem** [comment]
Signal on iOS does not have voice messages.

**Comment by FredericJacobs** [comment]
Duplicate of #230

**Comment by rmueller83** [comment]
I think the root cause of the message not being rendered is on the Android side: https://github.com/WhisperSystems/Signal-Android/issues/4640
