### ISSUE TITLE
Crash after first and nearly all subsequent messages to unregistered number

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#968]
Crash after messaging unregistered number for the first time
1. Open Group or single conversation with contact who just unregistered 
2. Send message (media or text)
3. Signal crashes
4. Restart Signal, and subsequent Single messages just state "Sending failed, tap to Retry" 
5. Calls fail to connect & recognize number as not registered then return to conversation screen
6. Attempt to send image, Signal crashes
7. Close Signal, Restart phone, Send group or direct message (text no media), app eventually or immediately crashes 

Signal 2.2
iOS 9.1

**Comment by FredericJacobs** [comment]
Fixed.
