### ISSUE TITLE
Crash after pressing and holding (extra press) to attach an image

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#969]
1. Open Signal
2. Go to conversation
3. Choose to attach image
4. Press on image and hold.  (could be related to 3D touch, just need to I press the image a little hard)
5. Signal crashes

Normal messaging does not crash app. Selecting image (without holding) does not crash app. No problem sending and receiving messages otherwise.

**Comment by FredericJacobs** [comment]
It's an iOS bug.

https://forums.developer.apple.com/thread/21932

Developers have no control over that stuff.

**Comment by michaelkirk** [comment]
reported as fixed by @riyapenn 🎉
