### ISSUE TITLE
More space for ERROR_MESSAGE_WRONG_TRUSTED_IDENTITY_KEY

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#975]
Noticed that some identity key change issues have been tagged with the 2.3 milestone and recalled this small related ui issue.

The string `"Identity key changed. Tap to verify new key."` (`ERROR_MESSAGE_WRONG_TRUSTED_IDENTITY_KEY`) does not have enough space with some of the translations and devices. See attached screen shot below.
![key changed ui string](https://cloud.githubusercontent.com/assets/174176/11459647/03bfe856-96e4-11e5-98a6-4e2512e8e55e.png)
E.g. in the Finnish translation it's cut like this
_"Identiteettiavain on vaihtunut. Varmenna uusi a:scissors:vain napauttamalla."_

Is that ui element easily expandable?

**Comment by FredericJacobs** [comment]
I'm working on rewriting all of that from scratch, will take it into account in the next 2 months.

**Comment by 2-4601** [comment]
Is this still an issue?

**Comment by michaelkirk** [comment]
I think it's been resolved. Thanks!
