### ISSUE TITLE
What happens / do you lose all your messages with a contact when they send you a new identity key?

### ISSUE THREAD

**Issue by saltyseathings** [WhisperSystems/Signal-iOS#978]
I use Signal on my iOS device, and my contact was using TextSecure on his Android. Two days ago, he picked up his phone to send me a message, and all of our correspondence was gone on his end. On WhisperSystem's advice, my contact installed the new Signal for Android, and he sent me a new identity key. I received 2 identical messages that say:

[red exclamation point inside a red diamond]
Identity key changed. Tap to verify new key.

I am afraid that if I verify his new key, I will also lose our entire correspondence. I have tried to contact Signal's customer service back just to verify that this will not happen, but they have been unresponsive.

Does anyone have experience with this / can let me know what to expect if I tap to verify?

Thanks-

**Comment by riyapenn** [comment]
You will not lose past messages on your iPhone.  You will only be able to read new messages after accepting the key change. 

If you delete the conversation thread, reinstall Signal on iOS, or tap "Delete Account" in settings, then your past messages will be cleared.

**Comment by saltyseathings** [comment]
Thank you for your reply - I just want to be clear... if I verify his new key, none of our old messages will be lost AND I will be able to receive his new messages. Is that correct? 

Sorry, I am paranoid :)

**Comment by riyapenn** [comment]
Correct.

**Comment by saltyseathings** [comment]
Thank you - worked just as you said!
