### ISSUE TITLE
The string FAILED_RETRYING_DIRECTORY_DOWNLOAD needs better plural support

### ISSUE THREAD

**Issue by amire80** [WhisperSystems/Signal-iOS#981]
The string FAILED_RETRYING_DIRECTORY_DOWNLOAD is "Retrying in %f hours".

In Hebrew and Arabic the word "hours" is translated differently for "2 hours" and "3 hours".

In Russian the word "hours" is translated differently for "4 hours" and "5 hours".

There are many such issues in other languages.

Is it possible in iOS to have different plural forms for different numbers? Sorry, I'm an experienced localizer, but not an iOS developer. It should be possible if there is CLDR support, but I don't know how well does iOS support CLDR.

**Comment by FredericJacobs** [comment]
The string is no more present in the new revision. Thanks for reporting though.
