### ISSUE TITLE
App not respecting active DoNotDisturb

### ISSUE THREAD

**Issue by dibblah** [WhisperSystems/Signal-iOS#982]
Hi!

My problem is that Signal rings even though my iPhones DoNotDisturb is activated.

* DoNotDisturb activated & set as Always (not just with a locked screen)
* not jailbroken iPhone 5S running non-beta iOS9.1
* Replicated the first instanse with both an iOS & an Android using friend calling and both times Signal ignored DoNotDisturb

Hope you can fix this problem, real annoying when you have DND set when you sleep ...

Thnx in advance /dibblah

**Comment by FredericJacobs** [comment]
Apple doesn't give us the APIs for it.
