### ISSUE TITLE
Usage info leaked

### ISSUE THREAD

**Issue by winhowes** [WhisperSystems/Signal-iOS#984]
When I open the app or receive a message a request is made to http://itunes.apple.com/US/lookup?id=874139669. I've checked this for other apps like whatsapp, but no other app (that I've checked) seems to make this request. 

Unfortunately what this means is that if someone does a MITM or is listening on the network, they can see if I'm using signal.

**Comment by hubert3** [comment]
This seems bad.

**Comment by FredericJacobs** [comment]
A network adversary already knows when you're using Signal because it will open a WebSocket connection to the Signal server. Apple also already collects usage data.

This request is performed by the rating system we have in place. I have no issue removing this in an upcoming release.
