### ISSUE TITLE
No option to set signal as default sms/phone app.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#985]
When receiving a text from a non signal user the text/sms goes to the default imessages app. When the user manually disables imesages the text will be lost and does not get sent to the receipient signal user.

Their should be a way to set signal as the default sms/text/phone app to receive such messages from non signal users.

Thanks!

**Comment by FredericJacobs** [comment]
Unlike on Android, this is not something that iOS lets us do.

There is no way for developers to access to a user's text messages.

**Comment by nanotechz9l** [comment]
Understood thanks!

**Comment by rdhyee** [comment]
Alas, this proved to be a deal-breaker for someone I know.  It's so handy to be able to make Signal the default messenging app on Android.
