### ISSUE TITLE
No option to sms/text user inviting them to DL signal.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#986]
There is currenty no option to sms/text a non signal contact to invite them to DL and use signal.

**Comment by michaelkirk** [comment]
To invite a non-signal user, you can type their phone number into the "search by name or number". 

I think we should do better though.

**Comment by riyapenn** [comment]
Invite through

1. Signal > Message compose icon (top right) > Invite Friends to Signal > Choose Message or Mail > choose contact > Select Done > Send SMS/MMS message or email
2. Signal > Settings wheel (top left) > Invite Your Friends > Choose Message or Mail > choose contact > Select Done > Send SMS/MMS message or email
3. From outside of Signal and through other means to your contact, share the link: https://signal.org/install
