### ISSUE TITLE
Long press crashes signal app.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#990]
Open signal app and from the main inbox UI long press any white space under the recent contacts main screen.

App will crash.

This also happens in the archives UI by long pressing on any white space area.

**Comment by FredericJacobs** [comment]
Good catch.

**Comment by big-r81** [comment]
I can't reproduce this...
For me, SIgnal is not crashing if i press long on any white space area...

**Comment by nanotechz9l** [comment]
Issue is still present on current release.

**Comment by big-r81** [comment]
@nanotechz9l 
if i press long on any white space area, it happens nothing...

**Comment by nanotechz9l** [comment]
Congrats!

**Comment by big-r81** [comment]
?

**Comment by FredericJacobs** [comment]
@big-r81 : It only crashes on 3D Touch capable devices I think.

It's been fixed for next release.

**Comment by nanotechz9l** [comment]
Hi Frederic,

I checked the link below and noticed the following entry from WhisperBTC.
"Thanks! BitHub has sent payment of $29.11USD for this commit". Do you guys get paid per commit?

Ref: https://github.com/WhisperSystems/Signal-iOS/commit/f4f6c61df12a0580bd2e9660ab93fe168b2215e8

**Comment by nanotechz9l** [comment]
Issue is still present on current Signal version 2.2 from Nov 9th, 2015. Issue was closed but fix was not pushed out. Bug was filed two months ago. What is the 2.3 release date and what is the Signal update release cycle?

**Comment by nanotechz9l** [comment]
Why so slow to release, what is the delay? Bug opened Dec 6, 2015, fix committed Dec 26, 2015 but still no new version for users. This issue and other known bugs still exist.

https://github.com/WhisperSystems/Signal-iOS/issues/1074
