### ISSUE TITLE
Disappearing contact names

### ISSUE THREAD

**Issue by forthrin** [WhisperSystems/Signal-iOS#992]
From time to time, I'm unsure when, contact names are not shown in my contact list, only phone numbers. By restarting the app, contact names reappear.

**Comment by riyapenn** [comment]
Check section "Erroneously listed contacts" at http://support.whispersystems.org/hc/en-us/articles/212743488-Why-are-my-contacts-different-colors-in-my-contact-list-

**Comment by forthrin** [comment]
This does not seem to be related. My problem is: Sometimes my Signal contacts are listed with their name from the iPhone contact list (like they should). But suddenly, only the phone number is listed for all contacts. If I restart the app, the names appear again. This must surely be a bug.

**Comment by riyapenn** [comment]
Is this still an issue w/ an update to Signal 2.4?

**Comment by michaelkirk** [comment]
@forthrin please feel free to re-open if this is still an issue.
