### ISSUE TITLE
Screen Security should be explained

### ISSUE THREAD

**Issue by forthrin** [WhisperSystems/Signal-iOS#993]
In Settings > Privacy there is an option called "Screen Security"? What is this? This should be displayed with a short and intuitive sentence underneath (like Apple does for many of its settings).

**Comment by thateclipseguy** [comment]
It's a feature that prevents screenshots being taken when inside the app.

**Comment by liliakai** [comment]
http://support.whispersystems.org/hc/en-us/articles/212476218-What-are-these-options-Screen-Security-Archive-Group-chat-

**Comment by forthrin** [comment]
Don't tell it to me or put it in a hidden-away FAQ. Put it in writing inside the app so no-one will have the slightest doubt.

![explanation](https://cloud.githubusercontent.com/assets/1167421/11650247/be23362c-9d87-11e5-9a21-71a73a599161.jpg)

**Comment by kunickiaj** [comment]
Opened PR https://github.com/WhisperSystems/Signal-iOS/pull/1014 to address this.

**Comment by JimLoose** [comment]
let's keep it easy and remove the setting (could be enabled by default)

**Comment by kunickiaj** [comment]
I'm in favor of keeping it, as sometimes you want to be able to flip back and forth, e.g. to read part of a number that you're filling out into another app. It's often easier than having to fully switch to the other app.

Hopefully my explanation makes sense.

**Comment by thateclipseguy** [comment]
It's a question of freedom. Granted, iPhone users don't care much for it,
no offense, but I believe that the user should have the option. Don't make
the decision for the user.

**Comment by JimLoose** [comment]
@kunickiaj your reason makes sense! (i removed my comment)
@thateclipseguy freedom or security? ... or usability?

**Comment by thateclipseguy** [comment]
@JimLoose 

”He who would trade liberty for some temporary security, deserves neither liberty nor security.”

**Comment by forthrin** [comment]
I support removing the option. An increasing number of settings is a general disease in apps, and though one may have the occasional complaint about lost flexibility, there is a huge upside in simplicity for most people. Signal should be the foremost example of how security can be clear as day for everyone.

**Comment by thateclipseguy** [comment]
The Apple philosophy people. I guess Apple users wouldn't mind the loss in freedom, to be honest, so removing the option is not of great consequence.

**Comment by FredericJacobs** [comment]
By removing the option, you would remove the feature?

I don't think it's reasonable to make hiding thumbnail in the app switcher the default.
