### ISSUE TITLE
Feature suggestion: sender-controlled message deletion

### ISSUE THREAD

**Issue by sorenr** [WhisperSystems/Signal-iOS#997]
Signal is great for preventing message interception, but it leaves endpoints vulnerable. Messages are stored forever, and can be read by anyone who takes control of the device, unless the recipient deletes messages manually or enables auto-deletion. (Which defaults to the last 500 messages.) 

Other "secure messaging apps" enable the sender to set a message expiry time, after which the messages automatically delete. If a friend's phone gets taken and they don't have a strong passcode, or if someone's reading over their shoulder on public transport, the attacker will only see however many minutes/hours/days of conversation that you set for your messages.

I'd very much like a feature in Signal that lets the sender set a message expiration time. This could either be the "$FOO minutes after the user views the message", or "$BAR hours after the device receives the message".

**Comment by sorenr** [comment]
It might also be nice if "delete old messages" could be based on time ("younger than 1 week") rather than number ("500 messages per conversation").

**Comment by mawed** [comment]
http://support.whispersystems.org/hc/en-us/articles/213134237-Why-doesn-t-Signal-have-self-destructing-messages-or-remote-deletion-functionality-

**Comment by 2-4601** [comment]
1. comment: duplicate of #945
2. comment: duplicate of #254 (#906)

There's a thread on the [mailing list](https://lists.riseup.net/www/info/whispersystems) about this subject. You can share your ideas there.

**Comment by FredericJacobs** [comment]
As noted, these are either duplicates or not the right place to discuss these ideas.

@2-4601 : Thanks for your comments and work. Terrific as always, can you please email me: fred@whispersystems.org?
