### ISSUE TITLE
Inconsistent notification content 

### ISSUE THREAD

**Issue by roberthaverly** [WhisperSystems/Signal-iOS#999]
Normally, my push/lock screen notification will say "Message from < name >"

- However it will sometimes say "Message from < phone number >"
- And I've even seen it say "New Signal Message!" (or something along those lines) 

"Sender name only" is turned on. Signal version 2.2, iOS version 9.2

**Comment by abcdev** [comment]
The notification depends on your current signal database status. If it is encrypted because the phone has not been unlocked (i.e. you restarted your phone or it was locked for a long time) it will not be able to display all information.

**Comment by FredericJacobs** [comment]
Duplicate #797
